Repository geodynamics/aspect, pull requests merged in 2018-05, with the labels that each got.

#2196 reference new cite.html
  README.md
  doc/manual/manual.tex
Labels: ready to merge

#2220 fix drucker prager 3d derivatives and extend test to catch this in the future.
  source/material_model/drucker_prager.cc
  tests/drucker_prager_derivatives.cc
  tests/drucker_prager_derivatives/screen-output
Labels: bug

#2223 Close output directory handle
  source/utilities.cc
Labels: bug, ready to merge

#2255 Add way to access mesh refinement strategies
  include/aspect/mesh_refinement/interface.h
  include/aspect/simulator_access.h
  source/simulator/simulator_access.cc
Labels: ready to merge
