Repository geodynamics/aspect, pull requests merged in 2018-09, with the labels that each got.

#2646 Fix plugin graph generation
  source/simulator/core.cc
Labels: ready to merge, ready to test

#2651 Better explain what kinds of checks run with --validate.
  source/main.cc
Labels: ready to merge

#2668 Negative longitude in uniform radial particle generator
  source/particle/generator/uniform_radial.cc
Labels: ready to test

#2672 Fix typo in documentation
  source/postprocess/visualization/maximum_horizontal_compressive_stress.cc
Labels: ready to test

#2525 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: ready to test
