Repository geodynamics/aspect, pull requests merged in 2018-08, with the labels that each got.

#2588 Fix manual references
  doc/manual/cookbooks/gplates/gplates.part.prm
  doc/manual/manual.tex
Labels: ready to test

#1014 Dynamic Citation Thing
  CITATION
  doc/make_cite_html.py
  doc/manual/manual.bib
  doc/modules/changes/20180725_tjhei
  include/aspect/citation_info.h
  source/citation_info.cc
  source/global.cc
  source/particle/world.cc
  source/simulator/core.cc
  source/simulator/free_surface.cc
  source/simulator/melt.cc
  unit_tests/common.h
  unit_tests/first.cc
Labels: ready to merge

#2610 fix tests/global_melt_parallel
  tests/global_melt_parallel.prm
Labels: ready to merge

#2607 Allow negative scale factor for boundary velocity
  source/boundary_velocity/gplates.cc
  source/utilities.cc
Labels: ready to merge, ready to test

#2615 Jenkinsfile.k8s whitespace and step names
  Jenkinsfile.k8s
Labels: ready to merge, ready to test

#2621 Use 'nullptr' instead of '0' for pointers.
  source/boundary_composition/spherical_constant.cc
  source/boundary_temperature/two_merged_boxes.cc
  source/boundary_traction/initial_lithostatic_pressure.cc
  source/boundary_velocity/ascii_data.cc
  source/boundary_velocity/function.cc
  source/boundary_velocity/gplates.cc
  source/geometry_model/box.cc
  source/geometry_model/chunk.cc
  source/geometry_model/initial_topography_model/ascii_data.cc
  source/geometry_model/sphere.cc
  source/geometry_model/spherical_shell.cc
  source/geometry_model/two_merged_boxes.cc
  source/gravity_model/radial.cc
  source/gravity_model/vertical.cc
  source/initial_temperature/spherical_shell.cc
  source/postprocess/basic_statistics.cc
  source/postprocess/gravity_point_values.cc
  source/postprocess/point_values.cc
  source/postprocess/spherical_velocity_statistics.cc
  source/simulator/core.cc
  source/simulator/helper_functions.cc
  source/utilities.cc
Labels: ready to merge

#2609 Add a termination criteria based on wall time.
  include/aspect/termination_criteria/end_walltime.h
  source/termination_criteria/end_walltime.cc
  tests/walltime.prm
  tests/walltime/screen-output
Labels: ready to merge, ready to test

#2619 Jenkinsfile.k8s : Build in Jenkins workspace instead of /home/dealii and other build step cleanup
  Jenkinsfile.k8s
Labels: ready to test

#2608 Cleanup documentation for ascii data plugins
  source/adiabatic_conditions/ascii_data.cc
  source/boundary_composition/ascii_data.cc
  source/boundary_temperature/ascii_data.cc
  source/boundary_traction/ascii_data.cc
  source/boundary_velocity/ascii_data.cc
  source/geometry_model/initial_topography_model/ascii_data.cc
  source/gravity_model/ascii_data.cc
  source/initial_composition/ascii_data.cc
  source/initial_temperature/ascii_data.cc
  source/initial_temperature/ascii_profile.cc
  source/material_model/ascii_reference_profile.cc
  source/prescribed_stokes_solution/ascii_data.cc
  source/utilities.cc
Labels: ready to test

#2577 Lazy expression
  cookbooks/muparser_temperature_example/muparser-temperature-example.prm
  cookbooks/muparser_temperature_example/muparser_if_temperature_example.py
  cookbooks/muparser_temperature_example/readme
  cookbooks/muparser_temperature_example/temperature_muparser_if.pdf
  doc/manual/cookbooks/muparser-temperature-example/check-initial-condition.part.prm
  doc/manual/cookbooks/muparser-temperature-example/initial_temperature.png
  doc/manual/cookbooks/muparser-temperature-example/initial_temperature_on_mesh.png
  doc/manual/cookbooks/muparser-temperature-example/initial_temperature_on_mesh_zoom.png
  doc/manual/cookbooks/muparser-temperature-example/mesh-refinement.part.prm
  doc/manual/cookbooks/muparser-temperature-example/repetitions.part.prm
  doc/manual/cookbooks/muparser-temperature-example/temperature.part.prm
  doc/manual/manual.tex
  tests/muparser-temperature-example/muparser-temperature-example.prm
  tests/muparser-temperature-example/screen-output
  tests/muparser-temperature-example/solution-00000.0000.gnuplot
  tests/muparser-temperature-example/statistics
Labels: ready to test

#2600 Add basic parameter file validation mode.
  source/main.cc
Labels: ready to test

#2585 add an adiabatic temperature gradient to the flow-law in visco_plastic
  include/aspect/material_model/visco_plastic.h
  source/material_model/visco_plastic.cc
  tests/visco_plastic_adiabat_temperature.prm
  tests/visco_plastic_adiabat_temperature/screen-output
  tests/visco_plastic_adiabat_temperature/solution/solution-00000.0000.gnuplot
  tests/visco_plastic_adiabat_temperature/statistics
Labels: ready to merge, ready to test

#2533 Postprocessor to calculate intermediate quantities for grain orientation lag parameter
  doc/modules/changes/20180812_hmark
  include/aspect/postprocess/visualization/ISA_rotation_timescale.h
  include/aspect/postprocess/visualization/grain_lag_angle.h
  source/postprocess/visualization/ISA_rotation_timescale.cc
  source/postprocess/visualization/grain_lag_angle.cc
  tests/ISA_rotation_timescale.prm.deal.II.9.0
  tests/ISA_rotation_timescale/solution/solution-00000.0000.gnuplot
  tests/grain_lag_angle.prm.deal.II.9.0
  tests/grain_lag_angle/solution/solution-00000.0000.gnuplot
Labels: ready to test

#2623 Refactor visco plastic
  include/aspect/material_model/visco_plastic.h
  source/material_model/visco_plastic.cc
Labels: ready to merge

#2641 Clarify a comment and a formula.
  source/geometry_model/spherical_shell.cc
Labels: ready to merge
