Repository geodynamics/aspect, pull requests merged in 2019-06, with the labels that each got.

#3122 Remove deal.II version check from sphere geometry model
  include/aspect/geometry_model/sphere.h
  source/geometry_model/sphere.cc
Labels: ready to merge, ready to test

#3130 Finish removing 9.0.0 references from geometry_model
  include/aspect/geometry_model/chunk.h
  include/aspect/geometry_model/ellipsoidal_chunk.h
  source/geometry_model/chunk.cc
  source/geometry_model/ellipsoidal_chunk.cc
Labels: ready to test

#3131 manual: fix a typo
  doc/manual/manual.tex
Labels: ready to merge

#3127 document entropy viscosity
  doc/manual/manual.tex
Labels: ready to merge

#3043 New benchmark for translation of brittle thrust wedge
  benchmarks/buiter_et_al_2016_jsg/README
  benchmarks/buiter_et_al_2016_jsg/exp_1.prm
Labels: ready to test

#3125 Refactor parts of lithosphere_mask.cc
  data/initial-temperature/lithosphere-mask/LAB_CAM2016.txt
  include/aspect/initial_temperature/lithosphere_mask.h
  source/initial_temperature/lithosphere_mask.cc
  tests/initial_condition_lithosphere_mask/screen-output
Labels: ready to test

#2970 New: Realistic compressible equation of state (Modified Tait)
  doc/manual/manual.bib
  doc/modules/changes/20190527_myhill
  include/aspect/material_model/modified_tait.h
  source/material_model/modified_tait.cc
  tests/modified_tait_forsterite_box.prm
  tests/modified_tait_forsterite_box/screen-output
  tests/modified_tait_forsterite_box/solution/solution-00000.0000.gnuplot
  tests/modified_tait_forsterite_box/statistics
Labels: ready to test

#3120 Correction for initial guess/tol in GMRES solve
  source/simulator/solver.cc
  source/simulator/stokes_matrix_free.cc
Labels: ready to test

#3134 Use semantic mark-up for SI units in the manual.
  doc/manual/manual.tex
Labels: documentation

#3135 Use semantic mark-up for SI units in the manual.
  source/boundary_temperature/box.cc
  source/boundary_temperature/dynamic_core.cc
  source/boundary_temperature/function.cc
  source/boundary_temperature/initial_temperature.cc
  source/boundary_temperature/spherical_constant.cc
  source/boundary_temperature/two_merged_boxes.cc
  source/boundary_traction/initial_lithostatic_pressure.cc
  source/geometry_model/box.cc
  source/geometry_model/chunk.cc
  source/geometry_model/sphere.cc
  source/geometry_model/spherical_shell.cc
  source/geometry_model/two_merged_boxes.cc
  source/heating_model/radioactive_decay.cc
  source/initial_temperature/adiabatic.cc
  source/initial_temperature/adiabatic_boundary.cc
  source/initial_temperature/continental_geotherm.cc
  source/material_model/composition_reaction.cc
  source/material_model/diffusion_dislocation.cc
  source/material_model/drucker_prager.cc
  source/material_model/dynamic_friction.cc
  source/material_model/equation_of_state/multicomponent_incompressible.cc
  source/material_model/grain_size.cc
  source/material_model/latent_heat.cc
  source/material_model/latent_heat_melt.cc
  source/material_model/melt_global.cc
  source/material_model/melt_simple.cc
  source/material_model/multicomponent.cc
  source/material_model/perplex_lookup.cc
  source/material_model/simple.cc
  source/material_model/simpler.cc
  source/material_model/visco_plastic.cc
  source/material_model/viscoelastic.cc
  source/material_model/viscoelastic_plastic.cc
  source/postprocess/visualization/geoid.cc
  source/simulator/parameters.cc
Labels: ready to test

#3145 added if !DEAL_II_VERSION_GTE(9,2,0) back into compat.h
  include/aspect/compat.h
Labels: ready to merge, ready to test

#3066 Anisotropy cookbook
  cookbooks/anisotropic_viscosity/AV_Rayleigh_Taylor.prm
  cookbooks/anisotropic_viscosity/CMakeLists.txt
  cookbooks/anisotropic_viscosity/av_material.cc
Labels: ready to test

#3154 Introduce a reset function for heating model outputs
  doc/modules/changes/20190612_jdannberg
  include/aspect/heating_model/interface.h
  source/heating_model/interface.cc
  tests/global_latent_heat.prm
  tests/global_latent_heat/screen-output
  tests/global_latent_heat/statistics
  tests/shear_heating_with_melt/screen-output
  tests/shear_heating_with_melt/statistics
Labels: ready to merge

#3147 cookbook for brittle thrust wedges experiments
  doc/manual/cookbooks/benchmarks/brittle_thrust_wedges/convergence_part.prm
  doc/manual/cookbooks/benchmarks/brittle_thrust_wedges/exp1.png
  doc/manual/cookbooks/benchmarks/brittle_thrust_wedges/exp2.png
  doc/manual/cookbooks/benchmarks/brittle_thrust_wedges/velocity_bc_part.prm
  doc/manual/manual.bib
  doc/manual/manual.tex
Labels: ready to test

#3142 Initial isotherm plugin
  data/initial-temperature/ascii-data/test/initial_isotherm_1000K_box_2d.txt
  data/initial-temperature/ascii-data/test/initial_isotherm_1000K_box_3d.txt
  data/initial-temperature/ascii-data/test/initial_isotherm_1000K_chunk_2d.txt
  data/initial-temperature/ascii-data/test/initial_isotherm_1000K_chunk_3d.txt
  data/initial-temperature/ascii-data/test/initial_isotherm_500K_box_2d.txt
  data/initial-temperature/ascii-data/test/initial_isotherm_500K_box_3d.txt
  data/initial-temperature/ascii-data/test/initial_isotherm_500K_chunk_2d.txt
  data/initial-temperature/ascii-data/test/initial_isotherm_500K_chunk_3d.txt
  include/aspect/initial_temperature/ascii_data_layered.h
  include/aspect/utilities.h
  source/initial_temperature/ascii_data_layered.cc
  source/utilities.cc
  tests/ascii_data_layered_initial_temperature_2d_box.prm
  tests/ascii_data_layered_initial_temperature_2d_box/depth_average.gnuplot
  tests/ascii_data_layered_initial_temperature_2d_box/screen-output
  tests/ascii_data_layered_initial_temperature_2d_box/statistics
  tests/ascii_data_layered_initial_temperature_2d_chunk.prm
  tests/ascii_data_layered_initial_temperature_2d_chunk/depth_average.gnuplot
  tests/ascii_data_layered_initial_temperature_2d_chunk/screen-output
  tests/ascii_data_layered_initial_temperature_2d_chunk/statistics
  tests/ascii_data_layered_initial_temperature_3d_box.prm
  tests/ascii_data_layered_initial_temperature_3d_box/depth_average.gnuplot
  tests/ascii_data_layered_initial_temperature_3d_box/screen-output
  tests/ascii_data_layered_initial_temperature_3d_box/statistics
  tests/ascii_data_layered_initial_temperature_3d_chunk.prm
  tests/ascii_data_layered_initial_temperature_3d_chunk/depth_average.gnuplot
  tests/ascii_data_layered_initial_temperature_3d_chunk/screen-output
  tests/ascii_data_layered_initial_temperature_3d_chunk/statistics
  tests/ascii_data_layered_initial_temperature_piecewise_constant_3d_box.prm
  tests/ascii_data_layered_initial_temperature_piecewise_constant_3d_box/depth_average.gnuplot
  tests/ascii_data_layered_initial_temperature_piecewise_constant_3d_box/screen-output
  tests/ascii_data_layered_initial_temperature_piecewise_constant_3d_box/statistics
Labels: ready to test

#3148 New: Layered ASCII data initial composition plugin
  data/initial-composition/ascii-data/test/initial_composition_top_crust_box_2d.txt
  data/initial-composition/ascii-data/test/initial_composition_top_mantle_box_2d.txt
  doc/modules/changes/20190619_myhill
  include/aspect/initial_composition/ascii_data_layered.h
  source/initial_composition/ascii_data_layered.cc
  tests/ascii_data_layered_initial_composition_2d_box.prm
  tests/ascii_data_layered_initial_composition_2d_box/depth_average.gnuplot
  tests/ascii_data_layered_initial_composition_2d_box/screen-output
  tests/ascii_data_layered_initial_composition_2d_box/statistics
Labels: ready to test

#3165 Fix error avmaterial
  cookbooks/anisotropic_viscosity/av_material.cc
Labels: ready to test
