Repository geodynamics/aspect, pull requests merged in 2019-05, with the labels that each got.

#2903 no temperature matrix for Stokes only
  source/simulator/core.cc
Labels: ready to test

#2954 Use consistent ParaView capitalization.
  doc/manual/manual.tex
Labels: ready to test

#2941 Remove deal.II compatibility fix
  source/postprocess/heat_flux_map.cc
Labels: ready to merge, ready to test

#2942 Remove DEAL.II compatibility fix
  source/postprocess/depth_average.cc
Labels: ready to merge, ready to test

#2953 Fix manual typo
  doc/manual/manual.tex
Labels: ready to test

#2947 Removed a now unnecessary compatibility fix
  source/simulator/solver.cc
Labels: ready to merge, ready to test

#2950 Remove deal.II compatibility fix
  source/simulator/assemblers/advection.cc
Labels: ready to test

#2945 Remove dealii compatibility fix
  source/simulator/helper_functions.cc
Labels: ready to test

#2943 Remove deal.II compatibility fix
  source/utilities.cc
Labels: ready to merge, ready to test

#2944 Remove dealii compatibility fix
  source/simulator/core.cc
Labels: ready to merge, ready to test

#2940 Remove deal.II compatiblity fix
  source/postprocess/stokes_residual.cc
Labels: ready to test

#2952 Added a note to a section of the manual
  doc/manual/manual.tex
Labels: ready to test

#2961 do not use std::make_unique
  source/simulator/lateral_averaging.cc
Labels: ready to test

#2937 Verify parameter/variable settings when restart, for issue #2090
  source/simulator/checkpoint_restart.cc
Labels: ready to test

#2939 Removed a now unnecessary compatibility fix
  source/simulator/melt.cc
Labels: ready to merge, ready to test

#2963 remove unnecessary "return;"
  source/boundary_composition/interface.cc
  source/boundary_temperature/dynamic_core.cc
  source/boundary_temperature/interface.cc
  source/boundary_velocity/interface.cc
  source/material_model/latent_heat_melt.cc
  source/material_model/melt_global.cc
  source/material_model/melt_simple.cc
  source/mesh_refinement/particle_density.cc
  source/mesh_refinement/volume_of_fluid_interface.cc
  source/simulator/solver_schemes.cc
Labels: ready to merge, ready to test

#2705 fix strain weakening logic
  include/aspect/material_model/visco_plastic.h
  source/material_model/visco_plastic.cc
  source/simulator/parameters.cc
  tests/visco_plastic_yield_max.prm
Labels: ready to merge

#2976 Remove more references to std::shared_ptr.
  include/aspect/boundary_velocity/gplates.h
  source/boundary_velocity/gplates.cc
Labels: ready to test

#2948 Manual typo
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#2958 Convert more std::shared_ptr to std::unique_ptr.
  doc/modules/changes/20190522_bangerth-2
  doc/modules/changes/20190522_bangerth-3
  include/aspect/boundary_velocity/interface.h
  include/aspect/simulator_access.h
  source/boundary_velocity/ascii_data.cc
  source/boundary_velocity/interface.cc
  source/simulator/simulator_access.cc
  tests/ascii_boundary_member.cc
Labels: ready to test

#2980 corrected a few typos in the ellipsoidal chunk model
  source/geometry_model/ellipsoidal_chunk.cc
  tests/ellipsoidal_chunk_coordinate_parallel.prm
  tests/ellipsoidal_chunk_noncoordinate_parallel.prm
Labels: ready to test

#2986 Convert the majority of the remaining std::shared_ptr to std::unique_ptr
  include/aspect/boundary_composition/interface.h
  include/aspect/gravity_model/ascii_data.h
  include/aspect/initial_temperature/interface.h
  include/aspect/particle/property/interface.h
  include/aspect/postprocess/interface.h
  include/aspect/postprocess/visualization.h
  source/boundary_composition/interface.cc
  source/heating_model/adiabatic_heating_of_melt.cc
  source/heating_model/shear_heating_with_melt.cc
  source/initial_temperature/interface.cc
  source/material_model/ascii_reference_profile.cc
  source/material_model/composition_reaction.cc
  source/material_model/depth_dependent.cc
  source/material_model/grain_size.cc
  source/material_model/melt_global.cc
  source/material_model/melt_simple.cc
  source/material_model/steinberger.cc
  source/material_model/visco_plastic.cc
  source/material_model/viscoelastic.cc
  source/particle/property/interface.cc
  source/postprocess/visualization.cc
  source/postprocess/visualization/seismic_anomalies.cc
  source/postprocess/visualization/spd_factor.cc
  source/simulator/assemblers/stokes.cc
  source/simulator/lateral_averaging.cc
  source/simulator/melt.cc
  source/simulator/newton.cc
  source/volume_of_fluid/handler.cc
  unit_tests/additional_outputs.cc
Labels: ready to test

#2967 Viscosity in no melting/freezing set-up
  source/material_model/melt_global.cc
  tests/adiabatic_heating_with_melt.prm
  tests/average_density_boundary_fluid_pressure/screen-output
  tests/average_density_boundary_fluid_pressure/statistics
  tests/melt_and_traction/screen-output
  tests/melt_and_traction/statistics
  tests/statistics_output.prm
  tests/statistics_output/screen-output
  tests/statistics_output/statistics
Labels: ready to test

#2984 Prohibit copying MaterialModelOutputs objects.
  include/aspect/material_model/interface.h
  source/material_model/interface.cc
Labels: ready to test

#2994 remove semicolons
  include/aspect/parameters.h
Labels: ready to merge, ready to test

#2993 Also check additional input objects when copying MaterialModelInputs.
  include/aspect/material_model/interface.h
  source/material_model/interface.cc
Labels: ready to test

#3002 Simply prohibit copying material model inputs/outputs.
  include/aspect/material_model/interface.h
  source/material_model/interface.cc
Labels: ready to test

#2936 Implement the stabilized Q1-Q1 element combination
  doc/manual/manual.bib
  include/aspect/parameters.h
  source/simulator/assemblers/stokes.cc
  source/simulator/core.cc
  source/simulator/introspection.cc
  source/simulator/parameters.cc
  tests/q1_q1.cc
  tests/q1_q1.prm
  tests/q1_q1/screen-output
  tests/q1_q1_6.cc
  tests/q1_q1_6.prm
  tests/q1_q1_6/screen-output
  tests/sol_cx_2_equal_order.cc
  tests/sol_cx_2_equal_order.prm
  tests/sol_cx_2_equal_order/screen-output
  tests/sol_cx_2_equal_order/statistics
  tests/sol_cx_4_equal_order.cc
  tests/sol_cx_4_equal_order.prm
  tests/sol_cx_4_equal_order/screen-output
  tests/sol_cx_4_equal_order/statistics
Labels: ready to merge, ready to test

#2638 Reimplement supg #412
  doc/modules/changes/20190524_gassmoeller
  include/aspect/parameters.h
  include/aspect/simulator/assemblers/interface.h
  source/simulator/assemblers/advection.cc
  source/simulator/assemblers/interface.cc
  source/simulator/assembly.cc
  source/simulator/entropy_viscosity.cc
  source/simulator/parameters.cc
  tests/supg-compositional-passive.prm
  tests/supg-compositional-passive/screen-output
  tests/supg-compositional-passive/statistics
  tests/supg.prm
  tests/supg/screen-output
  tests/supg/statistics
Labels: ready to merge, ready to test

#3005 added more doc/comments to ellipsoidal chunk
  source/geometry_model/ellipsoidal_chunk.cc
Labels: ready to test

#3011 Remove reference to deal.II version 9.0.0.
  include/aspect/geometry_model/spherical_shell.h
  source/geometry_model/spherical_shell.cc
Labels: ready to test

#2979 Add plugin to track plastic, viscous, or total strain using particles.
  doc/modules/changes/20190525_neuharth
  include/aspect/material_model/visco_plastic.h
  include/aspect/particle/property/viscoplastic_strain_invariants.h
  source/material_model/visco_plastic.cc
  source/particle/property/viscoplastic_strain_invariants.cc
  tests/visco_plastic_yield_plastic_strain_weakening_particles.prm
  tests/visco_plastic_yield_plastic_strain_weakening_particles/screen-output
  tests/visco_plastic_yield_plastic_strain_weakening_particles/solution/solution-00000.0000.gnuplot
  tests/visco_plastic_yield_plastic_strain_weakening_particles/statistics
  tests/visco_plastic_yield_plastic_viscous_strain_weakening_particles.prm
  tests/visco_plastic_yield_plastic_viscous_strain_weakening_particles/screen-output
  tests/visco_plastic_yield_plastic_viscous_strain_weakening_particles/solution/solution-00000.0000.gnuplot
  tests/visco_plastic_yield_plastic_viscous_strain_weakening_particles/statistics
  tests/visco_plastic_yield_strain_weakening_particles.prm
  tests/visco_plastic_yield_strain_weakening_particles/screen-output
  tests/visco_plastic_yield_strain_weakening_particles/solution/solution-00000.0000.gnuplot
  tests/visco_plastic_yield_strain_weakening_particles/statistics
  tests/visco_plastic_yield_viscous_strain_weakening_particles.prm
  tests/visco_plastic_yield_viscous_strain_weakening_particles/screen-output
  tests/visco_plastic_yield_viscous_strain_weakening_particles/solution/solution-00000.0000.gnuplot
  tests/visco_plastic_yield_viscous_strain_weakening_particles/statistics
Labels: ready to test

#3010 Get rid of the remaining uses of std::shared_ptr.
  benchmarks/operator_splitting/advection_reaction/advection_reaction.cc
  benchmarks/operator_splitting/exponential_decay/exponential_decay.cc
  include/aspect/material_model/averaging.h
  include/aspect/material_model/compositing.h
  include/aspect/material_model/depth_dependent.h
  include/aspect/material_model/grain_size.h
  include/aspect/material_model/interface.h
  include/aspect/material_model/steinberger.h
  source/material_model/interface.cc
  source/material_model/viscoelastic_plastic.cc
  tests/additional_outputs_02.cc
  tests/additional_outputs_03.cc
  tests/anisotropic_viscosity.cc
  tests/drucker_prager_derivatives.cc
  tests/multiple_named_additional_outputs.cc
  tests/prescribed_field.cc
  tests/prescribed_field_with_diffusion.cc
  tests/simple_nonlinear.cc
  tests/spiegelman_material.cc
  tests/visco_plastic_derivatives_2d.cc
  tests/visco_plastic_derivatives_3d.cc
Labels: ready to test

#3027 Add a note to the benchmark section of the manual.
  doc/manual/manual.bib
  doc/manual/manual.tex
Labels: documentation

#3032 cmake: fix file formatting
  tests/CMakeLists.txt
Labels: ready to merge, ready to test

#2998 Improved: Ascii datafile end-read warning message
  source/utilities.cc
  tests/ascii_boundary_member/screen-output
  tests/ascii_data_boundary_composition_2d_box_time/screen-output
  tests/ascii_data_boundary_composition_3d_box/screen-output
  tests/ascii_data_boundary_temperature_2d_box_time/screen-output
  tests/ascii_data_boundary_temperature_3d_box/screen-output
  tests/ascii_data_boundary_velocity_2d_box/screen-output
  tests/ascii_data_boundary_velocity_2d_box_list/screen-output
  tests/ascii_data_boundary_velocity_2d_box_time/screen-output
  tests/ascii_data_boundary_velocity_2d_box_time_backward/screen-output
  tests/ascii_data_boundary_velocity_2d_chunk/screen-output
  tests/ascii_data_boundary_velocity_2d_shell/screen-output
  tests/ascii_data_boundary_velocity_2d_shell_spherical/screen-output
  tests/ascii_data_boundary_velocity_3d_box/screen-output
  tests/ascii_data_boundary_velocity_3d_chunk/screen-output
  tests/ascii_data_boundary_velocity_3d_shell/screen-output
  tests/ascii_data_boundary_velocity_3d_shell_spherical/screen-output
  tests/ascii_data_boundary_velocity_3d_sphere/screen-output
  tests/box_initial_topography_ascii_data/screen-output
  tests/box_initial_topography_ascii_data_moved_origin/screen-output
  tests/traction_ascii_data/screen-output
Labels: ready to merge, ready to test

#3031 Provide a base class with a virtual destructor.
  include/aspect/postprocess/visualization.h
Labels: ready to test

#3008 Provide documentation to the SphericalShell constructor.
  include/aspect/geometry_model/spherical_shell.h
Labels: ready to test

#3033 Update a couple of comments in visualization.cc.
  source/postprocess/visualization.cc
Labels: ready to merge, ready to test

#3029 Assert that the viz postprocessors fall into known categories.
  source/postprocess/visualization.cc
Labels: ready to merge, ready to test

#3035 replace tabs with spaces and enforce using indent script
  benchmarks/annulus/CMakeLists.txt
  benchmarks/blankenbach/plugin/CMakeLists.txt
  benchmarks/burstedde/CMakeLists.txt
  benchmarks/crameri_et_al/case_1/CMakeLists.txt
  benchmarks/davies_et_al/case-2.3-plugin/CMakeLists.txt
  benchmarks/doneahuerta/CMakeLists.txt
  benchmarks/finite_strain/CMakeLists.txt
  benchmarks/hollow_sphere/CMakeLists.txt
  benchmarks/inclusion/CMakeLists.txt
  benchmarks/inclusion/compositional_fields/CMakeLists.txt
  benchmarks/king2dcompressible/CMakeLists.txt
  benchmarks/king2dcompressible/README
  benchmarks/king2dcompressible/ala.prm
  benchmarks/layeredflow/CMakeLists.txt
  benchmarks/newton_solver_benchmark_set/tosi_et_al_2015/input.prm
  benchmarks/nonlinear_channel_flow/CMakeLists.txt
  benchmarks/nsinker/CMakeLists.txt
  benchmarks/onset-of-convection/convection-box-base.prm
  benchmarks/operator_splitting/advection_reaction/CMakeLists.txt
  benchmarks/operator_splitting/exponential_decay/CMakeLists.txt
  benchmarks/shear_bands/CMakeLists.txt
  benchmarks/solcx/CMakeLists.txt
  benchmarks/solcx/compositional_fields/CMakeLists.txt
  benchmarks/solkz/CMakeLists.txt
  benchmarks/solkz/compositional_fields/CMakeLists.txt
  benchmarks/tangurnis/ba/tan.prm
  benchmarks/tangurnis/code/CMakeLists.txt
  benchmarks/tangurnis/tala/tan.prm
  benchmarks/tangurnis/tala_c/tan.prm
  benchmarks/time_dependent_annulus/plugin/CMakeLists.txt
  benchmarks/tosi_et_al_2015_gcubed/Tosi_Case1.prm
  benchmarks/tosi_et_al_2015_gcubed/Tosi_Case2.prm
  benchmarks/tosi_et_al_2015_gcubed/Tosi_Case3.prm
  benchmarks/tosi_et_al_2015_gcubed/Tosi_Case4.prm
  benchmarks/tosi_et_al_2015_gcubed/Tosi_Case5.prm
  benchmarks/tosi_et_al_2015_gcubed/Tosi_base.prm
  benchmarks/zhong_et_al_93/zhong_case1.prm
  contrib/utilities/indent
  cookbooks/finite_strain/CMakeLists.txt
  cookbooks/free-surface-with-crust/plugin/CMakeLists.txt
  cookbooks/inner_core_convection/CMakeLists.txt
  cookbooks/morency_doin_2004/CMakeLists.txt
  cookbooks/prescribed_velocity/CMakeLists.txt
  tests/ISA_rotation_timescale.prm
  tests/adiabatic_boundary.prm
  tests/artificial_postprocess.prm
  tests/boundary_heatflux.prm
  tests/grain_lag_angle.prm
  tests/king_ala.prm
  tests/no_flow.prm
  tests/quarter_shell_variable_coordinate_systems_cartesian.prm
  tests/quarter_shell_variable_coordinate_systems_depth.prm
  tests/quarter_shell_variable_coordinate_systems_spherical.prm
  tests/refinement_switch.prm
  tests/solidus_initial_conditions.prm
  tests/spherical_constant_boundary_3d_sphere.prm
  tests/topo_box.prm
  tests/topo_chunk.prm
  tests/topo_shell.prm
Labels: ready to merge, ready to test

#3037 Refactor writing data in the viz postprocessor.
  include/aspect/postprocess/visualization.h
  source/postprocess/visualization.cc
Labels: ready to test

#3028 cmake: do not configure test project every time
  CMakeLists.txt
  doc/manual/manual.tex
  doc/modules/changes/20190426_tjhei
Labels: ready to merge, ready to test

#3024 fix missing ElasticAdditionalOutputs instantiation
  source/material_model/viscoelastic.cc
Labels: ready to merge, ready to test

#2973 This is a supplementary explanation of using the minimum refinement function in manual
  cookbooks/muparser_temperature_example/muparser-temperature-example.prm
  doc/manual/cookbooks/muparser-temperature-example/mesh-refinement.part.prm
  doc/manual/cookbooks/muparser-temperature-example/temperature.part.prm
  doc/manual/manual.tex
Labels: ready to test

#3041 Add missing include files.
  source/material_model/rheology/constant_viscosity.cc
Labels: ready to test

#3021 Fix a minor error in gravity_point_values postprocessor
  source/postprocess/gravity_point_values.cc
  tests/gravity_point_values_map/output_gravity/gravity-00000
  tests/gravity_point_values_map/screen-output
Labels: ready to test

#3044 Mark up physical units in latex.
  source/boundary_composition/box.cc
  source/boundary_composition/two_merged_boxes.cc
  source/boundary_temperature/box.cc
  source/boundary_temperature/dynamic_core.cc
  source/boundary_temperature/function.cc
  source/boundary_temperature/initial_temperature.cc
  source/boundary_temperature/spherical_constant.cc
  source/boundary_temperature/two_merged_boxes.cc
  source/boundary_traction/initial_lithostatic_pressure.cc
  source/geometry_model/box.cc
  source/geometry_model/chunk.cc
  source/geometry_model/sphere.cc
  source/geometry_model/spherical_shell.cc
  source/geometry_model/two_merged_boxes.cc
  source/heating_model/radioactive_decay.cc
  source/initial_temperature/adiabatic.cc
  source/initial_temperature/adiabatic_boundary.cc
  source/initial_temperature/continental_geotherm.cc
  source/material_model/composition_reaction.cc
  source/material_model/diffusion_dislocation.cc
  source/material_model/drucker_prager.cc
  source/material_model/dynamic_friction.cc
  source/material_model/grain_size.cc
  source/material_model/latent_heat.cc
  source/material_model/latent_heat_melt.cc
  source/material_model/melt_global.cc
  source/material_model/melt_simple.cc
  source/material_model/multicomponent.cc
  source/material_model/perplex_lookup.cc
  source/material_model/simple.cc
  source/material_model/simpler.cc
  source/material_model/visco_plastic.cc
  source/material_model/viscoelastic.cc
  source/material_model/viscoelastic_plastic.cc
  source/postprocess/visualization/geoid.cc
  source/simulator/parameters.cc
Labels: ready to test

#3009 Move Lookup namespace from grain_size to material_model/utilities
  include/aspect/material_model/grain_size.h
  include/aspect/material_model/steinberger.h
  include/aspect/material_model/utilities.h
  source/material_model/grain_size.cc
  source/material_model/steinberger.cc
  source/material_model/utilities.cc
  tests/latent_heat_enthalpy.cc
Labels: ready to test

#3045 Fix incorrect formatting of the degree symbol.
  source/material_model/latent_heat_melt.cc
  source/postprocess/visualization/melt_fraction.cc
Labels: ready to test

#3025 Replace using std::shared_ptr in tests and benchmarks.
  benchmarks/annulus/annulus.cc
  benchmarks/burstedde/burstedde.cc
  benchmarks/doneahuerta/doneahuerta.cc
  benchmarks/hollow_sphere/hollow_sphere.cc
  benchmarks/inclusion/inclusion.h
  benchmarks/layeredflow/layeredflow.cc
  benchmarks/operator_splitting/advection_reaction/advection_reaction.cc
  benchmarks/operator_splitting/exponential_decay/exponential_decay.cc
  benchmarks/solcx/solcx.h
  tests/burstedde_stokes_rhs.cc
  tests/prescribed_velocity_boundary.cc
  tests/q1_q1.cc
Labels: ready to test

#2987 Initial GMG Stokes solver
  benchmarks/nsinker/nsinker_gmg.prm
  include/aspect/parameters.h
  include/aspect/simulator.h
  include/aspect/stokes_matrix_free.h
  source/simulator/assembly.cc
  source/simulator/core.cc
  source/simulator/parameters.cc
  source/simulator/solver.cc
  source/simulator/solver_schemes.cc
  source/simulator/stokes_matrix_free.cc
  tests/hollow_sphere_gmg.cc
  tests/hollow_sphere_gmg.prm
  tests/hollow_sphere_gmg/screen-output
  tests/sol_cx_2_gmg.cc
  tests/sol_cx_2_gmg.prm
  tests/sol_cx_2_gmg/screen-output
  tests/sol_cx_2_gmg/statistics
  tests/sol_cx_4_gmg.cc
  tests/sol_cx_4_gmg.prm
  tests/sol_cx_4_gmg/screen-output
  tests/sol_cx_4_gmg/statistics
Labels: ready to test

#2972 Provide a way to check whether the simulator has been completely initialized
  doc/modules/changes/20190522_bangerth-4
  doc/modules/changes/20190524_bangerth
  include/aspect/simulator.h
  include/aspect/simulator_access.h
  source/material_model/drucker_prager.cc
  source/simulator/core.cc
  source/simulator/simulator_access.cc
Labels: ready to test

#3055 Fix supg test results
  tests/supg/screen-output
  tests/supg/statistics
Labels: ready to merge, ready to test

#3004 new cookbook: polydiapirism
  benchmarks/polydiapirs/polydiapirs.prm
  doc/manual/cookbooks/polydiapirism/diapirs0000.png
  doc/manual/cookbooks/polydiapirism/diapirs0005.png
  doc/manual/cookbooks/polydiapirism/diapirs0010.png
  doc/manual/cookbooks/polydiapirism/diapirs0015.png
  doc/manual/cookbooks/polydiapirism/vrms.pdf
  doc/manual/manual.bib
  doc/manual/manual.tex
  doc/modules/changes/20190526_thieulot
Labels: ready to test

#3053 Rename a variable.
  include/aspect/simulator.h
  source/simulator/core.cc
  source/simulator/simulator_access.cc
Labels: ready to merge, ready to test

#3049 doxygen: add amssymb package
  doc/options.dox
Labels: ready to merge

#3056 Provide an error message for a case we ran into this morning.
  source/simulator/helper_functions.cc
Labels: ready to test

#3050 /benchmark/ fixes
  benchmarks/check.sh
  benchmarks/hollow_sphere/hollow_sphere.cc
  benchmarks/inclusion/inclusion.h
  tests/spectral_comparison.prm
Labels: ready to merge, ready to test

#3060 indent: fix tab replace on OSX
  contrib/utilities/indent
Labels: ready to merge

#3061 Use the \degree symbol for degrees in the manual.
  doc/manual/manual.tex
Labels: documentation, ready to test

#3063 re-indent Jenkinsfile
  Jenkinsfile
  Jenkinsfile.cig
Labels: ready to merge, ready to test

#3059 cleanup: introduce a new variable
  source/simulator/helper_functions.cc
Labels: ready to merge, ready to test

#3047 Fix: avoid MPI deadlock in constraints
  doc/modules/changes/20190527_tjhei
  source/simulator/core.cc
Labels: ready to merge

#3040 Further refactor the viz postprocessor.
  include/aspect/postprocess/visualization.h
  source/postprocess/visualization.cc
Labels: ready to test

#3062 Use the \degree symbol for degrees in the parameter descriptions.
  source/material_model/latent_heat_melt.cc
  source/material_model/melt_simple.cc
  source/postprocess/visualization/melt_fraction.cc
Labels: ready to test

#3026 Added benchmark of anelastic Vs to temperature conversion
  benchmarks/yamauchi_takei_2016_anelasticity/CMakeLists.txt
  benchmarks/yamauchi_takei_2016_anelasticity/anelasticity_temperature.cc
  benchmarks/yamauchi_takei_2016_anelasticity/anelasticity_temperature.h
  benchmarks/yamauchi_takei_2016_anelasticity/plot_output/50km_picked.txt
  benchmarks/yamauchi_takei_2016_anelasticity/plot_output/75km_picked.txt
  benchmarks/yamauchi_takei_2016_anelasticity/plot_output/YT16_benchmark.jpg
  benchmarks/yamauchi_takei_2016_anelasticity/plot_output/plot_output.gmt
  benchmarks/yamauchi_takei_2016_anelasticity/plot_output/yamauchi_takei_2016_figure20.jpg
  benchmarks/yamauchi_takei_2016_anelasticity/yamauchi_takei_2016_anelasticity.prm
  data/initial-temperature/ascii-data/test/box_2d_Vs_YT16.txt
  doc/manual/cookbooks/benchmarks/anelasticity/YT16_benchmark.png
  doc/manual/manual.bib
  doc/manual/manual.tex
Labels: ready to test

#3007 Initial Temperature Plug-in - Lithosphere mask
  data/initial-temperature/lithosphere_mask/LAB_CAM2016.txt
  doc/modules/changes/20190525_coulson
  include/aspect/initial_temperature/lithosphere_mask.h
  include/aspect/utilities.h
  source/initial_temperature/interface.cc
  source/initial_temperature/lithosphere_mask.cc
  source/initial_temperature/patch_on_S40RTS.cc
  source/utilities.cc
  tests/initial_condition_lithosphere_mask.prm
  tests/initial_condition_lithosphere_mask/screen-output
  tests/initial_condition_lithosphere_mask/solution/solution-00000.0000.gnuplot
  tests/initial_condition_lithosphere_mask/statistics
Labels: ready to test

#3081 Use a clearer way to check whether everything has been initialized.
  source/geometry_model/box.cc
  source/geometry_model/two_merged_boxes.cc
Labels: ready to test

#3082 Fix test files without newline at the end of the file.
  tests/particle_property_composition.cc
  tests/topo_chunk.prm
  tests/topo_shell.prm
Labels: ready to test

#3048 Added missing grid interpolator
  include/aspect/compat.h
Labels: ready to merge, ready to test

#3084 move and cleanup geomio.prm
  cookbooks/geomio/geomIO.prm
Labels: ready to merge, ready to test

#3087 Add get_model_operator_options function in utilities so operator options don't get out of sync
  include/aspect/utilities.h
  source/boundary_composition/interface.cc
  source/boundary_temperature/interface.cc
  source/initial_composition/interface.cc
  source/initial_temperature/interface.cc
  source/utilities.cc
Labels: ready to test

#3093 More latex markup.
  source/boundary_composition/box.cc
  source/boundary_composition/two_merged_boxes.cc
Labels: ready to test

#3091 use VectorTools::compute_global_error
  benchmarks/annulus/annulus.cc
  benchmarks/burstedde/burstedde.cc
  benchmarks/doneahuerta/doneahuerta.cc
  benchmarks/hollow_sphere/hollow_sphere.cc
  benchmarks/inclusion/inclusion.h
  benchmarks/layeredflow/layeredflow.cc
  benchmarks/operator_splitting/advection_reaction/advection_reaction.cc
  benchmarks/operator_splitting/exponential_decay/exponential_decay.cc
  benchmarks/solcx/solcx.h
  benchmarks/solitary_wave/solitary_wave.cc
  benchmarks/solkz/solkz.h
  benchmarks/time_dependent_annulus/plugin/time_dependent_annulus.h
  tests/burstedde_stokes_rhs.cc
  tests/hydrostatic_compression.cc
  tests/melt_compressible_advection.cc
  tests/melt_force_vector.cc
  tests/melt_force_vector/screen-output
  tests/melt_transport_adaptive.cc
  tests/melt_transport_adaptive/screen-output
  tests/melt_transport_compressible.cc
  tests/melt_transport_compressible/screen-output
  tests/melt_transport_compressible_iterative/screen-output
  tests/melt_transport_convergence_simple.cc
  tests/melt_transport_convergence_test.cc
  tests/prescribed_velocity_boundary.cc
  tests/q1_q1.cc
Labels: ready to merge, ready to test

#2999 Advection benchmark in 2d annulus
  benchmarks/advection_in_annulus/CMakeLists.txt
  benchmarks/advection_in_annulus/advection_in_annulus.cc
  benchmarks/advection_in_annulus/advection_in_annulus.prm
  benchmarks/advection_in_annulus/creates_formatted_tables.sh
  benchmarks/advection_in_annulus/plots_of_results/plot_results_panel_a.gnuplot
  benchmarks/advection_in_annulus/plots_of_results/plot_results_panel_b.gnuplot
  benchmarks/advection_in_annulus/plots_of_results/plot_results_panel_c.gnuplot
  benchmarks/advection_in_annulus/plots_of_results/plot_results_panel_d.gnuplot
  benchmarks/advection_in_annulus/plots_of_results/results_Q1_refinement4_beta0.052.dat
  benchmarks/advection_in_annulus/plots_of_results/results_Q1_refinement4_cR0.11.dat
  benchmarks/advection_in_annulus/plots_of_results/results_Q2_beta0.026_cR0.06.dat
  benchmarks/advection_in_annulus/plots_of_results/results_Q2_beta0.052_cR0.11.dat
  benchmarks/advection_in_annulus/plots_of_results/results_Q2_beta0.078_cR0.33.dat
  benchmarks/advection_in_annulus/plots_of_results/results_Q2_beta0.0_cR0.0.dat
  benchmarks/advection_in_annulus/plots_of_results/results_Q2_refinement4_beta0.052.dat
  benchmarks/advection_in_annulus/plots_of_results/results_Q2_refinement4_cR0.11.dat
  benchmarks/advection_in_annulus/plots_of_results/results_Q3_refinement4_beta0.052.dat
  benchmarks/advection_in_annulus/plots_of_results/results_Q3_refinement4_cR0.11.dat
  benchmarks/advection_in_annulus/run_all_models
  doc/modules/changes/20190529_euen
Labels: ready to test

#3094 Avoid using scientific notation for numbers in the manual.
  doc/manual/manual.tex
Labels: documentation, ready to test

#3013 Allow particles to be applied to fields when particles aren't distributed throughout model.
  include/aspect/particle/interpolator/cell_average.h
  include/aspect/particle/interpolator/harmonic_average.h
  include/aspect/particle/interpolator/nearest_neighbor.h
  source/particle/interpolator/cell_average.cc
  source/particle/interpolator/harmonic_average.cc
  source/particle/interpolator/nearest_neighbor.cc
Labels: ready to merge, ready to test

#2971 Add a new shear benchmark for instantaneous and time-dependent flow
  benchmarks/rigid_shear/README.md
  benchmarks/rigid_shear/instantaneous/create_formatted_tables.sh
  benchmarks/rigid_shear/instantaneous/results.txt
  benchmarks/rigid_shear/instantaneous/rigid_shear.prm
  benchmarks/rigid_shear/instantaneous/run_all_models
  benchmarks/rigid_shear/plugin/CMakeLists.txt
  benchmarks/rigid_shear/plugin/rigid_shear.cc
  benchmarks/rigid_shear/time-dependent/create_formatted_tables.sh
  benchmarks/rigid_shear/time-dependent/results_Q2_bilinear_least_squares_rk2.dat
  benchmarks/rigid_shear/time-dependent/results_Q2_bilinear_least_squares_rk4.dat
  benchmarks/rigid_shear/time-dependent/results_Q2_cell_average_rk2.dat
  benchmarks/rigid_shear/time-dependent/results_Q2_cell_average_rk4.dat
  benchmarks/rigid_shear/time-dependent/results_Q3_bilinear_least_squares_rk2.dat
  benchmarks/rigid_shear/time-dependent/results_Q3_bilinear_least_squares_rk4.dat
  benchmarks/rigid_shear/time-dependent/results_Q3_cell_average_rk2.dat
  benchmarks/rigid_shear/time-dependent/results_Q3_cell_average_rk4.dat
  benchmarks/rigid_shear/time-dependent/rigid_shear.prm
  benchmarks/rigid_shear/time-dependent/run_all_models
  doc/modules/changes/20190524_gassmoeller_2
  tests/rigid_shear_instantaneous.cc
  tests/rigid_shear_instantaneous.prm
  tests/rigid_shear_instantaneous/screen-output
  tests/rigid_shear_instantaneous/statistics
  tests/rigid_shear_time_dependent.cc
  tests/rigid_shear_time_dependent.prm
  tests/rigid_shear_time_dependent/screen-output
  tests/rigid_shear_time_dependent/statistics
Labels: ready to merge, ready to test

#3077 new groovy benchmark
  benchmarks/viscosity_grooves/gnuplot_script
  benchmarks/viscosity_grooves/viscosity_grooves.prm
  doc/manual/cookbooks/benchmarks/viscosity_grooves/conv_0p1.pdf
  doc/manual/cookbooks/benchmarks/viscosity_grooves/press3x3.png
  doc/manual/cookbooks/benchmarks/viscosity_grooves/rhs3x3.png
  doc/manual/cookbooks/benchmarks/viscosity_grooves/vel3x3.png
  doc/manual/cookbooks/benchmarks/viscosity_grooves/viscs.png
  doc/manual/manual.bib
  doc/manual/manual.tex
  doc/modules/changes/20190529_thieulot
Labels: ready to merge, ready to test

#3104 Implement natural_to_cartesian_coordinates for SphericalShell
  include/aspect/geometry_model/spherical_shell.h
  source/geometry_model/spherical_shell.cc
Labels: ready to merge, ready to test

#3064 The bibtex generated by Mendeley incorrectly categorizes several mast…
  doc/manual/citing_aspect.bib
Labels: ready to test

#3105 Rearrange savani_perturbation to be the same as s40rts_perturbation
  include/aspect/initial_temperature/SAVANI_perturbation.h
  source/initial_temperature/SAVANI_perturbation.cc
Labels: ready to test

#3097 Custom spherical shell
  include/aspect/geometry_model/spherical_shell.h
  source/geometry_model/spherical_shell.cc
  tests/custom_spherical_shell_2d_list.prm
  tests/custom_spherical_shell_2d_list/screen-output
  tests/custom_spherical_shell_2d_list/solution/solution-00000.0000.gnuplot
  tests/custom_spherical_shell_2d_list/statistics
  tests/custom_spherical_shell_2d_slices.prm
  tests/custom_spherical_shell_2d_slices/screen-output
  tests/custom_spherical_shell_2d_slices/solution/solution-00000.0000.gnuplot
  tests/custom_spherical_shell_2d_slices/statistics
  tests/custom_spherical_shell_3d_list.prm
  tests/custom_spherical_shell_3d_list/screen-output
  tests/custom_spherical_shell_3d_list/solution/solution-00000.0000.gnuplot
  tests/custom_spherical_shell_3d_list/statistics
  tests/custom_spherical_shell_3d_slices.prm
  tests/custom_spherical_shell_3d_slices/screen-output
  tests/custom_spherical_shell_3d_slices/solution/solution-00000.0000.gnuplot
  tests/custom_spherical_shell_3d_slices/statistics
Labels: ready to test

#3075 Multicomponent equation of state
  include/aspect/material_model/dynamic_friction.h
  include/aspect/material_model/equation_of_state/multicomponent_incompressible.h
  include/aspect/material_model/multicomponent.h
  include/aspect/material_model/visco_plastic.h
  include/aspect/material_model/viscoelastic.h
  include/aspect/material_model/viscoelastic_plastic.h
  source/material_model/dynamic_friction.cc
  source/material_model/equation_of_state/multicomponent_incompressible.cc
  source/material_model/multicomponent.cc
  source/material_model/visco_plastic.cc
  source/material_model/viscoelastic.cc
  source/material_model/viscoelastic_plastic.cc
  tests/viscoelastic_bending_beam/statistics
  tests/viscoelastic_plastic_bending_beam/statistics
Labels: ready to test

#3069 use natural_coordinates in boundary get_data_component
  include/aspect/geometry_model/sphere.h
  source/geometry_model/sphere.cc
  source/utilities.cc
Labels: ready to test

#3106 fix visco plastic get timestep number problem.
  source/material_model/visco_plastic.cc
Labels: ready to merge, ready to test

#3042 Benchmark for brittle thrust wedge experiments in Buiter et al., 2016,JSG paper
  benchmarks/buiter_et_al_2016_jsg/README
  benchmarks/buiter_et_al_2016_jsg/exp_2_high_resolution.prm
  benchmarks/buiter_et_al_2016_jsg/exp_2_low_resolution.prm
Labels: ready to test

#3100 New: Multicomponent compressible model
  doc/modules/changes/20190530_myhill
  include/aspect/material_model/equation_of_state/multicomponent_compressible.h
  include/aspect/material_model/multicomponent_compressible.h
  source/material_model/equation_of_state/multicomponent_compressible.cc
  source/material_model/multicomponent_compressible.cc
  tests/compressible_forsterite_box.prm
  tests/compressible_forsterite_box/screen-output
  tests/compressible_forsterite_box/solution/solution-00000.0000.gnuplot
  tests/compressible_forsterite_box/statistics
  tests/multicomponent_compressible_arithmetic_visocity_averaging/screen-output
  tests/multicomponent_compressible_arithmetic_visocity_averaging/statistics
Labels: ready to test

#3116 Fixed the steinberger_viscosity test
  tests/steinberger_viscosity.prm
  tests/steinberger_viscosity/depth_average.gnuplot
  tests/steinberger_viscosity/screen-output
  tests/steinberger_viscosity/statistics
  tests/steinberger_viscosity_adiabatic.prm
Labels: ready to test

#3123 add change log for custom spherical shell
  doc/modules/changes/20190530_jeanniot
Labels: ready to test
