Repository geodynamics/aspect, pull requests merged in 2020-07, with the labels that each got.

#3544 phase transition: average phase value
  doc/modules/changes/20200701_haoyuanli
  include/aspect/material_model/equation_of_state/interface.h
  include/aspect/material_model/utilities.h
  source/material_model/equation_of_state/interface.cc
  source/material_model/utilities.cc
  source/material_model/visco_plastic.cc
Labels: ready to test

#3591 unity build fixes
  CMakeLists.txt
  source/simulator/melt.cc
Labels: ready to merge

#3488 separate two merged boxes from box geometry model
  benchmarks/tosi_et_al_2015_gcubed/tosi.cc
  include/aspect/geometry_model/two_merged_boxes.h
  source/boundary_traction/initial_lithostatic_pressure.cc
  source/geometry_model/initial_topography_model/ascii_data.cc
  source/geometry_model/initial_topography_model/function.cc
  source/geometry_model/two_merged_boxes.cc
  source/initial_temperature/adiabatic.cc
  source/initial_temperature/harmonic_perturbation.cc
  source/particle/world.cc
  source/utilities.cc
Labels: ready to merge

#3593 disable world builder in cmake UNITY_BUILD
  CMakeLists.txt
Labels: ready to merge

#3602 Fix the name of a replacement function.
  include/aspect/particle/property/interface.h
Labels: documentation, ready to test

#3609 Add Heron et al 2020 to publication list
  doc/manual/citing_aspect.bib
Labels: ready to test

#3611 Enable unity build by default if possible
  CMakeLists.txt
  Jenkinsfile
  Jenkinsfile.cig
  doc/modules/changes/20200706_tjhei
Labels: ready to merge

#3613 Update visco plastic is yielding
  include/aspect/material_model/visco_plastic.h
  include/aspect/particle/property/viscoplastic_strain_invariants.h
  source/material_model/visco_plastic.cc
  source/particle/property/viscoplastic_strain_invariants.cc
Labels: ready to merge

#3617 Enable precompiling headers on CIG testers
  Jenkinsfile.cig
Labels: ready to merge

#3606 Update free surface cookbooks
  cookbooks/check.mk
  cookbooks/free-surface-with-crust/free-surface-with-crust.prm
  cookbooks/free-surface.prm
  cookbooks/free_surface/doc/free_surface.part.prm
  cookbooks/free_surface/doc/free_surface.tex
  cookbooks/free_surface/doc/free_surface_blob.png
  cookbooks/free_surface/doc/free_surface_topography.png
  cookbooks/free_surface/doc/plot.plt
  cookbooks/free_surface/free_surface.prm
  cookbooks/free_surface_with_crust/doc/free_surface_with_crust.part1.prm
  cookbooks/free_surface_with_crust/doc/free_surface_with_crust.part2.prm
  cookbooks/free_surface_with_crust/doc/free_surface_with_crust.png
  cookbooks/free_surface_with_crust/doc/free_surface_with_crust.tex
  cookbooks/free_surface_with_crust/doc/plot.plt
  cookbooks/free_surface_with_crust/doc/topography.png
  cookbooks/free_surface_with_crust/free_surface_with_crust.prm
  cookbooks/free_surface_with_crust/plugin/CMakeLists.txt
  cookbooks/free_surface_with_crust/plugin/simpler_with_crust.cc
  doc/Makefile
  doc/manual/cookbooks/free_surface
  doc/manual/cookbooks/free_surface/doc/free_surface_blob.png
  doc/manual/cookbooks/free_surface/doc/free_surface_topography.png
  doc/manual/cookbooks/free_surface/doc/freesurface.part.prm
  doc/manual/cookbooks/free_surface_with_crust
  doc/manual/cookbooks/free_surface_with_crust/doc/Topography.png
  doc/manual/cookbooks/free_surface_with_crust/doc/free-surface-wc.part1.prm
  doc/manual/cookbooks/free_surface_with_crust/doc/free-surface-wc.part2.prm
  doc/manual/cookbooks/free_surface_with_crust/doc/free-surfaceWC.png
  doc/manual/manual.tex
Labels: ready to merge

#3620 indent script: return failure
  contrib/utilities/indent
Labels: ready to merge

#3627 Fix cookbook phase for slow testers
  Jenkinsfile.cig
Labels: ready to merge

#3632 manual: update installation instructions to deal.II 9.2
  doc/manual/manual.tex
Labels: ready to merge

#3636 github-actions: test no-unity build and unittests
  .github/workflows/linux.yml
Labels: ready to merge

#3637 Keep everything of one class in one file.
  source/volume_of_fluid/assembly.cc
  source/volume_of_fluid/handler.cc
Labels: bug, ready to test
