Repository geodynamics/aspect, pull requests merged in 2020-08, with the labels that each got.

#3638 Address a warning.
  include/aspect/particle/property/integrated_strain.h
Labels: ready to merge, ready to test

#3634 Fix a problem with template explicit specializations.
  include/aspect/volume_of_fluid/utilities.h
  source/volume_of_fluid/setup_initial_conditions.cc
  source/volume_of_fluid/utilities.cc
  tests/vof_err_calc.h
Labels: bug, ready to test

#3641 github actions: enable -Werror
  .github/workflows/linux.yml
Labels: ready to merge

#3639 Speedup some unnecessarily slow tests
  tests/compression_heating.prm
  tests/compression_heating/screen-output
  tests/compression_heating/statistics
  tests/continental_extension.prm
  tests/continental_extension/screen-output
  tests/discontinuous_temperature_blankenbach.prm
  tests/discontinuous_temperature_blankenbach/screen-output
  tests/discontinuous_temperature_blankenbach/statistics
  tests/global_melt.prm
  tests/global_melt/screen-output
  tests/global_melt/statistics
  tests/global_melt_parallel.prm
  tests/global_melt_parallel/screen-output
  tests/global_melt_parallel/statistics
  tests/heat_advection_by_melt.prm
  tests/heat_advection_by_melt/screen-output
  tests/heat_advection_by_melt/statistics
  tests/particle_interpolator_nearest_neighbor.prm
  tests/particle_interpolator_nearest_neighbor/screen-output
  tests/particle_interpolator_nearest_neighbor/statistics
  tests/particle_interpolator_time_dependence.prm
  tests/particle_interpolator_time_dependence/screen-output
  tests/particle_interpolator_time_dependence/statistics
  tests/particle_melt_advection.prm
  tests/particle_melt_advection/particles/particles-00001.0000.gnuplot
  tests/particle_melt_advection/particles/particles-00007.0000.gnuplot
  tests/particle_melt_advection/screen-output
  tests/particle_melt_advection/statistics
  tests/rising_melt_blob_freezing.prm
  tests/rising_melt_blob_freezing/screen-output
  tests/rising_melt_blob_freezing/statistics
  tests/segregation_heating.prm
  tests/segregation_heating/screen-output
  tests/segregation_heating/statistics
  tests/shell_3d_gmg.prm
  tests/shell_3d_gmg/screen-output
  tests/statistics_output.prm
  tests/statistics_output/screen-output
  tests/statistics_output/statistics
  tests/vof_circle_mpi_amr.prm
  tests/vof_circle_mpi_amr/screen-output
  tests/vof_circle_mpi_amr/statistics
  tests/vof_linear_amr_mpi.prm
  tests/vof_linear_amr_mpi/screen-output
  tests/vof_linear_amr_mpi/statistics
  tests/vof_linear_periodic_amr.prm
  tests/vof_linear_periodic_amr/screen-output
  tests/vof_linear_periodic_amr/statistics
Labels: ready to merge

#3654 remove stray preprocessor command
  source/material_model/interface.cc
Labels: ready to merge, ready to test

#3655 add missing instantiation
  source/geometry_model/chunk.cc
Labels: ready to merge, ready to test

#3664 removed a now unnecessary compatibility fix for DEAL-II version
  source/geometry_model/spherical_shell.cc
  source/simulator/checkpoint_restart.cc
Labels: ready to merge, ready to test

#3659 Removed a now unnecessary compatibility fix
  source/postprocess/visualization.cc
Labels: ready to merge, ready to test

#3669 Remove unused input parameter
  source/material_model/visco_plastic.cc
Labels: ready to merge, ready to test

#3646 Jenkins: run testers with -O1
  Jenkinsfile
Labels: ready to merge

#3672 No need to have two backslashes in .h file documentation.
  include/aspect/material_model/viscoelastic.h
Labels: ready to merge

#3668 Added documentation for points in 3D case.
  source/boundary_velocity/gplates.cc
Labels: ready to merge, ready to test

#3667 Removed a now unnecessary compatibility fix
  source/simulator/core.cc
Labels: ready to merge, ready to test

#3660 Removed a now unnecessary compatibility fix
  source/particle/world.cc
Labels: ready to test

#3665 Remove dealii compatibility fix
  source/simulator/stokes_matrix_free.cc
  source/volume_of_fluid/assembler.cc
Labels: ready to test

#3663 Removed a now unnecessary compatibility fix
  source/simulator/entropy_viscosity.cc
Labels: ready to merge, ready to test

#3680 manual.tex: remove trailing whitespace
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#3677 markup for units in composition reaction
  doc/manual/parameters.tex
  source/material_model/composition_reaction.cc
Labels: ready to merge, ready to test

#3683 Lessen reliance on a friend declaration.
  source/mesh_deformation/interface.cc
Labels: ready to merge, ready to test

#3688 Removed a now unnecessary compatibility fix (KA)
  source/postprocess/memory_statistics.cc
Labels: ready to merge, ready to test

#3684 Fixes and updates to citing_aspect.bib
  doc/manual/citing_aspect.bib
Labels: ready to test

#3661 Removed a now unnecessary compatibility fix
  source/simulator/assembly.cc
  source/volume_of_fluid/reconstruct.cc
Labels: ready to test

#3679 Fix an error message in normalize.pl.
  tests/normalize.pl
Labels: ready to merge

#3687 Fixed default viscosity file for depth dependent model
  data/material-model/depth-dependent/visc_depth.txt
  source/material_model/depth_dependent.cc
  tests/depth_dependent_box_file_simple.prm
Labels: ready to test

#3690 Modify documentation of filename in asciiboundary.
  source/utilities.cc
Labels: ready to merge, ready to test

#3702 Minor cleanups.
  include/aspect/postprocess/visualization/gravity.h
  include/aspect/postprocess/visualization/spherical_velocity_components.h
Labels: ready to test

#3715 Avoid a warning about missing braces.
  source/material_model/rheology/strain_dependent.cc
Labels: ready to merge, ready to test

#3431 Fix use of invalid iterator
  source/mesh_deformation/interface.cc
  tests/free_surface_tangential_mesh_velocity_2.prm
  tests/free_surface_tangential_mesh_velocity_2/screen-output
  tests/free_surface_tangential_mesh_velocity_2/statistics
Labels: ready to merge, ready to test

#3716 Make global constants 'constexpr' variables.
  include/aspect/global.h
  source/global.cc
Labels: ready to test

#3662 Removed a now unnecessary compatibility fix
  source/postprocess/particles.cc
Labels: ready to merge, ready to test

#3670 fix typos and make text the same for viscoelastic and visco-plastic
  source/material_model/visco_plastic.cc
  source/material_model/viscoelastic.cc
Labels: ready to merge, ready to test

#3693 fix temperature dependence of viscosity in latent heat models
  doc/modules/changes/20200805_jdannberg
  source/material_model/latent_heat.cc
  source/material_model/latent_heat_melt.cc
  tests/latent_heat_viscosity_adiabatic.prm
  tests/latent_heat_viscosity_adiabatic/depth_average.gnuplot
  tests/latent_heat_viscosity_adiabatic/screen-output
  tests/latent_heat_viscosity_adiabatic/statistics
Labels: ready to merge

#3598 Calculate viscosity on phases
  doc/modules/changes/20200806_haoyuanli
  include/aspect/material_model/rheology/diffusion_creep.h
  include/aspect/material_model/rheology/dislocation_creep.h
  include/aspect/material_model/visco_plastic.h
  source/material_model/rheology/diffusion_creep.cc
  source/material_model/rheology/dislocation_creep.cc
  source/material_model/visco_plastic.cc
  tests/visco_plastic_phases_viscosity.prm
  tests/visco_plastic_phases_viscosity/screen-output
  tests/visco_plastic_phases_viscosity/statistics
Labels: ready to merge, ready to test

#3704 Fixed the url link and the LIBDAP environment variable
  contrib/opendap/prm_files/aspect_url_test.prm
  source/utilities.cc
Labels: ready to test

#3734 fix indentation
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_line_search.prm
Labels: ready to merge, ready to test

#3721 slightly loosen the tolerance for the Newton tests.
  tests/nonlinear_channel_flow_tractions_Newton_Stokes.prm
  tests/nonlinear_channel_flow_tractions_Newton_Stokes/screen-output
  tests/nonlinear_channel_flow_tractions_Newton_Stokes/solution/solution-00000.0000.gnuplot
  tests/nonlinear_channel_flow_tractions_Newton_Stokes/solution/solution-00001.0000.gnuplot
  tests/nonlinear_channel_flow_tractions_Newton_Stokes/statistics
  tests/nonlinear_channel_flow_tractions_Newton_Stokes_no_deviator.prm
  tests/nonlinear_channel_flow_tractions_Newton_Stokes_no_deviator/screen-output
  tests/nonlinear_channel_flow_tractions_Newton_Stokes_no_deviator/solution/solution-00000.0000.gnuplot
  tests/nonlinear_channel_flow_tractions_Newton_Stokes_no_deviator/solution/solution-00001.0000.gnuplot
  tests/nonlinear_channel_flow_tractions_Newton_Stokes_no_deviator/statistics
  tests/nonlinear_channel_flow_tractions_Newton_Stokes_no_line_search/screen-output
  tests/nonlinear_channel_flow_velocities_Newton_Stokes.prm
  tests/nonlinear_channel_flow_velocities_Newton_Stokes/screen-output
  tests/nonlinear_channel_flow_velocities_Newton_Stokes/solution/solution-00001.0000.gnuplot
  tests/nonlinear_channel_flow_velocities_Newton_Stokes/statistics
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_GMG/screen-output
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_GMG/statistics
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_deviator.prm
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_deviator/screen-output
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_deviator/solution/solution-00001.0000.gnuplot
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_deviator/statistics
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_line_search/screen-output
  tests/nonlinear_channel_flow_velocities_single_advection_Newton_Stokes/screen-output
  tests/nonlinear_channel_flow_velocities_single_advection_Newton_Stokes/solution/solution-00001.0000.gnuplot
  tests/nonlinear_channel_flow_velocities_single_advection_Newton_Stokes/statistics
Labels: ready to merge, ready to test

#3732 fix postprocessing nonlinear iterations in Newton schemes
  doc/modules/changes/20200807_jdannberg
  source/simulator/solver_schemes.cc
  tests/newton_postprocess_nonlinear.prm
  tests/newton_postprocess_nonlinear/screen-output
  tests/newton_postprocess_nonlinear/statistics
Labels: ready to merge, ready to test

#3678 Clarify description of some refinement function
  source/mesh_refinement/interface.cc
  source/simulator/parameters.cc
Labels: ready to test

#3735 fix deprecation warnings in tests
  tests/melt_transport_adaptive.cc
Labels: ready to merge

#3694 Update citing aspect
  doc/manual/manual.bib
Labels: ready to merge

#3749 fix gravity test.
  tests/gravity_function_time/screen-output
  tests/gravity_function_time/statistics
Labels: ready to merge

#3748 fix error in world builder for unity build
  contrib/world_builder/source/features/interface.cc
  contrib/world_builder/source/features/mantle_layer.cc
  contrib/world_builder/source/features/mantle_layer_models/grains/uniform.cc
Labels: ready to merge

#3692 Introduce TimeStepping::Manager
  include/aspect/simulator.h
  include/aspect/termination_criteria/interface.h
  include/aspect/time_stepping/interface.h
  source/simulator/core.cc
  source/simulator/helper_functions.cc
  source/simulator/parameters.cc
  source/termination_criteria/interface.cc
  source/time_stepping/interface.cc
Labels: ready to merge, ready to test

#3698 Adding option for FK viscosity in visco_plastic
  doc/modules/changes/20200807_erinheilman
  include/aspect/material_model/rheology/frank_kamenetskii.h
  include/aspect/material_model/visco_plastic.h
  source/material_model/rheology/frank_kamenetskii.cc
  source/material_model/visco_plastic.cc
  tests/visco_plastic_frank_kamenetskii.prm
  tests/visco_plastic_frank_kamenetskii/screen-output
  tests/visco_plastic_frank_kamenetskii/solution/solution-00000.0000.gnuplot
  tests/visco_plastic_frank_kamenetskii/statistics
Labels: ready to test

#3707 PerpleX lookup now uses column labels to assign properties
  include/aspect/material_model/utilities.h
  source/material_model/utilities.cc
Labels: ready to merge, ready to test

#3757 Use common spacing between functions in a few places.
  source/particle/property/integrated_strain_invariant.cc
  source/particle/property/interface.cc
Labels: ready to merge

#3686 AsciiDataLookup: allow directly initializing
  data/boundary-temperature/ascii-data/test/box_3d_bottom.0.txt
  data/initial-temperature/ascii-data/test/initial_isotherm_500K_box_3d.txt
  include/aspect/utilities.h
  source/utilities.cc
  unit_tests/utilities.cc
Labels: ready to merge, ready to test

#3711 add brackets to newton solver assembly.
  source/simulator/assemblers/newton_stokes.cc
  tests/nonlinear_channel_flow_tractions_Newton_Stokes/screen-output
  tests/nonlinear_channel_flow_tractions_Newton_Stokes/solution/solution-00000.0000.gnuplot
  tests/nonlinear_channel_flow_tractions_Newton_Stokes/solution/solution-00001.0000.gnuplot
  tests/nonlinear_channel_flow_tractions_Newton_Stokes/statistics
  tests/nonlinear_channel_flow_tractions_Newton_Stokes_no_deviator/screen-output
  tests/nonlinear_channel_flow_tractions_Newton_Stokes_no_deviator/solution/solution-00000.0000.gnuplot
  tests/nonlinear_channel_flow_tractions_Newton_Stokes_no_deviator/solution/solution-00001.0000.gnuplot
  tests/nonlinear_channel_flow_tractions_Newton_Stokes_no_deviator/statistics
  tests/nonlinear_channel_flow_tractions_Newton_Stokes_no_line_search/screen-output
  tests/nonlinear_channel_flow_velocities_Newton_Stokes/screen-output
  tests/nonlinear_channel_flow_velocities_Newton_Stokes/statistics
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_derivative/screen-output
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_derivative/statistics
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_derivative_EW/screen-output
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_derivative_EW/solution/solution-00001.0000.gnuplot
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_derivative_EW/statistics
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_deviator/screen-output
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_deviator/statistics
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_line_search/screen-output
  tests/nonlinear_channel_flow_velocities_single_advection_Newton_Stokes/screen-output
  tests/nonlinear_channel_flow_velocities_single_advection_Newton_Stokes/statistics
  tests/spiegelman_fail_test/screen-output
  tests/visco_plastic_newton_nonlinear_channelflow/screen-output
Labels: ready to test

#3744 Cookbooks files movearound
  cookbooks/burnman/burnman.prm
  cookbooks/burnman/doc/adiabatic_conditions.part.prm
  cookbooks/burnman/doc/burnman.tex
  cookbooks/burnman/doc/comparison.pdf
  cookbooks/burnman/doc/formulation.part.prm
  cookbooks/burnman/doc/formulation_ica.part.prm
  cookbooks/burnman/doc/gravity_model.part.prm
  cookbooks/burnman/doc/material_model.part.prm
  cookbooks/burnman/doc/plot_reference_profile.plt
  cookbooks/burnman/doc/plot_vrms.plt
  cookbooks/burnman/doc/reference_profile.pdf
  cookbooks/burnman/doc/statistics_ala
  cookbooks/burnman/doc/statistics_ica
  cookbooks/burnman/doc/statistics_tala
  cookbooks/burnman/doc/tala.part.prm
  cookbooks/burnman/doc/temperature.png
  cookbooks/burnman/doc/viscosity.png
  cookbooks/burnman/doc/vrms.pdf
  doc/manual/cookbooks/burnman
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#3761 Fix a typo.
  source/utilities.cc
Labels: ready to merge

#3754 played with timestepping and added my results in the readme
  benchmarks/free_surface_tractions/viscoelastic/README
Labels: ready to merge, ready to test

#3703 Output the stress as a tensor, rather than individual scalar components.
  doc/modules/changes/20200811_bangerth
  include/aspect/postprocess/visualization/shear_stress.h
  include/aspect/postprocess/visualization/strain_rate.h
  include/aspect/postprocess/visualization/stress.h
  source/postprocess/visualization/shear_stress.cc
  source/postprocess/visualization/strain_rate_tensor.cc
  source/postprocess/visualization/stress.cc
  tests/chunk_lithostatic_pressure_2d/solution/solution-00000.0000.gnuplot
  tests/stress_vs_surface_stress/solution/solution-00000.0000.gnuplot
  tests/visualization_shear_stress/solution/solution-00000.0000.gnuplot
  tests/visualization_shear_stress_pointwise/solution/solution-00000.0000.gnuplot
  tests/visualization_stress/solution/solution-00000.0000.gnuplot
  tests/visualization_stress_pointwise/solution/solution-00000.0000.gnuplot
Labels: ready to test

#3772 added constructor for NamedAdditionalMaterialOutputs
  include/aspect/material_model/interface.h
  source/material_model/interface.cc
Labels: ready to test

#3766 Fix frank kamenetskii rheology
  include/aspect/material_model/visco_plastic.h
  source/material_model/rheology/frank_kamenetskii.cc
  source/material_model/visco_plastic.cc
  tests/visco_plastic_derivatives_2d.cc
  tests/visco_plastic_derivatives_3d.cc
  tests/visco_plastic_phases_viscosity.prm
Labels: ready to merge, ready to test

#3777 Changed dash to underscore convection_box_3d
  cookbooks/convection_box_3d.prm
  doc/manual/cookbooks/convection_box_3d/doc/amr.part.prm
  doc/manual/cookbooks/convection_box_3d/doc/checkpoint.part.prm
  doc/manual/cookbooks/convection_box_3d/doc/gravity.part.prm
  doc/manual/cookbooks/convection_box_3d/doc/heat-flux.png
  doc/manual/cookbooks/convection_box_3d/doc/initial.part.prm
  doc/manual/cookbooks/convection_box_3d/doc/mesh0060.png
  doc/manual/cookbooks/convection_box_3d/doc/mesh0100.png
  doc/manual/cookbooks/convection_box_3d/doc/mesh0180.png
  doc/manual/cookbooks/convection_box_3d/doc/movie0010.png
  doc/manual/cookbooks/convection_box_3d/doc/movie0040.png
  doc/manual/cookbooks/convection_box_3d/doc/movie0060.png
  doc/manual/cookbooks/convection_box_3d/doc/movie0100.png
  doc/manual/cookbooks/convection_box_3d/doc/movie0130.png
  doc/manual/cookbooks/convection_box_3d/doc/movie0180.png
  doc/manual/cookbooks/convection_box_3d/doc/postprocess.part.prm
  doc/manual/cookbooks/convection_box_3d/doc/start.part.prm
  doc/manual/manual.tex
Labels: ready to test

#3709 Optimize the newton solver scheme rebuild flags.
  source/simulator/solver_schemes.cc
  tests/prescribed_dilation_newton/screen-output
Labels: ready to merge, ready to test

#3784 Cookbooks movearound
  cookbooks/burnman/doc/burnman.tex
  cookbooks/continental_extension/continental_extension.prm
  cookbooks/continental_extension/doc/continental_extension.tex
  cookbooks/continental_extension/doc/continental_extension_boundary_conditions.prm
  cookbooks/continental_extension/doc/continental_extension_composition.prm
  cookbooks/continental_extension/doc/continental_extension_cookbook_composition_5e6yr.png
  cookbooks/continental_extension/doc/continental_extension_cookbook_strainrate_5e6yr.png
  cookbooks/continental_extension/doc/continental_extension_cookbook_strainrate_highres_10e6yr.png
  cookbooks/continental_extension/doc/continental_extension_geometry_mesh.prm
  cookbooks/continental_extension/doc/continental_extension_material_model.prm
  cookbooks/crustal_deformation/crustal_model_2D.prm
  cookbooks/crustal_deformation/crustal_model_3D.prm
  cookbooks/crustal_deformation/doc/all3D.png
  cookbooks/crustal_deformation/doc/both.png
  cookbooks/crustal_deformation/doc/bottombc2.png
  cookbooks/crustal_deformation/doc/crustal_deformation.tex
  cookbooks/crustal_deformation/doc/crustal_model_2D_part1.prm
  cookbooks/crustal_deformation/doc/crustal_model_2D_part2.prm
  cookbooks/crustal_deformation/doc/crustal_model_2D_part3.prm
  cookbooks/crustal_deformation/doc/crustal_model_2D_part4.prm
  cookbooks/crustal_deformation/doc/crustal_model_3D_part1.prm
  cookbooks/crustal_deformation/doc/grids.png
  doc/manual/cookbooks/continental_extension
  doc/manual/cookbooks/crustal_deformation
  doc/manual/manual.tex
  tests/continental_extension.prm
Labels: ready to merge, ready to test

#3739 Modified calculate_isostrain_viscosities function inputs.
  include/aspect/material_model/visco_plastic.h
  source/material_model/visco_plastic.cc
Labels: ready to test

#3780 Adding some helpful comments to GMG code
  include/aspect/stokes_matrix_free.h
  source/simulator/stokes_matrix_free.cc
Labels: ready to test

#3789 Fix a whitespace problem.
  source/boundary_traction/initial_lithostatic_pressure.cc
Labels: ready to merge

#3793 Fix grammar.
  source/simulator/solver_schemes.cc
  tests/spiegelman_fail_test/screen-output
Labels: ready to merge

#3791 correct quotes type in lithosphere mask manual entry
  source/initial_temperature/lithosphere_mask.cc
Labels: ready to merge, ready to test

#3801 rename viscosity argument to base_viscosity in ConstantViscosityPrefactors
  include/aspect/material_model/rheology/constant_viscosity_prefactors.h
  source/material_model/rheology/constant_viscosity_prefactors.cc
Labels: ready to merge, ready to test

#3810 corrected manual typos
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#3813 Fix function name
  include/aspect/mesh_deformation/interface.h
Labels: ready to merge, ready to test

#3811 fixed some typos in source code comments/doc strings
  benchmarks/time_dependent_annulus/plugin/time_dependent_annulus.cc
  benchmarks/time_dependent_annulus/plugin/time_dependent_annulus.h
  source/boundary_temperature/dynamic_core.cc
  source/heating_model/compositional_heating.cc
  source/initial_composition/ascii_data_layered.cc
  source/material_model/diffusion_dislocation.cc
  source/material_model/grain_size.cc
  source/material_model/visco_plastic.cc
  source/postprocess/geoid.cc
  source/postprocess/gravity_point_values.cc
  source/postprocess/particles.cc
  source/simulator/core.cc
  source/simulator/solver_schemes.cc
  source/simulator/stokes_matrix_free.cc
  source/termination_criteria/end_walltime.cc
  source/volume_of_fluid/handler.cc
  source/volume_of_fluid/utilities.cc
Labels: ready to merge, ready to test

#3782 Use range-based for loops in a variety of places.
  source/boundary_temperature/constant.cc
  source/boundary_temperature/two_merged_boxes.cc
  source/boundary_velocity/interface.cc
  source/geometry_model/interface.cc
  source/initial_temperature/interface.cc
  source/mesh_deformation/free_surface.cc
  source/mesh_deformation/function.cc
  source/mesh_deformation/interface.cc
  source/mesh_refinement/interface.cc
  source/particle/generator/reference_cell.cc
  source/particle/interpolator/cell_average.cc
  source/particle/interpolator/harmonic_average.cc
  source/particle/property/interface.cc
  source/particle/world.cc
  source/postprocess/depth_average.cc
  source/postprocess/heat_flux_statistics.cc
  source/postprocess/interface.cc
  source/postprocess/mass_flux_statistics.cc
  source/postprocess/particles.cc
  source/postprocess/point_values.cc
  source/postprocess/velocity_boundary_statistics.cc
  source/postprocess/visualization.cc
  source/simulator/core.cc
  source/simulator/helper_functions.cc
  source/simulator/parameters.cc
  source/termination_criteria/interface.cc
  source/volume_of_fluid/handler.cc
Labels: ready to merge

#3812 fixed typos in deep source and header files
  include/aspect/adiabatic_conditions/compute_profile.h
  include/aspect/boundary_temperature/dynamic_core.h
  include/aspect/geometry_model/ellipsoidal_chunk.h
  include/aspect/geometry_model/initial_topography_model/interface.h
  include/aspect/geometry_model/two_merged_boxes.h
  include/aspect/material_model/grain_size.h
  include/aspect/material_model/interface.h
  include/aspect/material_model/rheology/diffusion_creep.h
  include/aspect/material_model/rheology/dislocation_creep.h
  include/aspect/material_model/utilities.h
  include/aspect/material_model/visco_plastic.h
  include/aspect/material_model/viscoelastic.h
  include/aspect/particle/generator/interface.h
  include/aspect/particle/interpolator/bilinear_least_squares.h
  include/aspect/postprocess/gravity_point_values.h
  include/aspect/postprocess/load_balance_statistics.h
  include/aspect/postprocess/particles.h
  include/aspect/postprocess/visualization/temperature_anomaly.h
  include/aspect/stokes_matrix_free.h
  include/aspect/time_stepping/interface.h
  include/aspect/volume_of_fluid/handler.h
  source/material_model/rheology/elasticity.cc
  source/particle/generator/probability_density_function.cc
  source/particle/property/elastic_stress.cc
  source/postprocess/visualization/temperature_anomaly.cc
  source/simulator/assemblers/newton_stokes.cc
Labels: ready to merge, ready to test

#3787 Newton fail test fix
  source/simulator/solver_schemes.cc
  tests/prescribed_dilation_newton/screen-output
  tests/sol_cx_newton_crash.cc
  tests/sol_cx_newton_crash.prm
  tests/sol_cx_newton_crash/screen-output
  tests/sol_cx_newton_crash/statistics
Labels: ready to merge, ready to test

#3759 added new strain rate and derivative functions to diffusion and dislocation creep
  doc/modules/changes/20200814b_bobmyhill
  include/aspect/material_model/diffusion_dislocation.h
  include/aspect/material_model/rheology/diffusion_creep.h
  include/aspect/material_model/rheology/dislocation_creep.h
  source/material_model/diffusion_dislocation.cc
  source/material_model/rheology/diffusion_creep.cc
  source/material_model/rheology/dislocation_creep.cc
Labels: ready to test

#3733 Perplex lookup volume fractions
  contrib/perplex/create_aspect_readable_perplex_table_with_phase_volumes.py
  data/material-model/steinberger/morb_G13_with_volume_fractions_lo_res.dat
  data/material-model/steinberger/pyr_MS95_with_volume_fractions_lo_res.dat
  doc/modules/changes/20200814_bobmyhill
  include/aspect/material_model/steinberger.h
  include/aspect/material_model/utilities.h
  source/material_model/steinberger.cc
  source/material_model/utilities.cc
  tests/steinberger_phase_fractions.prm
  tests/steinberger_phase_fractions/screen-output
  tests/steinberger_phase_fractions/solution/solution-00000.0000.gnuplot
  tests/steinberger_phase_fractions/solution/solution-00001.0000.gnuplot
  tests/steinberger_phase_fractions/statistics
  tests/steinberger_phase_fractions_background.prm
  tests/steinberger_phase_fractions_background/screen-output
  tests/steinberger_phase_fractions_background/solution/solution-00000.0000.gnuplot
  tests/steinberger_phase_fractions_background/solution/solution-00001.0000.gnuplot
  tests/steinberger_phase_fractions_background/statistics
Labels: ready to test

#3817 Ignore differences in line endings on Windows and Linux.
  tests/cmake/diff_test.sh
Labels: ready to test

#3671 Quadratic least squares particle interpolation
  doc/modules/changes/20200819_sac-bsa
  include/aspect/particle/interpolator/quadratic_least_squares.h
  source/particle/interpolator/quadratic_least_squares.cc
  tests/particle_interpolator_quadratic_least_squares_2d_add_particles.cc
  tests/particle_interpolator_quadratic_least_squares_2d_add_particles.prm
  tests/particle_interpolator_quadratic_least_squares_2d_add_particles/screen-output
  tests/particle_interpolator_quadratic_least_squares_2d_add_particles/statistics
  tests/particle_interpolator_quadratic_least_squares_3d.prm
  tests/particle_interpolator_quadratic_least_squares_3d/screen-output
  tests/particle_interpolator_quadratic_least_squares_3d/statistics
Labels: ready to merge, ready to test

#3797 Cookbooks in folder
  cookbooks/composition_active/composition_active.prm
  cookbooks/composition_active/doc/active.part.prm
  cookbooks/composition_active/doc/composition_active.tex
  cookbooks/composition_active/doc/postprocess.part.prm
  cookbooks/composition_active/doc/visit0000.png
  cookbooks/composition_active/doc/visit0001.png
  cookbooks/composition_active/doc/visit0002.png
  cookbooks/composition_active/doc/visit0003.png
  cookbooks/composition_active/doc/visit0004.png
  cookbooks/composition_active/doc/visit0005.png
  cookbooks/composition_active/doc/visit0006.png
  cookbooks/composition_active/doc/visit0007.png
  cookbooks/composition_active/doc/visit0008.png
  cookbooks/composition_active/doc/visit0009.png
  cookbooks/composition_active_particles/composition_active_particles.prm
  cookbooks/composition_active_particles/doc/composition.part.prm
  cookbooks/composition_active_particles/doc/composition_active_particles.tex
  cookbooks/composition_active_particles/doc/particles.part.prm
  cookbooks/composition_passive/composition_passive.prm
  cookbooks/composition_passive/doc/composition_passive.tex
  cookbooks/composition_passive/doc/mass-composition-1.png
  cookbooks/composition_passive/doc/passive.part.prm
  cookbooks/composition_passive/doc/postprocess.part.prm
  cookbooks/composition_passive/doc/visit0007.png
  cookbooks/composition_passive/doc/visit0008.png
  cookbooks/composition_passive/doc/visit0009.png
  cookbooks/composition_passive/doc/visit0010.png
  cookbooks/composition_passive/doc/visit0011.png
  cookbooks/composition_passive/doc/visit0012.png
  cookbooks/composition_passive/doc/visit0013.png
  cookbooks/composition_passive/doc/visit0014.png
  cookbooks/composition_passive/doc/visit0015.png
  cookbooks/composition_passive/doc/visit0017.png
  cookbooks/composition_passive_particles/composition_passive_particles.prm
  cookbooks/composition_passive_particles/composition_passive_particles_properties.prm
  cookbooks/composition_passive_particles/doc/composition-C1.png
  cookbooks/composition_passive_particles/doc/composition_passive_particles.tex
  cookbooks/composition_passive_particles/doc/initial-position-00000.png
  cookbooks/composition_passive_particles/doc/initial-position-00199.png
  cookbooks/composition_passive_particles/doc/particle-properties.part.prm
  cookbooks/composition_passive_particles/doc/particles-C1.png
  cookbooks/composition_passive_particles/doc/particles.part.prm
  cookbooks/composition_passive_particles/doc/solution-00072.png
  doc/manual/cookbooks/composition_active
  doc/manual/cookbooks/composition_active_particles
  doc/manual/cookbooks/composition_passive
  doc/manual/cookbooks/composition_passive_particles
  doc/manual/manual.tex
Labels: ready to test

#3425 Add VOF Van Keken benchmark section
  cookbooks/van-keken-vof/doc/amr.part.prm
  cookbooks/van-keken-vof/doc/init_diff_rms_vel_comparison.png
  cookbooks/van-keken-vof/doc/main.part.prm
  cookbooks/van-keken-vof/doc/postprocess.part.prm
  cookbooks/van-keken-vof/doc/rms_vel_comparison.png
  cookbooks/van-keken-vof/doc/van-keken-vof.tex
  cookbooks/van-keken-vof/doc/variation.part.prm
  cookbooks/van-keken-vof/doc/vof_van_keken_refinement_comparison.png
  cookbooks/van-keken-vof/van-keken-vof.prm
  doc/manual/cookbooks/van-keken-vof
  doc/manual/manual.bib
  doc/manual/manual.tex
Labels: ready to test

#3831 Make cmake command UPPERCASE.
  CMakeLists.txt
Labels: ready to test

#3830 Make all captions italics.
  cookbooks/van-keken-vof/doc/van-keken-vof.tex
  doc/manual/manual.tex
Labels: ready to test
