Repository geodynamics/aspect, pull requests merged in 2020-04, with the labels that each got.

#3438 Set the precision of gravity to 12 in gravity_point_values postprocessor
  doc/modules/changes/20200330_jeanniot
  include/aspect/postprocess/gravity_point_values.h
  source/postprocess/gravity_point_values.cc
Labels: ready to test

#3449 fix GMG for compressible computations - correct_stokes_rhs()
  source/simulator/assembly.cc
  source/simulator/stokes_matrix_free.cc
  tests/prescribed_dilation_gmg.cc
  tests/prescribed_dilation_gmg.prm
  tests/prescribed_dilation_gmg/screen-output
  tests/simple_compressibility_iterated_stokes_gmg.cc
  tests/simple_compressibility_iterated_stokes_gmg.prm
  tests/simple_compressibility_iterated_stokes_gmg/screen-output
  tests/steinberger_compressible_gmg.prm.dealii9.2
  tests/steinberger_compressible_gmg/screen-output
  tests/steinberger_compressible_gmg/statistics
Labels: ready to test

#3455 fix trilinos amg bug
  source/simulator/assembly.cc
Labels: ready to test

#3465 Make spacing in one file more uniform.
  source/boundary_velocity/gplates.cc
Labels: ready to test

#3469 Use Utilities::fexists where appropriate
  source/simulator/checkpoint_restart.cc
  source/simulator/parameters.cc
  source/termination_criteria/user_request.cc
Labels: ready to merge

#3471 add missing deal.II header
  source/mesh_deformation/interface.cc
  source/simulator/stokes_matrix_free.cc
Labels: ready to merge

#3485 Cookbooks folder conversion: gplates
  cookbooks/gplates/doc/gplates-comparison.png
  cookbooks/gplates/doc/gplates.part.prm
  cookbooks/gplates/doc/gplates.tex
  cookbooks/gplates/doc/slice1.part.prm
  cookbooks/gplates/doc/slice2.part.prm
  cookbooks/gplates/gplates_2d.prm
  cookbooks/gplates/gplates_3d.prm
  doc/manual/cookbooks/gplates
  doc/manual/manual.tex
Labels: ready to merge

#3464 Make error message clearer.
  source/boundary_velocity/gplates.cc
  tests/burnman_seismic_test/screen-output
  tests/burnman_test/screen-output
  tests/depth_dependent_initialize_base_model/screen-output
  tests/gplates_1_3/screen-output
  tests/gplates_1_4/screen-output
  tests/gplates_3d/screen-output
  tests/gplates_rotation/screen-output
  tests/latent_heat_viscosity/screen-output
Labels: ready to merge, ready to test
