Repository geodynamics/aspect, pull requests merged in 2020-12, with the labels that each got.

#3893 Modified the plugin for depths more than the input viscosity file.
  tests/rheology_scaled_profile.cc
Labels: ready to test

#3908 ViscoPlastic rheology migrated into separate rheology module
  doc/modules/changes/20201130_bobmyhill
  include/aspect/material_model/rheology/visco_plastic.h
  include/aspect/material_model/visco_plastic.h
  source/material_model/rheology/visco_plastic.cc
  source/material_model/visco_plastic.cc
Labels: ready to test

#3924 remove some unnecessary includes
  source/simulator/helper_functions.cc
Labels: ready to merge

#3798 new mantle convection cookbook
  cookbooks/bunge_et_al_mantle_convection/bunge_et_al.prm
  cookbooks/bunge_et_al_mantle_convection/visc_depth_a.txt
  cookbooks/bunge_et_al_mantle_convection/visc_depth_b.txt
  cookbooks/bunge_et_al_mantle_convection/visc_depth_c.txt
  cookbooks/bunge_et_al_mantle_convection/visc_depth_d.txt
  doc/manual/cookbooks/bunge_et_al_mantle_convection/temps.png
  doc/manual/manual.bib
  doc/manual/manual.tex
Labels: ready to test, work in progress

#3926 add new citation Negredo et al.
  doc/manual/citing_aspect.bib
Labels: ready to test
