Repository geodynamics/aspect, pull requests merged in 2020-06, with the labels that each got.

#3496 Change input method, allowing single input value for compositions and…
  doc/modules/changes/20200506_haoyuanli
  source/material_model/equation_of_state/multicomponent_incompressible.cc
  source/utilities.cc
  unit_tests/parse_map_to_double_array.cc
Labels: ready to test

#3510 add IDR(s) Stokes Kylov solver
  doc/modules/changes/20200525_clevenger
  include/aspect/parameters.h
  source/simulator/parameters.cc
  source/simulator/stokes_matrix_free.cc
  tests/nsinker_gmg_idr.cc
  tests/nsinker_gmg_idr.prm.dealii_9.2
  tests/nsinker_gmg_idr/screen-output
Labels: ready to test

#3500 Add Viscoelastic Cantilever Benchmark
  benchmarks/viscoelastic_beam_modified/20km_opentopbot.prm
  benchmarks/viscoelastic_beam_modified/beam_image_error.ipynb
  benchmarks/viscoelastic_beam_modified/flexure_with_time.ipynb
  benchmarks/viscoelastic_beam_modified/sigma_profile.ipynb
  benchmarks/viscoelastic_beam_modified/sigma_with_time.ipynb
  doc/modules/changes/20200513_douglas
Labels: ready to test

#3527 Add geoid citation info
  include/aspect/postprocess/visualization/geoid.h
  source/postprocess/geoid.cc
  source/postprocess/visualization/geoid.cc
Labels: ready to test

#3523 added Heyn et al. 2020 to pub list
  doc/manual/citing_aspect.bib
Labels: ready to merge, ready to test

#3529 Add to citating_aspect Glerum & Muluneh
  doc/manual/citing_aspect.bib
Labels: ready to test

#3495 add Q1 viscosity projection for GMG
  doc/modules/changes/20200616_clevenger
  include/aspect/stokes_matrix_free.h
  source/simulator/stokes_matrix_free.cc
  tests/hollow_sphere_gmg_project_q1.cc
  tests/hollow_sphere_gmg_project_q1.prm
  tests/hollow_sphere_gmg_project_q1/screen-output
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_GMG/screen-output
Labels: ready to test

#3564 update copyright
  include/aspect/compat.h
  source/postprocess/visualization/temperature_anomaly.cc
  unit_tests/additional_outputs.cc
Labels: ready to merge

#3563 make_cite_html.py fix formatting in citation
  doc/make_cite_html.py
Labels: ready to merge

#3568 adding the two missing files of the viscosity_grooves benchmark
  benchmarks/viscosity_grooves/CMakeLists.txt
  benchmarks/viscosity_grooves/viscosity_grooves.cc
Labels: ready to test

#3569 update viscosity_grooves benchmark
  benchmarks/check.mk
  benchmarks/viscosity_grooves/CMakeLists.txt
  benchmarks/viscosity_grooves/viscosity_grooves.cc
Labels: ready to merge
