Repository geodynamics/aspect, pull requests merged in 2020-09, with the labels that each got.

#3820 New: Add Peierls exact formulation
  doc/modules/changes/20200829b_bobmyhill
  include/aspect/material_model/rheology/peierls_creep.h
  source/material_model/rheology/peierls_creep.cc
  tests/visco_plastic_peierls_mei_exact.prm
  tests/visco_plastic_peierls_mei_exact/screen-output
  tests/visco_plastic_peierls_mei_exact/statistics
Labels: ready to test

#3436 Qr bilinear interpolation
  source/particle/interpolator/bilinear_least_squares.cc
Labels: ready to test

#3836 Cleanup some tests
  tests/nonlinear_channel_flow_velocities_Newton_Stokes.prm
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_GMG.cc
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_derivative.prm
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_derivative_EW.prm
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_deviator.prm
  tests/nonlinear_channel_flow_velocities_iterated_IMPES.prm
Labels: ready to merge

#3809 corrected vof parameter typo
  cookbooks/van-keken-vof/doc/main.part.prm
  cookbooks/van-keken-vof/doc/variation.part.prm
  cookbooks/van-keken-vof/van-keken-vof.prm
  source/volume_of_fluid/handler.cc
  tests/vof_circle_1.prm
  tests/vof_circle_amr.prm
  tests/vof_circle_mpi.prm
  tests/vof_circle_mpi_amr.prm
  tests/vof_composition_init.prm
  tests/vof_linear.prm
  tests/vof_linear_2f.prm
  tests/vof_linear_amr.prm
  tests/vof_linear_amr_mpi.prm
  tests/vof_linear_periodic.prm
  tests/vof_linear_periodic_amr.prm
  tests/vof_mpi_amr_no_dof.prm
Labels: ready to merge, ready to test

#3600 Boundary velocity residual postprocessor
  data/postprocess/boundary-velocity-residual/shell_3d_boundary_velocity.txt
  doc/modules/changes/20200902_alarshi
  include/aspect/postprocess/visualization/boundary_velocity_residual.h
  source/postprocess/visualization/boundary_velocity_residual.cc
  tests/ascii_data_boundary_velocity_residual_shell.prm
  tests/ascii_data_boundary_velocity_residual_shell/screen-output
  tests/ascii_data_boundary_velocity_residual_shell/solution/solution_surface-00000.0000.gnuplot
  tests/ascii_data_boundary_velocity_residual_shell/statistics
Labels: ready to test

#3832 Fix a couple of funny uses of \si.
  doc/manual/manual.tex
Labels: ready to test

#3852 Modified documentation for a typo.
  source/postprocess/velocity_boundary_statistics.cc
Labels: ready to merge, ready to test
