Repository geodynamics/aspect, pull requests merged in 2021-08, with the labels that each got.

#4294 Minor edits to the manual.
  cookbooks/christensen_yuen_phase_function/doc/christensen_yuen_phase_function.tex
  doc/manual/cookbooks/visualizing_phase_diagram/doc/visualizing_phase_diagram.tex
  doc/manual/manual.tex
Labels: ready to test

#4286 Use a proper reference in another place.
  source/postprocess/visualization/grain_lag_angle.cc
Labels: ready to merge, ready to test

#4270 Don't open the same file on all processes.
  source/simulator/checkpoint_restart.cc
Labels: ready to test

#4296 bump required ASPECT version in cmake files
  benchmarks/advection_in_annulus/CMakeLists.txt
  benchmarks/annulus/CMakeLists.txt
  benchmarks/blankenbach/plugin/CMakeLists.txt
  benchmarks/burstedde/CMakeLists.txt
  benchmarks/compressibility_formulations/plugins/CMakeLists.txt
  benchmarks/crameri_et_al/case_1/CMakeLists.txt
  benchmarks/davies_et_al/case-2.3-plugin/CMakeLists.txt
  benchmarks/doneahuerta/CMakeLists.txt
  benchmarks/entropy_adiabat/plugins/CMakeLists.txt
  benchmarks/finite_strain/CMakeLists.txt
  benchmarks/hollow_sphere/CMakeLists.txt
  benchmarks/inclusion/CMakeLists.txt
  benchmarks/inclusion/compositional_fields/CMakeLists.txt
  benchmarks/king2dcompressible/CMakeLists.txt
  benchmarks/layeredflow/CMakeLists.txt
  benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/CMakeLists.txt
  benchmarks/newton_solver_benchmark_set/spiegelman_et_al_2016/CMakeLists.txt
  benchmarks/nsinker/CMakeLists.txt
  benchmarks/operator_splitting/advection_reaction/CMakeLists.txt
  benchmarks/operator_splitting/exponential_decay/CMakeLists.txt
  benchmarks/rayleigh_taylor_instability/CMakeLists.txt
  benchmarks/rigid_shear/plugin/CMakeLists.txt
  benchmarks/shear_bands/CMakeLists.txt
  benchmarks/sinking_block/CMakeLists.txt
  benchmarks/solcx/CMakeLists.txt
  benchmarks/solcx/compositional_fields/CMakeLists.txt
  benchmarks/solitary_wave/CMakeLists.txt
  benchmarks/solkz/CMakeLists.txt
  benchmarks/solkz/compositional_fields/CMakeLists.txt
  benchmarks/tangurnis/code/CMakeLists.txt
  benchmarks/time_dependent_annulus/plugin/CMakeLists.txt
  benchmarks/tosi_et_al_2015_gcubed/CMakeLists.txt
  benchmarks/viscosity_grooves/CMakeLists.txt
  benchmarks/yamauchi_takei_2016_anelasticity/CMakeLists.txt
  cookbooks/anisotropic_viscosity/CMakeLists.txt
  cookbooks/finite_strain/CMakeLists.txt
  cookbooks/free_surface_with_crust/plugin/CMakeLists.txt
  cookbooks/inner_core_convection/CMakeLists.txt
  cookbooks/morency_doin_2004/CMakeLists.txt
  cookbooks/prescribed_velocity/CMakeLists.txt
  cookbooks/prescribed_velocity_ascii_data/CMakeLists.txt
  doc/plugin-CMakeLists.txt
  tests/CMakeLists.txt
Labels: ready to merge, ready to test

#4295 update parameters
  doc/manual/parameters.tex
  doc/manual/plugin_graph.dot
  doc/manual/plugin_graph.pdf
  doc/parameter_view/parameters.xml
Labels: ready to merge, ready to test

#4299 GMG Newton: correct Stokes rhs
  source/simulator/stokes_matrix_free.cc
Labels: ready to test

#4301 GMG Stokes: minor fix
  source/simulator/stokes_matrix_free.cc
  tests/tosi_benchmark_gmg_newton_solver/screen-output
  tests/tosi_benchmark_gmg_newton_solver/statistics
Labels: ready to merge, ready to test

#4305 Adding recent publication, Gouiza and Naliboff
  doc/manual/citing_aspect.bib
Labels: ready to test

#4309 Remove unnecessary computation
  source/simulator/assemblers/stokes.cc
Labels: ready to merge

#4310 Add missing mapping
  source/simulator/stokes_matrix_free.cc
  tests/gmg_no_normal_flux_only/screen-output
Labels: ready to merge

#4185 thick_shell_grav_bench
  benchmarks/gravity_thick_shell/thick_shell.prm
  doc/manual/cookbooks/benchmarks/gravity_thick_shell/doc/gravity_U.pdf
  doc/manual/cookbooks/benchmarks/gravity_thick_shell/doc/gravity_g.pdf
  doc/manual/cookbooks/benchmarks/gravity_thick_shell/doc/thick_shell.prm
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#4218 simple plume cookbook in 2D
  cookbooks/plume_2D_chunk/doc/T1.png
  cookbooks/plume_2D_chunk/doc/T2.png
  cookbooks/plume_2D_chunk/doc/T3.png
  cookbooks/plume_2D_chunk/doc/eta1.png
  cookbooks/plume_2D_chunk/doc/eta2.png
  cookbooks/plume_2D_chunk/doc/eta3.png
  cookbooks/plume_2D_chunk/doc/exp1_22.png
  cookbooks/plume_2D_chunk/doc/exp1_45.png
  cookbooks/plume_2D_chunk/doc/exp1_90.png
  cookbooks/plume_2D_chunk/doc/plume.tex
  cookbooks/plume_2D_chunk/doc/vel1.png
  cookbooks/plume_2D_chunk/doc/vel2.png
  cookbooks/plume_2D_chunk/doc/vel3.png
  cookbooks/plume_2D_chunk/doc/vrms.pdf
  cookbooks/plume_2D_chunk/opening_angle_45degrees.prm
  cookbooks/plume_2D_chunk/opening_angle_90degrees.prm
  cookbooks/plume_2D_chunk/plume2D.prm
  cookbooks/plume_2D_chunk/strongly_temperature_dependent.prm
  cookbooks/plume_2D_chunk/weakly_temperature_dependent.prm
  doc/manual/cookbooks/plume_2D_chunk
  doc/manual/manual.bib
  doc/manual/manual.tex
Labels: ready to test

#4314 Use BoundingBox in the generation of particles.
  source/particle/generator/interface.cc
Labels: ready to test

#4219 [deal.II 9.3] Simplify some code using C++14 capture semantics.
  source/simulator/helper_functions.cc
Labels: ready to merge, ready to test

#4315 GMG: rm if DEAL_II_VERSION_GTE(9,3,0)
  source/simulator/stokes_matrix_free.cc
Labels: ready to merge, ready to test

#4316 rm more DEAL_II_VERSION_GTE(9,3,0)
  benchmarks/diffusion_of_hill/analytical_topography.cc
  include/aspect/compat.h
  include/aspect/material_model/interface.h
  include/aspect/particle/world.h
  source/geometry_model/spherical_shell.cc
  source/material_model/equation_of_state/thermodynamic_table_lookup.cc
  source/material_model/grain_size.cc
  source/material_model/interface.cc
  source/mesh_deformation/diffusion.cc
  source/mesh_deformation/free_surface.cc
  source/particle/generator/interface.cc
  source/particle/world.cc
  source/postprocess/topography.cc
  source/postprocess/visualization/boundary_velocity_residual.cc
  source/postprocess/visualization/dynamic_topography.cc
  source/postprocess/visualization/geoid.cc
  source/postprocess/visualization/heat_flux_map.cc
  source/postprocess/visualization/heating.cc
  source/postprocess/visualization/material_properties.cc
  source/postprocess/visualization/surface_dynamic_topography.cc
  source/simulator/checkpoint_restart.cc
  source/simulator/core.cc
  source/simulator/melt.cc
Labels: ready to merge, ready to test

#4319 remove more cxx14::make_unique
  include/aspect/compat.h
  unit_tests/additional_outputs.cc
Labels: ready to merge, ready to test

#4320 update citation
  doc/make_cite_html.py
  doc/manual/manual.bib
Labels: ready to merge, ready to test

#4333 Improve documentation of changelog
  CONTRIBUTING.md
  doc/manual/manual.tex
Labels: ready to merge
