Repository geodynamics/aspect, pull requests merged in 2021-07, with the labels that each got.

#4108 Remove a PETSC option
  source/simulator/solver.cc
Labels: ready to test

#4106 Removed a deprecated option (5x)
  source/mesh_deformation/interface.cc
Labels: ready to merge, ready to test

#4107 removed PETSC option
  source/mesh_deformation/free_surface.cc
Labels: ready to test

#4119 Fix crustal cookbook
  cookbooks/crustal_deformation/crustal_model_2D.prm
Labels: ready to merge

#4112 Remove unused PETSC option
  source/simulator/core.cc
Labels: ready to test

#4122 GMG option for additional details
  benchmarks/nsinker/nsinker_gmg.prm
  include/aspect/stokes_matrix_free.h
  source/simulator/parameters.cc
  source/simulator/stokes_matrix_free.cc
  tests/nsinker_gmg_idr/screen-output
Labels: ready to test

#4127 Update some matrix-free functions
  source/simulator/stokes_matrix_free.cc
Labels: ready to test

#3918 added viscous damper to elasticity to make firmoviscous material
  doc/modules/changes/20210707_bobmyhill
  include/aspect/material_model/rheology/elasticity.h
  source/material_model/rheology/elasticity.cc
  tests/damped_viscoelastic_bending_beam.prm
  tests/damped_viscoelastic_bending_beam/depth_average.txt
  tests/damped_viscoelastic_bending_beam/screen-output
  tests/damped_viscoelastic_bending_beam/statistics
Labels: ready to test

#4109 Removed a PETSC option
  source/simulator/melt.cc
Labels: ready to merge, ready to test

#4076 Average before producing graphical output.
  source/postprocess/visualization/material_properties.cc
  tests/output_averaging_arithmetic.cc
  tests/output_averaging_arithmetic.prm
  tests/output_averaging_arithmetic/solution/solution-00000.0000.gnuplot
  tests/output_averaging_harmonic.cc
  tests/output_averaging_harmonic.prm
  tests/output_averaging_harmonic/solution/solution-00000.0000.gnuplot
Labels: ready to test

#4102 Fix a test for certain versions of openmpi
  doc/manual/manual.tex
  doc/modules/changes/20210707_gassmoeller
  tests/CMakeLists.txt
  tests/checkpoint_05_mpi.cc
  tests/checkpoint_05_mpi/screen-output
  tests/checkpoint_05_mpi/statistics1
  tests/checkpoint_05_mpi/statistics2
  tests/checkpoint_05_mpi_create.prm
  tests/checkpoint_05_mpi_create/screen-output
  tests/checkpoint_05_mpi_create/statistics
  tests/checkpoint_05_mpi_resume.cc
  tests/checkpoint_05_mpi_resume.prm
  tests/checkpoint_05_mpi_resume/screen-output
  tests/checkpoint_05_mpi_resume/statistics
Labels: ready to merge, ready to test

#4134 Fix incorrect doxygen markup.
  include/aspect/boundary_temperature/dynamic_core.h
  include/aspect/particle/property/integrated_strain.h
  include/aspect/particle/property/melt_particle.h
  include/aspect/particle/property/pT_path.h
  include/aspect/simulator/assemblers/interface.h
  include/aspect/volume_of_fluid/assembly.h
Labels: ready to test

#4135 Use std::numeric_limits::lowest() instead of -max().
  source/boundary_temperature/box.cc
  source/boundary_temperature/two_merged_boxes.cc
  source/geometry_model/initial_topography_model/prm_polygon.cc
  source/initial_temperature/S40RTS_perturbation.cc
  source/initial_temperature/SAVANI_perturbation.cc
  source/initial_temperature/patch_on_S40RTS.cc
  source/material_model/averaging.cc
  source/material_model/interface.cc
  source/material_model/utilities.cc
  source/particle/interpolator/bilinear_least_squares.cc
  source/particle/interpolator/quadratic_least_squares.cc
  source/postprocess/boundary_velocity_residual_statistics.cc
  source/postprocess/composition_statistics.cc
  source/postprocess/gravity_point_values.cc
  source/postprocess/melt_statistics.cc
  source/postprocess/pressure_statistics.cc
  source/postprocess/temperature_statistics.cc
  source/postprocess/topography.cc
  source/postprocess/velocity_boundary_statistics.cc
  source/simulator/entropy_viscosity.cc
  source/simulator/helper_functions.cc
  source/simulator/parameters.cc
  source/simulator/stokes_matrix_free.cc
  source/structured_data.cc
Labels: ready to test

#4136 Fix a grammar mistake.
  source/postprocess/boundary_densities.cc
  source/postprocess/boundary_pressures.cc
  source/postprocess/boundary_velocity_residual_statistics.cc
  source/postprocess/composition_statistics.cc
  source/postprocess/core_statistics.cc
  source/postprocess/heat_flux_densities.cc
  source/postprocess/heat_flux_statistics.cc
  source/postprocess/heating_statistics.cc
  source/postprocess/pressure_statistics.cc
  source/postprocess/spherical_velocity_statistics.cc
  source/postprocess/temperature_statistics.cc
  source/postprocess/velocity_boundary_statistics.cc
  source/postprocess/velocity_statistics.cc
  source/postprocess/volume_of_fluid_statistics.cc
Labels: ready to merge, ready to test

#4133 Make a function purely internal to a .cc file.
  include/aspect/termination_criteria/steady_rms_velocity.h
  include/aspect/termination_criteria/steady_temperature.h
  source/termination_criteria/steady_temperature.cc
  unit_tests/termination_criteria.cc
Labels: ready to test

#4138 Avoid using Worldbuilder in top namespace
  contrib/world_builder/source/config.cc.in
Labels: ready to merge, ready to test

#4139 Add a missing space.
  source/utilities.cc
Labels: ready to test

#4142 update citing_aspect.bib with missing information
  doc/manual/citing_aspect.bib
Labels: ready to merge, ready to test

#4145 removed a deprecated option in source/simulator/nullspace.cc
  source/simulator/nullspace.cc
Labels: ready to merge, ready to test

#3828 New: Make thermodynamic table lookup into an EquationOfState
  doc/modules/changes/20210708_bobmyhill
  include/aspect/material_model/equation_of_state/thermodynamic_table_lookup.h
  include/aspect/material_model/steinberger.h
  source/material_model/equation_of_state/thermodynamic_table_lookup.cc
  source/material_model/steinberger.cc
Labels: ready to test

#4147 minor fixes to manual
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#4150 Remove deal.II compatibility code
  include/aspect/mesh_deformation/interface.h
  include/aspect/postprocess/particles.h
  include/aspect/simulator_access.h
  include/aspect/utilities.h
  source/global.cc
  source/mesh_refinement/volume_of_fluid_interface.cc
  source/particle/generator/quadrature_points.cc
  source/particle/generator/reference_cell.cc
  source/simulator/assemblers/advection.cc
  source/utilities.cc
Labels: ready to merge, ready to test

#4148 Created multicomponent EoS->Material averaging function
  include/aspect/material_model/equation_of_state/interface.h
  source/material_model/equation_of_state/interface.cc
  source/material_model/steinberger.cc
Labels: ready to test

#4153 test: traction bc with GMG
  tests/poiseuille_2d_pressure_bc_gmg.prm
  tests/poiseuille_2d_pressure_bc_gmg/screen-output
  tests/poiseuille_2d_pressure_bc_gmg/statistics
Labels: ready to merge, ready to test

#4155 Fix a typo in two places.
  source/simulator/assemblers/newton_stokes.cc
Labels: ready to test

#4158 Make an error message easier to read.
  source/boundary_composition/interface.cc
  source/boundary_temperature/constant.cc
  source/boundary_temperature/interface.cc
  source/boundary_velocity/interface.cc
  source/mesh_deformation/diffusion.cc
  source/mesh_deformation/interface.cc
  source/simulator/parameters.cc
Labels: ready to merge, ready to test

#4165 Improve comments and simplify chunk
  include/aspect/geometry_model/chunk.h
  source/geometry_model/chunk.cc
Labels: ready to merge, ready to test

#4159 apply clang-tidy fixes
  source/main.cc
  source/material_model/interface.cc
  source/mesh_refinement/isosurfaces.cc
  source/postprocess/boundary_pressures.cc
  source/postprocess/depth_average.cc
  source/postprocess/entropy_viscosity_statistics.cc
  source/postprocess/melt_statistics.cc
  source/postprocess/particles.cc
  source/postprocess/point_values.cc
  source/postprocess/pressure_statistics.cc
  source/postprocess/spherical_velocity_statistics.cc
  source/postprocess/stokes_residual.cc
  source/postprocess/temperature_statistics.cc
  source/postprocess/topography.cc
  source/postprocess/velocity_statistics.cc
  source/postprocess/visualization.cc
  source/simulator/checkpoint_restart.cc
  source/simulator/parameters.cc
  source/termination_criteria/steady_rms_velocity.cc
  source/termination_criteria/steady_temperature.cc
  source/termination_criteria/user_request.cc
  source/utilities.cc
Labels: ready to merge

#4160 cleanup for lookup EOS
  include/aspect/material_model/equation_of_state/interface.h
  include/aspect/material_model/equation_of_state/thermodynamic_table_lookup.h
  include/aspect/material_model/steinberger.h
  include/aspect/material_model/utilities.h
  source/material_model/equation_of_state/interface.cc
  source/material_model/equation_of_state/thermodynamic_table_lookup.cc
  source/material_model/steinberger.cc
  source/material_model/utilities.cc
  tests/steinberger_several_fields.prm
  tests/steinberger_several_fields/depth_average.gnuplot
  tests/steinberger_several_fields/screen-output
  tests/steinberger_several_fields/statistics
Labels: ready to test

#4140 Update gravitational constant
  include/aspect/global.h
  tests/dynamic_core/screen-output
  tests/dynamic_core/statistics
  tests/geoid/CMB_dynamic_topography_contribution_SH_coefficients.00000
  tests/geoid/density_anomaly_contribution_SH_coefficients.00000
  tests/geoid/dynamic_topography_bottom.00000
  tests/geoid/dynamic_topography_surface.00000
  tests/geoid/geoid_anomaly.00000
  tests/geoid/geoid_anomaly_SH_coefficients.00000
  tests/geoid/gravity_anomaly.00000
  tests/geoid/surface_dynamic_topography_contribution_SH_coefficients.00000
  tests/geoid_no_topo/density_anomaly_contribution_SH_coefficients.00000
  tests/geoid_no_topo/geoid_anomaly.00000
  tests/geoid_no_topo/geoid_anomaly_SH_coefficients.00000
  tests/geoid_no_topo/gravity_anomaly.00000
  tests/geoid_visualization/geoid_anomaly.00000
  tests/geoid_visualization/solution/solution-00000.0000.gnuplot
  tests/gravity_point_values_list/output_gravity/gravity-00000
  tests/gravity_point_values_list/statistics
  tests/gravity_point_values_map/output_gravity/gravity-00000
  tests/gravity_point_values_map/statistics
  tests/gravity_point_values_spiral/output_gravity/gravity-00000
  tests/gravity_point_values_spiral/statistics
  tests/spectral_comparison/gravity_anomaly.00000
Labels: ready to merge, ready to test

#4166 whitespace/tab removal from contributed prms
  contrib/opendap/prm_files/aspect_test.prm
  contrib/opendap/prm_files/aspect_url_test.prm
  contrib/perplex/perplex_lookup_composition.prm
  contrib/python/convection-box.prm
Labels: ready to test

#4156 Enforce consistent constant temperature boundary indicators
  doc/modules/changes/20210708c_bobmyhill
  source/boundary_temperature/constant.cc
  tests/chunk_topography_postprocessor.prm
  tests/depth_postprocessor_ellipsoidal_chunk.prm
  tests/free_surface_adaptive_blob.prm
  tests/free_surface_adaptive_blob_petsc.prm
  tests/free_surface_blob.prm
  tests/free_surface_blob_melt.prm
  tests/free_surface_blob_nonzero_melt.prm
  tests/free_surface_iterated_IMPES.prm
  tests/free_surface_iterated_stokes.prm
  tests/free_surface_relaxation.prm
  tests/melt_velocity_boundary_conditions.prm
  tests/mesh_velocity_output.prm
  tests/periodic_box.prm
  tests/periodic_box_freesurface.prm
  tests/periodic_linear_momentum.prm
  tests/resume_free_surface.prm
  tests/slope_refinement.prm
Labels: ready to merge, ready to test

#4062 Store integrator properties as regular particle properties
  doc/modules/changes/20210708_gassmoeller
  include/aspect/particle/integrator/euler.h
  include/aspect/particle/integrator/interface.h
  include/aspect/particle/integrator/rk_2.h
  include/aspect/particle/integrator/rk_4.h
  include/aspect/particle/property/interface.h
  source/particle/integrator/interface.cc
  source/particle/integrator/rk_2.cc
  source/particle/integrator/rk_4.cc
  source/particle/interpolator/bilinear_least_squares.cc
  source/particle/interpolator/quadratic_least_squares.cc
  source/particle/property/interface.cc
  source/particle/world.cc
  source/postprocess/particles.cc
  unit_tests/particles.cc
Labels: ready to merge, ready to test

#4169 move fill_averaged_equation_of_state_outputs to utilities
  include/aspect/material_model/equation_of_state/interface.h
  include/aspect/material_model/utilities.h
  source/material_model/equation_of_state/interface.cc
  source/material_model/steinberger.cc
  source/material_model/utilities.cc
Labels: ready to test

#4173 correct typo
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#4175 Add check to CMakeLists.txt preventing insource builds
  CMakeLists.txt
Labels: ready to merge, ready to test

#4164 gravity benchmark thin shell
  benchmarks/gravity_thin_shell/gravity_thin_shell.prm
  doc/manual/cookbooks/benchmarks/gravity_thin_shell/doc/thinshell_a.prm
  doc/manual/cookbooks/benchmarks/gravity_thin_shell/doc/thinshell_b.prm
  doc/manual/cookbooks/benchmarks/gravity_thin_shell/doc/thinshell_c.prm
  doc/manual/manual.tex
Labels: ready to test

#4143 change lower limit quad increase
  source/postprocess/gravity_point_values.cc
  tests/gravity_quadrature_degree_increase.prm
  tests/gravity_quadrature_degree_increase/screen-output
  tests/gravity_quadrature_degree_increase/statistics
Labels: ready to test

#4010 Add Peierls cutoff stress
  doc/modules/changes/20210323_danieldouglas92
  include/aspect/material_model/rheology/peierls_creep.h
  source/material_model/rheology/peierls_creep.cc
  tests/visco_plastic_peierls_cutoff_test.prm
  tests/visco_plastic_peierls_cutoff_test/screen-output
  tests/visco_plastic_peierls_cutoff_test/statistics
Labels: ready to test

#3808 corrected geoid parameter typo
  source/postprocess/geoid.cc
  tests/geoid.prm
  tests/geoid_no_topo.prm
  tests/geoid_visualization.prm
Labels: ready to test

#4189 Remove an unused variable in the multicomponent incompressible model.
  include/aspect/material_model/equation_of_state/multicomponent_incompressible.h
Labels: ready to merge, ready to test

#4187 Use std::unique_ptr instead of std::shared_ptr in a number of places.
  include/aspect/material_model/equation_of_state/multicomponent_incompressible.h
  include/aspect/material_model/replace_lithosphere_viscosity.h
  include/aspect/material_model/rheology/composite_visco_plastic.h
  include/aspect/material_model/rheology/diffusion_creep.h
  include/aspect/material_model/rheology/dislocation_creep.h
  include/aspect/material_model/rheology/peierls_creep.h
  include/aspect/material_model/rheology/visco_plastic.h
  include/aspect/material_model/utilities.h
  include/aspect/utilities.h
  source/material_model/diffusion_dislocation.cc
  source/material_model/equation_of_state/multicomponent_incompressible.cc
  source/material_model/rheology/composite_visco_plastic.cc
  source/material_model/rheology/diffusion_creep.cc
  source/material_model/rheology/dislocation_creep.cc
  source/material_model/rheology/peierls_creep.cc
  source/material_model/rheology/visco_plastic.cc
  source/material_model/utilities.cc
  source/material_model/visco_plastic.cc
  source/utilities.cc
  tests/composite_viscous_outputs.cc
  unit_tests/parse_map_to_double_array.cc
Labels: ready to test

#4196 cmake: error when detecting insource cmakecache
  CMakeLists.txt
  doc/modules/changes/20210713_gassmoeller_tjhei
Labels: ready to merge, ready to test

#4195 install missing headers
  CMakeLists.txt
Labels: ready to merge, ready to test

#4192 fixing units in manual
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#4191 Update Material properties plugin description
  source/postprocess/visualization/material_properties.cc
Labels: ready to merge

#4174 read in the dominant phase from a lookup table
  data/material-model/steinberger/test-steinberger-compressible/constant_material_2_small.txt
  data/material-model/steinberger/test-steinberger-compressible/constant_material_small.txt
  data/material-model/steinberger/test-steinberger-compressible/constant_material_small_hefesto.txt
  data/material-model/steinberger/test-steinberger-compressible/constant_material_small_hefesto_derivatives.txt
  doc/modules/changes/20210710_jdannberg
  include/aspect/material_model/equation_of_state/thermodynamic_table_lookup.h
  include/aspect/material_model/interface.h
  include/aspect/material_model/utilities.h
  source/material_model/equation_of_state/thermodynamic_table_lookup.cc
  source/material_model/interface.cc
  source/material_model/utilities.cc
  tests/steinberger_phases.prm
  tests/steinberger_phases/depth_average.gnuplot
  tests/steinberger_phases/screen-output
  tests/steinberger_phases/statistics
  tests/steinberger_phases/thermodynamic_lookup_table_phases.txt
  tests/steinberger_phases_2_lookups.prm
  tests/steinberger_phases_2_lookups/depth_average.gnuplot
  tests/steinberger_phases_2_lookups/screen-output
  tests/steinberger_phases_2_lookups/statistics
  tests/steinberger_phases_2_lookups/thermodynamic_lookup_table_phases.txt
  tests/steinberger_phases_hefesto.prm
  tests/steinberger_phases_hefesto/depth_average.gnuplot
  tests/steinberger_phases_hefesto/screen-output
  tests/steinberger_phases_hefesto/statistics
Labels: ready to merge

#4207 use top instead of outer as boundary id
  source/initial_temperature/adiabatic_boundary.cc
Labels: ready to merge

#3844 Cookbook: Prescribed velocity ascii data
  cookbooks/prescribed_velocity_ascii_data/CMakeLists.txt
  cookbooks/prescribed_velocity_ascii_data/aspect_name.pdf
  cookbooks/prescribed_velocity_ascii_data/aspect_name.png
  cookbooks/prescribed_velocity_ascii_data/make_ascii_files_from_png.py
  cookbooks/prescribed_velocity_ascii_data/prescribed_velocity_ascii_data.cc
  cookbooks/prescribed_velocity_ascii_data/prescribed_velocity_ascii_data.prm
  doc/manual/cookbooks/prescribed_velocity_ascii_data/doc/prescribed_velocities_ascii_data_initial_conditions.png
  doc/manual/cookbooks/prescribed_velocity_ascii_data/doc/prescribed_velocity_ascii_data.png
  doc/manual/cookbooks/prescribed_velocity_ascii_data/doc/prescribed_velocity_ascii_data.prm.0.out
  doc/manual/cookbooks/prescribed_velocity_ascii_data/doc/prescribed_velocity_ascii_data.prm.1.out
  doc/manual/cookbooks/prescribed_velocity_ascii_data/doc/prescribed_velocity_ascii_data.prm.2.out
  doc/manual/manual.tex
  doc/modules/changes/20210713_bobmyhill
Labels: ready to merge, ready to test

#4211 Minor edits to the manual.
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#4210 update dynamic topography postprocessor to use translate_symbolic_bou…
  source/postprocess/dynamic_topography.cc
Labels: ready to merge

#4213 added Bob and Cedric to the list of maintainers/principal developers
  AUTHORS.md
  README.md
  doc/manual/manual.tex
Labels: ready to test

#4222 Fix missing template argument.
  source/particle/generator/interface.cc
Labels: ready to merge, ready to test

#4179 Minor edits to the gravity benchmark section.
  doc/manual/manual.tex
Labels: ready to merge

#4221 Add check that printouts Temperature & Pressure values when nonpositive diffusion or dislocation viscosity is detected
  source/material_model/rheology/diffusion_creep.cc
  source/material_model/rheology/dislocation_creep.cc
Labels: ready to merge, ready to test

#4227 fix and cleanup the nonlinear channel flow input_t.prm in the newton benchmark set
  benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/input_t.prm
Labels: ready to merge, ready to test

#4233 Correct spelling of 'Stokes'.
  source/simulator/melt.cc
  source/simulator/stokes_matrix_free.cc
Labels: ready to test

#4230 README: replace license badge
  README.md
Labels: ready to merge, ready to test

#4229 Avoid some viscosity computations when not necessary.
  source/material_model/rheology/visco_plastic.cc
Labels: ready to merge, ready to test

#4226 Assert SPD factor visualization against full Stokes solver.
  include/aspect/postprocess/visualization/spd_factor.h
  source/postprocess/visualization/spd_factor.cc
Labels: ready to merge, ready to test

#4200 Migrate support points function to utilities
  cookbooks/prescribed_velocity/prescribed_velocity.cc
  cookbooks/prescribed_velocity_ascii_data/prescribed_velocity_ascii_data.cc
  include/aspect/utilities.h
  source/utilities.cc
  tests/prescribed_velocity_dgp.cc
Labels: ready to test

#4223 Optimize boundary name lookups in postprocessors
  source/mesh_refinement/slope.cc
  source/postprocess/dynamic_topography.cc
  source/postprocess/geoid.cc
Labels: ready to merge, ready to test

#4232 Move simple nonlinear to newton nonlinear channel
  benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/CMakeLists.txt
  benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/input_t.prm
  benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/input_v.prm
  benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/simple_nonlinear.cc
  tests/nonlinear_channel_flow_tractions_Newton_Stokes.cc
  tests/nonlinear_channel_flow_tractions_Newton_Stokes_no_deviator.cc
  tests/nonlinear_channel_flow_tractions_Newton_Stokes_no_line_search.cc
  tests/nonlinear_channel_flow_tractions_Newton_Stokes_particles.cc
  tests/nonlinear_channel_flow_tractions_iterated_IMPES.cc
  tests/nonlinear_channel_flow_velocities_Newton_Stokes.cc
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_GMG.cc
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_derivative.cc
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_derivative_EW.cc
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_deviator.cc
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_no_line_search.cc
  tests/nonlinear_channel_flow_velocities_iterated_IMPES.cc
  tests/nonlinear_channel_flow_velocities_single_advection_Newton_Stokes.cc
  tests/simple_nonlinear.cc
Labels: ready to merge

#4224 Consistently use American English spelling of 'meter'.
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#4181 Output surface stress as a tensor field.
  doc/modules/changes/20210712_bangerth
  include/aspect/postprocess/visualization/surface_stress.h
  source/postprocess/visualization/surface_stress.cc
  tests/stress_vs_surface_stress/solution/solution_surface-00000.0000.gnuplot
Labels: ready to test

#4149 Fix the 'prescribed dilation' in newton_stokes
  doc/modules/changes/20210709_sliu
  source/simulator/assemblers/newton_stokes.cc
  tests/prescribed_dilation_newton/statistics
  tests/prescribed_dilation_newton_singleadvection.cc
  tests/prescribed_dilation_newton_singleadvection.prm
  tests/prescribed_dilation_newton_singleadvection/screen-output
  tests/prescribed_dilation_newton_singleadvection/statistics
Labels: ready to merge, ready to test

#4209 fixed stress update in damped elasticity
  source/material_model/rheology/elasticity.cc
  tests/damped_viscoelastic_bending_beam/statistics
Labels: ready to test

#4240 fix benchmarks/newton/spiegelman
  benchmarks/newton_solver_benchmark_set/spiegelman_et_al_2016/input.prm
Labels: ready to merge, ready to test

#4245 fix a typo
  source/simulator/core.cc
Labels: ready to merge, ready to test

#4243 Unify particle update for deal.II 9.2 and 9.3
  source/particle/world.cc
Labels: ready to merge, ready to test

#4241 avoiding division by zero in dyn topo pp
  source/postprocess/dynamic_topography.cc
Labels: ready to merge, ready to test

#4242 add 6 names to coverpage bottom
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#4161 add option for different plasticity for different phases
  include/aspect/material_model/rheology/composite_visco_plastic.h
  include/aspect/material_model/rheology/drucker_prager.h
  include/aspect/material_model/rheology/visco_plastic.h
  source/material_model/rheology/composite_visco_plastic.cc
  source/material_model/rheology/drucker_prager.cc
  source/material_model/rheology/visco_plastic.cc
  source/material_model/visco_plastic.cc
  tests/composite_viscous_outputs.cc
  tests/visco_plastic_phases_plasticity.prm
  tests/visco_plastic_phases_plasticity/screen-output
  tests/visco_plastic_phases_plasticity/solution/solution-00000.0000.gnuplot
  tests/visco_plastic_phases_plasticity/statistics
Labels: ready to test

#4250 Fix benchmarks/
  benchmarks/crameri_et_al/case_1/crameri_benchmark_1.prm
  benchmarks/inclusion/adaptive.prm.base
  benchmarks/inclusion/global.prm.base
Labels: ready to merge, ready to test

#4152 Static temperature
  doc/modules/changes/20210708_fildes
  source/simulator/core.cc
  source/simulator/parameters.cc
  source/simulator/solver_schemes.cc
  tests/static_temperature.prm
  tests/static_temperature/screen-output
  tests/static_temperature/solution/solution-00000.0000.gnuplot
  tests/static_temperature/solution/solution-00001.0000.gnuplot
  tests/static_temperature/statistics
Labels: ready to test

#4261 Don't use std::make_unique just yet.
  source/material_model/diffusion_dislocation.cc
  source/material_model/utilities.cc
  source/material_model/visco_plastic.cc
  source/particle/property/interface.cc
  source/particle/world.cc
Labels: ready to test

#4247 Allow to use adiabatic P for creep viscosity calculation in visco-plastic rheology
  include/aspect/material_model/rheology/visco_plastic.h
  source/material_model/rheology/visco_plastic.cc
  tests/visco_plastic_adiabatic_pressure_in_viscous_creep.prm
  tests/visco_plastic_adiabatic_pressure_in_viscous_creep/screen-output
  tests/visco_plastic_adiabatic_pressure_in_viscous_creep/solution/solution-00000.0000.gnuplot
  tests/visco_plastic_adiabatic_pressure_in_viscous_creep/statistics
Labels: ready to test

#4217 GMG Newton solver
  benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/input_t_gmg.prm
  benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/input_v_gmg.prm
  benchmarks/newton_solver_benchmark_set/tosi_et_al_2015/input_gmg.prm
  doc/modules/changes/20210715_jiaqi
  include/aspect/stokes_matrix_free.h
  source/simulator/solver_schemes.cc
  source/simulator/stokes_matrix_free.cc
  tests/nonlinear_channel_flow_tractions_Newton_Stokes_GMG.prm
  tests/nonlinear_channel_flow_tractions_Newton_Stokes_GMG/screen-output
  tests/nonlinear_channel_flow_tractions_Newton_Stokes_GMG/statistics
  tests/tosi_benchmark_gmg_newton_solver.prm
  tests/tosi_benchmark_gmg_newton_solver/screen-output
  tests/tosi_benchmark_gmg_newton_solver/statistics
Labels: ready to test

#4262 check DG limiters only used with cartesian mapping
  source/simulator/core.cc
Labels: ready to merge

#4268 Fix a possible bug.
  source/material_model/interface.cc
Labels: ready to test

#4266 Remove some unnecessary include files.
  source/postprocess/composition_statistics.cc
  source/postprocess/gravity_point_values.cc
  source/postprocess/heating_statistics.cc
  source/postprocess/matrix_statistics.cc
  source/postprocess/max_depth_field.cc
  source/postprocess/melt_statistics.cc
  source/postprocess/memory_statistics.cc
  source/postprocess/particle_count_statistics.cc
  source/postprocess/spherical_velocity_statistics.cc
  source/postprocess/temperature_statistics.cc
Labels: ready to test

#4274 [2.3] take over Disable failing particle integration schemes in periodic shells
  source/particle/world.cc
  tests/particle_periodic_quarter_shell.prm
  tests/particle_periodic_quarter_shell/particles/particles-00001.0000.vtu
  tests/particle_periodic_quarter_shell/particles/particles-00001.0001.vtu
Labels: ready to merge, ready to test

#4267 Rename an argument.
  include/aspect/material_model/interface.h
  source/material_model/interface.cc
Labels: ready to test

#4279 add maintainers to zenodo template
  .zenodo.json
Labels: ready to merge, ready to test

#4284 Use a proper reference.
  doc/manual/manual.bib
  source/postprocess/visualization/ISA_rotation_timescale.cc
Labels: ready to test

#4283 Remove remaining uses of PETSc from the code base.
  include/aspect/global.h
  source/global.cc
  source/main.cc
  source/mesh_deformation/diffusion.cc
  source/mesh_deformation/free_surface.cc
  source/simulator/assembly.cc
  source/volume_of_fluid/solver.cc
Labels: ready to test

#4271 Update strain healing field tests
  tests/visco_plastic_yield_plastic_viscous_strain_healing.prm
  tests/visco_plastic_yield_plastic_viscous_strain_healing/screen-output
  tests/visco_plastic_yield_plastic_viscous_strain_healing/solution/solution-00000.0000.gnuplot
  tests/visco_plastic_yield_plastic_viscous_strain_healing/statistics
  tests/visco_plastic_yield_total_strain_healing.prm
  tests/visco_plastic_yield_total_strain_healing/screen-output
  tests/visco_plastic_yield_total_strain_healing/solution/solution-00000.0000.gnuplot
  tests/visco_plastic_yield_total_strain_healing/statistics
Labels: ready to test

#4285 Use \[...\] instead of $$...$$.
  source/particle/integrator/interface.cc
Labels: ready to merge, ready to test

#4287 Minor grammar fixes.
  source/postprocess/visualization/volume_of_fluid_values.cc
Labels: ready to merge, ready to test

#4290 Move a screen message.
  source/structured_data.cc
  tests/ascii_data_boundary_composition_2d_box_time/screen-output
  tests/ascii_data_boundary_temperature_2d_box_time/screen-output
  tests/ascii_data_boundary_velocity_2d_box_time/screen-output
  tests/ascii_data_boundary_velocity_2d_box_time_backward/screen-output
  tests/ascii_data_boundary_velocity_2d_box_time_non_equidistant/screen-output
  tests/traction_ascii_data/screen-output
Labels: ready to merge, ready to test

#4257 Phase diagram
  cookbooks/visualizing_phase_diagram.prm
  doc/manual/cookbooks/visualizing_phase_diagram/doc/harzburgite.prm
  doc/manual/cookbooks/visualizing_phase_diagram/doc/material_model.prm
  doc/manual/cookbooks/visualizing_phase_diagram/doc/pyrolite_harzburgite.png
  doc/manual/cookbooks/visualizing_phase_diagram/doc/pyrolite_linear.png
  doc/manual/cookbooks/visualizing_phase_diagram/doc/steinberg.png
  doc/manual/cookbooks/visualizing_phase_diagram/doc/steinberg.prm
  doc/manual/cookbooks/visualizing_phase_diagram/doc/visualizing_phase_diagram.tex
  doc/manual/cookbooks/visualizing_phase_diagram/visualizing_phase_diagram.prm
  doc/manual/manual.bib
  doc/manual/manual.tex
  doc/modules/changes/20210716_lhy11009
Labels: ready to merge, ready to test
