Repository geodynamics/aspect, pull requests merged in 2021-09, with the labels that each got.

#4220 S40RTS mantle gravity
  benchmarks/gravity_mantle/convert_gravity_ascii_to_vtu_map.py
  benchmarks/gravity_mantle/mantle_gravity.prm
  doc/manual/cookbooks/benchmarks/gravity_mantle/T.png
  doc/manual/cookbooks/benchmarks/gravity_mantle/grav.png
  doc/manual/cookbooks/benchmarks/gravity_mantle/mesh.png
  doc/manual/cookbooks/benchmarks/gravity_mantle/pot.png
  doc/manual/cookbooks/benchmarks/gravity_mantle/rho.png
  doc/manual/manual.tex
  doc/modules/changes/20210831_cedrict
Labels: ready to test

#4337 improved parse_map error message for string format
  source/utilities.cc
  tests/stokes_solver_fail_A/screen-output
  tests/stokes_solver_fail_S/screen-output
  unit_tests/parse_map_to_double_array.cc
Labels: ready to test

#4351 remove duplicate ChunkGeometry instantiation
  source/geometry_model/two_merged_chunks.cc
Labels: bug, ready to merge, ready to test

#4352 add missing override keywords
  include/aspect/particle/integrator/rk_2.h
  include/aspect/particle/integrator/rk_4.h
  include/aspect/particle/property/interface.h
  include/aspect/stokes_matrix_free.h
Labels: ready to test

#4347 Fix manual comment for 3D Drucker Prager
  include/aspect/material_model/drucker_prager.h
  source/material_model/drucker_prager.cc
Labels: ready to test

#4311 Change the representative point to include initial topography in the box model geometry
  source/geometry_model/box.cc
  tests/resume_free_surface/log.txt2
  tests/world_builder_simple_2d_cartesian_sticky_air/solution/solution-00000.0000.gnuplot
Labels: ready to test

#4338 remove lines with code line number from screen-output
  tests/advection_solver_fail/screen-output
  tests/cmake/default
  tests/stokes_solver_fail/screen-output
  tests/stokes_solver_fail_A/screen-output
  tests/stokes_solver_fail_S/screen-output
  tests/stokes_solver_fail_gmg/screen-output
Labels: ready to test

#4358 Clean up references somewhat.
  doc/manual/citing_aspect.bib
Labels: ready to merge, ready to test

#4332 print total wall time after restarts
  doc/modules/changes/20210920_ekendall
  include/aspect/simulator.h
  source/simulator/checkpoint_restart.cc
  source/simulator/core.cc
  source/simulator/helper_functions.cc
Labels: ready to test

#4361 Apply update scripts to source and parameter files
  cookbooks/plume_2D_chunk/plume2D.prm
  tests/melt_visco_plastic.cc
  tests/particle_property_initial_composition_boundary.prm
  tests/visco_plastic_adiabatic_heating_density.prm
Labels: ready to merge

#4367 fix MeshDeformationHandler<dim>::*_matching_mesh_deformation_object
  include/aspect/mesh_deformation/interface.h
Labels: ready to test

#4366 benchmarks: use output* for output directories
  benchmarks/buiter_et_al_2016_jsg/exp_1.prm
  benchmarks/buiter_et_al_2016_jsg/exp_2_high_resolution.prm
  benchmarks/diffusion_of_hill/1_sine_zero_flux.prm
  benchmarks/diffusion_of_hill/2_sine_constant_h.prm
  benchmarks/finite_strain/pure_shear.prm
  benchmarks/finite_strain/simple_shear.prm
  benchmarks/viscoelastic_plastic_simple_shear/viscoelastic_plastic_simple_shear.prm
Labels: ready to merge
