Repository geodynamics/aspect, pull requests merged in 2021-06, with the labels that each got.

#4048 Avoid the use of TriaAccessor::number_of_children().
  source/mesh_refinement/volume_of_fluid_interface.cc
  source/simulator/assemblers/advection.cc
  source/volume_of_fluid/assembler.cc
Labels: ready to test

#4049 Avoid a deprecated version of MappingQCache::initialize().
  source/simulator/checkpoint_restart.cc
  source/simulator/core.cc
Labels: ready to test

#4047 Avoid the use of Threads::Thread.
  include/aspect/postprocess/particles.h
  include/aspect/postprocess/visualization.h
  include/aspect/simulator.h
  source/postprocess/particles.cc
  source/postprocess/visualization.cc
  source/simulator/core.cc
  source/simulator/helper_functions.cc
Labels: ready to test

#4050 Avoid the use of deprecated functions for iterating over local vector elements.
  source/simulator/stokes_matrix_free.cc
Labels: ready to test

#4044 Add an explanatory sentence to the 'compositing' material model.
  source/material_model/compositing.cc
Labels: ready to merge, ready to test

#4059 Fix deprecation warning
  source/particle/property/elastic_stress.cc
  source/particle/world.cc
Labels: ready to merge

#4053 Add elastic stresses to surface stress output
  include/aspect/postprocess/visualization/surface_stress.h
  source/postprocess/visualization/surface_stress.cc
  tests/stress_vs_surface_stress/solution/solution_surface-00000.0000.gnuplot
Labels: ready to merge

#4065 Add a missing assertion.
  source/material_model/interface.cc
Labels: ready to test

#4074 Fix matrix-free deprecation warnings
  source/simulator/stokes_matrix_free.cc
Labels: ready to merge, ready to test

#4063 Make particle removal compatible with latest deal.II particle structure
  source/particle/world.cc
Labels: bug

#4078 Improve a comment.
  source/simulator/nullspace.cc
Labels: ready to test

#4079 Fix indentation in a test.
  tests/additional_outputs_03.prm
Labels: ready to merge, ready to test

#4080 Small logic cleanups.
  source/postprocess/particles.cc
Labels: ready to test

#4083 Use std::move to move data instead of copy where possible.
  include/aspect/structured_data.h
  source/structured_data.cc
  unit_tests/utilities.cc
Labels: ready to test

#4087 Cherry pick the cleanups in #4086
  include/aspect/structured_data.h
  source/structured_data.cc
Labels: ready to test

#4084 Rename a couple of functions.
  include/aspect/structured_data.h
  source/structured_data.cc
  tests/rheology_scaled_profile.cc
Labels: ready to test

#4100 Fix unit tests for deal.II dev
  unit_tests/mesh_refinement.cc
  unit_tests/parse_map_to_double_array.cc
Labels: ready to merge
