Repository geodynamics/aspect, pull requests merged in 2022-09, with the labels that each got.

#4941 Simplify plastic additional outputs
  include/aspect/material_model/rheology/visco_plastic.h
  source/material_model/rheology/visco_plastic.cc
  source/material_model/visco_plastic.cc
Labels: ready to merge

#4956 Fix warning: unused variable
  include/aspect/plugins.h
Labels: ready to merge, ready to test

#4913 visualize undeformed mesh and mesh displacement
  doc/modules/changes/20220716_tjhei
  include/aspect/mesh_deformation/interface.h
  include/aspect/postprocess/visualization.h
  source/mesh_deformation/interface.cc
  source/postprocess/visualization.cc
  tests/viz_mesh_deform_vector.prm
  tests/viz_mesh_deform_vector/screen-output
  tests/viz_mesh_deform_vector/solution/solution-00010.0000.gnuplot
Labels: ready to test

#4869 Docs: continental extension cookbook
  cookbooks/continental_extension/doc/continental_extension.md
Labels: ready to test

#4962 GMG: rm compute_no_normal_flux_constraints_box/shell
  include/aspect/stokes_matrix_free.h
  source/mesh_deformation/interface.cc
  source/simulator/stokes_matrix_free.cc
  tests/free_surface_VE_cylinder_2D_loading_fixed_elastic_dt_gmg/statistics
  tests/gmg_mesh_deform/solution/solution-00000.0000.gnuplot
  tests/gmg_mesh_deform_adaptive/screen-output
  tests/gmg_mesh_deform_adaptive/statistics
  tests/gmg_mesh_deform_adaptive_bug/screen-output
  tests/gmg_mesh_deform_adaptive_bug/statistics
  tests/gmg_mesh_deform_ghost_entries/statistics
  tests/matrix_nonzeros_7/statistics
Labels: ready to test

#4944 Docs: Sphinx conversion of several more benchmarks
  benchmarks/annulus/doc/annulus.md
  benchmarks/burstedde/doc/burstedde.md
  benchmarks/burstedde/doc/burstedde.png
  benchmarks/crameri_et_al/doc/crameri_et_al.md
  benchmarks/davies_et_al/doc/davies-2DcylinderFSS.png
  benchmarks/davies_et_al/doc/davies-2DcylinderVrms.png
  benchmarks/davies_et_al/doc/davies_et_al.md
  benchmarks/hollow_sphere/doc/hollow-sphere.png
  benchmarks/hollow_sphere/doc/hollow_sphere.md
  benchmarks/slab_detachment/doc/slab_detachment.md
  benchmarks/solitary_wave/doc/solitary_wave.md
  benchmarks/viscosity_grooves/doc/benchmark-grooves.png
  benchmarks/viscosity_grooves/doc/viscosity_grooves.md
  cookbooks/latent-heat/doc/latent-heat-benchmark.png
  cookbooks/latent-heat/doc/latent-heat-results.png
  cookbooks/latent-heat/doc/latent-heat.md
  cookbooks/stokes/doc/stokes.md
  cookbooks/stokes/doc/stokes2d.png
  cookbooks/stokes/doc/stokes3d.png
  doc/sphinx/references.bib
  doc/sphinx/user/run-aspect/checkpoint-restart.md
Labels: ready to merge, ready to test

#4934 cookbooks/initial-condition-S20RTS
  cookbooks/initial-condition-S20RTS/S20RTS.prm
Labels: ready to merge, ready to test
