Repository geodynamics/aspect, pull requests merged in 2022-04, with the labels that each got.

#4525 Move dynamic friction into a friction rheology add function for friction
  include/aspect/material_model/rheology/friction_models.h
  source/material_model/rheology/friction_models.cc
  source/material_model/rheology/visco_plastic.cc
  tests/visco_plastic_friction_function.prm
  tests/visco_plastic_friction_function/screen-output
Labels: ready to test

#4483 add sheared torsion BM after Farrington et al. 2014
  benchmarks/viscoelastic_sheared_torsion/viscoelastic_sheared_torsion.prm
  tests/viscoelastic_sheared_torsion.prm
  tests/viscoelastic_sheared_torsion/screen-output
  tests/viscoelastic_sheared_torsion/statistics
Labels: ready to test

#4541 Avoid compiler warnings for a test.
  tests/melt_transport_compressible.cc
Labels: ready to merge, ready to test

#4536 Provide centralized facilities for quadrature formulas.
  include/aspect/introspection.h
  source/simulator/introspection.cc
  source/simulator/stokes_matrix_free.cc
Labels: ready to test

#4537 2 citation updates
  doc/manual/citing_aspect.bib
Labels: ready to test

#4543 Make quadrature objects 'const'.
  source/mesh_deformation/free_surface.cc
  source/mesh_deformation/interface.cc
  source/mesh_refinement/composition.cc
  source/mesh_refinement/temperature.cc
  source/postprocess/dynamic_topography.cc
  source/simulator/helper_functions.cc
  source/simulator/initial_conditions.cc
  source/simulator/nullspace.cc
  source/volume_of_fluid/reconstruct.cc
Labels: ready to test

#4540 Moved finite strain cookbook documentation
  cookbooks/finite_strain/doc/finite_strain.cc
  cookbooks/finite_strain/doc/finite_strain.part.prm
  cookbooks/finite_strain/doc/finite_strain.pdf
  cookbooks/finite_strain/doc/finite_strain.tex
  doc/manual/cookbooks/finite_strain
  doc/manual/manual.tex
Labels: ready to test

#4544 Provide the infrastructure for face quadratures.
  include/aspect/introspection.h
  source/postprocess/boundary_velocity_residual_statistics.cc
  source/postprocess/mobility_statistics.cc
  source/simulator/introspection.cc
Labels: ready to test

#4468 add steinberger cookbook
  cookbooks/future/steinberger.prm
  cookbooks/steinberger/doc/density.png
  cookbooks/steinberger/doc/geometry.part.prm
  cookbooks/steinberger/doc/lookup.part.prm
  cookbooks/steinberger/doc/nullspace.part.prm
  cookbooks/steinberger/doc/projected_density.part.prm
  cookbooks/steinberger/doc/radial-visc-simple.pdf
  cookbooks/steinberger/doc/radial-visc.pdf
  cookbooks/steinberger/doc/rheology.part.prm
  cookbooks/steinberger/doc/specific_heat.png
  cookbooks/steinberger/doc/steinberger.tex
  cookbooks/steinberger/doc/temperature.png
  cookbooks/steinberger/doc/viscosity.png
  cookbooks/steinberger/steinberger.prm
  data/material-model/steinberger/description.txt
  doc/manual/cookbooks/steinberger
  doc/manual/manual.bib
  doc/manual/manual.tex
  source/material_model/utilities.cc
  tests/steinberger_cookbook.prm
  tests/steinberger_cookbook/screen-output
  tests/steinberger_cookbook/statistics
Labels: ready to merge

#4546 Moved Bunge et al mantle convection cookbook
  cookbooks/bunge_et_al_mantle_convection/doc/bunge_et_al_mantle_convection.tex
  cookbooks/bunge_et_al_mantle_convection/doc/temps.png
  doc/manual/cookbooks/bunge_et_al_mantle_convection
  doc/manual/manual.tex
Labels: ready to test

#4547 Moved the convection box 3d cookbook documentation
  cookbooks/convection_box_3d/convection_box_3d.prm
  cookbooks/convection_box_3d/doc/amr.part.prm
  cookbooks/convection_box_3d/doc/checkpoint.part.prm
  cookbooks/convection_box_3d/doc/convection_box_3d.tex
  cookbooks/convection_box_3d/doc/gravity.part.prm
  cookbooks/convection_box_3d/doc/heat-flux.png
  cookbooks/convection_box_3d/doc/initial.part.prm
  cookbooks/convection_box_3d/doc/mesh0060.png
  cookbooks/convection_box_3d/doc/mesh0100.png
  cookbooks/convection_box_3d/doc/mesh0180.png
  cookbooks/convection_box_3d/doc/movie0010.png
  cookbooks/convection_box_3d/doc/movie0040.png
  cookbooks/convection_box_3d/doc/movie0060.png
  cookbooks/convection_box_3d/doc/movie0100.png
  cookbooks/convection_box_3d/doc/movie0130.png
  cookbooks/convection_box_3d/doc/movie0180.png
  cookbooks/convection_box_3d/doc/postprocess.part.prm
  cookbooks/convection_box_3d/doc/start.part.prm
  doc/manual/cookbooks/convection_box_3d
  doc/manual/manual.tex
Labels: ready to test

#4549 Use centralized quadrature formulas.
  source/mesh_refinement/composition.cc
  source/mesh_refinement/temperature.cc
  source/mesh_refinement/velocity.cc
  source/particle/generator/quadrature_points.cc
  source/postprocess/spherical_velocity_statistics.cc
  source/simulator/entropy_viscosity.cc
  source/simulator/helper_functions.cc
  source/simulator/nullspace.cc
  source/termination_criteria/steady_rms_velocity.cc
  source/termination_criteria/steady_temperature.cc
Labels: ready to test

#4551 Fix override warnings
  include/aspect/geometry_model/box.h
  include/aspect/geometry_model/spherical_shell.h
  include/aspect/geometry_model/two_merged_boxes.h
  include/aspect/postprocess/gravity_point_values.h
Labels: ready to merge

#4550 Moved geomIO cookbook
  cookbooks/geomio/doc/geomIO.prm
  cookbooks/geomio/doc/geomio.tex
  cookbooks/geomio/doc/jelly-paraview.pdf
  cookbooks/geomio/doc/jelly.png
  cookbooks/geomio/doc/jellyfish.pdf
  cookbooks/geomio/doc/run_geomio.part1.m
  cookbooks/geomio/doc/run_geomio.part2.m
  cookbooks/geomio/doc/save_file_as_txt.m
  doc/manual/cookbooks/geomio
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#4552 More using of centralized quadrature objects.
  include/aspect/introspection.h
  source/boundary_temperature/dynamic_core.cc
  source/postprocess/boundary_densities.cc
  source/postprocess/boundary_pressures.cc
  source/postprocess/composition_statistics.cc
  source/postprocess/heating_statistics.cc
  source/postprocess/mass_flux_statistics.cc
  source/postprocess/material_statistics.cc
  source/postprocess/max_depth_field.cc
  source/postprocess/melt_statistics.cc
  source/postprocess/temperature_statistics.cc
  source/postprocess/velocity_boundary_statistics.cc
  source/postprocess/velocity_statistics.cc
  source/postprocess/viscous_dissipation_statistics.cc
  source/simulator/assembly.cc
  source/simulator/helper_functions.cc
  source/simulator/initial_conditions.cc
  source/simulator/introspection.cc
  source/simulator/melt.cc
  source/simulator/nullspace.cc
  source/simulator/stokes_matrix_free.cc
Labels: ready to test

#4553 Moved Global Melt cookbook
  cookbooks/global_melt/doc/global_melt.prm
  cookbooks/global_melt/doc/global_melt.tex
  cookbooks/global_melt/doc/global_no_melt.prm
  cookbooks/global_melt/doc/model_evolution.pdf
  cookbooks/global_melt/global_melt.prm
  cookbooks/global_melt/global_no_melt.prm
  doc/manual/cookbooks/global_melt
  doc/manual/manual.tex
Labels: ready to test

#4554 Moved Inner Core Convection Cookbook
  cookbooks/inner_core_convection/doc/Diagstab.pdf
  cookbooks/inner_core_convection/doc/Ra1e0P0modif.png
  cookbooks/inner_core_convection/doc/Ra1e2P-1modif.png
  cookbooks/inner_core_convection/doc/Ra1e2P-1rescalemodif.png
  cookbooks/inner_core_convection/doc/Ra1e5P4modif.png
  cookbooks/inner_core_convection/doc/Ra1e5P4rescalemodif.png
  cookbooks/inner_core_convection/doc/convection.png
  cookbooks/inner_core_convection/doc/inner_core_convection.tex
  cookbooks/inner_core_convection/doc/inner_core_traction.part.1.prm
  cookbooks/inner_core_convection/doc/inner_core_traction.part.2.prm
  cookbooks/inner_core_convection/doc/inner_core_traction.part.3.prm
  cookbooks/inner_core_convection/doc/no_convection.png
  cookbooks/inner_core_convection/doc/translation.png
  cookbooks/inner_core_convection/doc/translation_over_P.pdf
  cookbooks/inner_core_convection/doc/translation_over_Ra_P.pdf
  doc/manual/cookbooks/inner_core_convection
  doc/manual/manual.tex
Labels: ready to test

#4558 Moved Morency Doin 2004 Cookbook
  cookbooks/morency_doin_2004/doc/morency_doin.part.prm
  cookbooks/morency_doin_2004/doc/morency_doin_2004.tex
  cookbooks/morency_doin_2004/doc/morency_doin_2004_fig1.pdf
  doc/manual/cookbooks/morency_doin_2004
  doc/manual/manual.tex
Labels: ready to test

#4560 Fix a number of typos.
  cookbooks/global_melt/doc/global_melt.prm
  cookbooks/global_melt/global_melt.prm
  doc/Makefile
  include/aspect/utilities.h
  source/material_model/grain_size.cc
  source/material_model/rheology/strain_dependent.cc
  source/material_model/steinberger.cc
  source/mesh_refinement/isosurfaces.cc
  source/simulator/parameters.cc
  tests/spiegelman_fail_test.prm
Labels: ready to test

#4566 Fix deprecation warnings and incompatibility with deal.II
  source/particle/world.cc
Labels: ready to merge, ready to test

#4564 Moved Muparser temperature/lazy syntax cookbook
  cookbooks/muparser_temperature_example/doc/check-initial-condition.part.prm
  cookbooks/muparser_temperature_example/doc/initial_temperature.png
  cookbooks/muparser_temperature_example/doc/initial_temperature_on_mesh.png
  cookbooks/muparser_temperature_example/doc/initial_temperature_on_mesh_zoom.png
  cookbooks/muparser_temperature_example/doc/mesh-refinement.part.prm
  cookbooks/muparser_temperature_example/doc/muparser_temperature_example.tex
  cookbooks/muparser_temperature_example/doc/repetitions.part.prm
  cookbooks/muparser_temperature_example/doc/temperature.part.prm
  doc/manual/cookbooks/muparser_temperature_example
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#4568 Moved Polydiapirism cookbook
  benchmarks/polydiapirs/doc/diapirs0000.png
  benchmarks/polydiapirs/doc/diapirs0005.png
  benchmarks/polydiapirs/doc/diapirs0010.png
  benchmarks/polydiapirs/doc/diapirs0015.png
  benchmarks/polydiapirs/doc/polydiapirs.tex
  benchmarks/polydiapirs/doc/vrms.pdf
  doc/manual/cookbooks/benchmarks/polydiapirs
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#4569 Moved platelike boundary cookbook
  cookbooks/platelike-boundary/doc/boundary.part.prm
  cookbooks/platelike-boundary/doc/platelike-boundary.tex
  cookbooks/platelike-boundary/doc/platelike.prm
  cookbooks/platelike-boundary/doc/visit0000.png
  cookbooks/platelike-boundary/doc/visit0001.png
  cookbooks/platelike-boundary/doc/visit0002.png
  cookbooks/platelike-boundary/doc/visit0003.png
  cookbooks/platelike-boundary/doc/visit0004.png
  cookbooks/platelike-boundary/doc/visit0005.png
  cookbooks/platelike-boundary/doc/visit0006.png
  cookbooks/platelike-boundary/platelike-boundary.prm
  doc/manual/cookbooks/platelike-boundary
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#4570 Moved initial condition S20RTS cookbook
  cookbooks/initial-condition-S20RTS/S20RTS.prm
  cookbooks/initial-condition-S20RTS/doc/Fig_cookbook_V4-01.png
  cookbooks/initial-condition-S20RTS/doc/Fig_cookbook_V4-02.png
  cookbooks/initial-condition-S20RTS/doc/S20RTS.input.sph
  cookbooks/initial-condition-S20RTS/doc/S20RTS.part.prm
  cookbooks/initial-condition-S20RTS/doc/initial-condition-S20RTS.tex
  doc/manual/cookbooks/initial-condition-S20RTS
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#4571 Moved the prescribed velocity cookbook
  cookbooks/prescribed_velocity/doc/circle.png
  cookbooks/prescribed_velocity/doc/corner_flow.png
  cookbooks/prescribed_velocity/doc/minimal.prm
  cookbooks/prescribed_velocity/doc/prescribed_velocity.tex
  doc/manual/cookbooks/prescribed_velocity
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#4572 Moved prescribed velocity ASCII data cookbook
  cookbooks/prescribed_velocity_ascii_data/doc/prescribed_velocities_ascii_data_initial_conditions.png
  cookbooks/prescribed_velocity_ascii_data/doc/prescribed_velocity_ascii_data.png
  cookbooks/prescribed_velocity_ascii_data/doc/prescribed_velocity_ascii_data.prm.0.out
  cookbooks/prescribed_velocity_ascii_data/doc/prescribed_velocity_ascii_data.prm.1.out
  cookbooks/prescribed_velocity_ascii_data/doc/prescribed_velocity_ascii_data.prm.2.out
  cookbooks/prescribed_velocity_ascii_data/doc/prescribed_velocity_ascii_data.tex
  doc/manual/cookbooks/prescribed_velocity_ascii_data
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#4573 Moved shell 3d postprocess cookbook
  cookbooks/shell_3d_postprocess/doc/postprocess_cookbook-01.png
  cookbooks/shell_3d_postprocess/doc/shell_3d_postprocess.part.prm
  cookbooks/shell_3d_postprocess/doc/shell_3d_postprocess.tex
  cookbooks/shell_3d_postprocess/shell_3d_postprocess.prm
  doc/manual/cookbooks/shell_3d_postprocess
  doc/manual/manual.tex
Labels: ready to merge, ready to test
