Repository geodynamics/aspect, pull requests merged in 2022-02, with the labels that each got.

#4467 Adds first publication of the year to the publication list
  doc/manual/citing_aspect.bib
Labels: ready to test

#4459 add pressure- and temperature-dependent thermal conductivity
  doc/modules/changes/20220121_jdannberg
  include/aspect/material_model/steinberger.h
  source/material_model/steinberger.cc
  tests/steinberger_conductivity.prm
  tests/steinberger_conductivity/screen-output
  tests/steinberger_conductivity/solution/solution-00000.0000.gnuplot
  tests/steinberger_conductivity/statistics
  tests/steinberger_conductivity_tosi.prm
  tests/steinberger_conductivity_tosi/screen-output
  tests/steinberger_conductivity_tosi/solution/solution-00000.0000.gnuplot
  tests/steinberger_conductivity_tosi/statistics
Labels: ready to merge

#4472 GMG: fix max/min of the evaluated viscosities
  include/aspect/stokes_matrix_free.h
  source/simulator/stokes_matrix_free.cc
  tests/nsinker_gmg_idr/screen-output
  tests/poiseuille_2d_pressure_bc_gmg/screen-output
Labels: ready to merge, ready to test

#4480 Save a few cycles when outputting only a single char.
  benchmarks/blankenbach/plugin/code.cc
  benchmarks/newton_solver_benchmark_set/spiegelman_et_al_2016/drucker_prager_compositions.cc
  source/boundary_velocity/gplates.cc
  source/global.cc
  source/initial_temperature/lithosphere_mask.cc
  source/main.cc
  source/material_model/equation_of_state/thermodynamic_table_lookup.cc
  source/postprocess/boundary_velocity_residual_statistics.cc
  source/postprocess/depth_average.cc
  source/postprocess/heat_flux_densities.cc
  source/postprocess/mass_flux_statistics.cc
  source/postprocess/point_values.cc
  source/postprocess/rotation_statistics.cc
  source/postprocess/velocity_boundary_statistics.cc
  source/postprocess/velocity_statistics.cc
  source/postprocess/volume_of_fluid_statistics.cc
  source/simulator/core.cc
  source/simulator/helper_functions.cc
  source/simulator/solver_schemes.cc
  source/simulator/stokes_matrix_free.cc
  source/structured_data.cc
  source/utilities.cc
  tests/additional_outputs_03.cc
  tests/artificial_postprocess.cc
  tests/boundary_heatflux_update.cc
  tests/composite_viscous_outputs.cc
  tests/coordinate_transformation.cc
  tests/plugin.cc
  tests/vof_err_calc.h
  unit_tests/common.h
Labels: ready to test

#4479 GMG: fix negative viscosity
  doc/modules/changes/20220205_jiaqi
  source/simulator/stokes_matrix_free.cc
  tests/gmg_test_project_q1.prm
  tests/gmg_test_project_q1/screen-output
  tests/gmg_test_project_q1/statistics
  tests/stokes_solver_fail_gmg/screen-output
  tests/stokes_solver_fail_gmg/solver_history.txt
Labels: ready to test

#4456 Rework the gravity postprocessor
  include/aspect/postprocess/gravity_point_values.h
  source/postprocess/gravity_point_values.cc
Labels: ready to test

#4484 Cleanup and fix large file issues
  source/utilities.cc
Labels: ready to test

#4454 Matrix-free free surface stabilization
  benchmarks/crameri_et_al/case_1/crameri_benchmark_1_gmg.prm
  doc/modules/changes/20220119_jiaqi
  include/aspect/stokes_matrix_free.h
  source/mesh_deformation/interface.cc
  source/simulator/stokes_matrix_free.cc
  tests/crameri_benchmark_1_gmg.cc
  tests/crameri_benchmark_1_gmg.prm
  tests/crameri_benchmark_1_gmg/screen-output
  tests/crameri_benchmark_1_gmg/statistics
  tests/free_surface_blob_gmg.prm
  tests/free_surface_blob_gmg/screen-output
  tests/free_surface_blob_gmg/statistics
  tests/free_surface_iterated_stokes_gmg.prm
  tests/free_surface_iterated_stokes_gmg/screen-output
  tests/free_surface_iterated_stokes_gmg/statistics
Labels: ready to test

#4415 Use precomputed mapping information during particle updates
  source/particle/world.cc
Labels: ready to merge

#4492 Add newlines between functions.
  source/gravity_model/vertical.cc
Labels: ready to test

#4491 comment about melt solver
  source/simulator/assembly.cc
Labels: ready to merge, ready to test

#4477 fixing typos and adding 2022 paper
  doc/manual/manual.bib
  source/simulator/parameters.cc
Labels: ready to test
