Repository geodynamics/aspect, pull requests merged in 2022-03, with the labels that each got.

#4509 update parameters
  doc/manual/parameters.tex
  doc/manual/plugin_graph.pdf
  doc/parameter_view/parameters.xml
Labels: ready to merge, ready to test

#4502 Add new publication by ONeill and Aulbach
  doc/manual/citing_aspect.bib
Labels: ready to test

#4510 Fix a UTF8 character.
  doc/manual/citing_aspect.bib
Labels: ready to test

#4515 Cosmetic changes.
  include/aspect/simulator/assemblers/interface.h
Labels: ready to test

#4514 fixed a typo in a path in cookbook 5.3.4
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#4517 Update a reference to GeometryInfo.
  source/geometry_model/box.cc
Labels: ready to test

#4518 Avoid access to GeometryInfo in particle code.
  source/particle/world.cc
Labels: ready to test

#4519 Replace GeometryInfo in a test .cc file.
  tests/free_surface_relaxation.cc
Labels: ready to test

#4511 Add a necessary header file.
  source/simulator/stokes_matrix_free.cc
Labels: ready to test

#4520 Test for deal.II >= 9.4 instead of 10.0.
  source/material_model/melt_global.cc
  source/particle/property/elastic_stress.cc
  source/particle/world.cc
  source/postprocess/particles.cc
Labels: ready to merge, ready to test

#4526 Test for deal.II >= 9.4 instead of 10.0.
  include/aspect/compat.h
Labels: ready to merge, ready to test

#4512 Adds new publication by Stein et al.
  doc/manual/citing_aspect.bib
Labels: ready to test

#4487 add the comments recommended for #4483 also to the simple shear BM
  benchmarks/viscoelastic_plastic_simple_shear/viscoelastic_plastic_simple_shear.prm
  tests/visco_plastic_vep_simple_shear/screen-output
  tests/visco_plastic_vep_simple_shear/statistics
Labels: ready to test

#4516 Get rid of a bunch of GeometryInfo related things.
  include/aspect/simulator/assemblers/interface.h
  include/aspect/volume_of_fluid/assembly.h
  source/simulator/assemblers/advection.cc
  source/simulator/assemblers/interface.cc
  source/simulator/assembly.cc
  source/volume_of_fluid/assembler.cc
  source/volume_of_fluid/handler.cc
Labels: ready to test

#4403 Keep constrained dofs in composition block
  source/simulator/core.cc
Labels: ready to merge, ready to test

#4529 Use updated deal.II 9.3.2 container for github actions
  .github/workflows/linux.yml
Labels: ready to merge, ready to test

#4357 Move dynamic friction into a friction rheology model
  doc/manual/manual.bib
  doc/modules/changes/20210923_estherheck
  include/aspect/material_model/dynamic_friction.h
  include/aspect/material_model/rheology/friction_models.h
  include/aspect/material_model/rheology/visco_plastic.h
  source/material_model/dynamic_friction.cc
  source/material_model/rheology/friction_models.cc
  source/material_model/rheology/visco_plastic.cc
  tests/dynamic_friction.prm
  tests/dynamic_friction/screen-output
Labels: ready to test

#4495 GMG: compute mesh displacement
  doc/modules/changes/20220311_jiaqi
  include/aspect/mesh_deformation/interface.h
  include/aspect/stokes_matrix_free.h
  source/mesh_deformation/interface.cc
  source/simulator/stokes_matrix_free.cc
  tests/crameri_benchmark_1_gmg/screen-output
  tests/free_surface_blob_gmg/screen-output
  tests/free_surface_iterated_stokes_gmg/screen-output
  tests/gmg_mesh_deform/screen-output
  tests/gmg_mesh_deform_adaptive/screen-output
  tests/gmg_mesh_deform_function/screen-output
  tests/gmg_mesh_deform_ghost_entries/screen-output
  tests/gmg_mesh_deform_prescribed/screen-output
  tests/gmg_mesh_deform_topo/screen-output
Labels: ready to merge, ready to test

#4528 GMG and mesh deformation: disable for older deal.II
  source/simulator/stokes_matrix_free.cc
  tests/gmg_mesh_deform_adaptive_bug.prm
  tests/gmg_mesh_deform_adaptive_bug/screen-output
  tests/gmg_mesh_deform_adaptive_bug/statistics
Labels: ready to merge
