Repository geodynamics/aspect, pull requests merged in 2022-06, with the labels that each got.

#4842 [WIP] Fix dealii dev
  source/particle/world.cc
Labels: ready to merge, ready to test

#4350 Apply free surface stabilization to other mesh deformation plugins
  include/aspect/mesh_deformation/ascii_data.h
  include/aspect/mesh_deformation/diffusion.h
  include/aspect/mesh_deformation/free_surface.h
  include/aspect/mesh_deformation/function.h
  include/aspect/mesh_deformation/interface.h
  source/mesh_deformation/ascii_data.cc
  source/mesh_deformation/diffusion.cc
  source/mesh_deformation/free_surface.cc
  source/mesh_deformation/function.cc
  source/mesh_deformation/interface.cc
  source/simulator/melt.cc
  source/simulator/stokes_matrix_free.cc
Labels: ready to test

#4845 Follow-up fix to #4842
  source/particle/world.cc
Labels: ready to merge

#4690 Add strain rate particle property
  data/particle/generator/ascii/shearbox_particle_strain_rate.dat
  include/aspect/particle/property/strain_rate.h
  prmfiles/shearbox_3d_Agi_randParticles.prm
  prmfiles/shearbox_test_LPO_AV_SstensorParticle.prm
  source/particle/property/strain_rate.cc
  tests/shearbox_particle_strain_rate.prm
  tests/shearbox_particle_strain_rate/particles/particles-00000.0000.gnuplot
  tests/shearbox_particle_strain_rate/particles/particles-00001.0000.gnuplot
Labels: ready to test

#4811 Docs: free surface with crust cookbook
  cookbooks/free_surface_with_crust/doc/free_surface_with_crust.md
  cookbooks/free_surface_with_crust/doc/freesurface_with_crust.svg
Labels: ready to merge, ready to test

#4863 Fix Clang warnings
  include/aspect/heating_model/latent_heat_melt.h
  source/postprocess/visualization.cc
Labels: ready to merge, ready to test

#4857 json2markdown: mangle/demangle for special characters
  contrib/utilities/jsontomarkdown.py
  doc/sphinx/parameters/Geometry_20model.md
  doc/sphinx/parameters/Initial_20temperature_20model.md
  doc/sphinx/parameters/Postprocess.md
  doc/sphinx/parameters/Solver_20parameters.md
  doc/sphinx/parameters/global.md
Labels: documentation

#4853 Use straight d/dt instead of partials.
  doc/manual/manual.tex
  doc/sphinx/user/methods/particles.md
Labels: ready to test
