Repository geodynamics/aspect, pull requests merged in 2022-07, with the labels that each got.

#4870 Do not set strain_rate to size 0 in MaterialModel
  include/aspect/material_model/interface.h
  include/aspect/material_model/multicomponent.h
  include/aspect/material_model/multicomponent_compressible.h
  include/aspect/material_model/steinberger.h
  include/aspect/material_model/viscoelastic.h
  source/boundary_traction/initial_lithostatic_pressure.cc
  source/material_model/interface.cc
Labels: ready to test

#4884 Better document an implementation detail in the pT path particle property.
  source/particle/property/pT_path.cc
Labels: ready to merge, ready to test

#4881 Recompute global volume after each mesh deformation
  doc/modules/changes/20220706_gassmoeller
  source/simulator/core.cc
  tests/advect_mesh_vertically/statistics
  tests/chunk_topography_postprocessor/statistics
  tests/free_surface_adaptive_blob/statistics
  tests/free_surface_blob/statistics
  tests/free_surface_blob_gmg/statistics
  tests/free_surface_blob_melt/statistics
  tests/free_surface_relaxation/statistics
  tests/gmg_mesh_deform_adaptive_bug2/screen-output
  tests/gmg_mesh_deform_adaptive_bug2/statistics
  tests/gmg_mesh_deform_ghost_entries/statistics
  tests/gmg_mesh_deform_topo/screen-output
  tests/gmg_mesh_deform_topo/statistics
  tests/mesh_velocity_output/statistics
  tests/resume_free_surface/log.txt1
  tests/resume_free_surface/statistics1
  tests/resume_free_surface/statistics2
  tests/visco_plastic_vep_brick_extension/statistics
Labels: ready to merge

#4882 Do not specify a template argument where not necessary.
  source/simulator/stokes_matrix_free.cc
Labels: ready to test

#4883 Use more obvious language.
  include/aspect/simulator_signals.h
Labels: ready to merge, ready to test

#4878 Add more testers
  .github/workflows/linux.yml
  benchmarks/blankenbach/plugin/code.cc
  include/aspect/compat.h
  include/aspect/compat/mapping_cartesian.h
  source/simulator/compat/mapping_cartesian.cc
  source/simulator/core.cc
  source/volume_of_fluid/handler.cc
  tests/boundary_traction_function_cartesian_free_surface.prm
  tests/boundary_traction_function_cartesian_free_surface/screen-output
  tests/boundary_traction_function_cartesian_free_surface/statistics
  tests/boundary_traction_function_cartesian_free_surface/topography.00000
  tests/boundary_traction_function_cartesian_free_surface/topography.00001
  tests/boundary_traction_function_cartesian_free_surface/topography.00002
  tests/boundary_traction_function_spherical_free_surface.prm
  tests/boundary_traction_function_spherical_free_surface/screen-output
  tests/boundary_traction_function_spherical_free_surface/statistics
  tests/boundary_traction_function_spherical_free_surface/topography.00000
  tests/boundary_traction_function_spherical_free_surface/topography.00001
  tests/boundary_traction_function_spherical_free_surface/topography.00002
  tests/grain_size_latent_heat.cc
  tests/latent_heat_enthalpy.cc
Labels: ready to merge

#4904 Make a function pointer declaration easier to read.
  include/aspect/adiabatic_conditions/interface.h
  include/aspect/boundary_composition/interface.h
  include/aspect/boundary_fluid_pressure/interface.h
  include/aspect/boundary_heat_flux/interface.h
  include/aspect/boundary_temperature/interface.h
  include/aspect/boundary_traction/interface.h
  include/aspect/boundary_velocity/interface.h
  include/aspect/geometry_model/initial_topography_model/interface.h
  include/aspect/geometry_model/interface.h
  include/aspect/gravity_model/interface.h
  include/aspect/heating_model/interface.h
  include/aspect/initial_composition/interface.h
  include/aspect/initial_temperature/interface.h
  include/aspect/material_model/interface.h
  include/aspect/mesh_deformation/interface.h
  include/aspect/mesh_refinement/interface.h
  include/aspect/particle/generator/interface.h
  include/aspect/particle/integrator/interface.h
  include/aspect/particle/interpolator/interface.h
  include/aspect/postprocess/interface.h
  include/aspect/prescribed_stokes_solution/interface.h
  include/aspect/termination_criteria/interface.h
  include/aspect/time_stepping/interface.h
  source/adiabatic_conditions/interface.cc
  source/boundary_composition/interface.cc
  source/boundary_fluid_pressure/interface.cc
  source/boundary_heat_flux/interface.cc
  source/boundary_temperature/interface.cc
  source/boundary_traction/interface.cc
  source/boundary_velocity/interface.cc
  source/geometry_model/initial_topography_model/interface.cc
  source/geometry_model/interface.cc
  source/gravity_model/interface.cc
  source/heating_model/interface.cc
  source/initial_composition/interface.cc
  source/initial_temperature/interface.cc
  source/material_model/interface.cc
  source/mesh_deformation/interface.cc
  source/mesh_refinement/interface.cc
  source/particle/generator/interface.cc
  source/particle/integrator/interface.cc
  source/particle/interpolator/interface.cc
  source/postprocess/interface.cc
  source/prescribed_stokes_solution/interface.cc
  source/termination_criteria/interface.cc
  source/time_stepping/interface.cc
Labels: ready to merge, ready to test

#4896 Tests of GMG DC Picard Stokes
  tests/nonlinear_channel_flow_tractions_dc_picard_Stokes_GMG.cc
  tests/nonlinear_channel_flow_tractions_dc_picard_Stokes_GMG.prm
  tests/nonlinear_channel_flow_tractions_dc_picard_Stokes_GMG/screen-output
  tests/nonlinear_channel_flow_tractions_dc_picard_Stokes_GMG/statistics
  tests/nonlinear_channel_flow_velocities_dc_picard_Stokes_GMG/screen-output
  tests/nonlinear_channel_flow_velocities_dc_picard_Stokes_GMG/statistics
  tests/tosi_benchmark_gmg_dc_picard_solver.cc
  tests/tosi_benchmark_gmg_dc_picard_solver.prm
  tests/tosi_benchmark_gmg_dc_picard_solver/screen-output
  tests/tosi_benchmark_gmg_dc_picard_solver/statistics
Labels: ready to test

#4893 No need to double up semicolons ;-)
  include/aspect/plugins.h
  source/boundary_traction/ascii_data.cc
  source/geometry_model/two_merged_boxes.cc
  source/material_model/steinberger.cc
  source/simulator/assembly.cc
  source/utilities.cc
Labels: ready to test

#4888 Small cosmetic changes.
  source/simulator/checkpoint_restart.cc
  source/simulator/helper_functions.cc
  source/simulator/initial_conditions.cc
Labels: ready to test

#4895 Minor clean-up in the plugin infrastructure.
  include/aspect/plugins.h
Labels: ready to test

#4889 Release initial conditions objects when possible.
  benchmarks/entropy_adiabat/plugins/prescribed_temperature.cc
  benchmarks/entropy_adiabat/plugins/prescribed_temperature.h
  benchmarks/solitary_wave/solitary_wave.cc
  include/aspect/adiabatic_conditions/compute_profile.h
  include/aspect/boundary_composition/initial_composition.h
  include/aspect/boundary_temperature/initial_temperature.h
  include/aspect/particle/property/pT_path.h
  include/aspect/simulator.h
  include/aspect/simulator_access.h
  source/adiabatic_conditions/compute_profile.cc
  source/boundary_composition/initial_composition.cc
  source/boundary_temperature/initial_temperature.cc
  source/particle/property/pT_path.cc
  source/simulator/checkpoint_restart.cc
  source/simulator/core.cc
  source/simulator/initial_conditions.cc
  source/simulator/simulator_access.cc
  tests/prescribed_temperature_in_field.cc
Labels: ready to merge, ready to test

#4927 readme, bib entries, citing update for 2.4
  README.md
  contrib/release/release-tasklist
  doc/make_cite_html.py
  doc/manual/manual.bib
Labels: ready to merge

#4928 www: update citing database
  citing.html
  database.js
Labels: ready to merge

#4844 Docs: A few benchmarks (cleanup)
  benchmarks/onset-of-convection/doc/onset-of-convection.md
  benchmarks/polydiapirs/doc/polydiapirs.md
  benchmarks/rayleigh_taylor_instability/doc/rayleigh_taylor_instability.md
  benchmarks/sinking_block/doc/sinking_block.md
  cookbooks/bunge_et_al_mantle_convection/doc/bunge_et_al_mantle_convection.md
  cookbooks/van-keken-vof/doc/van-keken-vof.md
  cookbooks/van-keken/doc/van-keken.md
  doc/sphinx/references.bib
Labels: ready to test
