Repository geodynamics/aspect, pull requests merged in 2022-05, with the labels that each got.

#4578 Moved visualizing phase diagram cookbook
  cookbooks/visualizing_phase_diagram/doc/harzburgite.prm
  cookbooks/visualizing_phase_diagram/doc/material_model.prm
  cookbooks/visualizing_phase_diagram/doc/pyrolite_harzburgite.png
  cookbooks/visualizing_phase_diagram/doc/pyrolite_linear.png
  cookbooks/visualizing_phase_diagram/doc/steinberg.png
  cookbooks/visualizing_phase_diagram/doc/steinberg.prm
  cookbooks/visualizing_phase_diagram/doc/visualizing_phase_diagram.tex
  cookbooks/visualizing_phase_diagram/visualizing_phase_diagram.prm
  doc/manual/cookbooks/visualizing_phase_diagram
  doc/manual/cookbooks/visualizing_phase_diagram/visualizing_phase_diagram.prm
Labels: ready to test

#4577 Moved sinker with averaging cookbook
  cookbooks/sinker-with-averaging/doc/conservative.prm
  cookbooks/sinker-with-averaging/doc/full.prm
  cookbooks/sinker-with-averaging/doc/harmonic.prm
  cookbooks/sinker-with-averaging/doc/q2q1/sinker-7-arithmetic.png
  cookbooks/sinker-with-averaging/doc/q2q1/sinker-7-geometric.png
  cookbooks/sinker-with-averaging/doc/q2q1/sinker-7-harmonic.png
  cookbooks/sinker-with-averaging/doc/q2q1/sinker-7-largest.png
  cookbooks/sinker-with-averaging/doc/q2q1/sinker-7-none.png
  cookbooks/sinker-with-averaging/doc/q2q1/sinker-7-project.png
  cookbooks/sinker-with-averaging/doc/q2q1/sinker-8-arithmetic.png
  cookbooks/sinker-with-averaging/doc/q2q1/sinker-8-geometric.png
  cookbooks/sinker-with-averaging/doc/q2q1/sinker-8-harmonic.png
  cookbooks/sinker-with-averaging/doc/q2q1/sinker-8-largest.png
  cookbooks/sinker-with-averaging/doc/q2q1/sinker-8-none.png
  cookbooks/sinker-with-averaging/doc/q2q1/sinker-8-project.png
  cookbooks/sinker-with-averaging/doc/q2q1plus/sinker-7-arithmetic.png
  cookbooks/sinker-with-averaging/doc/q2q1plus/sinker-7-geometric.png
  cookbooks/sinker-with-averaging/doc/q2q1plus/sinker-7-harmonic.png
  cookbooks/sinker-with-averaging/doc/q2q1plus/sinker-7-none.png
  cookbooks/sinker-with-averaging/doc/q2q1plus/sinker-7-pick-largest.png
  cookbooks/sinker-with-averaging/doc/q2q1plus/sinker-7-project-to-Q1.png
  cookbooks/sinker-with-averaging/doc/q2q1plus/sinker-8-arithmetic.png
  cookbooks/sinker-with-averaging/doc/q2q1plus/sinker-8-geometric.png
  cookbooks/sinker-with-averaging/doc/q2q1plus/sinker-8-harmonic.png
  cookbooks/sinker-with-averaging/doc/q2q1plus/sinker-8-none.png
  cookbooks/sinker-with-averaging/doc/q2q1plus/sinker-8-pick-largest.png
  cookbooks/sinker-with-averaging/doc/q2q1plus/sinker-8-project-to-Q1.png
  cookbooks/sinker-with-averaging/doc/sinker-with-averaging.tex
  doc/manual/cookbooks/sinker-with-averaging
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#4576 Moved shell simple 3d cookbook
  cookbooks/shell_simple_3d/doc/amr.part.prm
  cookbooks/shell_simple_3d/doc/checkpoint.part.prm
  cookbooks/shell_simple_3d/doc/heatflux.png
  cookbooks/shell_simple_3d/doc/part1.part.prm
  cookbooks/shell_simple_3d/doc/part2.part.prm
  cookbooks/shell_simple_3d/doc/part3.part.prm
  cookbooks/shell_simple_3d/doc/part4.part.prm
  cookbooks/shell_simple_3d/doc/postprocess.part.prm
  cookbooks/shell_simple_3d/doc/shell_simple_3d.tex
  cookbooks/shell_simple_3d/doc/velocities.png
  cookbooks/shell_simple_3d/doc/x-movie0700.png
  cookbooks/shell_simple_3d/shell_simple_3d.prm
  doc/manual/cookbooks/shell_simple_3d
  doc/manual/cookbooks/shell_simple_3d/doc/amr.part.prm
  doc/manual/cookbooks/shell_simple_3d/doc/checkpoint.part.prm
  doc/manual/cookbooks/shell_simple_3d/doc/part1.part.prm
  doc/manual/cookbooks/shell_simple_3d/doc/postprocess.part.prm
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#4579 Moved kinematically driven subduction 2d cookbook
  cookbooks/kinematically_driven_subduction_2d/doc/Case1_compositions.prm
  cookbooks/kinematically_driven_subduction_2d/doc/Case1_dens_t0.png
  cookbooks/kinematically_driven_subduction_2d/doc/Case1_diagnostics.png
  cookbooks/kinematically_driven_subduction_2d/doc/Case1_materialmodel.prm
  cookbooks/kinematically_driven_subduction_2d/doc/Case1_meshrefinement.prm
  cookbooks/kinematically_driven_subduction_2d/doc/Case1_postprocessing.prm
  cookbooks/kinematically_driven_subduction_2d/doc/Case1_vel_t0.png
  cookbooks/kinematically_driven_subduction_2d/doc/Case1_velocity.prm
  cookbooks/kinematically_driven_subduction_2d/doc/Case1_visc_15My.png
  cookbooks/kinematically_driven_subduction_2d/doc/Case1_visc_8My.png
  cookbooks/kinematically_driven_subduction_2d/doc/Case1_visc_t0.png
  cookbooks/kinematically_driven_subduction_2d/doc/kinematically_driven_subduction_2d.tex
  cookbooks/kinematically_driven_subduction_2d/doc/setup_Quinquis2014.png
  doc/manual/cookbooks/kinematically_driven_subduction_2d
  doc/manual/manual.tex
Labels: ready to test

#4583 Moved van Keken cookbook documentation
  cookbooks/van-keken/doc/2viscosities-final.png
  cookbooks/van-keken/doc/2viscosities-velocity.png
  cookbooks/van-keken/doc/contrast_viscosity.png
  cookbooks/van-keken/doc/main.part.prm
  cookbooks/van-keken/doc/mesh-comparison-initial-conditions.png
  cookbooks/van-keken/doc/mesh-comparison.png
  cookbooks/van-keken/doc/movie0000.png
  cookbooks/van-keken/doc/movie0003.png
  cookbooks/van-keken/doc/movie0009.png
  cookbooks/van-keken/doc/movie0018.png
  cookbooks/van-keken/doc/postprocess.part.prm
  cookbooks/van-keken/doc/smooth.part.prm
  cookbooks/van-keken/doc/smoothing-parameter-velocity.png
  cookbooks/van-keken/doc/smoothing-parameter.png
  cookbooks/van-keken/doc/van-keken.tex
  cookbooks/van-keken/doc/velocity-discontinuous.png
  cookbooks/van-keken/doc/velocity-smooth.png
  cookbooks/van-keken/van-keken-discontinuous.prm
  cookbooks/van-keken/van-keken-smooth.prm
  doc/manual/cookbooks/benchmarks/van-keken
  doc/manual/manual.tex
  tests/visualization_higher_order_output.prm
Labels: ready to merge, ready to test

#4582 Moved onset of convection benchmark documentation
  .gitignore
  benchmarks/onset-of-convection/doc/onset-of-convection.tex
  benchmarks/onset-of-convection/doc/racr.png
  benchmarks/onset-of-convection/doc/racr_error.png
  doc/manual/cookbooks/benchmarks/onset-of-convection
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#4584 Moved several benchmark's documentation
  benchmarks/inclusion/doc/inclusion-solution-pressure.png
  benchmarks/inclusion/doc/inclusion-solution.png
  benchmarks/inclusion/doc/inclusion.prm
  benchmarks/inclusion/doc/inclusion.tex
  benchmarks/rayleigh_taylor_instability/doc/grid.png
  benchmarks/rayleigh_taylor_instability/doc/grid2.png
  benchmarks/rayleigh_taylor_instability/doc/plot.pdf
  benchmarks/rayleigh_taylor_instability/doc/rayleigh_taylor_instability.tex
  benchmarks/rayleigh_taylor_instability/doc/setup.png
  benchmarks/sinking_block/doc/dens_vel.png
  benchmarks/sinking_block/doc/plot.pdf
  benchmarks/sinking_block/doc/sinking_block.tex
  benchmarks/solcx/doc/solcx-solution-pressure.png
  benchmarks/solcx/doc/solcx-solution.png
  benchmarks/solcx/doc/solcx.prm
  benchmarks/solcx/doc/solcx.tex
  benchmarks/solkz/doc/solkz-solution-pressure.png
  benchmarks/solkz/doc/solkz-solution-viscosity.png
  benchmarks/solkz/doc/solkz-solution.png
  benchmarks/solkz/doc/solkz.prm
  benchmarks/solkz/doc/solkz.tex
  doc/Makefile
  doc/manual/cookbooks/benchmarks/inclusion
  doc/manual/cookbooks/benchmarks/rayleigh_taylor_instability
  doc/manual/cookbooks/benchmarks/sinking_block
  doc/manual/cookbooks/benchmarks/solcx
  doc/manual/cookbooks/benchmarks/solkz
  doc/manual/manual.tex
Labels: ready to test

#4545 add noninitial plastic strain property
  doc/modules/changes/20220505_naliboff
  source/particle/property/viscoplastic_strain_invariants.cc
  tests/visco_plastic_yield_noninitial-plastic-strain_particles.prm
  tests/visco_plastic_yield_noninitial-plastic-strain_particles/solution/solution-00000.0000.gnuplot
  tests/visco_plastic_yield_noninitial-plastic-strain_particles/solution/solution-00001.0000.gnuplot
  tests/visco_plastic_yield_noninitial-plastic-strain_particles/solution/solution-00002.0000.gnuplot
  tests/visco_plastic_yield_noninitial-plastic-strain_particles/solution/solution-00003.0000.gnuplot
  tests/visco_plastic_yield_noninitial-plastic-strain_particles/statistics
Labels: ready to test

#4585 Moved another batch of benchmark documentation
  benchmarks/annulus/doc/annulus.tex
  benchmarks/annulus/doc/density.png
  benchmarks/annulus/doc/errors_annulus.pdf
  benchmarks/annulus/doc/pressures.png
  benchmarks/annulus/doc/velocities2.png
  benchmarks/burstedde/doc/burstedde.prm
  benchmarks/burstedde/doc/burstedde.tex
  benchmarks/burstedde/doc/errors.pdf
  benchmarks/burstedde/doc/pressure.png
  benchmarks/burstedde/doc/velocity_x.png
  benchmarks/burstedde/doc/velocity_z.png
  benchmarks/burstedde/doc/viscosity.png
  benchmarks/hollow_sphere/doc/errors_hollowsphere.pdf
  benchmarks/hollow_sphere/doc/hollow_sphere.tex
  benchmarks/hollow_sphere/doc/pressure.png
  benchmarks/hollow_sphere/doc/vel.png
  benchmarks/hollow_sphere/doc/vel2.png
  benchmarks/slab_detachment/doc/composition0000.png
  benchmarks/slab_detachment/doc/composition0007.png
  benchmarks/slab_detachment/doc/composition0011.png
  benchmarks/slab_detachment/doc/drawing.png
  benchmarks/slab_detachment/doc/results.png
  benchmarks/slab_detachment/doc/slab_detachment.tex
  benchmarks/slab_detachment/doc/strainrate.png
  benchmarks/slab_detachment/doc/velocity.png
  benchmarks/slab_detachment/doc/viscosity0000.png
  benchmarks/slab_detachment/doc/viscosity0007.png
  benchmarks/slab_detachment/doc/viscosity0011.png
  benchmarks/viscosity_grooves/doc/conv_0p1.pdf
  benchmarks/viscosity_grooves/doc/press3x3.png
  benchmarks/viscosity_grooves/doc/rhs3x3.png
  benchmarks/viscosity_grooves/doc/vel3x3.png
  benchmarks/viscosity_grooves/doc/viscosity_grooves.tex
  benchmarks/viscosity_grooves/doc/viscs.png
  cookbooks/stokes/doc/composition.png
  cookbooks/stokes/doc/mesh.png
  cookbooks/stokes/doc/stokes-density.png
  cookbooks/stokes/doc/stokes-velocity.png
  cookbooks/stokes/doc/stokes.tex
  cookbooks/stokes/doc/stokeslaw.prm
  cookbooks/stokes/doc/velocity.png
  cookbooks/stokes/stokes.prm
  doc/manual/cookbooks/benchmarks/annulus
  doc/manual/cookbooks/benchmarks/burstedde
  doc/manual/cookbooks/benchmarks/hollow_sphere
  doc/manual/cookbooks/benchmarks/slab_detachment
  doc/manual/cookbooks/benchmarks/stokes
  doc/manual/cookbooks/benchmarks/viscosity_grooves
  doc/manual/manual.tex
Labels: ready to test

#4588 Moved addtional benchmark documentation
  benchmarks/crameri_et_al/doc/crameri_1_comparison.pdf
  benchmarks/crameri_et_al/doc/crameri_2_comparison.pdf
  benchmarks/crameri_et_al/doc/crameri_2_convergence.pdf
  benchmarks/crameri_et_al/doc/crameri_benchmark_1.prm
  benchmarks/crameri_et_al/doc/crameri_benchmark_2.prm
  benchmarks/crameri_et_al/doc/crameri_et_al.tex
  benchmarks/crameri_et_al/doc/initial_topography.png
  benchmarks/crameri_et_al/doc/rising_blob.png
  benchmarks/davies_et_al/doc/Case11Vrms.png
  benchmarks/davies_et_al/doc/Case21Vrms.png
  benchmarks/davies_et_al/doc/Case22Vrms.png
  benchmarks/davies_et_al/doc/Case23Vrms.png
  benchmarks/davies_et_al/doc/case-1.1.prm
  benchmarks/davies_et_al/doc/case-2.1.prm
  benchmarks/davies_et_al/doc/case-2.2.prm
  benchmarks/davies_et_al/doc/case-2.3.prm
  benchmarks/davies_et_al/doc/case11_final.png
  benchmarks/davies_et_al/doc/case21_final.png
  benchmarks/davies_et_al/doc/case22_final.png
  benchmarks/davies_et_al/doc/case23_final.png
  benchmarks/davies_et_al/doc/davies_et_al.tex
  benchmarks/layeredflow/doc/gnuplot-script
  benchmarks/layeredflow/doc/layeredflow.tex
  benchmarks/layeredflow/doc/vel.png
  benchmarks/layeredflow/doc/viscosity.png
  benchmarks/layeredflow/doc/viscosityA.pdf
  benchmarks/layeredflow/doc/viscosityD.pdf
  benchmarks/solitary_wave/doc/setup.pdf
  benchmarks/solitary_wave/doc/solitary_wave.prm
  benchmarks/solitary_wave/doc/solitary_wave.tex
  benchmarks/tosi_et_al_2015_gcubed/doc/Case1_6_T.png
  benchmarks/tosi_et_al_2015_gcubed/doc/Case1_6_vel.png
  benchmarks/tosi_et_al_2015_gcubed/doc/Case1_6_visc.png
  benchmarks/tosi_et_al_2015_gcubed/doc/tosi_benchmark_2.prm
  benchmarks/tosi_et_al_2015_gcubed/doc/tosi_et_al_2015_gcubed.tex
  cookbooks/convection-box/doc/convection-box.prm
  cookbooks/latent-heat/doc/latent-heat-results-1.png
  cookbooks/latent-heat/doc/latent-heat-results-2.png
  cookbooks/latent-heat/doc/latent-heat-setup.png
  cookbooks/latent-heat/doc/latent-heat-temperature.png
  cookbooks/latent-heat/doc/latent-heat.tex
  cookbooks/latent-heat/doc/material.part.prm
  cookbooks/latent-heat/latent-heat.prm
  doc/Makefile
  doc/manual/cookbooks/benchmarks/crameri_et_al
  doc/manual/cookbooks/benchmarks/davies_et_al
  doc/manual/cookbooks/benchmarks/latent-heat
  doc/manual/cookbooks/benchmarks/latent-heat/doc/material.part.prm
  doc/manual/cookbooks/benchmarks/layeredflow
  doc/manual/cookbooks/benchmarks/solitary_wave
  doc/manual/cookbooks/benchmarks/tosi_et_al_2015_gcubed
  doc/manual/manual.tex
Labels: ready to test

#4206 Update continental extension cookbook
  cookbooks/continental_extension/continental_extension.prm
  cookbooks/continental_extension/doc/continental_extension.tex
  cookbooks/continental_extension/doc/continental_extension_boundary_conditions.prm
  cookbooks/continental_extension/doc/continental_extension_cookbook_0myr.png
  cookbooks/continental_extension/doc/continental_extension_cookbook_5myr.png
  cookbooks/continental_extension/doc/continental_extension_cookbook_composition_5e6yr.png
  cookbooks/continental_extension/doc/continental_extension_cookbook_strainrate_5e6yr.png
  cookbooks/continental_extension/doc/continental_extension_cookbook_strainrate_highres_10e6yr.png
  cookbooks/continental_extension/doc/continental_extension_geometry_mesh.prm
  doc/modules/changes/20210716_naliboff
  tests/continental_extension.prm
  tests/continental_extension/screen-output
Labels: ready to test

#4589 Move remaining benchmark documentation into separate files
  benchmarks/advection/doc/advection.tex
  benchmarks/advection/doc/drop.png
  benchmarks/advection/doc/rotate_shape.png
  benchmarks/buiter_et_al_2016_jsg/doc/buiter_et_al_2016_jsg.tex
  benchmarks/buiter_et_al_2016_jsg/doc/convergence.part.prm
  benchmarks/buiter_et_al_2016_jsg/doc/exp1.png
  benchmarks/buiter_et_al_2016_jsg/doc/exp2.png
  benchmarks/buiter_et_al_2016_jsg/doc/real-sandbox-1.jpg
  benchmarks/buiter_et_al_2016_jsg/doc/real-sandbox-2.jpg
  benchmarks/buiter_et_al_2016_jsg/doc/velocity_bc.part.prm
  benchmarks/doneahuerta/doc/doneahuerta.tex
  benchmarks/doneahuerta/doc/grav.png
  benchmarks/doneahuerta/doc/press.png
  benchmarks/doneahuerta/doc/vel.png
  benchmarks/gravity_mantle/doc/T.png
  benchmarks/gravity_mantle/doc/grav.png
  benchmarks/gravity_mantle/doc/gravity_mantle.tex
  benchmarks/gravity_mantle/doc/mesh.png
  benchmarks/gravity_mantle/doc/pot.png
  benchmarks/gravity_mantle/doc/rho.png
  benchmarks/gravity_thick_shell/doc/gravity_U.pdf
  benchmarks/gravity_thick_shell/doc/gravity_g.pdf
  benchmarks/gravity_thick_shell/doc/gravity_thick_shell.tex
  benchmarks/gravity_thick_shell/doc/thick_shell.prm
  benchmarks/gravity_thin_shell/doc/gravity_thin_shell.tex
  benchmarks/gravity_thin_shell/doc/thinshell_a.prm
  benchmarks/gravity_thin_shell/doc/thinshell_b.prm
  benchmarks/gravity_thin_shell/doc/thinshell_c.prm
  benchmarks/operator_splitting/doc/error_advection_reaction.pdf
  benchmarks/operator_splitting/doc/error_advection_reaction2.pdf
  benchmarks/operator_splitting/doc/error_exponential_decay.pdf
  benchmarks/operator_splitting/doc/exponential_decay.part.1.prm
  benchmarks/operator_splitting/doc/exponential_decay.part.2.prm
  benchmarks/operator_splitting/doc/operator_splitting.tex
  benchmarks/yamauchi_takei_2016_anelasticity/doc/YT16_benchmark.png
  benchmarks/yamauchi_takei_2016_anelasticity/doc/yamauchi_takei_2016_anelasticity.tex
  cookbooks/free_surface/doc/free_surface.tex
  cookbooks/free_surface_with_crust/doc/free_surface_with_crust.tex
  cookbooks/plume_2D_chunk/doc/plume.tex
  cookbooks/van-keken-vof/doc/van-keken-vof.tex
  doc/manual/cookbooks/benchmarks/advection
  doc/manual/cookbooks/benchmarks/buiter_et_al_2016_jsg
  doc/manual/cookbooks/benchmarks/doneahuerta
  doc/manual/cookbooks/benchmarks/gravity_mantle
  doc/manual/cookbooks/benchmarks/gravity_thick_shell
  doc/manual/cookbooks/benchmarks/gravity_thin_shell
  doc/manual/cookbooks/benchmarks/operator_splitting
  doc/manual/cookbooks/benchmarks/yamauchi_takei_2016_anelasticity
  doc/manual/manual.tex
Labels: ready to merge, ready to test

#4601 Updates an incomplete citation
  doc/manual/citing_aspect.bib
Labels: ready to test

#4602 Disable mesh deformation+GMG for dealii versions older than 9.3.2
  source/simulator/stokes_matrix_free.cc
Labels: ready to test

#4599 Avoid ending a preprocessor macro with an empty line.
  source/fe_variable_collection.cc
  source/simulator/entropy_viscosity.cc
  source/simulator/melt.cc
Labels: ready to merge, ready to test

#4604 Add missing empty lines.
  source/postprocess/visualization/compositional_vector.cc
  source/postprocess/visualization/geoid.cc
  source/postprocess/visualization/heating.cc
  source/postprocess/visualization/material_properties.cc
  source/postprocess/visualization/melt.cc
  source/postprocess/visualization/temperature_anomaly.cc
Labels: ready to merge, ready to test

#4606 Break awkwardly long lines.
  source/postprocess/visualization/strain_rate.cc
Labels: ready to merge, ready to test

#4603 Add missing instantiation.
  source/postprocess/visualization.cc
Labels: ready to merge, ready to test

#4605 Make percentage computation clearer.
  source/postprocess/visualization/seismic_anomalies.cc
Labels: ready to merge, ready to test

#4607 Rename a function.
  source/postprocess/visualization.cc
Labels: ready to test

#4615 2nd attempt at correcting deal.II correction
  doc/sphinx/user/intro.md
Labels: ready to merge, ready to test

#4557 Correct the computation of e_dot_ii.
  source/material_model/diffusion_dislocation.cc
  source/material_model/grain_size.cc
  source/material_model/rheology/composite_visco_plastic.cc
  source/material_model/rheology/elasticity.cc
  source/material_model/rheology/strain_dependent.cc
  source/material_model/rheology/visco_plastic.cc
  source/particle/property/integrated_strain_invariant.cc
  source/particle/property/viscoplastic_strain_invariants.cc
  source/postprocess/visualization/strain_rate.cc
  source/postprocess/visualization/stress_second_invariant.cc
Labels: ready to test

#4621 Documentation: Dim or no Dim
  doc/sphinx/user/methods/dimensionalize/index.md
Labels: ready to merge, ready to test

#4619 Documentation: fix coefficient/index.md 4 Earth
  doc/sphinx/user/methods/coefficients/index.md
Labels: ready to merge, ready to test

#4616 Fix grammatical errors
  doc/sphinx/user/intro.md
Labels: ready to merge, ready to test

#4618 Documentation: Basic equations 2d-models.md
  doc/sphinx/user/methods/basic-equations/2d-models.md
Labels: ready to merge, ready to test

#4620 Be explicit by marking functions in a derived class as 'virtual'.
  source/postprocess/visualization.cc
Labels: ready to test

#4624 Documentation: Static or Dynamic grammar fixes
  doc/sphinx/user/methods/pressure-static-dyn.md
Labels: ready to merge, ready to test

#4625 Documentation: Pressure normalization
  doc/sphinx/user/methods/pressure-norm.md
Labels: ready to merge, ready to test

#4626 Documentation: Init cond adiabatic
  doc/sphinx/user/methods/initial-conditions.md
Labels: ready to merge, ready to test

#4635 Make --close-templates the default for astyle.
  contrib/utilities/astyle.rc
Labels: ready to merge, ready to test

#4629 Documentation: Numerical methods - library names
  doc/sphinx/user/methods/numerical-methods.md
Labels: ready to merge, ready to test

#4630 Documentation: ALA - spelling
  doc/sphinx/user/methods/approximate-equations/ala.md
Labels: ready to merge, ready to test

#4631 Documentation: BA punctuation fix
  doc/sphinx/user/methods/approximate-equations/ba.md
Labels: ready to merge, ready to test

#4638 Fix typo
  cookbooks/check.mk
Labels: ready to merge, ready to test

#4627 Documentation: Compositional Fields
  doc/sphinx/user/methods/compositional-fields.md
Labels: ready to merge, ready to test

#4639 Use standard idiom to write data in the background.
  include/aspect/postprocess/visualization.h
  source/postprocess/visualization.cc
Labels: ready to merge, ready to test

#4636 Revert the accidental addition of 'virtual'.
  source/postprocess/visualization.cc
Labels: ready to merge, ready to test

#4655 Documentation: Free surface - insert reference
  doc/sphinx/user/methods/freesurface/stabilization.md
Labels: ready to merge, ready to test

#4651 Some more fixes for the .md documentation.
  doc/sphinx/user/methods/freesurface/arbitrary-le-implementation.md
  doc/sphinx/user/methods/melt-transport.md
  doc/sphinx/user/methods/particles.md
Labels: ready to test

#4649 Fix .md markup problems with <span.
  doc/sphinx/user/extending/compatibility.md
  doc/sphinx/user/extending/contributing.md
  doc/sphinx/user/extending/extending-solver.md
  doc/sphinx/user/extending/idea-of-plugins.md
  doc/sphinx/user/extending/index.md
  doc/sphinx/user/extending/plugin-types/heating-models.md
  doc/sphinx/user/extending/plugin-types/initial-conditions.md
  doc/sphinx/user/extending/plugin-types/mesh-refinement.md
  doc/sphinx/user/extending/plugin-types/vis-postprocessors.md
  doc/sphinx/user/extending/signals.md
  doc/sphinx/user/extending/testing/running-tests.md
  doc/sphinx/user/extending/testing/writing-tests.md
  doc/sphinx/user/install/docker-container/developing-in-container.md
  doc/sphinx/user/install/docker-container/installing-docker.md
  doc/sphinx/user/install/docker-container/running-models.md
  doc/sphinx/user/install/index.md
  doc/sphinx/user/install/local-installation/compiling.md
  doc/sphinx/user/install/local-installation/system-prereqs.md
  doc/sphinx/user/install/local-installation/using-candi.md
  doc/sphinx/user/run-aspect/2d-vs-3d.md
  doc/sphinx/user/run-aspect/debug-mode.md
  doc/sphinx/user/run-aspect/gui/using.md
  doc/sphinx/user/run-aspect/overview.md
  doc/sphinx/user/run-aspect/parameters-overview/muparser-format.md
  doc/sphinx/user/run-aspect/parameters-overview/structure.md
  doc/sphinx/user/run-aspect/run-faster/debug-vs-optimized.md
  doc/sphinx/user/run-aspect/run-faster/index.md
  doc/sphinx/user/run-aspect/run-faster/limiting-postprocessing.md
  doc/sphinx/user/run-aspect/run-faster/multithreading.md
  doc/sphinx/user/run-aspect/run-faster/preconditioner-tolerance.md
  doc/sphinx/user/run-aspect/run-faster/solver-tolerance.md
  doc/sphinx/user/run-aspect/visualizing-results/large-data-issues.md
  doc/sphinx/user/run-aspect/visualizing-results/stat-data.md
Labels: ready to test

#4648 Use unformatted output -- we here really just want a bit-by-bit copy into a file.
  source/postprocess/visualization.cc
Labels: ready to merge, ready to test

#4613 Allow use of 'No Advection, No Stokes' nonlinear solver scheme with the strain rheology module
  source/material_model/rheology/strain_dependent.cc
  tests/visco_plastic_yield_strain_weakening_no-advect_no_stokes.prm
  tests/visco_plastic_yield_strain_weakening_no-advect_no_stokes/screen-output
  tests/visco_plastic_yield_strain_weakening_no-advect_no_stokes/solution/solution-00000.0000.gnuplot
  tests/visco_plastic_yield_strain_weakening_no-advect_no_stokes/statistics
Labels: ready to test

#4667 Fix more problems with <span.
  doc/sphinx/user/answers.md
  doc/sphinx/user/extending/idea-of-plugins.md
  doc/sphinx/user/extending/index.md
  doc/sphinx/user/extending/plugin-types/postprocessors.md
  doc/sphinx/user/extending/write-a-plugin.md
  doc/sphinx/user/install/docker-container/running-models.md
  doc/sphinx/user/install/index.md
  doc/sphinx/user/run-aspect/first-steps.md
  doc/sphinx/user/run-aspect/overview.md
  doc/sphinx/user/run-aspect/parameters-overview/categories.md
  doc/sphinx/user/run-aspect/visualizing-results/large-data-issues.md
  doc/sphinx/user/run-aspect/visualizing-results/visit.md
Labels: ready to test

#4664 GMG: use right mapping with mesh deformation
  source/simulator/stokes_matrix_free.cc
Labels: ready to merge, ready to test

#4663 Fix a number of sphinx markdown problems.
  doc/sphinx/user/methods/advection-stabilization/entropy-viscosity.md
  doc/sphinx/user/methods/advection-stabilization/index.md
  doc/sphinx/user/methods/advection-stabilization/supg.md
  doc/sphinx/user/methods/freesurface/arbitrary-le-implementation.md
  doc/sphinx/user/methods/melt-transport.md
Labels: ready to merge, ready to test

#4658 Make quickref clearer and more accurate
  doc/sphinx/quickref.md
Labels: ready to merge, ready to test

#4652 Separate computation and output in the gravity postprocessor.
  source/postprocess/gravity_point_values.cc
Labels: ready to test

#4592 Disabled pointwise visualization
  tests/visualization_stress.prm
  tests/visualization_stress/solution/solution-00000.0000.gnuplot
Labels: ready to test

#4665 Fix code block markup.
  doc/sphinx/user/extending/idea-of-plugins.md
  doc/sphinx/user/extending/plugin-types/geometry-models.md
  doc/sphinx/user/extending/plugin-types/gravity-models.md
  doc/sphinx/user/extending/plugin-types/heating-models.md
  doc/sphinx/user/extending/plugin-types/initial-conditions.md
  doc/sphinx/user/extending/plugin-types/material-models.md
  doc/sphinx/user/extending/plugin-types/mesh-refinement.md
  doc/sphinx/user/extending/plugin-types/postprocessors.md
  doc/sphinx/user/extending/plugin-types/temp-bc.md
  doc/sphinx/user/extending/plugin-types/terminate-criteria.md
  doc/sphinx/user/extending/plugin-types/velocity-bc.md
  doc/sphinx/user/extending/plugin-types/vis-postprocessors.md
  doc/sphinx/user/extending/signals.md
Labels: ready to merge, ready to test

#4672 Documentation: installing Docker
  doc/sphinx/user/install/docker-container/installing-docker.md
Labels: ready to merge, ready to test

#4660 Docs: Burnman cookbook converted
  cookbooks/burnman/doc/burnman.md
Labels: ready to test

#4673 Fix spelling of deal.II and Trilinos.
  doc/sphinx/user/extending/extending-solver.md
  doc/sphinx/user/extending/index.md
  doc/sphinx/user/extending/plugin-types/geometry-models.md
  doc/sphinx/user/extending/plugin-types/postprocessors.md
  doc/sphinx/user/extending/write-a-plugin.md
  doc/sphinx/user/install/docker-container/developing-in-container.md
  doc/sphinx/user/install/index.md
  doc/sphinx/user/install/local-installation/index.md
  doc/sphinx/user/install/local-installation/obtaining.md
  doc/sphinx/user/install/local-installation/using-candi.md
  doc/sphinx/user/intro.md
  doc/sphinx/user/methods/geometric-multigrid.md
  doc/sphinx/user/run-aspect/2d-vs-3d.md
  doc/sphinx/user/run-aspect/debug-mode.md
  doc/sphinx/user/run-aspect/gui/index.md
  doc/sphinx/user/run-aspect/gui/installing.md
  doc/sphinx/user/run-aspect/overview.md
  doc/sphinx/user/run-aspect/run-faster/debug-vs-optimized.md
Labels: ready to merge, ready to test

#4674 Use ASCII quotes.
  doc/sphinx/user/cookbooks/cookbooks-overview.md
  doc/sphinx/user/cookbooks/geophysical-setups.md
  doc/sphinx/user/extending/idea-of-plugins.md
  doc/sphinx/user/extending/plugin-types/geometry-models.md
  doc/sphinx/user/extending/plugin-types/mesh-refinement.md
  doc/sphinx/user/extending/plugin-types/postprocessors.md
  doc/sphinx/user/extending/plugin-types/vis-postprocessors.md
  doc/sphinx/user/extending/signals.md
  doc/sphinx/user/extending/testing/test-properties.md
  doc/sphinx/user/extending/write-a-cookbook/manual-section.md
  doc/sphinx/user/extending/write-a-plugin.md
Labels: ready to merge, ready to test

#4671 Documentation: docker - rm duplicate header
  doc/sphinx/user/install/docker-container/index.md
Labels: ready to merge, ready to test

#4679 Documentation: VM
  doc/sphinx/user/install/virtual-machine/installing-vm.md
Labels: ready to merge, ready to test

#4677 Documentation: Dev in container
  doc/sphinx/user/install/docker-container/developing-in-container.md
Labels: ready to merge, ready to test

#4681 Documentation: System Prereqs
  doc/sphinx/user/install/local-installation/system-prereqs.md
Labels: ready to merge, ready to test

#4684 Documentation: Compiling ASPECT
  doc/sphinx/user/install/local-installation/compiling.md
Labels: ready to merge, ready to test

#4680 Add tikz environment.
  doc/sphinx/environment.yml
  doc/sphinx/requirements.txt
Labels: ready to merge, ready to test

#4686 No longer take arguments by value.
  include/aspect/postprocess/visualization.h
  source/postprocess/visualization.cc
Labels: ready to merge, ready to test

#4688 Save a few bytes.
  source/postprocess/gravity_point_values.cc
Labels: ready to merge, ready to test

#4687 Add a test for parallel computation of gravity point values.
  tests/gravity_point_values_spiral_parallel.prm
  tests/gravity_point_values_spiral_parallel/screen-output
  tests/gravity_point_values_spiral_parallel/statistics
Labels: ready to merge, ready to test

#4691 Documentation: overview - add note
  doc/sphinx/user/run-aspect/overview.md
Labels: ready to merge, ready to test

#4693 Documentation: selecting 2d and 3d
  doc/sphinx/user/run-aspect/2d-vs-3d.md
Labels: ready to merge, ready to test

#4694 Documentation: debug mode
  doc/sphinx/user/run-aspect/debug-mode.md
Labels: ready to merge, ready to test

#4696 Documentation: Visit
  doc/sphinx/user/run-aspect/visualizing-results/visit.md
Labels: ready to merge, ready to test

#4678 Drop duplicate markdown headers.
  doc/sphinx/user/install/docker-container/index.md
  doc/sphinx/user/install/docker-container/running-models.md
  doc/sphinx/user/install/local-installation/compiling.md
  doc/sphinx/user/install/local-installation/index.md
  doc/sphinx/user/install/local-installation/obtaining.md
  doc/sphinx/user/install/local-installation/system-prereqs.md
  doc/sphinx/user/install/local-installation/using-candi.md
  doc/sphinx/user/methods/advection-stabilization/entropy-viscosity.md
  doc/sphinx/user/methods/advection-stabilization/index.md
  doc/sphinx/user/methods/advection-stabilization/supg.md
  doc/sphinx/user/methods/freesurface/arbitrary-le-implementation.md
  doc/sphinx/user/methods/freesurface/stabilization.md
  doc/sphinx/user/methods/geometric-multigrid.md
  doc/sphinx/user/methods/particles.md
  doc/sphinx/user/run-aspect/2d-vs-3d.md
  doc/sphinx/user/run-aspect/checkpoint-restart.md
  doc/sphinx/user/run-aspect/debug-mode.md
  doc/sphinx/user/run-aspect/gui/installing.md
  doc/sphinx/user/run-aspect/gui/using.md
  doc/sphinx/user/run-aspect/overview.md
  doc/sphinx/user/run-aspect/parameters-overview/categories.md
  doc/sphinx/user/run-aspect/parameters-overview/compatibility.md
  doc/sphinx/user/run-aspect/parameters-overview/muparser-format.md
  doc/sphinx/user/run-aspect/parameters-overview/structure.md
  doc/sphinx/user/run-aspect/run-faster/limiting-postprocessing.md
  doc/sphinx/user/run-aspect/run-faster/lower-order-elements.md
  doc/sphinx/user/run-aspect/run-faster/multithreading.md
  doc/sphinx/user/run-aspect/run-faster/preconditioner-tolerance.md
  doc/sphinx/user/run-aspect/run-faster/pressure-norm-off.md
  doc/sphinx/user/run-aspect/run-faster/regularize.md
  doc/sphinx/user/run-aspect/run-faster/solver-tolerance.md
  doc/sphinx/user/run-aspect/visualizing-results/large-data-issues.md
  doc/sphinx/user/run-aspect/visualizing-results/stat-data.md
Labels: ready to merge, ready to test

#4683 Documentation: Obtaining ASPECT
  doc/sphinx/user/install/local-installation/obtaining.md
Labels: ready to merge, ready to test

#4698 Documentation: large data
  doc/sphinx/user/run-aspect/visualizing-results/large-data-issues.md
Labels: ready to merge, ready to test

#4704 Parallelize the computation of theoretical gravity values.
  source/postprocess/gravity_point_values.cc
Labels: ready to merge, ready to test

#4708 Documentation: multiparser format
  doc/sphinx/user/run-aspect/parameters-overview/muparser-format.md
Labels: ready to test

#4711 Add Lorraine to list of trusted testers
  Jenkinsfile
Labels: ready to merge, ready to test

#4705 Documentation: parameter structure
  doc/sphinx/user/run-aspect/parameters-overview/structure.md
Labels: ready to test

#4706 Documentation: parameter categories
  doc/sphinx/user/run-aspect/parameters-overview/categories.md
Labels: ready to test

#4709 Documentation: compatability
  doc/sphinx/user/run-aspect/parameters-overview/compatibility.md
Labels: ready to test

#4710 Documentation: aspect-gui
  doc/sphinx/user/run-aspect/gui/using.md
Labels: ready to test

#4699 Documentation: checkpoint restart
  doc/sphinx/user/run-aspect/checkpoint-restart.md
Labels: ready to merge, ready to test

#4700 Documentation: pressure normalization
  doc/sphinx/user/run-aspect/run-faster/pressure-norm-off.md
Labels: ready to merge, ready to test

#4701 Documentation: Parameter overview
  doc/sphinx/user/run-aspect/parameters-overview/index.md
Labels: ready to merge, ready to test

#4702 Docs: sphinx conversion - methods chapter remainder
  benchmarks/solitary_wave/doc/solitary_wave.md
  cookbooks/free_surface/doc/free_surface.md
  cookbooks/sinker-with-averaging/doc/sinker-with-averaging.md
  doc/sphinx/_static/images/rigid_rotation.png
  doc/sphinx/references.bib
  doc/sphinx/user/cookbooks/cookbooks-particles.md
  doc/sphinx/user/install/index.md
  doc/sphinx/user/methods/advection-stabilization/entropy-viscosity.md
  doc/sphinx/user/methods/advection-stabilization/index.md
  doc/sphinx/user/methods/advection-stabilization/supg.md
  doc/sphinx/user/methods/basic-equations/index.md
  doc/sphinx/user/methods/freesurface/arbitrary-le-implementation.md
  doc/sphinx/user/methods/freesurface/index.md
  doc/sphinx/user/methods/freesurface/stabilization.md
  doc/sphinx/user/methods/geometric-multigrid.md
  doc/sphinx/user/methods/melt-transport.md
  doc/sphinx/user/methods/nullspace-removal.md
  doc/sphinx/user/methods/particles.md
Labels: ready to test

#4685 Add a test for writing data in the background.
  tests/background_output_writer.prm
  tests/background_output_writer/solution/solution-00000.0000.gnuplot
  tests/background_output_writer/solution/solution-00000.0001.gnuplot
  tests/background_output_writer/solution/solution-00001.0000.gnuplot
  tests/background_output_writer/solution/solution-00001.0001.gnuplot
  tests/background_output_writer/solution/solution-00002.0000.gnuplot
  tests/background_output_writer/solution/solution-00002.0001.gnuplot
  tests/background_output_writer/solution/solution-00003.0000.gnuplot
  tests/background_output_writer/solution/solution-00003.0001.gnuplot
  tests/background_output_writer/solution/solution-00004.0000.gnuplot
  tests/background_output_writer/solution/solution-00004.0001.gnuplot
Labels: ready to test

#4722 remove reference viscosity from the material model interface
  benchmarks/compressibility_formulations/plugins/compressibility_formulations.cc
  benchmarks/operator_splitting/advection_reaction/advection_reaction.cc
  benchmarks/operator_splitting/exponential_decay/exponential_decay.cc
  doc/modules/changes/20220520_jdannberg
  include/aspect/material_model/ascii_reference_profile.h
  include/aspect/material_model/averaging.h
  include/aspect/material_model/compositing.h
  include/aspect/material_model/composition_reaction.h
  include/aspect/material_model/depth_dependent.h
  include/aspect/material_model/diffusion_dislocation.h
  include/aspect/material_model/drucker_prager.h
  include/aspect/material_model/grain_size.h
  include/aspect/material_model/interface.h
  include/aspect/material_model/latent_heat.h
  include/aspect/material_model/latent_heat_melt.h
  include/aspect/material_model/melt_global.h
  include/aspect/material_model/melt_simple.h
  include/aspect/material_model/modified_tait.h
  include/aspect/material_model/multicomponent.h
  include/aspect/material_model/multicomponent_compressible.h
  include/aspect/material_model/nondimensional.h
  include/aspect/material_model/perplex_lookup.h
  include/aspect/material_model/replace_lithosphere_viscosity.h
  include/aspect/material_model/simple.h
  include/aspect/material_model/simple_compressible.h
  include/aspect/material_model/simpler.h
  include/aspect/material_model/steinberger.h
  include/aspect/material_model/visco_plastic.h
  include/aspect/material_model/viscoelastic.h
  source/material_model/averaging.cc
  source/material_model/compositing.cc
  source/material_model/depth_dependent.cc
  source/material_model/replace_lithosphere_viscosity.cc
  tests/depth_dependent_3d_shell_list_simple.prm
  tests/depth_dependent_box_file_simple.prm
  tests/depth_dependent_box_function_simple.prm
  tests/depth_dependent_box_function_time_dependent.prm
  tests/depth_dependent_box_none_simple.prm
  tests/depth_dependent_initialize_base_model.prm
  tests/melt_visco_plastic.cc
  tests/n_expensive_stokes_solver_steps.prm
  tests/rheology_scaled_profile.cc
Labels: ready to merge, ready to test

#4622 add tests for GMG with elasticity
  tests/viscoelastic_bending_beam_gmg.prm
  tests/viscoelastic_bending_beam_gmg/depth_average.txt
  tests/viscoelastic_bending_beam_gmg/screen-output
  tests/viscoelastic_bending_beam_gmg/statistics
  tests/viscoelastic_stress_build-up_gmg.prm
  tests/viscoelastic_stress_build-up_gmg/screen-output
  tests/viscoelastic_stress_build-up_gmg/solution/solution-00000.0000.gnuplot
  tests/viscoelastic_stress_build-up_gmg/solution/solution-00001.0000.gnuplot
  tests/viscoelastic_stress_build-up_gmg/statistics
Labels: ready to merge, ready to test

#4726 Avoid deprecated combination of 'xargs' flags.
  contrib/utilities/indent
Labels: ready to test

#4668 Remove .pdf files; use .svg instead.
  benchmarks/annulus/doc/annulus.tex
  benchmarks/annulus/doc/errors_annulus.pdf
  benchmarks/burstedde/doc/burstedde.tex
  benchmarks/burstedde/doc/errors.pdf
  benchmarks/crameri_et_al/doc/crameri_1_comparison.pdf
  benchmarks/crameri_et_al/doc/crameri_2_comparison.pdf
  benchmarks/crameri_et_al/doc/crameri_2_convergence.pdf
  benchmarks/crameri_et_al/doc/crameri_et_al.tex
  benchmarks/gravity_thick_shell/doc/gravity_U.pdf
  benchmarks/gravity_thick_shell/doc/gravity_g.pdf
  benchmarks/gravity_thick_shell/doc/gravity_thick_shell.tex
  benchmarks/hollow_sphere/doc/errors_hollowsphere.pdf
  benchmarks/hollow_sphere/doc/hollow_sphere.tex
  benchmarks/layeredflow/doc/layeredflow.tex
  benchmarks/layeredflow/doc/viscosityA.pdf
  benchmarks/layeredflow/doc/viscosityD.pdf
  benchmarks/operator_splitting/doc/error_advection_reaction.pdf
  benchmarks/operator_splitting/doc/error_advection_reaction2.pdf
  benchmarks/operator_splitting/doc/error_exponential_decay.pdf
  benchmarks/operator_splitting/doc/operator_splitting.tex
  benchmarks/polydiapirs/doc/polydiapirs.tex
  benchmarks/polydiapirs/doc/vrms.pdf
  benchmarks/rayleigh_taylor_instability/doc/plot.pdf
  benchmarks/rayleigh_taylor_instability/doc/rayleigh_taylor_instability.tex
  benchmarks/sinking_block/doc/plot.pdf
  benchmarks/sinking_block/doc/sinking_block.tex
  benchmarks/solitary_wave/doc/setup.pdf
  benchmarks/solitary_wave/doc/solitary_wave.tex
  benchmarks/viscosity_grooves/doc/conv_0p1.pdf
  benchmarks/viscosity_grooves/doc/viscosity_grooves.tex
  cookbooks/burnman/doc/burnman.tex
  cookbooks/burnman/doc/comparison.pdf
  cookbooks/burnman/doc/reference_profile.pdf
  cookbooks/burnman/doc/vrms.pdf
  cookbooks/finite_strain/doc/finite_strain.pdf
  cookbooks/finite_strain/doc/finite_strain.tex
  cookbooks/geomio/doc/geomio.tex
  cookbooks/geomio/doc/jelly-paraview.pdf
  cookbooks/geomio/doc/jellyfish.pdf
  cookbooks/global_melt/doc/global_melt.tex
  cookbooks/global_melt/doc/model_evolution.pdf
  cookbooks/inner_core_convection/doc/Diagstab.pdf
  cookbooks/inner_core_convection/doc/inner_core_convection.tex
  cookbooks/inner_core_convection/doc/translation_over_P.pdf
  cookbooks/inner_core_convection/doc/translation_over_Ra_P.pdf
  cookbooks/mid_ocean_ridge/doc/depletion_profile.pdf
  cookbooks/mid_ocean_ridge/doc/mid_ocean_ridge.pdf
  cookbooks/mid_ocean_ridge/doc/mid_ocean_ridge.tex
  cookbooks/mid_ocean_ridge/doc/refinement.pdf
  cookbooks/morency_doin_2004/doc/morency_doin_2004.tex
  cookbooks/morency_doin_2004/doc/morency_doin_2004_fig1.pdf
  cookbooks/plume_2D_chunk/doc/plume.tex
  cookbooks/plume_2D_chunk/doc/vrms.pdf
  cookbooks/steinberger/doc/radial-visc-simple.pdf
  cookbooks/steinberger/doc/radial-visc.pdf
  cookbooks/steinberger/doc/steinberger.tex
  doc/Makefile
  doc/manual/manual.tex
Labels: ready to test

#4718 Sphinx documentation fix for artifical viscosity smoothing.
  cookbooks/shell_simple_2d_smoothing/doc/artificial_viscosity_smoothing.svg
  cookbooks/shell_simple_2d_smoothing/doc/shell_simple_2d_smoothing.md
Labels: ready to test

#4723 Improve documentation start page
  doc/sphinx/index.md
  doc/sphinx/user/index.md
Labels: ready to merge, ready to test

#4717 Add functionality to read compressed gzip files.
  data/initial-composition/ascii-data/test/box_2d.txt.gz
  doc/modules/changes/20220520_gassmoeller
  source/utilities.cc
  tests/ascii_data_initial_composition_2d_box_gz.prm
  tests/ascii_data_initial_composition_2d_box_gz/screen-output
  tests/ascii_data_initial_composition_2d_box_gz/statistics
Labels: ready to merge, ready to test

#4623 Darcy flow
  doc/modules/changes/20220517_danieldouglas92
  include/aspect/parameters.h
  include/aspect/simulator/assemblers/advection.h
  source/simulator/assemblers/advection.cc
  source/simulator/assembly.cc
  source/simulator/core.cc
  source/simulator/parameters.cc
  source/simulator/solver_schemes.cc
  tests/darcy_velocity.cc
  tests/darcy_velocity.prm
  tests/darcy_velocity/screen-output
  tests/darcy_velocity/statistics
Labels: ready to test

#4656 Create the .prm.tex files from all .prm files.
  CMakeLists.txt
  doc/CMakeLists.txt
  doc/manual/cookbooks/annotate.pl
  doc/manual/cookbooks/escape_index_entries.pl
Labels: ready to test

#4729 Automatically parse VERSION for sphinx documentation
  doc/sphinx/conf.py
Labels: ready to merge, ready to test

#4637 Output physical units in viz output
  include/aspect/postprocess/visualization.h
  include/aspect/postprocess/visualization/ISA_rotation_timescale.h
  include/aspect/postprocess/visualization/artificial_viscosity.h
  include/aspect/postprocess/visualization/artificial_viscosity_composition.h
  include/aspect/postprocess/visualization/boundary_indicator.h
  include/aspect/postprocess/visualization/boundary_strain_rate_residual.h
  include/aspect/postprocess/visualization/boundary_velocity_residual.h
  include/aspect/postprocess/visualization/error_indicator.h
  include/aspect/postprocess/visualization/grain_lag_angle.h
  include/aspect/postprocess/visualization/maximum_horizontal_compressive_stress.h
  include/aspect/postprocess/visualization/particle_count.h
  include/aspect/postprocess/visualization/seismic_anomalies.h
  include/aspect/postprocess/visualization/spherical_velocity_components.h
  source/postprocess/visualization.cc
  source/postprocess/visualization/ISA_rotation_timescale.cc
  source/postprocess/visualization/adiabat.cc
  source/postprocess/visualization/artificial_viscosity.cc
  source/postprocess/visualization/artificial_viscosity_composition.cc
  source/postprocess/visualization/boundary_indicator.cc
  source/postprocess/visualization/boundary_strain_rate_residual.cc
  source/postprocess/visualization/boundary_velocity_residual.cc
  source/postprocess/visualization/compositional_vector.cc
  source/postprocess/visualization/depth.cc
  source/postprocess/visualization/dynamic_topography.cc
  source/postprocess/visualization/error_indicator.cc
  source/postprocess/visualization/geoid.cc
  source/postprocess/visualization/grain_lag_angle.cc
  source/postprocess/visualization/gravity.cc
  source/postprocess/visualization/heat_flux_map.cc
  source/postprocess/visualization/heating.cc
  source/postprocess/visualization/material_properties.cc
  source/postprocess/visualization/maximum_horizontal_compressive_stress.cc
  source/postprocess/visualization/melt.cc
  source/postprocess/visualization/melt_fraction.cc
  source/postprocess/visualization/named_additional_outputs.cc
  source/postprocess/visualization/nonadiabatic_pressure.cc
  source/postprocess/visualization/nonadiabatic_temperature.cc
  source/postprocess/visualization/particle_count.cc
  source/postprocess/visualization/partition.cc
  source/postprocess/visualization/principal_stress.cc
  source/postprocess/visualization/seismic_anomalies.cc
  source/postprocess/visualization/shear_stress.cc
  source/postprocess/visualization/spd_factor.cc
  source/postprocess/visualization/spherical_velocity_components.cc
  source/postprocess/visualization/strain_rate.cc
  source/postprocess/visualization/strain_rate_tensor.cc
  source/postprocess/visualization/stress.cc
  source/postprocess/visualization/stress_second_invariant.cc
  source/postprocess/visualization/surface_dynamic_topography.cc
  source/postprocess/visualization/surface_stress.cc
  source/postprocess/visualization/temperature_anomaly.cc
  source/postprocess/visualization/vertical_heat_flux.cc
  source/postprocess/visualization/volume_of_fluid_values.cc
  source/postprocess/visualization/volumetric_strain_rate.cc
  tests/composition_names_duplicates/screen-output
Labels: ready to merge, ready to test

#4682 Documentation: Using candi
  doc/sphinx/user/install/local-installation/using-candi.md
Labels: ready to merge

#4744 Remove duplicate math environments
  cookbooks/burnman/doc/burnman.md
  doc/sphinx/quickref.md
  doc/sphinx/user/methods/approximate-equations/ala.md
  doc/sphinx/user/methods/approximate-equations/ba.md
  doc/sphinx/user/methods/approximate-equations/index.md
  doc/sphinx/user/methods/approximate-equations/tala.md
  doc/sphinx/user/methods/basic-equations/2d-models.md
  doc/sphinx/user/methods/basic-equations/adiabatic-heating.md
  doc/sphinx/user/methods/basic-equations/bc.md
  doc/sphinx/user/methods/basic-equations/index.md
  doc/sphinx/user/methods/choosing-a-formulation/adiabatic-profile.md
  doc/sphinx/user/methods/coefficients/averaging.md
  doc/sphinx/user/methods/coefficients/self-consistency.md
  doc/sphinx/user/methods/compositional-fields.md
  doc/sphinx/user/methods/constitutive-laws.md
  doc/sphinx/user/methods/freesurface/arbitrary-le-implementation.md
  doc/sphinx/user/methods/initial-conditions.md
  doc/sphinx/user/methods/melt-transport.md
  doc/sphinx/user/methods/particles.md
  doc/sphinx/user/methods/pressure-static-dyn.md
  doc/sphinx/user/run-aspect/run-faster/preconditioner-tolerance.md
Labels: ready to merge, ready to test

#4737 Docs: Converting cookbooks and benchmarks chapters
  benchmarks/solcx/doc/solcx.md
  cookbooks/convection-box-particles/doc/convection-box-particles.md
  cookbooks/heat_flow/doc/heat-flow.md
  cookbooks/magnetic_stripes/doc/magnetic_stripes.md
  cookbooks/onset_of_convection/doc/onset_of_convection.md
  doc/sphinx/references.bib
  doc/sphinx/user/benchmarks/benchmark-run.md
  doc/sphinx/user/benchmarks/index.md
  doc/sphinx/user/cookbooks/cookbooks-composition.md
  doc/sphinx/user/cookbooks/cookbooks-overview.md
  doc/sphinx/user/cookbooks/cookbooks-particles.md
  doc/sphinx/user/cookbooks/geophysical-setups.md
  doc/sphinx/user/cookbooks/index.md
  doc/sphinx/user/cookbooks/simple-setups.md
  doc/sphinx/user/cookbooks/teaching-setups.md
Labels: ready to merge

#4746 Documentation: nullspace removal
  doc/sphinx/user/methods/nullspace-removal.md
Labels: ready to merge

#4747 Fix edit button in documentation
  doc/sphinx/conf.py
Labels: ready to merge, ready to test

#4749 shorten an assert
  source/simulator/parameters.cc
Labels: ready to merge, ready to test

#4697 Documentation: statistical data
  doc/sphinx/user/run-aspect/visualizing-results/stat-data.md
Labels: ready to merge, ready to test

#4745 Parameters documentation in Sphinx
  contrib/utilities/jsontomarkdown.py
  doc/sphinx/index.md
  doc/sphinx/parameters/Adiabatic_20conditions_20model.md
  doc/sphinx/parameters/Boundary_20composition_20model.md
  doc/sphinx/parameters/Boundary_20fluid_20pressure_20model.md
  doc/sphinx/parameters/Boundary_20heat_20flux_20model.md
  doc/sphinx/parameters/Boundary_20temperature_20model.md
  doc/sphinx/parameters/Boundary_20traction_20model.md
  doc/sphinx/parameters/Boundary_20velocity_20model.md
  doc/sphinx/parameters/Checkpointing.md
  doc/sphinx/parameters/Compositional_20fields.md
  doc/sphinx/parameters/Discretization.md
  doc/sphinx/parameters/Formulation.md
  doc/sphinx/parameters/Geometry_20model.md
  doc/sphinx/parameters/Gravity_20model.md
  doc/sphinx/parameters/Heating_20model.md
  doc/sphinx/parameters/Initial_20composition_20model.md
  doc/sphinx/parameters/Initial_20temperature_20model.md
  doc/sphinx/parameters/Material_20model.md
  doc/sphinx/parameters/Melt_20settings.md
  doc/sphinx/parameters/Mesh_20deformation.md
  doc/sphinx/parameters/Mesh_20refinement.md
  doc/sphinx/parameters/Nullspace_20removal.md
  doc/sphinx/parameters/Postprocess.md
  doc/sphinx/parameters/Prescribed_20Stokes_20solution.md
  doc/sphinx/parameters/Solver_20parameters.md
  doc/sphinx/parameters/Temperature_20field.md
  doc/sphinx/parameters/Termination_20criteria.md
  doc/sphinx/parameters/Time_20stepping.md
  doc/sphinx/parameters/Volume_20of_20Fluid.md
  doc/sphinx/parameters/global.md
  doc/sphinx/parameters/index.md
  doc/sphinx/quickref.md
  doc/update_parameters.sh
Labels: ready to merge, ready to test

#4741 Doc: Updated SolCx and Solkz benchmark
  benchmarks/solcx/doc/solcx.md
  benchmarks/solkz/doc/solkz.md
Labels: ready to test

#4756 Add two changelog entries for recent patches of mine.
  doc/modules/changes/20220519_wolfgangbangerth
  doc/modules/changes/20220520_wolfgangbangerth
Labels: ready to test

#4759 References fix
  cookbooks/finite_strain/doc/finite_strain.md
  doc/sphinx/user/methods/compositional-fields.md
  doc/sphinx/user/methods/dimensionalize/index.md
Labels: ready to merge, ready to test

#4758 doc: do not make headers bold
  contrib/utilities/jsontomarkdown.py
  doc/sphinx/parameters/Adiabatic_20conditions_20model.md
  doc/sphinx/parameters/Boundary_20composition_20model.md
  doc/sphinx/parameters/Boundary_20fluid_20pressure_20model.md
  doc/sphinx/parameters/Boundary_20heat_20flux_20model.md
  doc/sphinx/parameters/Boundary_20temperature_20model.md
  doc/sphinx/parameters/Boundary_20traction_20model.md
  doc/sphinx/parameters/Boundary_20velocity_20model.md
  doc/sphinx/parameters/Checkpointing.md
  doc/sphinx/parameters/Compositional_20fields.md
  doc/sphinx/parameters/Discretization.md
  doc/sphinx/parameters/Formulation.md
  doc/sphinx/parameters/Geometry_20model.md
  doc/sphinx/parameters/Gravity_20model.md
  doc/sphinx/parameters/Heating_20model.md
  doc/sphinx/parameters/Initial_20composition_20model.md
  doc/sphinx/parameters/Initial_20temperature_20model.md
  doc/sphinx/parameters/Material_20model.md
  doc/sphinx/parameters/Melt_20settings.md
  doc/sphinx/parameters/Mesh_20deformation.md
  doc/sphinx/parameters/Mesh_20refinement.md
  doc/sphinx/parameters/Nullspace_20removal.md
  doc/sphinx/parameters/Postprocess.md
  doc/sphinx/parameters/Prescribed_20Stokes_20solution.md
  doc/sphinx/parameters/Solver_20parameters.md
  doc/sphinx/parameters/Temperature_20field.md
  doc/sphinx/parameters/Termination_20criteria.md
  doc/sphinx/parameters/Time_20stepping.md
  doc/sphinx/parameters/Volume_20of_20Fluid.md
Labels: ready to merge, ready to test

#4760 update readme with doc links
  README.md
Labels: ready to merge

#4762 Docs: move images to images directories
  doc/sphinx/user/methods/images/rigid_rotation.png
  doc/sphinx/user/methods/nullspace-removal.md
  doc/sphinx/user/run-aspect/gui/images/aspect-gui.png
  doc/sphinx/user/run-aspect/gui/using.md
  doc/sphinx/user/run-aspect/images/depthaverage2.png
  doc/sphinx/user/run-aspect/overview.md
  doc/sphinx/user/run-aspect/visualizing-results/images/visit-1-multi.svg
  doc/sphinx/user/run-aspect/visualizing-results/images/visit-2-multi.svg
  doc/sphinx/user/run-aspect/visualizing-results/images/viz-gnuplot.svg
  doc/sphinx/user/run-aspect/visualizing-results/stat-data.md
  doc/sphinx/user/run-aspect/visualizing-results/visit.md
Labels: ready to merge, ready to test

#4761 Documentation: nonlinear Stokes solver
  doc/sphinx/user/methods/nonlinear-stokes-solvers.md
Labels: ready to merge, ready to test

#4751 Docs: Convert Extending and Answers chapters
  benchmarks/davies_et_al/doc/davies_et_al.md
  cookbooks/inner_core_convection/doc/inner_core_convection.md
  cookbooks/prescribed_velocity/doc/prescribed_velocity.md
  doc/sphinx/user/answers.md
  doc/sphinx/user/extending/compatibility.md
  doc/sphinx/user/extending/contributing.md
  doc/sphinx/user/extending/extending-solver.md
  doc/sphinx/user/extending/idea-of-plugins.md
  doc/sphinx/user/extending/images/plugin_graph.svg
  doc/sphinx/user/extending/index.md
  doc/sphinx/user/extending/plugin-types/geometry-models.md
  doc/sphinx/user/extending/plugin-types/gravity-models.md
  doc/sphinx/user/extending/plugin-types/heating-models.md
  doc/sphinx/user/extending/plugin-types/initial-conditions.md
  doc/sphinx/user/extending/plugin-types/material-models.md
  doc/sphinx/user/extending/plugin-types/mesh-refinement.md
  doc/sphinx/user/extending/plugin-types/postprocessors.md
  doc/sphinx/user/extending/plugin-types/temp-bc.md
  doc/sphinx/user/extending/plugin-types/terminate-criteria.md
  doc/sphinx/user/extending/plugin-types/velocity-bc.md
  doc/sphinx/user/extending/plugin-types/vis-postprocessors.md
  doc/sphinx/user/extending/signals.md
  doc/sphinx/user/extending/testing/running-tests.md
  doc/sphinx/user/extending/testing/writing-tests.md
  doc/sphinx/user/extending/write-a-cookbook/index.md
  doc/sphinx/user/extending/write-a-cookbook/manual-section.md
  doc/sphinx/user/extending/write-a-cookbook/parameter-file.md
  doc/sphinx/user/extending/write-a-cookbook/plugins.md
  doc/sphinx/user/extending/write-a-plugin.md
  doc/sphinx/user/install/docker-container/index.md
  doc/sphinx/user/install/local-installation/compiling.md
Labels: ready to merge, ready to test

#4086 Enable data sharing across processes
  doc/modules/changes/20210728_bangerth
  include/aspect/structured_data.h
  source/structured_data.cc
  unit_tests/utilities.cc
Labels: ready to test

#4776 Documentation: geometry models
  doc/sphinx/user/extending/plugin-types/geometry-models.md
Labels: ready to merge, ready to test

#4765 Documentation: Cookbooks how to
  doc/sphinx/user/cookbooks/cookbooks-overview.md
Labels: ready to merge, ready to test

#4768 Documentation: Extending
  doc/sphinx/user/extending/index.md
Labels: ready to merge, ready to test

#4783 Documentation: postprocessors
  doc/sphinx/user/extending/plugin-types/postprocessors.md
Labels: ready to merge, ready to test

#4781 Add an svg version of the logo.
  doc/logo/unlabeled_logo.svg
Labels: ready to merge, ready to test

#4769 Doc: Add manual section for Darcy Advection Method
  doc/modules/changes/20220522_danieldouglas92
  doc/sphinx/user/methods/melt-transport.md
Labels: ready to merge

#4786 Create svg version of the plugin graph.
  doc/manual/manual.tex
  doc/manual/plugin_graph.pdf
  doc/manual/plugin_graph.svg
  doc/update_parameters.sh
Labels: ready to test

#4766 StructuredData: support large indices
  include/aspect/structured_data.h
  source/structured_data.cc
Labels: ready to merge, ready to test

#4789 Avoid an #ifdef inside a comment.
  include/aspect/structured_data.h
Labels: ready to merge, ready to test

#4757 Docs: Update parameter references and TODOs
  cookbooks/shell_simple_2d_smoothing/doc/shell_simple_2d_smoothing.md
  doc/sphinx/parameters/Formulation.md
  doc/sphinx/user/cookbooks/cookbooks-overview.md
  doc/sphinx/user/methods/advection-stabilization/entropy-viscosity.md
  doc/sphinx/user/methods/advection-stabilization/index.md
  doc/sphinx/user/methods/basic-equations/adiabatic-heating.md
  doc/sphinx/user/methods/choosing-a-formulation/combined-formulations.md
  doc/sphinx/user/methods/choosing-a-formulation/index.md
  doc/sphinx/user/methods/choosing-a-formulation/mass-conservation-approx.md
  doc/sphinx/user/methods/choosing-a-formulation/temp-equation-approx.md
  doc/sphinx/user/methods/initial-conditions.md
  doc/sphinx/user/methods/nullspace-removal.md
  doc/sphinx/user/methods/particles.md
  doc/sphinx/user/run-aspect/checkpoint-restart.md
  doc/sphinx/user/run-aspect/overview.md
  doc/sphinx/user/run-aspect/parameters-overview/categories.md
  doc/sphinx/user/run-aspect/run-faster/limiting-postprocessing.md
  doc/sphinx/user/run-aspect/run-faster/lower-order-elements.md
  doc/sphinx/user/run-aspect/run-faster/pressure-norm-off.md
  doc/sphinx/user/run-aspect/run-faster/solver-tolerance.md
  doc/sphinx/user/run-aspect/visualizing-results/index.md
  doc/sphinx/user/run-aspect/visualizing-results/large-data-issues.md
  doc/sphinx/user/run-aspect/visualizing-results/stat-data.md
Labels: ready to merge, ready to test

#4662 Boundary traction spherical
  include/aspect/boundary_traction/function.h
  source/boundary_traction/function.cc
  tests/boundary_traction_function_cartesian_free_surface.prm
  tests/boundary_traction_function_cartesian_free_surface/screen-output
  tests/boundary_traction_function_cartesian_free_surface/statistics
  tests/boundary_traction_function_cartesian_free_surface/topography.00000
  tests/boundary_traction_function_cartesian_free_surface/topography.00001
  tests/boundary_traction_function_cartesian_free_surface/topography.00002
  tests/boundary_traction_function_spherical_free_surface.prm
  tests/boundary_traction_function_spherical_free_surface/screen-output
  tests/boundary_traction_function_spherical_free_surface/statistics
  tests/boundary_traction_function_spherical_free_surface/topography.00000
  tests/boundary_traction_function_spherical_free_surface/topography.00001
  tests/boundary_traction_function_spherical_free_surface/topography.00002
Labels: ready to merge, ready to test

#4716 Add infill density benchmark
  benchmarks/infill_density/CMakeLists.txt
  benchmarks/infill_density/data/box_2d_top.0.txt
  benchmarks/infill_density/data/box_2d_top.1.txt
  benchmarks/infill_density/data/box_2d_top.10.txt
  benchmarks/infill_density/data/box_2d_top.2.txt
  benchmarks/infill_density/data/box_2d_top.3.txt
  benchmarks/infill_density/data/box_2d_top.4.txt
  benchmarks/infill_density/data/box_2d_top.5.txt
  benchmarks/infill_density/data/box_2d_top.6.txt
  benchmarks/infill_density/data/box_2d_top.7.txt
  benchmarks/infill_density/data/box_2d_top.8.txt
  benchmarks/infill_density/data/box_2d_top.9.txt
  benchmarks/infill_density/doc/choosing_infill_densities.png
  benchmarks/infill_density/doc/flexure_comparison.png
  benchmarks/infill_density/doc/infill_density.md
  benchmarks/infill_density/infill_ascii.prm
  benchmarks/infill_density/infill_ascii_data.cc
  doc/modules/changes/20220522b_danieldouglas92
  doc/sphinx/user/benchmarks/index.md
  tests/infill_density_flexure.cc
  tests/infill_density_flexure.prm
  tests/infill_density_flexure/screen-output
  tests/infill_density_flexure/statistics
Labels: ready to test

#4770 Documentation: plugins
  doc/sphinx/user/extending/idea-of-plugins.md
Labels: ready to merge, ready to test

#4780 Use 'include' instead of 'input' in latex
  cookbooks/bunge_et_al_mantle_convection/doc/bunge_et_al_mantle_convection.tex
  cookbooks/burnman/doc/burnman.tex
  cookbooks/christensen_yuen_phase_function/doc/christensen_yuen_phase_function.tex
  cookbooks/composition-reaction/doc/composition-reaction.tex
  cookbooks/composition_active/doc/composition_active.tex
  cookbooks/composition_active_particles/doc/composition_active_particles.tex
  cookbooks/composition_passive/doc/composition_passive.tex
  cookbooks/composition_passive_particles/doc/composition_passive_particles.tex
  cookbooks/continental_extension/doc/continental_extension.tex
  cookbooks/convection-box-particles/doc/convection-box-particles.tex
  cookbooks/convection-box/doc/convection-box.tex
  cookbooks/convection_box_3d/doc/convection_box_3d.tex
  cookbooks/crustal_deformation/doc/crustal_deformation.tex
  cookbooks/finite_strain/doc/finite_strain.tex
  cookbooks/free_surface/doc/free_surface.tex
  cookbooks/free_surface_with_crust/doc/free_surface_with_crust.tex
  cookbooks/geomio/doc/geomio.tex
  cookbooks/global_melt/doc/global_melt.tex
  cookbooks/gplates/doc/gplates.tex
  cookbooks/heat_flow/doc/heat-flow.tex
  cookbooks/initial-condition-S20RTS/doc/initial-condition-S20RTS.tex
  cookbooks/inner_core_convection/doc/inner_core_convection.tex
  cookbooks/kinematically_driven_subduction_2d/doc/kinematically_driven_subduction_2d.tex
  cookbooks/magnetic_stripes/doc/magnetic_stripes.tex
  cookbooks/mid_ocean_ridge/doc/mid_ocean_ridge.tex
  cookbooks/morency_doin_2004/doc/morency_doin_2004.tex
  cookbooks/muparser_temperature_example/doc/muparser_temperature_example.tex
  cookbooks/onset_of_convection/doc/onset_of_convection.tex
  cookbooks/platelike-boundary/doc/platelike-boundary.tex
  cookbooks/plume_2D_chunk/doc/plume.tex
  cookbooks/prescribed_velocity/doc/prescribed_velocity.tex
  cookbooks/prescribed_velocity_ascii_data/doc/prescribed_velocity_ascii_data.tex
  cookbooks/shell_3d_postprocess/doc/shell_3d_postprocess.tex
  cookbooks/shell_simple_2d/doc/shell_simple_2d.tex
  cookbooks/shell_simple_2d_smoothing/doc/shell_simple_2d_smoothing.tex
  cookbooks/shell_simple_3d/doc/shell_simple_3d.tex
  cookbooks/sinker-with-averaging/doc/sinker-with-averaging.tex
  cookbooks/steinberger/doc/steinberger.tex
  cookbooks/van-keken-vof/doc/van-keken-vof.tex
  cookbooks/visualizing_phase_diagram/doc/visualizing_phase_diagram.tex
  doc/manual/manual.tex
Labels: ready to test

#4778 Documentation: convection cookbooks
  cookbooks/convection_box_3d/doc/box_3d_mesh.png
  cookbooks/convection_box_3d/doc/box_3d_solution.png
  cookbooks/convection_box_3d/doc/convection_box_3d.md
  cookbooks/platelike-boundary/doc/platelike-boundary.md
  cookbooks/platelike-boundary/doc/platelike.png
  doc/sphinx/user/extending/plugin-types/velocity-bc.md
Labels: ready to merge, ready to test

#4790 Simplify code structure in python script slightly.
  contrib/utilities/jsontomarkdown.py
Labels: ready to merge, ready to test

#4763 Documentation: Figures for nonlinear stokes solve
  doc/sphinx/user/methods/nonlinear-stokes-solvers.md
Labels: ready to merge, ready to test

#4724 Prescribed velocity doc
  cookbooks/prescribed_velocity/doc/prescribed_velocity.md
  cookbooks/prescribed_velocity/doc/prescribed_velocity.svg
Labels: ready to merge, ready to test

#4774 Documentation: manual sections
  doc/sphinx/user/extending/write-a-cookbook/manual-section.md
Labels: ready to merge, ready to test

#4775 Documentation: material models
  doc/sphinx/user/extending/plugin-types/material-models.md
Labels: ready to merge

#4777 Docs 2d annulus cookbook
  cookbooks/shell_simple_2d/doc/avgtemp-multi.png
  cookbooks/shell_simple_2d/doc/heatflux-multi.svg
  cookbooks/shell_simple_2d/doc/rms-multi.png
  cookbooks/shell_simple_2d/doc/shell_simple_2d.md
  cookbooks/shell_simple_2d/doc/x-movie.svg
Labels: ready to merge, ready to test

#4725 Remove a duplicate function
  include/aspect/simulator.h
  include/aspect/simulator_access.h
  source/material_model/interface.cc
  source/mesh_deformation/free_surface.cc
  source/simulator/assemblers/advection.cc
  source/simulator/assembly.cc
  source/simulator/melt.cc
  source/simulator/simulator_access.cc
  source/simulator/stokes_matrix_free.cc
Labels: ready to test

#4739 Sphinx documentation fix for convection box 2d
  cookbooks/convection-box/doc/convection-box.md
  cookbooks/convection-box/doc/convection_box_fields.svg
  cookbooks/convection-box/doc/convection_box_fields_different_Ra.svg
  cookbooks/convection-box/doc/convection_box_stats.svg
  cookbooks/convection-box/doc/convection_box_stats_different_Ra.svg
  cookbooks/convection-box/doc/convection_box_stats_steps.svg
Labels: ready to merge, ready to test

#4785 Add 3 lines utilities
  source/utilities.cc
Labels: ready to merge, ready to test

#4801 include cc file from benchmarks folder
  tests/infill_density_flexure.cc
Labels: ready to merge

#4806 Documentation: contributing
  doc/sphinx/user/extending/contributing.md
Labels: ready to merge

#4808 Documentation: future plans
  doc/sphinx/user/extending/future-plans.md
Labels: ready to merge

#4791 Convert some latex to md in doc strings.
  contrib/utilities/jsontomarkdown.py
  doc/manual/parameters.tex
  doc/parameter_view/parameters.xml
  doc/sphinx/parameters/Adiabatic_20conditions_20model.md
  doc/sphinx/parameters/Boundary_20composition_20model.md
  doc/sphinx/parameters/Boundary_20fluid_20pressure_20model.md
  doc/sphinx/parameters/Boundary_20heat_20flux_20model.md
  doc/sphinx/parameters/Boundary_20temperature_20model.md
  doc/sphinx/parameters/Boundary_20traction_20model.md
  doc/sphinx/parameters/Boundary_20velocity_20model.md
  doc/sphinx/parameters/Compositional_20fields.md
  doc/sphinx/parameters/Discretization.md
  doc/sphinx/parameters/Formulation.md
  doc/sphinx/parameters/Geometry_20model.md
  doc/sphinx/parameters/Gravity_20model.md
  doc/sphinx/parameters/Heating_20model.md
  doc/sphinx/parameters/Initial_20composition_20model.md
  doc/sphinx/parameters/Initial_20temperature_20model.md
  doc/sphinx/parameters/Material_20model.md
  doc/sphinx/parameters/Melt_20settings.md
  doc/sphinx/parameters/Mesh_20deformation.md
  doc/sphinx/parameters/Mesh_20refinement.md
  doc/sphinx/parameters/Nullspace_20removal.md
  doc/sphinx/parameters/Postprocess.md
  doc/sphinx/parameters/Prescribed_20Stokes_20solution.md
  doc/sphinx/parameters/Solver_20parameters.md
  doc/sphinx/parameters/Temperature_20field.md
  doc/sphinx/parameters/Termination_20criteria.md
  doc/sphinx/parameters/Time_20stepping.md
  doc/sphinx/parameters/Volume_20of_20Fluid.md
  doc/sphinx/parameters/global.md
Labels: ready to test

#4782 Bilinear Least Squares particle interpolation updates
  include/aspect/particle/interpolator/bilinear_least_squares.h
  source/particle/interpolator/bilinear_least_squares.cc
  source/particle/interpolator/cell_average.cc
  tests/particle_interpolator_bilinear_3d.prm
  tests/particle_interpolator_bilinear_3d/screen-output
  tests/particle_interpolator_bilinear_3d/statistics
  tests/particle_interpolator_bilinear_add_particles.prm
  tests/particle_interpolator_bilinear_add_particles/screen-output
  tests/particle_interpolator_bilinear_least_squares_solkz/screen-output
  tests/particle_interpolator_bilinear_least_squares_solkz/statistics
Labels: ready to merge, ready to test

#4805 Docs: Remove \texttt from references.bib
  doc/sphinx/references.bib
Labels: ready to merge, ready to test

#4809 Documentation: inclusion benchmark
  benchmarks/inclusion/doc/inclusion.md
Labels: ready to merge

#4814 fix a section reference
  doc/sphinx/user/benchmarks/benchmark-run.md
Labels: ready to merge, ready to test

#4825 Remove a python package no longer needed.
  doc/sphinx/environment.yml
Labels: ready to test

#4820 Use #include "..." when using relative paths.
  tests/crameri_benchmark_1_gmg.cc
  tests/infill_density_flexure.cc
  tests/magnetic_stripes.cc
  tests/melt_track.cc
  tests/particle_property_composition.cc
  tests/rigid_shear_instantaneous.cc
  tests/rigid_shear_time_dependent.cc
  tests/shear_bands.cc
  tests/solitary_wave.cc
  tests/spiegelman_material.cc
  tests/tosi_benchmark.cc
  tests/tosi_benchmark_newton_solver.cc
  tests/tosi_benchmark_newton_solver_full_A.cc
Labels: ready to test

#4819 Add to the documentation of a function.
  include/aspect/utilities.h
Labels: ready to test

#4795 Docs: Update manual-writing section
  doc/sphinx/quickref.md
  doc/sphinx/user/extending/write-a-cookbook/index.md
  doc/sphinx/user/extending/write-a-cookbook/manual-section.md
Labels: ready to merge, ready to test

#4816 Add a publication that uses ASPECT.
  doc/manual/citing_aspect.bib
Labels: ready to test

#4823 Fix typos.
  doc/CMakeLists.txt
Labels: ready to merge, ready to test

#4822 Improve mark up of parameter descriptions.
  contrib/utilities/jsontomarkdown.py
  doc/sphinx/parameters/Boundary_20composition_20model.md
  doc/sphinx/parameters/Boundary_20heat_20flux_20model.md
  doc/sphinx/parameters/Boundary_20temperature_20model.md
  doc/sphinx/parameters/Boundary_20traction_20model.md
  doc/sphinx/parameters/Boundary_20velocity_20model.md
  doc/sphinx/parameters/Compositional_20fields.md
  doc/sphinx/parameters/Discretization.md
  doc/sphinx/parameters/Geometry_20model.md
  doc/sphinx/parameters/Gravity_20model.md
  doc/sphinx/parameters/Heating_20model.md
  doc/sphinx/parameters/Initial_20composition_20model.md
  doc/sphinx/parameters/Initial_20temperature_20model.md
  doc/sphinx/parameters/Material_20model.md
  doc/sphinx/parameters/Melt_20settings.md
  doc/sphinx/parameters/Mesh_20refinement.md
  doc/sphinx/parameters/Nullspace_20removal.md
  doc/sphinx/parameters/Postprocess.md
  doc/sphinx/parameters/Solver_20parameters.md
  doc/sphinx/parameters/Temperature_20field.md
  doc/sphinx/parameters/Termination_20criteria.md
  doc/sphinx/parameters/global.md
Labels: ready to test

#4728 Add instructions for simple figure in documentation quickref
  doc/sphinx/quickref.md
Labels: ready to merge, ready to test
