Repository geodynamics/aspect, pull requests merged in 2023-10, with the labels that each got.

#5411 Some changes in compute_current_constraints().
  source/simulator/core.cc
Labels: ready to test

#5415 fix formatting in parameter doc
  source/simulator/parameters.cc
Labels: documentation

#5416 Update citing_aspect.bib
  doc/manual/citing_aspect.bib
Labels: ready to merge, ready to test

#5409 Clean up some details in solve_stokes().
  source/simulator/solver.cc
Labels: ready to test

#5424 Fix a memory leak.
  benchmarks/shear_bands/shear_bands.cc
Labels: ready to merge, ready to test

#5425 Avoid bare 'new' operator. Use std::make_unique/shared.
  benchmarks/annulus/plugin/annulus.cc
  benchmarks/burstedde/burstedde.cc
  benchmarks/doneahuerta/doneahuerta.cc
  benchmarks/hollow_sphere/hollow_sphere.cc
  benchmarks/inclusion/inclusion.h
  benchmarks/layeredflow/layeredflow.cc
  benchmarks/solcx/solcx.h
  benchmarks/solitary_wave/solitary_wave.cc
  benchmarks/time_dependent_annulus/plugin/time_dependent_annulus.h
  benchmarks/viscosity_grooves/viscosity_grooves.cc
  source/material_model/grain_size.cc
  source/material_model/rheology/elasticity.cc
  source/material_model/rheology/strain_dependent.cc
  source/mesh_deformation/interface.cc
  source/postprocess/visualization/ISA_rotation_timescale.cc
  source/postprocess/visualization/grain_lag_angle.cc
  source/simulator/introspection.cc
  source/volume_of_fluid/handler.cc
Labels: ready to merge, ready to test

#5427 A couple of cleanups.
  source/mesh_deformation/interface.cc
Labels: ready to merge, ready to test

#5428 Add an assertion.
  source/geometry_model/chunk.cc
Labels: ready to merge, ready to test

#5419 Use a constraints object of the right size.
  source/simulator/helper_functions.cc
  source/simulator/solver.cc
  source/simulator/stokes_matrix_free.cc
Labels: ready to test

#5429 Add a new tester with deal.II 9.5
  .github/workflows/linux.yml
Labels: ready to merge

#5432 Augment the documentation of a signal.
  include/aspect/simulator_signals.h
Labels: ready to merge, ready to test

#5433 Better document the choice of manifold ids.
  source/geometry_model/chunk.cc
  source/geometry_model/ellipsoidal_chunk.cc
  source/geometry_model/two_merged_chunks.cc
Labels: ready to test

#5430 Clean up a string conversion
  source/geometry_model/interface.cc
Labels: ready to merge, ready to test

#5417 Add warning that CPO plugin in still a work in progress.
  source/particle/property/crystal_preferred_orientation.cc
Labels: ready to merge

#5440 Better document the choice of QTrapezoid.
  source/postprocess/sea_level.cc
  source/postprocess/topography.cc
Labels: ready to merge, ready to test

#5413 Parameter doc no escape backtick
  contrib/utilities/jsontomarkdown.py
  source/boundary_composition/function.cc
  source/boundary_heat_flux/function.cc
  source/boundary_temperature/function.cc
  source/boundary_velocity/function.cc
  source/gravity_model/function.cc
  source/heating_model/function.cc
  source/initial_composition/function.cc
  source/initial_temperature/adiabatic.cc
  source/initial_temperature/function.cc
  source/mesh_deformation/function.cc
  source/mesh_refinement/maximum_refinement_function.cc
  source/mesh_refinement/minimum_refinement_function.cc
  source/particle/generator/probability_density_function.cc
  source/particle/property/function.cc
  source/prescribed_stokes_solution/function.cc
Labels: documentation

#5444 doc: turn a warning into a note
  source/simulator/parameters.cc
Labels: documentation

#5445 Print the number of mesh deformation DoFs nicely.
  source/mesh_deformation/interface.cc
  tests/airy_isostasy/screen-output
  tests/airy_isostasy_initial_topo/screen-output
  tests/boundary_traction_function_cartesian_free_surface/screen-output
  tests/boundary_traction_function_spherical_free_surface/screen-output
  tests/box_simple_surface_strain_rate_residual/screen-output
  tests/checkpoint_07_enable_free_surface_create/screen-output
  tests/checkpoint_07_enable_free_surface_resume/screen-output
  tests/chunk_tangential_velocity/screen-output
  tests/crameri_benchmark_1_gmg/screen-output
  tests/crustal_model_3D/screen-output
  tests/dynamic_friction/screen-output
  tests/free_surface_VE_cylinder_2D_loading_fixed_elastic_dt_gmg/screen-output
  tests/free_surface_adaptive_blob/screen-output
  tests/free_surface_blob/screen-output
  tests/free_surface_blob_gmg/screen-output
  tests/free_surface_blob_melt/screen-output
  tests/free_surface_blob_nonzero_melt/screen-output
  tests/free_surface_iterated_IMPES/screen-output
  tests/free_surface_iterated_stokes/screen-output
  tests/free_surface_iterated_stokes_gmg/screen-output
  tests/free_surface_relaxation/screen-output
  tests/free_surface_tangential_mesh_velocity/screen-output
  tests/free_surface_tangential_mesh_velocity_2/screen-output
  tests/free_surface_timestep_repeat/screen-output
  tests/function_mesh_deformation_tangential_mesh_velocity/screen-output
  tests/gmg_mesh_deform_adaptive/screen-output
  tests/gmg_mesh_deform_adaptive_bug/screen-output
  tests/gmg_mesh_deform_function/screen-output
  tests/gmg_mesh_deform_ghost_entries/screen-output
  tests/hill_diffusion/screen-output
  tests/hill_diffusion_3D/screen-output
  tests/infill_density_flexure/screen-output
  tests/particle_fast_evaluate_many_compositions/screen-output
  tests/particle_fast_evaluate_multiple_compositions/screen-output
  tests/periodic_box_freesurface/screen-output
  tests/resume_free_surface/log.txt1
  tests/resume_free_surface/log.txt2
  tests/slope_refinement/screen-output
  tests/topo_box/screen-output
  tests/topo_shell/screen-output
  tests/viz_mesh_deform_vector/screen-output
Labels: ready to test

#5452 candi local.cfg: add netcdf
  contrib/install/local.cfg
  doc/sphinx/user/install/local-installation/using-candi.md
Labels: ready to merge

#5450 fix cite using sphinx command.
  contrib/utilities/jsontomarkdown.py
  source/material_model/drucker_prager.cc
  source/material_model/melt_simple.cc
  source/mesh_deformation/free_surface.cc
  source/mesh_deformation/interface.cc
  source/simulator/newton.cc
  source/simulator/parameters.cc
Labels: ready to test

#5456 fix notes using sphinx.
  source/geometry_model/spherical_shell.cc
  source/material_model/simple.cc
  source/postprocess/heat_flux_statistics.cc
  source/postprocess/mass_flux_statistics.cc
  source/postprocess/point_values.cc
  source/postprocess/visualization.cc
  source/simulator/parameters.cc
Labels: ready to test

#5446 Re-order particle world member variables.
  include/aspect/particle/world.h
Labels: ready to test

#5461 update a comment
  source/structured_data.cc
Labels: ready to merge
