Repository geodynamics/aspect, pull requests merged in 2023-02, with the labels that each got.

#5044 Avoid unneccessary copy.
  source/simulator/stokes_matrix_free.cc
Labels: ready to test

#5045 switch website to html doc
  index.html
Labels: documentation

#5060 GMG: use deal.II compute_diagonal() part I
  include/aspect/stokes_matrix_free.h
  source/simulator/stokes_matrix_free.cc
  tests/annulus_transient/screen-output
  tests/free_surface_blob_gmg/statistics
  tests/free_surface_iterated_stokes_gmg/screen-output
  tests/free_surface_iterated_stokes_gmg/statistics
  tests/gmg_mesh_deform_adaptive_bug/screen-output
  tests/gmg_mesh_deform_adaptive_bug/statistics
  tests/nonlinear_channel_flow_tractions_Newton_Stokes_GMG/screen-output
  tests/nonlinear_channel_flow_tractions_Newton_Stokes_GMG/statistics
  tests/nonlinear_channel_flow_tractions_dc_picard_Stokes_GMG/screen-output
  tests/nonlinear_channel_flow_tractions_dc_picard_Stokes_GMG/statistics
  tests/nonlinear_channel_flow_velocities_Newton_Stokes_GMG/screen-output
  tests/tosi_benchmark_gmg_dc_picard_solver/screen-output
  tests/tosi_benchmark_gmg_dc_picard_solver/statistics
  tests/tosi_benchmark_gmg_newton_solver/screen-output
  tests/tosi_benchmark_gmg_newton_solver/statistics
Labels: ready to test

#5059 Add option for time constant ascii data boundary
  include/aspect/structured_data.h
  source/structured_data.cc
  tests/adiabatic_boundary/screen-output
  tests/adiabatic_plate_cooling/screen-output
  tests/ascii_boundary_member/screen-output
  tests/ascii_data_boundary_composition_3d_box/screen-output
  tests/ascii_data_boundary_temperature_3d_box/screen-output
  tests/ascii_data_boundary_velocity_2d_box/screen-output
  tests/ascii_data_boundary_velocity_2d_box_list/screen-output
  tests/ascii_data_boundary_velocity_2d_chunk/screen-output
  tests/ascii_data_boundary_velocity_2d_shell/screen-output
  tests/ascii_data_boundary_velocity_2d_shell_spherical/screen-output
  tests/ascii_data_boundary_velocity_3d_box/screen-output
  tests/ascii_data_boundary_velocity_3d_chunk/screen-output
  tests/ascii_data_boundary_velocity_3d_shell/screen-output
  tests/ascii_data_boundary_velocity_3d_shell_spherical/screen-output
  tests/ascii_data_boundary_velocity_3d_sphere/screen-output
  tests/ascii_data_boundary_velocity_residual_shell/screen-output
  tests/box_initial_mesh_deformation_ascii_data/screen-output
  tests/box_initial_topography_ascii_data/screen-output
  tests/box_initial_topography_ascii_data_moved_origin/screen-output
  tests/chunk_initial_topography_ascii_data/screen-output
  tests/chunk_initial_topography_ascii_data_3d/screen-output
  tests/chunk_initial_topography_ascii_data_3d_colatitude/screen-output
  tests/gmg_mesh_deform/screen-output
  tests/gmg_velocity_boundary_component/screen-output
Labels: ready to merge

#5047 Adds missed publications and new ones for January 2023
  doc/manual/citing_aspect.bib
Labels: ready to merge

#5051 Standardize 2D->2d and 3D->3d in comments.
  source/boundary_temperature/dynamic_core.cc
  source/boundary_velocity/gplates.cc
  source/geometry_model/chunk.cc
  source/geometry_model/spherical_shell.cc
  source/particle/generator/uniform_radial.cc
  source/particle/interpolator/quadratic_least_squares.cc
  source/particle/property/crystal_preferred_orientation.cc
  source/postprocess/boundary_velocity_residual_statistics.cc
  source/postprocess/geoid.cc
  source/postprocess/particles.cc
  source/postprocess/viscous_dissipation_statistics.cc
  source/simulator/nullspace.cc
  source/structured_data.cc
  source/utilities.cc
Labels: ready to merge, ready to test

#5050 Standardize 2D->2d and 3D->3d.
  source/boundary_composition/function.cc
  source/boundary_heat_flux/function.cc
  source/boundary_temperature/function.cc
  source/boundary_traction/function.cc
  source/boundary_traction/initial_lithostatic_pressure.cc
  source/boundary_velocity/ascii_data.cc
  source/boundary_velocity/function.cc
  source/boundary_velocity/gplates.cc
  source/geometry_model/ellipsoidal_chunk.cc
  source/geometry_model/initial_topography_model/function.cc
  source/geometry_model/spherical_shell.cc
  source/gravity_model/vertical.cc
  source/initial_composition/ascii_data_layered.cc
  source/initial_composition/function.cc
  source/initial_temperature/S40RTS_perturbation.cc
  source/initial_temperature/adiabatic.cc
  source/initial_temperature/ascii_data_layered.cc
  source/initial_temperature/function.cc
  source/initial_temperature/harmonic_perturbation.cc
  source/material_model/drucker_prager.cc
  source/material_model/rheology/drucker_prager.cc
  source/material_model/rheology/friction_models.cc
  source/material_model/rheology/strain_dependent.cc
  source/material_model/visco_plastic.cc
  source/material_model/viscoelastic.cc
  source/mesh_refinement/maximum_refinement_function.cc
  source/mesh_refinement/minimum_refinement_function.cc
  source/particle/generator/uniform_box.cc
  source/particle/generator/uniform_radial.cc
  source/particle/interpolator/bilinear_least_squares.cc
  source/particle/property/crystal_preferred_orientation.cc
  source/postprocess/boundary_velocity_residual_statistics.cc
  source/postprocess/domain_volume_statistics.cc
  source/postprocess/geoid.cc
  source/postprocess/gravity_point_values.cc
  source/postprocess/rotation_statistics.cc
  source/postprocess/visualization/spherical_velocity_components.cc
  source/structured_data.cc
  source/volume_of_fluid/handler.cc
Labels: ready to merge, ready to test

#5062 GMG: compute diagonal: cleanup
  include/aspect/stokes_matrix_free.h
  source/simulator/stokes_matrix_free.cc
Labels: ready to merge

#5066 GMG: shared MatrixFree objects
  source/simulator/stokes_matrix_free.cc
Labels: bug, ready to test

#5069 fix solver comment
  source/simulator/solver.cc
Labels: ready to merge

#5082 CI: switch to checkout v3 to avoid warning
  .github/workflows/linux.yml
Labels: ready to merge

#5081 CMake: put additional info into detailed.log
  CMakeLists.txt
  cmake/write_config.cmake
Labels: ready to merge

#5086 Fix documentation for VM
  doc/sphinx/user/install/virtual-machine/running-models.md
Labels: ready to merge

#5091 Remove deprecated interface functions for boundary conditions
  include/aspect/boundary_composition/interface.h
  include/aspect/boundary_temperature/interface.h
  include/aspect/boundary_traction/interface.h
  include/aspect/boundary_velocity/interface.h
  source/boundary_composition/interface.cc
  source/boundary_temperature/interface.cc
  source/boundary_traction/interface.cc
Labels: ready to merge
