Repository geodynamics/aspect, pull requests merged in 2023-01, with the labels that each got.

#5014 update parameters
  doc/manual/parameters.tex
  doc/parameter_view/parameters.xml
  doc/sphinx/parameters/Initial_20temperature_20model.md
  doc/sphinx/parameters/Material_20model.md
  doc/sphinx/parameters/Postprocess.md
Labels: ready to test

#5017 fix/cleanup bib files
  doc/manual/citing_aspect.bib
  doc/sphinx/references.bib
Labels: ready to test

#5020 Docs: Sphinx convert last geophysical setups cookbooks
  benchmarks/operator_splitting/doc/operator_splitting.md
  cookbooks/crustal_deformation/doc/crustal_deformation.md
  cookbooks/global_melt/doc/global_melt.md
  cookbooks/kinematically_driven_subduction_2d/doc/Case1_t0.png
  cookbooks/kinematically_driven_subduction_2d/doc/Case1_visc.png
  cookbooks/kinematically_driven_subduction_2d/doc/kinematically_driven_subduction_2d.md
  cookbooks/mid_ocean_ridge/doc/mid_ocean_ridge.md
  cookbooks/morency_doin_2004/doc/morency_doin_2004.md
  cookbooks/steinberger/doc/endstate.png
  cookbooks/steinberger/doc/steinberger.md
  doc/sphinx/references.bib
Labels: ready to test

#5021 New shear heating output
  cookbooks/anisotropic_viscosity/av_material.cc
  doc/modules/changes/20230112_dannberg
  include/aspect/heating_model/shear_heating.h
  include/aspect/material_model/grain_size.h
  source/heating_model/shear_heating.cc
  source/material_model/grain_size.cc
  tests/anisotropic_viscosity.cc
Labels: ready to test

#5027 Fix compiler warnings gcc11
  source/geometry_model/chunk.cc
  source/heating_model/shear_heating.cc
  source/particle/property/crystal_preferred_orientation.cc
Labels: ready to merge

#5030 Docs: last batch of cookbooks
  cookbooks/christensen_yuen_phase_function/doc/christensen_yuen_phase_function.md
  cookbooks/finite_strain/doc/finite_strain.md
  cookbooks/finite_strain/doc/finite_strain.tex
  cookbooks/geomio/doc/geomio.md
  cookbooks/muparser_temperature_example/doc/muparser_temperature_example.md
  cookbooks/plume_2D_chunk/doc/plume-angular-opening.png
  cookbooks/plume_2D_chunk/doc/plume-diff-creep.png
  cookbooks/plume_2D_chunk/doc/plume.md
  cookbooks/prescribed_velocity_ascii_data/doc/prescribed_velocity_ascii_data.md
  cookbooks/sinker-with-averaging/doc/q2q1.png
  cookbooks/sinker-with-averaging/doc/q2q1plus.png
  cookbooks/sinker-with-averaging/doc/sinker-with-averaging.md
  cookbooks/visualizing_phase_diagram/doc/visualizing_phase_diagram.md
  doc/sphinx/references.bib
Labels: ready to merge, ready to test

#5034 added n_phase functions to PhaseFunction
  doc/modules/changes/20230122_myhill
  include/aspect/material_model/utilities.h
  source/material_model/utilities.cc
  source/material_model/visco_plastic.cc
Labels: ready to test

#5029 Added field type functions
  doc/modules/changes/20230119_bobmyhill
  include/aspect/introspection.h
  include/aspect/material_model/utilities.h
  include/aspect/parameters.h
  source/material_model/utilities.cc
  source/simulator/introspection.cc
  source/simulator/parameters.cc
  tests/check_compositional_field_functions.cc
  tests/check_compositional_field_functions.prm
  tests/check_compositional_field_functions/screen-output
Labels: ready to test

#5037 fix changelog entry
  doc/modules/changes/20230119_bobmyhill
  doc/modules/changes/20230119_bobmyhill2
Labels: ready to merge

#5032 Increase use of parse_map in material models
  source/material_model/diffusion_dislocation.cc
  source/material_model/melt_boukare.cc
  source/material_model/rheology/constant_viscosity_prefactors.cc
  source/material_model/rheology/elasticity.cc
  source/material_model/rheology/frank_kamenetskii.cc
  source/material_model/rheology/friction_models.cc
  source/material_model/rheology/strain_dependent.cc
  source/material_model/rheology/visco_plastic.cc
  source/material_model/visco_plastic.cc
  source/material_model/viscoelastic.cc
Labels: ready to test

#5035 Clarified phase / phase transition arguments and docstrings
  include/aspect/material_model/equation_of_state/interface.h
  include/aspect/material_model/equation_of_state/multicomponent_incompressible.h
  include/aspect/material_model/rheology/composite_visco_plastic.h
  include/aspect/material_model/rheology/diffusion_creep.h
  include/aspect/material_model/rheology/dislocation_creep.h
  include/aspect/material_model/rheology/drucker_prager.h
  include/aspect/material_model/rheology/peierls_creep.h
  include/aspect/material_model/rheology/visco_plastic.h
  include/aspect/material_model/utilities.h
  source/material_model/equation_of_state/interface.cc
  source/material_model/rheology/composite_visco_plastic.cc
  source/material_model/rheology/diffusion_creep.cc
  source/material_model/rheology/dislocation_creep.cc
  source/material_model/rheology/drucker_prager.cc
  source/material_model/rheology/peierls_creep.cc
  source/material_model/rheology/visco_plastic.cc
  source/material_model/utilities.cc
  tests/composite_viscous_outputs.cc
Labels: ready to test

#5040 remove deprecation warnings
  source/simulator/assemblers/newton_stokes.cc
  source/simulator/parameters.cc
Labels: ready to test

#4843 Ascii data velocity boundary conditions for the chunk_with_lithosphere_boundary_indicators geometry model
  source/structured_data.cc
Labels: ready to test
