Repository geodynamics/aspect, pull requests merged in 2023-07, with the labels that each got.

#5189 Remove unused option
  source/postprocess/visualization.cc
Labels: ready to merge, ready to test

#5184 post 2.5.0 release
  VERSION
  doc/manual/manual.tex
  doc/modules/changes/20220511_haoyuan
  doc/modules/changes/20220628_glerum
  doc/modules/changes/20220707_bangerth
  doc/modules/changes/20220716_tjhei
  doc/modules/changes/20220722_naliboff
  doc/modules/changes/20220729_ekendall
  doc/modules/changes/20220913_jiaqi
  doc/modules/changes/20221010_gassmoeller
  doc/modules/changes/20221202_gassmoeller
  doc/modules/changes/20221206_dannberg
  doc/modules/changes/20221206_douglas
  doc/modules/changes/20230112_dannberg
  doc/modules/changes/20230117_dannberg
  doc/modules/changes/20230119_bobmyhill
  doc/modules/changes/20230119_bobmyhill2
  doc/modules/changes/20230122_myhill
  doc/modules/changes/20230203_dannberg
  doc/modules/changes/20230213_tjhei
  doc/modules/changes/20230221_gassmoeller
  doc/modules/changes/20230222_tjhei
  doc/modules/changes/20230303_saxena
  doc/modules/changes/20230303_tjhei
  doc/modules/changes/20230309_tjhei
  doc/modules/changes/20230313_gassmoeller
  doc/modules/changes/20230322_gassmoeller
  doc/modules/changes/20230414_gassmoeller
  doc/modules/changes/20230429_tjhei
  doc/modules/changes/20230523_mills
  doc/modules/changes/20230606_fraters
  doc/modules/current_changes_header
  doc/modules/to-2.5.0.h
Labels: ready to merge, ready to test

#5190 Removed a deprecated option
  source/postprocess/particles.cc
Labels: ready to merge, ready to test

#5191 Removed a deprecated option
  source/particle/generator/interface.cc
  source/simulator/assemblers/interface.cc
Labels: ready to merge, ready to test

#5194 removed a deprecated option
  source/particle/property/grain_size.cc
Labels: ready to merge, ready to test

#5197 make assert throw consistent between geometry models for whether a po…
  source/geometry_model/chunk.cc
  source/geometry_model/spherical_shell.cc
Labels: ready to merge, ready to test

#5192 Remove unused option core
  source/simulator/core.cc
Labels: ready to merge, ready to test

#5203 Document the purpose of a command.
  .github/workflows/docker.yml
Labels: ready to merge, ready to test

#5193 Removed a deprecated option
  include/aspect/compat.h
  source/simulator/stokes_matrix_free.cc
Labels: ready to merge, ready to test

#5196 Removed a deprecated option
  source/material_model/melt_global.cc
  source/particle/property/elastic_stress.cc
Labels: ready to merge, ready to test

#5188 Explain to the compiler that there is an external instantiation of some member variables.
  include/aspect/simulator_signals.h
  source/simulator/simulator_signals.cc
Labels: ready to test

#5201 improved parameter description for replace_placeholders function
  source/structured_data.cc
Labels: ready to merge, ready to test

#5187 Make the protected object public to use its functions elsewhere.
  include/aspect/initial_composition/slab_model.h
  source/initial_composition/slab_model.cc
Labels: ready to merge, ready to test

#5181 Release notes for 2.5.0
  contrib/release/release-tasklist.md
Labels: ready to merge, ready to test

#5206 Prefer std::array over C-style arrays.
  source/simulator/nullspace.cc
Labels: ready to test

#5207 Improve code readability in small ways in two places.
  source/geometry_model/ellipsoidal_chunk.cc
  source/simulator/nullspace.cc
Labels: ready to test

#5205 Replace use of C-style array by std::array.
  include/aspect/compat.h
Labels: ready to test

#5208 [Urgent] Fix 'main' breakage.
  source/particle/property/integrated_strain.cc
  source/particle/property/integrated_strain_invariant.cc
  source/particle/property/strain_rate.cc
  source/particle/property/viscoplastic_strain_invariants.cc
Labels: ready to test

#5199 Limit time step increase.
  doc/modules/changes/20230707_busaleh
  doc/sphinx/references.bib
  source/simulator/parameters.cc
  tests/always_refine/screen-output
  tests/always_refine/statistics
  tests/artificial_postprocess/screen-output
  tests/artificial_postprocess/statistics
  tests/depth_average_03/depth_average.gnuplot
  tests/depth_average_04/depth_average.vtk
  tests/diffusion/depth_average.gnuplot
  tests/diffusion/screen-output
  tests/diffusion/statistics
  tests/diffusion_velocity/screen-output
  tests/diffusion_velocity/statistics
  tests/free_surface_adaptive_blob/screen-output
  tests/free_surface_adaptive_blob/statistics
  tests/free_surface_blob/screen-output
  tests/free_surface_blob/statistics
  tests/free_surface_blob_gmg/screen-output
  tests/free_surface_blob_gmg/statistics
  tests/free_surface_blob_melt/screen-output
  tests/free_surface_blob_melt/statistics
  tests/melt_restart/log.txt2
  tests/melt_restart/statistics2
  tests/no_adiabatic_heating/screen-output
  tests/no_adiabatic_heating_02/screen-output
  tests/no_dirichlet_on_outflow_melt/screen-output
  tests/no_dirichlet_on_outflow_melt/statistics
  tests/point_value_02_mpi/point_values.txt
  tests/point_value_02_mpi/screen-output
  tests/remove_angular_momentum_3d/screen-output
  tests/remove_angular_momentum_3d/statistics
  tests/remove_net_rotation_3d/screen-output
  tests/remove_net_rotation_3d/statistics
  tests/resume_free_surface/log.txt1
  tests/resume_free_surface/solution/solution-00004.0000.gnuplot1
  tests/resume_free_surface/statistics1
  tests/viz_mesh_deform_vector/screen-output
  tests/viz_mesh_deform_vector/solution/solution-00010.0000.gnuplot
Labels: ready to merge, ready to test

#5195 Adding a few new publications
  doc/manual/citing_aspect.bib
Labels: ready to merge, ready to test

#5209 [2.5] take over extern template #5188
  include/aspect/simulator_signals.h
  source/simulator/simulator_signals.cc
Labels: ready to merge, ready to test

#5219 [2.5] particle ref bug
  source/particle/property/integrated_strain.cc
  source/particle/property/integrated_strain_invariant.cc
  source/particle/property/strain_rate.cc
  source/particle/property/viscoplastic_strain_invariants.cc
Labels: ready to merge

#5213 Do not bind temporaries to references.
  source/particle/interpolator/bilinear_least_squares.cc
  source/particle/interpolator/quadratic_least_squares.cc
Labels: ready to test

#5217 A little clean up and one addition found while reviewing
  doc/manual/citing_aspect.bib
Labels: ready to merge, ready to test

#5212 Add a bunch of index checks.
  source/material_model/utilities.cc
Labels: ready to test

#5218 Check that material model supports elasticity when it is enabled
  source/material_model/viscoelastic.cc
  source/simulator/core.cc
Labels: ready to merge, ready to test

#5198 remove the condition DEAL_II_VERSION_GTE
  source/particle/world.cc
Labels: ready to merge, ready to test

#5222 Fix documentation layout
  .readthedocs.yaml
  doc/sphinx/_templates/navbar_end.html
  doc/sphinx/conf.py
Labels: ready to merge

#5223 Change particle postprocessor writer from raw pointers to unique pointers
  include/aspect/postprocess/particles.h
  source/postprocess/particles.cc
Labels: ready to merge, ready to test

#5226 Gravity std::pow() update
  source/postprocess/gravity_point_values.cc
Labels: ready to merge, ready to test

#5224 Make sure cells are consistently ordered.
  source/geometry_model/spherical_shell.cc
Labels: ready to test

#5065 add a new plugin for random initial temperature perturbations
  doc/modules/changes/20230210_dannberg
  include/aspect/initial_temperature/random_gaussian_perturbation.h
  source/initial_temperature/random_gaussian_perturbation.cc
  tests/random_perturbation_box.prm
  tests/random_perturbation_box/screen-output
  tests/random_perturbation_box/statistics
  tests/random_perturbation_chunk.prm
  tests/random_perturbation_chunk/screen-output
  tests/random_perturbation_chunk/statistics
  tests/random_perturbation_merged_boxes.prm
  tests/random_perturbation_merged_boxes/screen-output
  tests/random_perturbation_merged_boxes/statistics
  tests/random_perturbation_sphere.prm
  tests/random_perturbation_sphere/screen-output
  tests/random_perturbation_sphere/statistics
  tests/random_perturbation_spherical_shell.prm
  tests/random_perturbation_spherical_shell/screen-output
  tests/random_perturbation_spherical_shell/statistics
Labels: ready to merge

#5221 correctly set up two merged boxes for nonzero Y origin
  doc/modules/changes/20230708_dannberg
  source/geometry_model/two_merged_boxes.cc
  tests/lithosphere_boundary_indicator_origin.prm
  tests/lithosphere_boundary_indicator_origin/screen-output
  tests/lithosphere_boundary_indicator_origin/solution/solution-00000.0000.gnuplot
  tests/lithosphere_boundary_indicator_origin/statistics
Labels: ready to merge, ready to test

#5214 add a new benchmark for volatiles release, migration and reabsoption
  benchmarks/check.mk
  benchmarks/solubility/doc/solubility.md
  benchmarks/solubility/doc/solubility.png
  benchmarks/solubility/plugin/CMakeLists.txt
  benchmarks/solubility/plugin/solubility.cc
  benchmarks/solubility/solubility.prm
  doc/modules/changes/20230708b_dannberg
  doc/sphinx/user/benchmarks/index.md
  tests/solubility.cc
  tests/solubility.prm
  tests/solubility/screen-output
  tests/solubility/statistics
Labels: ready to test

#5235 fix cookbook/benchmark warnings
  benchmarks/blankenbach/plugin/code.cc
  benchmarks/hollow_sphere/hollow_sphere.cc
  benchmarks/inclusion/compositional_fields/inclusion_compositional_fields.h
  benchmarks/operator_splitting/advection_reaction/advection_reaction.cc
  benchmarks/operator_splitting/exponential_decay/exponential_decay.cc
  benchmarks/rigid_shear/plugin/rigid_shear.cc
  benchmarks/shear_bands/shear_bands.cc
  benchmarks/solcx/solcx.h
  benchmarks/solitary_wave/solitary_wave.cc
  benchmarks/solubility/plugin/solubility.cc
  benchmarks/tangurnis/code/tangurnis.cc
  benchmarks/time_dependent_annulus/plugin/time_dependent_annulus.h
  benchmarks/tosi_et_al_2015_gcubed/tosi.cc
  benchmarks/yamauchi_takei_2016_anelasticity/anelasticity_temperature.h
  cookbooks/inner_core_convection/inner_core_convection.cc
Labels: ready to merge, ready to test

#5234 [2.5] wb warnings
  contrib/world_builder/include/delaunator-cpp/delaunator.hpp
  contrib/world_builder/source/world_builder/objects/bezier_curve.cc
  contrib/world_builder/source/world_builder/utilities.cc
  contrib/world_builder/source/world_builder/world.cc
Labels: ready to merge, ready to test

#5236 Avoid use of taking .c_str() just to convert back to std::string.
  source/main.cc
  source/postprocess/depth_average.cc
  source/postprocess/particles.cc
  source/postprocess/visualization.cc
  source/simulator/checkpoint_restart.cc
Labels: ready to merge, ready to test

#5237 std::[io]fstream can take file names as std::string.
  source/boundary_temperature/dynamic_core.cc
  source/postprocess/depth_average.cc
  source/postprocess/geoid.cc
  source/postprocess/particles.cc
  source/postprocess/point_values.cc
  source/postprocess/stokes_residual.cc
  source/postprocess/visualization.cc
  source/simulator/checkpoint_restart.cc
  source/simulator/core.cc
  source/utilities.cc
Labels: ready to merge, ready to test

#5241 remove virtual from functions with override within cpo particle property
  include/aspect/particle/property/crystal_preferred_orientation.h
Labels: ready to merge, ready to test

#5229 Apply strict cutoff to the Peierls stress
  doc/modules/changes/20230708_lhy11009
  include/aspect/material_model/rheology/peierls_creep.h
  source/material_model/rheology/peierls_creep.cc
  tests/visco_plastic_peierls_strict_cutoff_test.prm
  tests/visco_plastic_peierls_strict_cutoff_test/screen-output
  tests/visco_plastic_peierls_strict_cutoff_test/statistics
Labels: ready to test

#5246 added entropy as optional field type
  benchmarks/entropy_adiabat/entropy_adiabat.prm
  include/aspect/introspection.h
  source/simulator/parameters.cc
Labels: ready to test

#5251 fix for latest deal.II master: support cell_weight
  include/aspect/particle/world.h
  source/particle/world.cc
Labels: ready to merge, ready to test

#5252 [2.5] take over #5251: fix for latest deal.II master: support cell_weight
  include/aspect/particle/world.h
  source/particle/world.cc
Labels: ready to merge, ready to test

#5261 Use a better name for a variable that indicates that it's a *number*.
  include/aspect/structured_data.h
  source/structured_data.cc
Labels: ready to merge, ready to test

#5262 Use list initialization when returning ... lists :-)
  source/postprocess/dynamic_topography.cc
  source/postprocess/interface.cc
  source/postprocess/particle_count_statistics.cc
  source/postprocess/visualization.cc
  source/postprocess/visualization/boundary_strain_rate_residual.cc
  source/postprocess/visualization/boundary_velocity_residual.cc
  source/postprocess/visualization/dynamic_topography.cc
  source/postprocess/visualization/geoid.cc
  source/postprocess/visualization/particle_count.cc
  source/postprocess/visualization/surface_dynamic_topography.cc
Labels: ready to merge, ready to test

#5263 Make it less obscure when we return a pair of empty strings.
  source/postprocess/composition_statistics.cc
  source/postprocess/depth_average.cc
  source/postprocess/gravity_point_values.cc
  source/postprocess/point_values.cc
  source/postprocess/visualization.cc
Labels: ready to merge, ready to test

#5264 Remove todo to assert that viscosity has been requested and computed
  source/material_model/visco_plastic.cc
Labels: ready to merge, ready to test

#5265 Use range-based for loops.
  source/postprocess/boundary_strain_rate_residual_statistics.cc
  source/postprocess/visualization/boundary_strain_rate_residual.cc
Labels: ready to merge, ready to test

#5267 Use a range-based for loop.
  source/postprocess/composition_velocity_statistics.cc
Labels: ready to merge, ready to test

#5255 new inclusions cookbook
  cookbooks/inclusions/doc/inclusions.md
  cookbooks/inclusions/doc/results1.png
  cookbooks/inclusions/doc/results2.png
  cookbooks/inclusions/doc/setup.png
  cookbooks/inclusions/doc/viscosities.png
  cookbooks/inclusions/ellipse_pure_shear.prm
  cookbooks/inclusions/ellipse_pure_shear_nonlinear.prm
  cookbooks/inclusions/ellipse_ref.prm
  cookbooks/inclusions/ellipse_simple_shear.prm
  cookbooks/inclusions/rectangle_pure_shear.prm
  cookbooks/inclusions/rectangle_ref.prm
  cookbooks/inclusions/rectangle_simple_shear.prm
  doc/modules/changes/20230711_thieulot
  doc/sphinx/references.bib
  doc/sphinx/user/cookbooks/geophysical-setups.md
Labels: ready to merge, ready to test

#5253 Do not leave NaN values in output vectors.
  doc/modules/changes/20230710_bangerth
  source/postprocess/visualization/artificial_viscosity.cc
  tests/composition_active_nans.prm
  tests/composition_active_nans/screen-output
Labels: ready to test

#5272 [2.5] take over #5270: more cookbook/benchmark fixes
  benchmarks/solcx/compositional_fields/solcx_compositional_fields.h
  cookbooks/check.mk
Labels: ready to merge, ready to test

#5039 Field types for multicomponent incompressible and derived modules
  doc/modules/changes/20230708_bobmyhill
  include/aspect/introspection.h
  include/aspect/material_model/visco_plastic.h
  include/aspect/parameters.h
  source/material_model/equation_of_state/multicomponent_incompressible.cc
  source/material_model/multicomponent.cc
  source/material_model/visco_plastic.cc
  source/material_model/viscoelastic.cc
  source/simulator/introspection.cc
  source/simulator/parameters.cc
  source/utilities.cc
  tests/check_compositional_field_functions.cc
  tests/check_compositional_field_functions/screen-output
  tests/check_compositional_field_names/screen-output
  tests/viscoelastic_bending_beam.prm
Labels: ready to merge, ready to test

#5274 Follow-up: Do not leave NaN values in output vectors.
  source/postprocess/visualization/artificial_viscosity_composition.cc
  tests/composition_active_nans.prm
Labels: ready to merge, ready to test

#5266 Update test and plugin description and add test
  source/postprocess/visualization/surface_stress.cc
  tests/stress_vs_surface_stress.prm
  tests/stress_vs_surface_stress_point_values.cc
  tests/stress_vs_surface_stress_point_values.prm
  tests/stress_vs_surface_stress_point_values/screen-output
  tests/stress_vs_surface_stress_point_values/solution/solution-00000.0000.gnuplot
  tests/stress_vs_surface_stress_point_values/solution/solution_surface-00000.0000.gnuplot
  tests/stress_vs_surface_stress_point_values/statistics
Labels: ready to merge, ready to test

#5279 Mark up two variables as math.
  cookbooks/inclusions/doc/inclusions.md
Labels: ready to merge

#5280 Use a simpler way to return a map.
  source/geometry_model/box.cc
  source/geometry_model/chunk.cc
  source/geometry_model/ellipsoidal_chunk.cc
  source/geometry_model/interface.cc
  source/geometry_model/sphere.cc
  source/geometry_model/spherical_shell.cc
  source/geometry_model/two_merged_boxes.cc
  source/geometry_model/two_merged_chunks.cc
Labels: ready to merge, ready to test

#5281 Fix grammar.
  source/material_model/steinberger.cc
Labels: ready to merge, ready to test

#5286 Use more curly brace initialization in return statements.
  source/geometry_model/interface.cc
  source/particle/generator/interface.cc
  source/particle/property/interface.cc
  source/simulator/assemblers/interface.cc
Labels: ready to merge, ready to test

#5289 remove duplicated code
  source/simulator/parameters.cc
Labels: ready to merge, ready to test

#5294 update description in update_parameters.sh
  doc/update_parameters.sh
Labels: ready to test

#5293 Fix Britishism
  benchmarks/yamauchi_takei_2016_anelasticity/doc/yamauchi_takei_2016_anelasticity.md
Labels: ready to merge, ready to test

#5292 add comments, rename variables in vep-related rheologies
  benchmarks/viscoelastic_stress_build-up/viscoelastic_stress_build-up.prm
  include/aspect/material_model/rheology/drucker_prager.h
  include/aspect/material_model/rheology/elasticity.h
  source/material_model/rheology/drucker_prager.cc
  source/material_model/rheology/elasticity.cc
  source/material_model/rheology/visco_plastic.cc
  tests/drucker_prager_derivatives_2d/screen-output
  tests/drucker_prager_derivatives_3d/screen-output
  tests/drucker_prager_extension/screen-output
  tests/visco_plastic_vep_stress_build-up_yield/depth_average.txt
  tests/visco_plastic_yield_strain_weakening_full_strain_tensor/solution/solution-00000.0000.gnuplot
Labels: ready to merge, ready to test

#5287 Replace post-increment with pre-increment
  source/adiabatic_conditions/interface.cc
  source/boundary_temperature/dynamic_core.cc
  source/boundary_traction/initial_lithostatic_pressure.cc
  source/boundary_velocity/ascii_data.cc
  source/boundary_velocity/gplates.cc
  source/geometry_model/box.cc
  source/geometry_model/chunk.cc
  source/geometry_model/ellipsoidal_chunk.cc
  source/geometry_model/initial_topography_model/ascii_data.cc
  source/geometry_model/initial_topography_model/function.cc
  source/geometry_model/initial_topography_model/prm_polygon.cc
  source/geometry_model/spherical_shell.cc
  source/geometry_model/two_merged_boxes.cc
  source/geometry_model/two_merged_chunks.cc
  source/initial_composition/interface.cc
  source/initial_temperature/interface.cc
  source/material_model/depth_dependent.cc
  source/material_model/diffusion_dislocation.cc
  source/material_model/drucker_prager.cc
  source/material_model/equation_of_state/thermodynamic_table_lookup.cc
  source/material_model/grain_size.cc
  source/material_model/utilities.cc
  source/material_model/visco_plastic.cc
  source/particle/property/composition.cc
  source/particle/property/cpo_bingham_average.cc
  source/particle/property/crystal_preferred_orientation.cc
  source/particle/property/function.cc
  source/particle/property/initial_composition.cc
  source/particle/property/initial_position.cc
  source/particle/property/viscoplastic_strain_invariants.cc
  source/postprocess/crystal_preferred_orientation.cc
  source/postprocess/point_values.cc
  source/simulator/lateral_averaging.cc
  source/simulator/solver_schemes.cc
  source/structured_data.cc
  source/termination_criteria/steady_rms_velocity.cc
  source/utilities.cc
Labels: ready to merge, ready to test

#5290 Minor code updates in a couple of places.
  source/simulator/solver.cc
  source/simulator/solver_schemes.cc
Labels: ready to merge, ready to test

#5284 Add elastic utilities
  include/aspect/utilities.h
  source/utilities.cc
  unit_tests/utilities.cc
Labels: ready to merge, ready to test

#5299 "where not" -> "were not"
  contrib/world_builder/CHANGELOG.md
  doc/modules/to-2.4.0.h
  tests/drucker_prager_derivatives_2d.cc
  tests/drucker_prager_derivatives_2d/screen-output
  tests/drucker_prager_derivatives_3d.cc
  tests/drucker_prager_derivatives_3d/screen-output
  tests/simple_nonlinear.cc
  tests/simple_nonlinear/screen-output
  tests/spiegelman_material.cc
  tests/spiegelman_material/screen-output
  tests/visco_plastic_derivatives_2d.cc
  tests/visco_plastic_derivatives_3d.cc
  tests/visco_plastic_derivatives_3d/screen-output
Labels: ready to merge, ready to test

#5302 ise->ize
  benchmarks/yamauchi_takei_2016_anelasticity/anelasticity_temperature.cc
  contrib/perplex/perplex_lookup_composition.prm
  doc/modules/to-1.4.0.h
  doc/modules/to-2.4.0.h
  include/aspect/geometry_model/chunk.h
  include/aspect/geometry_model/two_merged_chunks.h
  source/material_model/rheology/peierls_creep.cc
  tests/grain_size_growth.prm
  tests/grain_size_growth_log.prm
  tests/grain_size_growth_particles.prm
  tests/grain_size_growth_scaled.prm
  tests/visco_plastic_phases_plasticity.prm
Labels: ready to merge, ready to test

#5297 Require fields of type entropy in entropy assembler and adiabatic con…
  benchmarks/entropy_adiabat/entropy_conduction.prm
  benchmarks/entropy_adiabat/entropy_half_space.prm
  benchmarks/entropy_adiabat/plugins/compute_entropy_profile.cc
  benchmarks/entropy_adiabat/plugins/entropy_advection.cc
Labels: ready to merge, ready to test

#5301 Correctly mark functions with 'override'.
  tests/compressibility.cc
  tests/compressibility_iterated_stokes.cc
Labels: ready to merge, ready to test

#5303 correct_primes_in_manual
  source/material_model/nondimensional.cc
  source/postprocess/viscous_dissipation_statistics.cc
  source/postprocess/visualization/maximum_horizontal_compressive_stress.cc
Labels: ready to merge, ready to test

#5254 Rheology and conductivity modification for the entropy plugin
  benchmarks/entropy_adiabat/entropy_adiabat.prm
  benchmarks/entropy_adiabat/entropy_combined.prm
  benchmarks/entropy_adiabat/entropy_conduction.prm
  benchmarks/entropy_adiabat/entropy_half_space.prm
  benchmarks/entropy_adiabat/plugins/entropy_model.cc
  benchmarks/entropy_adiabat/plugins/entropy_model.h
  data/material-model/entropy-table/opxtable/constant_lateral_vis_prefactor.txt
  data/material-model/entropy-table/opxtable/constant_lateral_vis_prefactor_50000.txt
  doc/modules/changes/20230712_ranpengli
  tests/entropy_plasticity.cc
  tests/entropy_plasticity.prm
  tests/entropy_plasticity/screen-output
  tests/entropy_plasticity/statistics
Labels: ready to merge, ready to test

#5273 doc: explain cookbooks/check.mk
  doc/sphinx/user/extending/write-a-cookbook/manual-section.md
Labels: ready to merge, ready to test

#5305 Specify ranges to angles in ascii date init topo
  source/geometry_model/initial_topography_model/ascii_data.cc
Labels: ready to merge, ready to test

#5308 Remove debug output from CMakeLists.txt.
  CMakeLists.txt
Labels: ready to test

#5306 Add astyle installation instruction
  CONTRIBUTING.md
Labels: ready to merge, ready to test

#5309 Fix macos constexpr tensor utilities
  source/utilities.cc
Labels: bug, ready to merge, ready to test

#5220 Allowing multiple traction models for a boundary
  doc/modules/changes/20230713_chameerasilva
  include/aspect/boundary_traction/interface.h
  include/aspect/simulator.h
  include/aspect/simulator_access.h
  source/boundary_traction/ascii_data.cc
  source/boundary_traction/initial_lithostatic_pressure.cc
  source/boundary_traction/interface.cc
  source/simulator/assemblers/stokes.cc
  source/simulator/assembly.cc
  source/simulator/core.cc
  source/simulator/helper_functions.cc
  source/simulator/melt.cc
  source/simulator/newton.cc
  source/simulator/parameters.cc
  source/simulator/simulator_access.cc
  tests/traction_multiple_model.prm
  tests/traction_multiple_model/screen-output
  tests/traction_multiple_model/statistics
Labels: ready to merge, ready to test

#5288 Rename a function to better indicate what it is doing.
  include/aspect/utilities.h
  source/simulator/solver.cc
  source/simulator/stokes_matrix_free.cc
  source/utilities.cc
  tests/stokes_solver_fail_A/screen-output
  tests/stokes_solver_fail_S/screen-output
Labels: ready to merge, ready to test

#5307 Drop most of doc/CMakeLists.txt.
  doc/CMakeLists.txt
Labels: ready to merge, ready to test

#5317 fix name Newton Stokes function
  include/aspect/simulator.h
  source/simulator/core.cc
  source/simulator/solver_schemes.cc
Labels: ready to merge, ready to test

#5315 Use brace initialization of a pair.
  source/simulator/solver_schemes.cc
Labels: ready to merge, ready to test

#5089 Update initial lithostatic pressure plugin to account for initial topography and mesh deformation.
  doc/modules/changes/20230713_glerum
  include/aspect/boundary_traction/initial_lithostatic_pressure.h
  source/boundary_traction/initial_lithostatic_pressure.cc
  tests/airy_isostasy_initial_topo.prm
  tests/airy_isostasy_initial_topo/screen-output
  tests/airy_isostasy_initial_topo/statistics
Labels: ready to merge, ready to test

#5318 Add Levi-Civita tensor to Aspect
  include/aspect/utilities.h
  unit_tests/utilities.cc
Labels: ready to merge, ready to test

#5291 Clarify function argument names.
  include/aspect/simulator.h
  source/simulator/solver_schemes.cc
Labels: ready to test

#5259 Vankeken 2008 subduction benchmark
  cookbooks/check.mk
  cookbooks/vankeken_subduction/doc/pressure_mesh.png
  cookbooks/vankeken_subduction/doc/temperature_field.png
  cookbooks/vankeken_subduction/doc/vankeken_subduction.md
  cookbooks/vankeken_subduction/doc/velocity_field.png
  cookbooks/vankeken_subduction/plugin/CMakeLists.txt
  cookbooks/vankeken_subduction/plugin/van_Keken_mesh.cc
  cookbooks/vankeken_subduction/vankeken_corner_flow.prm
  doc/modules/changes/20230712_danieldouglas92
  doc/sphinx/references.bib
  tests/vankeken_subduction.cc
  tests/vankeken_subduction.prm
  tests/vankeken_subduction/screen-output
  tests/vankeken_subduction/statistics
Labels: ready to merge, ready to test

#5327 Break an overly long line.
  source/simulator/solver_schemes.cc
Labels: ready to merge, ready to test

#5321 fix minor things in manual
  source/material_model/ascii_reference_profile.cc
  source/material_model/depth_dependent.cc
  source/material_model/diffusion_dislocation.cc
  source/material_model/drucker_prager.cc
  source/material_model/latent_heat.cc
  source/material_model/replace_lithosphere_viscosity.cc
  source/material_model/simple.cc
  source/material_model/simple_compressible.cc
  source/material_model/simpler.cc
  source/material_model/steinberger.cc
  source/material_model/visco_plastic.cc
Labels: ready to merge, ready to test

#5314 Rename another function to make its intent clearer.
  include/aspect/simulator.h
  source/simulator/solver_schemes.cc
Labels: ready to test

#5271 contribute cookbook: simple subduction initiation
  cookbooks/subduction_initiation/doc/results1.png
  cookbooks/subduction_initiation/doc/results2.png
  cookbooks/subduction_initiation/doc/results3.png
  cookbooks/subduction_initiation/doc/setup.png
  cookbooks/subduction_initiation/doc/subduction_initiation.md
  cookbooks/subduction_initiation/subduction_initiation_basis.prm
  cookbooks/subduction_initiation/subduction_initiation_compositional_fields.prm
  cookbooks/subduction_initiation/subduction_initiation_particle_in_cell.prm
  doc/modules/changes/20230712_thieulot
  doc/sphinx/references.bib
  doc/sphinx/user/cookbooks/geophysical-setups.md
Labels: ready to merge, ready to test

#5239 Be safer and more correct when using strain rate
  source/material_model/rheology/visco_plastic.cc
  source/material_model/visco_plastic.cc
  source/simulator/assembly.cc
  source/simulator/melt.cc
  tests/continental_extension/screen-output
  tests/visco_plastic_derivatives_2d.prm
  tests/visco_plastic_derivatives_2d/screen-output
  tests/visco_plastic_derivatives_3d.prm
  tests/visco_plastic_derivatives_3d/screen-output
  tests/visco_plastic_yield_strain_weakening_defect_corr_stokes/screen-output
Labels: ready to test

#4336 Update strain rheology
  doc/modules/changes/20230714_naliboff
  source/material_model/rheology/strain_dependent.cc
  tests/visco_plastic_total_strain_healing_temperature_dependent.prm
  tests/visco_plastic_total_strain_healing_temperature_dependent/screen-output
  tests/visco_plastic_total_strain_healing_temperature_dependent/solution/solution-00000.0000.gnuplot
  tests/visco_plastic_total_strain_healing_temperature_dependent/solution/solution-00001.0000.gnuplot
  tests/visco_plastic_total_strain_healing_temperature_dependent/solution/solution-00002.0000.gnuplot
  tests/visco_plastic_total_strain_healing_temperature_dependent/solution/solution-00003.0000.gnuplot
  tests/visco_plastic_total_strain_healing_temperature_dependent/solution/solution-00004.0000.gnuplot
  tests/visco_plastic_total_strain_healing_temperature_dependent/solution/solution-00005.0000.gnuplot
  tests/visco_plastic_total_strain_healing_temperature_dependent/statistics
  tests/visco_plastic_yield_plastic_viscous_strain_healing/screen-output
  tests/visco_plastic_yield_plastic_viscous_strain_healing/statistics
  tests/visco_plastic_yield_total_strain_healing/screen-output
  tests/visco_plastic_yield_total_strain_healing/statistics
  tests/viscoelastoplastic_yield_plastic_viscous_strain_weakening/screen-output
  tests/viscoelastoplastic_yield_plastic_viscous_strain_weakening/solution/solution-00001.0000.gnuplot
  tests/viscoelastoplastic_yield_plastic_viscous_strain_weakening/statistics
Labels: ready to test

#5333 Make error messages more useful
  source/material_model/utilities.cc
Labels: ready to merge, ready to test

#5276 add lower crustal flow cookbook
  cookbooks/lower_crustal_flow/doc/clark1.png
  cookbooks/lower_crustal_flow/doc/clark2.png
  cookbooks/lower_crustal_flow/doc/lower_crustal_flow.md
  cookbooks/lower_crustal_flow/doc/section-press.png
  cookbooks/lower_crustal_flow/doc/section-sr.png
  cookbooks/lower_crustal_flow/doc/section-vel.png
  cookbooks/lower_crustal_flow/doc/velocity.png
  cookbooks/lower_crustal_flow/doc/viscosity.png
  cookbooks/lower_crustal_flow/lower_crustal_flow_obstacle.prm
  doc/modules/changes/20230713_thieulot
  doc/sphinx/references.bib
  doc/sphinx/user/cookbooks/geophysical-setups.md
Labels: ready to test

#5328 Address a clang compiler problem.
  include/aspect/utilities.h
  source/particle/property/crystal_preferred_orientation.cc
  source/utilities.cc
  unit_tests/utilities.cc
Labels: ready to merge, ready to test

#3773 Sea level postprocessor: finds and writes elevation of any desired location.
  data/postprocess/sea-level/shell_3d_ice_top.0.txt
  data/postprocess/sea-level/shell_3d_topo_top.0.txt
  doc/modules/changes/20230714_weerdesteijn
  doc/sphinx/references.bib
  include/aspect/postprocess/sea_level.h
  source/postprocess/sea_level.cc
  tests/sea_level_postprocessor.prm
  tests/sea_level_postprocessor/geoid_anomaly.00000
  tests/sea_level_postprocessor/nonuniform_sea_level_change.00000
  tests/sea_level_postprocessor/screen-output
  tests/sea_level_postprocessor/statistics
  tests/sea_level_postprocessor/topography.00000
Labels: ready to test
