Repository geodynamics/aspect, pull requests merged in 2023-11, with the labels that each got.

#4396 Fastscape coupling
  CMakeLists.txt
  contrib/fastscape/fastscape_rewrite_VTK_with_time.py
  cookbooks/check.mk
  cookbooks/fastscape_eroding_box/doc/README.md
  cookbooks/fastscape_eroding_box/fastscape_eroding_box.prm
  doc/modules/changes/20230301_neuharth
  doc/sphinx/user/cookbooks/simple-setups.md
  include/aspect/config.h.in
  include/aspect/geometry_model/box.h
  include/aspect/mesh_deformation/fastscape.h
  include/aspect/parameters.h
  include/aspect/simulator_access.h
  source/geometry_model/box.cc
  source/material_model/rheology/visco_plastic.cc
  source/mesh_deformation/fastscape.cc
  source/simulator/parameters.cc
  source/simulator/simulator_access.cc
Labels: ready to test

#5467 Do not store manifolds in geometry models.
  include/aspect/geometry_model/sphere.h
  include/aspect/geometry_model/spherical_shell.h
  source/geometry_model/sphere.cc
  source/geometry_model/spherical_shell.cc
Labels: ready to merge, ready to test

#5468 Remove a function that is never used.
  include/aspect/geometry_model/chunk.h
  include/aspect/geometry_model/two_merged_chunks.h
  source/geometry_model/chunk.cc
  source/geometry_model/two_merged_chunks.cc
  tests/natural_coordinates_conversion.cc
Labels: ready to merge, ready to test

#5471 Do not mark functions as 'virtual' if not necessary.
  include/aspect/geometry_model/two_merged_boxes.h
  include/aspect/geometry_model/two_merged_chunks.h
Labels: ready to test

#5469 Use the new interface of AffineConstraints.
  source/mesh_deformation/free_surface.cc
  source/mesh_deformation/interface.cc
  source/simulator/melt.cc
  source/simulator/nullspace.cc
  source/simulator/stokes_matrix_free.cc
Labels: ready to test

#5473 Use overloads instead of template specializations.
  source/geometry_model/spherical_shell.cc
Labels: ready to test

#5470 Do not keep around a manifold object in the Chunk class.
  include/aspect/geometry_model/chunk.h
  include/aspect/geometry_model/two_merged_chunks.h
  source/geometry_model/chunk.cc
  source/geometry_model/two_merged_chunks.cc
Labels: ready to test

#5477 Use the usual form of lambda functions.
  source/simulator/stokes_matrix_free.cc
Labels: ready to test

#5476 Make EllipsoidalChunkGeometry look more like Chunk.
  include/aspect/geometry_model/ellipsoidal_chunk.h
  source/geometry_model/ellipsoidal_chunk.cc
  tests/ellipsoidal_chunk_geometry.cc
Labels: ready to test

#5488 code cleanup.
  source/mesh_deformation/interface.cc
Labels: ready to merge, ready to test

#5483 Fix section reference.
  contrib/utilities/jsontomarkdown.py
  source/geometry_model/chunk.cc
  source/geometry_model/sphere.cc
  source/geometry_model/spherical_shell.cc
  source/geometry_model/two_merged_chunks.cc
  source/postprocess/visualization.cc
  source/simulator/parameters.cc
Labels: ready to test

#5491 Update tester images with netcdf
  .github/workflows/linux.yml
  contrib/ci/Dockerfile
Labels: ready to merge

#5474 Create a manifold for the spherical shell that can accommodate an initial topography.
  include/aspect/compat.h
  source/compat.cc
  source/geometry_model/spherical_shell.cc
Labels: ready to test

#5493 Make a variable 'unsigned'.
  include/aspect/geometry_model/spherical_shell.h
Labels: ready to test

#5492 The handwritten import() method is removed as it is now a part of Tri…
  source/simulator/stokes_matrix_free.cc
Labels: ready to test

#5497 Towards a SphericalShellWithTopography.
  include/aspect/geometry_model/spherical_shell.h
  source/geometry_model/spherical_shell.cc
Labels: ready to test

#5503 Make sure stuff in compat.h/cc is guarded by a deal.II version.
  include/aspect/compat.h
  source/compat.cc
Labels: ready to test

#5501 Avoid the use of raw pointers. Use std::unique_ptr instead.
  doc/modules/changes/20231128_bangerth
  include/aspect/postprocess/visualization.h
  include/aspect/postprocess/visualization/ISA_rotation_timescale.h
  include/aspect/postprocess/visualization/artificial_viscosity.h
  include/aspect/postprocess/visualization/artificial_viscosity_composition.h
  include/aspect/postprocess/visualization/boundary_indicator.h
  include/aspect/postprocess/visualization/error_indicator.h
  include/aspect/postprocess/visualization/grain_lag_angle.h
  include/aspect/postprocess/visualization/particle_count.h
  include/aspect/postprocess/visualization/seismic_anomalies.h
  source/postprocess/visualization.cc
  source/postprocess/visualization/ISA_rotation_timescale.cc
  source/postprocess/visualization/artificial_viscosity.cc
  source/postprocess/visualization/artificial_viscosity_composition.cc
  source/postprocess/visualization/boundary_indicator.cc
  source/postprocess/visualization/error_indicator.cc
  source/postprocess/visualization/grain_lag_angle.cc
  source/postprocess/visualization/particle_count.cc
  source/postprocess/visualization/seismic_anomalies.cc
Labels: ready to test

#4375 fixed stress visualization for elastic materials
  doc/modules/changes/20231110_bobmyhill
  source/postprocess/visualization/shear_stress.cc
  source/postprocess/visualization/stress.cc
  tests/viscoelastic_stress_build-up.prm
  tests/viscoelastic_stress_build-up/solution/solution-00000.0000.gnuplot
  tests/viscoelastic_stress_build-up/solution/solution-00001.0000.gnuplot
  tests/visualization_shear_stress_viscoelastic.prm
  tests/visualization_shear_stress_viscoelastic/solution/solution-00000.0000.gnuplot
  tests/visualization_shear_stress_viscoelastic/solution/solution-00001.0000.gnuplot
  tests/visualization_stress_viscoelastic.prm
  tests/visualization_stress_viscoelastic/solution/solution-00000.0000.gnuplot
  tests/visualization_stress_viscoelastic/solution/solution-00001.0000.gnuplot
Labels: ready to merge, ready to test
