Repository geodynamics/aspect, pull requests merged in 2024-05, with the labels that each got.

#5638 Fix alignment problem for VectorizedArray
  source/simulator/stokes_matrix_free.cc
Labels: ready to merge

#5639 Unify evaluation of number of material points
  source/boundary_heat_flux/function.cc
  source/heating_model/adiabatic_heating.cc
  source/heating_model/adiabatic_heating_of_melt.cc
  source/heating_model/interface.cc
  source/heating_model/latent_heat.cc
  source/heating_model/latent_heat_melt.cc
  source/heating_model/shear_heating.cc
  source/heating_model/shear_heating_with_melt.cc
  source/material_model/melt_boukare.cc
  source/material_model/reactive_fluid_transport.cc
  source/simulator/assemblers/newton_stokes.cc
  source/simulator/assemblers/stokes.cc
  source/simulator/lateral_averaging.cc
  source/simulator/melt.cc
  source/simulator/newton.cc
Labels: ready to merge

#5653 Remove an outdated version check.
  source/simulator/core.cc
Labels: ready to merge

#5658 Add directives for newer dealii in affineconstraints.
  source/mesh_deformation/free_surface.cc
  source/simulator/stokes_matrix_free.cc
Labels: ready to merge, ready to test

#5657 Ensure we only run the WGS84 code if in 3d.
  source/utilities.cc
Labels: ready to test

#5661 Minor cleanup.
  include/aspect/material_model/interface.h
Labels: ready to merge, ready to test

#5660 fix WGS84 warning
  source/utilities.cc
Labels: ready to merge, ready to test

#5640 Simplify creating and unrolling symmetric tensors
  include/aspect/utilities.h
  source/material_model/rheology/elasticity.cc
  source/particle/property/cpo_elastic_tensor.cc
Labels: ready to merge, ready to test

#5665 Make a 'struct' into a 'class'.
  include/aspect/material_model/interface.h
Labels: ready to merge, ready to test

#5667 Use an anonymous namespace instead of a named namespace.
  source/postprocess/visualization.cc
Labels: ready to merge, ready to test

#5669 Backporting removing -lc++ and -lstdc++ from world builder cmake.
  contrib/world_builder/CMakeLists.txt
Labels: ready to merge, ready to test

#5674 remove unnecessary includes
  source/simulator/core.cc
  source/utilities.cc
Labels: ready to merge

#5652 Add cutoff pressures to tian parameterization
  include/aspect/material_model/reactive_fluid_transport.h
  source/material_model/reactive_fluid_transport.cc
  tests/tian_MORB/screen-output
  tests/tian_gabbro/screen-output
  tests/tian_peridotite/screen-output
  tests/tian_sediment/screen-output
Labels: ready to test

#5664 refactored diffusion-dislocation
  doc/modules/changes/20240529_myhill
  include/aspect/material_model/diffusion_dislocation.h
  include/aspect/material_model/rheology/diffusion_dislocation.h
  source/material_model/diffusion_dislocation.cc
  source/material_model/rheology/diffusion_dislocation.cc
Labels: ready to test

#5676 backport gwb simplify cmake c++ version enforcement.
  contrib/world_builder/CMakeLists.txt
Labels: ready to merge, ready to test

#5666 Make a struct a class, complete with 'public:' specifier.
  include/aspect/material_model/interface.h
  source/heating_model/adiabatic_heating_of_melt.cc
  source/heating_model/shear_heating_with_melt.cc
Labels: ready to merge, ready to test

#4788 allken_et_al_2012_cookbook
  cookbooks/allken_et_al_2012_rift_interaction/allken.prm
  cookbooks/allken_et_al_2012_rift_interaction/doc/allken.md
  cookbooks/allken_et_al_2012_rift_interaction/doc/allken_setup.png
  cookbooks/allken_et_al_2012_rift_interaction/doc/sr.png
  cookbooks/allken_et_al_2012_rift_interaction/doc/visc.png
  cookbooks/allken_et_al_2012_rift_interaction/doc/vx.png
  cookbooks/allken_et_al_2012_rift_interaction/doc/vz.png
  doc/sphinx/user/cookbooks/geophysical-setups.md
Labels: ready to merge, ready to test

#5681 Make reset of grain size at phase transitions only depend on velocity
  doc/modules/changes/20240530_dannberg
  include/aspect/material_model/grain_size.h
  source/material_model/grain_size.cc
  tests/grain_size_crossed_transition.prm
  tests/grain_size_crossed_transition/screen-output
  tests/grain_size_crossed_transition/statistics
  tests/grain_size_latent_heat.cc
Labels: ready to merge, ready to test

#5671 Better (and correctly) document the SPD correction factor.
  include/aspect/utilities.h
  source/utilities.cc
Labels: ready to test

#5684 Make the four stages of the RK4 integrator look more similar.
  source/particle/integrator/rk_4.cc
Labels: ready to merge, ready to test

#5686 Better document the SPD safety factor.
  source/simulator/newton.cc
Labels: ready to test

#5691 Fix typo
  source/utilities.cc
Labels: ready to merge, ready to test

#5689 Try a better choice for the SPD factor in Newton's method.
  source/utilities.cc
Labels: ready to merge, ready to test

#5675 Create Melt Reaction Modules
  include/aspect/material_model/melt_simple.h
  include/aspect/material_model/reaction_model/katz2003_mantle_melting.h
  source/material_model/melt_simple.cc
  source/material_model/reaction_model/katz2003_mantle_melting.cc
Labels: ready to merge, ready to test
