Repository geodynamics/aspect, pull requests merged in 2024-08, with the labels that each got.

#5998 added phases test for CompositeViscoPlastic
  tests/composite_viscous_outputs_phases.cc
  tests/composite_viscous_outputs_phases.prm
  tests/composite_viscous_outputs_phases/screen-output
Labels: ready to test

#6005 fix damper stress calculation
  source/material_model/rheology/composite_visco_plastic.cc
  tests/composite_viscous_outputs_limited.cc
  tests/composite_viscous_outputs_limited.prm
  tests/composite_viscous_outputs_limited/screen-output
Labels: ready to test

#6010 Fix documentation tester
  doc/sphinx/user/run-aspect/debug-mode.md
Labels: ready to merge, ready to test

#6007 turn on c++ standard library debug checks
  CMakeLists.txt
  source/particle/property/interface.cc
Labels: ready to test

#6003 Switch continental extension to AMG solver.
  cookbooks/continental_extension/continental_extension.prm
  tests/continental_extension/screen-output
Labels: ready to merge

#6008 move viscosity averaging function
  include/aspect/material_model/interface.h
  source/material_model/interface.cc
  source/material_model/rheology/elasticity.cc
Labels: ready to merge, ready to test

#6016 ParameterHandler fix for deal.II master
  source/simulator/core.cc
Labels: ready to merge
