Repository geodynamics/aspect, pull requests merged in 2024-11, with the labels that each got.

#6130 doc: fix a few problems
  benchmarks/solitary_wave/doc/solitary_wave.md
  cookbooks/burnman/doc/burnman.md
Labels: ready to test

#6121 Also document boundary composition plugins.
  doc/sphinx/user/extending/plugin-types/temp-bc.md
Labels: documentation, ready to merge

#6133 Further newton code cleanup
  source/simulator/solver_schemes.cc
Labels: ready to merge

#6137 Create an original.wb when running ASPECT with the World Builder
  doc/modules/changes/20241106_danieldouglas92
  source/main.cc
  tests/original_wb.prm
  tests/original_wb/original.wb
  tests/original_wb/statistics
Labels: ready to test

#6142 remove std::ofstream default arg
  source/postprocess/depth_average.cc
Labels: ready to test

#6129 Fix the units for the darcy velocity postprocessor
  source/postprocess/visualization/darcy_velocity.cc
  tests/darcy_convection_step.prm
  tests/darcy_convection_step/log.txt
  tests/darcy_convection_step/screen-output
  tests/darcy_convection_step/solution/solution-00000.0000.gnuplot
  tests/darcy_convection_step/statistics
Labels: ready to merge, ready to test

#6143 Add changelog entry
  doc/modules/changes/20241108_gassmoeller
Labels: ready to merge

#6123 Add Burstedde Weighted BFBT test
  tests/burstedde_bfbt.cc
  tests/burstedde_bfbt.prm
  tests/burstedde_bfbt/screen-output
Labels: ready to test

#6144 Use the adiabatic temperature when calculating water fugacity during initialization
  source/material_model/rheology/compositional_viscosity_prefactors.cc
  tests/hk04_olivine_composite_hydration_prefactor.prm
  tests/hk04_olivine_composite_hydration_prefactor_with_melt.prm
  tests/hk04_olivine_composite_hydration_prefactor_with_melt/screen-output
  tests/hk04_olivine_composite_hydration_prefactor_with_melt/solution/solution-00000.0000.gnuplot
  tests/hk04_olivine_composite_hydration_prefactor_with_melt/statistics
Labels: ready to merge, ready to test

#6147 Remove unused variable
  source/particle/property/cpo_bingham_average.cc
Labels: ready to test

#6146 Fix extra text block colons.
  source/postprocess/visualization.cc
Labels: ready to merge, ready to test

#6148 make argument const and document
  include/aspect/particle/manager.h
  source/particle/manager.cc
Labels: ready to merge, ready to test

#6150 remove outdated deal.II comment
  include/aspect/postprocess/visualization.h
  source/postprocess/visualization.cc
Labels: documentation, ready to test

#6151 Document the heat flux plugin system.
  doc/sphinx/user/extending/plugin-types/boundary-heat-flux.md
  doc/sphinx/user/extending/plugin-types/index.md
  include/aspect/boundary_heat_flux/interface.h
  source/simulator/assemblers/advection.cc
Labels: documentation, ready to test

#6157 Adds new publictons for October and November
  doc/manual/citing_aspect.bib
Labels: ready to merge, ready to test
