Repository geodynamics/aspect, pull requests merged in 2024-01, with the labels that each got.

#5535 Don't break hyphenated words in the documentation.
  include/aspect/adiabatic_conditions/interface.h
  include/aspect/boundary_composition/initial_composition.h
  include/aspect/boundary_composition/spherical_constant.h
  include/aspect/boundary_temperature/spherical_constant.h
  include/aspect/initial_temperature/harmonic_perturbation.h
  include/aspect/mesh_deformation/interface.h
  include/aspect/particle/integrator/rk_4.h
  include/aspect/plugins.h
  include/aspect/postprocess/visualization.h
Labels: ready to test

#5506 Return user-set maximum topography when the initial topography model Function is asked for the max topography
  source/geometry_model/initial_topography_model/function.cc
  tests/airy_isostasy_initial_topo/screen-output
  tests/airy_isostasy_initial_topo/statistics
  tests/airy_isostasy_initial_topo_lithostatic_pressure/screen-output
  tests/airy_isostasy_initial_topo_lithostatic_pressure/statistics
  tests/box_initial_topography_function/screen-output
  tests/box_initial_topography_function/solution/solution-00000.0000.gnuplot
  tests/box_initial_topography_function/statistics
  tests/resume_free_surface.prm
  tests/resume_free_surface/log.txt2
  tests/world_builder_simple_2d_cartesian_sticky_air.prm
  tests/world_builder_simple_2d_cartesian_sticky_air/solution/solution-00000.0000.gnuplot
Labels: ready to merge

#5537 Improve the error message when dlopen fails.
  source/main.cc
Labels: ready to test

#5549 Fix a bibtex entry.
  doc/manual/citing_aspect.bib
Labels: ready to merge, ready to test

#5548 Next step towards equipping the sphere with topography.
  include/aspect/geometry_model/spherical_shell.h
  source/geometry_model/spherical_shell.cc
Labels: ready to merge, ready to test

#5539 Replace the matrix free class with another.
  include/aspect/mesh_deformation/interface.h
  include/aspect/stokes_matrix_free.h
  source/mesh_deformation/interface.cc
  source/simulator/stokes_matrix_free.cc
Labels: ready to test

#5547 fix: create additional material model outputs for base models
  include/aspect/material_model/depth_dependent.h
  include/aspect/material_model/prescribed_viscosity.h
  source/material_model/depth_dependent.cc
  source/material_model/prescribed_viscosity.cc
  tests/depth_dependent_additional_outputs.prm
  tests/depth_dependent_additional_outputs/screen-output
  tests/depth_dependent_additional_outputs/solution/solution-00000.0000.gnuplot
  tests/depth_dependent_additional_outputs/statistics
  tests/prescribed_viscosity_additional_outputs.prm
  tests/prescribed_viscosity_additional_outputs/screen-output
  tests/prescribed_viscosity_additional_outputs/statistics
Labels: ready to merge

#5554 simplify ghosting of MGTransfer
  source/mesh_deformation/interface.cc
Labels: ready to merge, ready to test

#5553 introduce using for MGTransferMF
  include/aspect/compat.h
  include/aspect/mesh_deformation/interface.h
  include/aspect/stokes_matrix_free.h
  source/mesh_deformation/interface.cc
  source/simulator/stokes_matrix_free.cc
Labels: ready to merge, ready to test

#5542 Use chemical compositions in rheology models for parameter parsing
  doc/modules/changes/20240122_glerum
  source/material_model/diffusion_dislocation.cc
  source/material_model/rheology/constant_viscosity_prefactors.cc
  source/material_model/rheology/diffusion_creep.cc
  source/material_model/rheology/dislocation_creep.cc
  source/material_model/rheology/drucker_prager.cc
  source/material_model/rheology/elasticity.cc
  source/material_model/rheology/frank_kamenetskii.cc
  source/material_model/rheology/friction_models.cc
  source/material_model/rheology/peierls_creep.cc
  source/material_model/rheology/strain_dependent.cc
  source/material_model/rheology/visco_plastic.cc
  source/material_model/visco_plastic.cc
  source/material_model/viscoelastic.cc
  tests/vep_chemical_compositions.prm
  tests/vep_chemical_compositions/screen-output
  tests/vep_chemical_compositions/solution/solution-00000.0000.gnuplot
  tests/vep_chemical_compositions/solution/solution-00001.0000.gnuplot
  tests/vep_chemical_compositions/statistics
Labels: ready to test

#5551 Clean up some places handling initial topography in geometry models.
  include/aspect/geometry_model/box.h
  include/aspect/geometry_model/chunk.h
  include/aspect/geometry_model/ellipsoidal_chunk.h
  source/geometry_model/box.cc
  source/geometry_model/chunk.cc
  source/geometry_model/ellipsoidal_chunk.cc
  tests/ellipsoidal_chunk_geometry.cc
Labels: ready to test

#5552 Get most of what's needed for spherical topography in place.
  include/aspect/geometry_model/spherical_shell.h
  source/geometry_model/spherical_shell.cc
Labels: ready to test

#5245 Create reactive fluid transport material model
  doc/modules/changes/20230714_naliboff_b
  include/aspect/material_model/reactive_fluid_transport.h
  source/material_model/reactive_fluid_transport.cc
  tests/reactive_fluid_transport_no_reaction.prm
  tests/reactive_fluid_transport_no_reaction/screen-output
  tests/reactive_fluid_transport_no_reaction/statistics
  tests/reactive_fluid_transport_zero_solubility.prm
  tests/reactive_fluid_transport_zero_solubility/screen-output
  tests/reactive_fluid_transport_zero_solubility/statistics
Labels: ready to test
