Repository geodynamics/aspect, pull requests merged in 2024-06, with the labels that each got.

#5672 add pyvista 2D example plotting script
  contrib/python/scripts/pyvista_2d_example.py
Labels: ready to test

#5622 Multicomponent entropy method - average the looked-up material properties
  data/material-model/entropy-table/opxtable/multi_composition_test.txt
  source/adiabatic_conditions/compute_entropy_profile.cc
  source/material_model/entropy_model.cc
  tests/entropy_plasticity.prm
  tests/entropy_read_multi_table.cc
  tests/entropy_read_multi_table.prm
  tests/entropy_read_multi_table/solution/solution-00000.0000.gnuplot
  tests/entropy_read_multi_table/statistics
Labels: ready to test

#5704 Convert cmake commands to lower-case.
  CMakeLists.txt
Labels: ready to test

#5703 Avoid a warning about cmake backward compatibility.
  contrib/world_builder/CMakeLists.txt
Labels: ready to test

#5690 Change plugin name in cpo elastic tensor and use olivine stiffness matrix in initialization
  source/particle/property/cpo_elastic_tensor.cc
Labels: ready to merge, ready to test

#5707 remove unnecessary includes
  source/main.cc
  source/simulator/assembly.cc
  source/simulator/helper_functions.cc
  source/simulator/introspection.cc
  source/simulator/melt.cc
Labels: ready to merge, ready to test

#5709 add --output-json command line flag
  source/main.cc
Labels: ready to merge, ready to test

#5679 Better document what a spherical shell with topography does with normal vectors.
  include/aspect/geometry_model/spherical_shell.h
  source/geometry_model/spherical_shell.cc
Labels: ready to test

#5711 Add pyvsita 2D annulus example
  contrib/python/scripts/pyvista_2D_annulus_example.py
Labels: ready to merge, ready to test

#5717 Use complete sentences.
  cookbooks/allken_et_al_2012_rift_interaction/doc/allken.md
  cookbooks/burnman/doc/burnman.md
  cookbooks/fastscape_eroding_box/doc/README.md
  cookbooks/finite_strain/doc/finite_strain.md
  cookbooks/free_surface/doc/free_surface.md
  cookbooks/free_surface_with_crust/doc/free_surface_with_crust.md
  cookbooks/geomio/doc/geomio.md
  cookbooks/gplates/doc/gplates.md
  cookbooks/initial-condition-S20RTS/doc/initial-condition-S20RTS.md
  cookbooks/morency_doin_2004/doc/morency_doin_2004.md
  cookbooks/muparser_temperature_example/doc/muparser_temperature_example.md
  cookbooks/prescribed_velocity/doc/prescribed_velocity.md
  cookbooks/prescribed_velocity_ascii_data/doc/prescribed_velocity_ascii_data.md
  cookbooks/shell_simple_2d_smoothing/doc/shell_simple_2d_smoothing.md
  cookbooks/tomography_based_plate_motions/doc/tomography_based_plate_motions.md
  cookbooks/vankeken_subduction/doc/vankeken_subduction.md
Labels: ready to merge

#5716 always create parameters.json as a post-build step
  CMakeLists.txt
Labels: ready to merge, ready to test

#5687 Refactor schur complement inverse operator
  source/simulator/solver.cc
  tests/stokes_solver_fail/screen-output
  tests/stokes_solver_fail_cheap/screen-output
Labels: ready to merge, ready to test

#5719 Fix some text.
  contrib/python/scripts/pyvista_2D_annulus_example.py
Labels: ready to merge

#5702 Make dg limiter field specific
  doc/modules/changes/20240601_gassmoeller
  include/aspect/parameters.h
  include/aspect/utilities.h
  source/particle/interpolator/bilinear_least_squares.cc
  source/particle/interpolator/quadratic_least_squares.cc
  source/simulator/core.cc
  source/simulator/parameters.cc
  source/simulator/solver.cc
  source/utilities.cc
  tests/discontinuous_composition_bound_preserving_limiter_selected_fields.prm
  tests/discontinuous_composition_bound_preserving_limiter_selected_fields/screen-output
  tests/discontinuous_composition_bound_preserving_limiter_selected_fields/statistics
Labels: ready to merge, ready to test

#5701 Update kaus 2010 vep benchmark
  benchmarks/viscoelastic_plastic_shear_bands/kaus_2010/kaus_2010_extension.prm
  tests/visco_plastic_vep_brick_extension.prm
  tests/visco_plastic_vep_brick_extension/screen-output
  tests/visco_plastic_vep_brick_extension/statistics
Labels: ready to merge, ready to test

#5710 Make sure we set flags before we use them to output physical units.
  doc/modules/changes/20240601_bangerth
  source/postprocess/visualization.cc
  tests/parallel_output_group_0/solution/solution-00000.pvtu
  tests/parallel_output_group_0/solution/solution-00001.pvtu
  tests/parallel_output_group_1/solution/solution-00000.pvtu
  tests/parallel_output_group_1/solution/solution-00001.pvtu
  tests/parallel_output_group_2/solution/solution-00000.pvtu
  tests/parallel_output_group_2/solution/solution-00001.pvtu
Labels: ready to merge, ready to test

#5715 Break TARGET_SRC into different categories.
  CMakeLists.txt
Labels: ready to test

#5722 Rename file to make it consistent with the other .py file in this directory.
  contrib/python/scripts/pyvista_2d_annulus_example.py
Labels: ready to merge

#4957 GMG mesh displacement: clear user constraints
  source/mesh_deformation/interface.cc
Labels: ready to merge, ready to test

#5729 skip unity build for two files
  CMakeLists.txt
Labels: ready to merge

#5680 Python script that converts the ascii data to netcdf in spherical system
  data/test/netcdf/file-3d-spherical.nc
  data/test/netcdf/netcdf_test.txt
  data/test/netcdf/test-3d-spherical.nc
  data/test/netcdf/test-3d-spherical.py
  unit_tests/netcdf.cc
Labels: ready to test

#5725 Add min/max bounds to the compaction viscosity
  include/aspect/material_model/reactive_fluid_transport.h
  source/material_model/reactive_fluid_transport.cc
Labels: ready to test

#5724 factor out AInvOperator in Stokes solver
  source/simulator/solver.cc
  tests/stokes_solver_fail/screen-output
  tests/stokes_solver_fail_cheap/screen-output
Labels: ready to merge, ready to test

#5732 Updated documentation in FK header file
  include/aspect/material_model/rheology/frank_kamenetskii.h
Labels: ready to merge, ready to test

#5739 grammar: casted -> cast
  include/aspect/boundary_composition/interface.h
  include/aspect/boundary_temperature/interface.h
  include/aspect/boundary_velocity/interface.h
  include/aspect/heating_model/interface.h
  include/aspect/initial_composition/interface.h
  include/aspect/initial_temperature/interface.h
  include/aspect/mesh_deformation/interface.h
  include/aspect/mesh_refinement/interface.h
  include/aspect/particle/property/interface.h
  include/aspect/postprocess/interface.h
Labels: ready to merge, ready to test

#5741 solver.cc: make variables const
  source/simulator/solver.cc
Labels: ready to merge, ready to test

#5743 fix brittle test melt_restart
  tests/melt_restart.prm
Labels: ready to merge

#5742 range-based for
  include/aspect/boundary_composition/interface.h
  include/aspect/boundary_temperature/interface.h
  include/aspect/boundary_velocity/interface.h
  include/aspect/heating_model/interface.h
  include/aspect/initial_temperature/interface.h
  include/aspect/mesh_refinement/interface.h
Labels: ready to merge, ready to test

#5678 Create new viscosity prefactor feature
  doc/modules/changes/20240601_douglas
  include/aspect/material_model/rheology/compositional_viscosity_prefactors.h
  include/aspect/material_model/rheology/visco_plastic.h
  source/material_model/rheology/compositional_viscosity_prefactors.cc
  source/material_model/rheology/visco_plastic.cc
  tests/hk04_olivine_diffusion_hydration_prefactor.prm
  tests/hk04_olivine_diffusion_hydration_prefactor/screen-output
  tests/hk04_olivine_diffusion_hydration_prefactor/solution/solution-00000.0000.gnuplot
  tests/hk04_olivine_diffusion_hydration_prefactor/statistics
  tests/hk04_olivine_dislocation_hydration_prefactor.prm
  tests/hk04_olivine_dislocation_hydration_prefactor/screen-output
  tests/hk04_olivine_dislocation_hydration_prefactor/solution/solution-00000.0000.gnuplot
  tests/hk04_olivine_dislocation_hydration_prefactor/statistics
Labels: ready to test

#5744 nsinker: skip nonlinear iteration
  benchmarks/nsinker/nsinker.prm
  benchmarks/nsinker/nsinker_2d.prm
  benchmarks/nsinker/nsinker_gmg.prm
  tests/nsinker/screen-output
  tests/nsinker_2d/screen-output
  tests/nsinker_gmg_idr/screen-output
Labels: ready to merge, ready to test

#5751 Add changelog entry
  doc/modules/changes/20240602_gassmoeller
Labels: ready to merge, ready to test

#5747 add Introspection unittest
  unit_tests/introspection.cc
Labels: ready to merge, ready to test

#5737 I changed the shell script to end in .sh as is convention.
  benchmarks/advection_in_annulus/run_all_models.sh
  benchmarks/nsinker/run_all_models.sh
  benchmarks/rigid_shear/instantaneous/run_all_models.sh
  benchmarks/rigid_shear/steady-state/run_all_models.sh
  benchmarks/rigid_shear/transient/run_all_models.sh
  benchmarks/time_dependent_annulus/run_all_models.sh
  benchmarks/time_dependent_annulus/transient/run_all_models.sh
Labels: ready to merge, ready to test

#5740 Work around an issue with outputting higher order data on lines.
  source/postprocess/visualization.cc
Labels: ready to test

#5713 Katz 2003 Melt Fraction Calculation in Reactive Fluid Transport Model
  doc/modules/changes/20240601_block
  include/aspect/material_model/reactive_fluid_transport.h
  source/material_model/reactive_fluid_transport.cc
  tests/viscoplastic_melt_fraction.prm
  tests/viscoplastic_melt_fraction/screen-output
  tests/viscoplastic_melt_fraction/solution/solution-00000.0000.gnuplot
  tests/viscoplastic_melt_fraction/solution/solution-00001.0000.gnuplot
  tests/viscoplastic_melt_fraction/statistics
Labels: ready to test

#5738 Remove project to Q1 option for material averaging in the Elasticity rheology
  source/material_model/rheology/elasticity.cc
  tests/free_surface_VE_cylinder_2D_loading_fixed_elastic_dt_gmg.prm
  tests/gmg_mesh_deform_ghost_entries.prm
  tests/skip_refinement.prm
  tests/skip_refinement/screen-output
  tests/viscoelastic_bending_beam_gmg.prm
  tests/viscoelastic_bending_beam_gmg/depth_average.txt
  tests/viscoelastic_bending_beam_gmg/screen-output
  tests/viscoelastic_bending_beam_gmg/statistics
  tests/viscoelastic_stress_build-up_gmg.prm
Labels: ready to test

#5761 add signal to modify pressure scaling
  include/aspect/simulator_signals.h
  source/simulator/helper_functions.cc
  tests/pressure_scaling_signal.cc
  tests/pressure_scaling_signal.prm
  tests/pressure_scaling_signal/screen-output
  tests/pressure_scaling_signal/statistics
Labels: ready to merge, ready to test

#5731 Add test for gmg with spherical geometry.
  data/test/gmg/mesh_deformation_spherical_shell_2d.txt
  tests/mesh_deformation_gmg_2d_spherical_shell.prm
  tests/mesh_deformation_gmg_2d_spherical_shell/screen-output
  tests/mesh_deformation_gmg_2d_spherical_shell/solution/solution-00000.0000.gnuplot
  tests/mesh_deformation_gmg_2d_spherical_shell/solution/solution_surface-00000.0000.gnuplot
  tests/mesh_deformation_gmg_2d_spherical_shell/statistics
  tests/mesh_deformation_gmg_2d_spherical_shell/topography.00000
Labels: ready to test

#5116 Add cpo elastic tensor decomposition plugin
  include/aspect/particle/property/elastic_tensor_decomposition.h
  source/particle/property/elastic_tensor_decomposition.cc
  unit_tests/crystal_preferred_orientation.cc
Labels: ready to merge, ready to test

#5771 Simplify cell loops
  benchmarks/shear_bands/shear_bands.cc
  benchmarks/solitary_wave/solitary_wave.cc
  benchmarks/tangurnis/code/tangurnis.cc
  benchmarks/tosi_et_al_2015_gcubed/tosi.cc
  cookbooks/prescribed_velocity/prescribed_velocity.cc
  source/mesh_deformation/interface.cc
  source/postprocess/entropy_viscosity_statistics.cc
  source/postprocess/visualization/grain_lag_angle.cc
Labels: ready to merge, ready to test

#5770 simplify CompositionThreshold mesh refinement
  source/mesh_refinement/composition_threshold.cc
Labels: ready to merge, ready to test

#5768 use background field to calculate adiabatic profile
  source/adiabatic_conditions/compute_entropy_profile.cc
  tests/entropy_read_multi_table/solution/solution-00000.0000.gnuplot
Labels: ready to merge, ready to test

#5780 fix typos
  benchmarks/burstedde/doc/burstedde.md
  benchmarks/gravity_mantle/doc/gravity_mantle.md
  benchmarks/infill_density/doc/infill_density.md
  benchmarks/rayleigh_taylor_instability/doc/rayleigh_taylor_instability.md
  benchmarks/slab_detachment/doc/slab_detachment.md
  benchmarks/yamauchi_takei_2016_anelasticity/doc/yamauchi_takei_2016_anelasticity.md
  cookbooks/allken_et_al_2012_rift_interaction/doc/allken.md
  cookbooks/crustal_deformation/doc/crustal_deformation.md
  cookbooks/heat_flow/doc/heat-flow.md
  cookbooks/inclusions/doc/inclusions.md
  cookbooks/lower_crustal_flow/doc/lower_crustal_flow.md
  cookbooks/tomography_based_plate_motions/doc/tomography_based_plate_motions.md
  doc/sphinx/user/extending/testing/writing-tests.md
  doc/sphinx/user/intro.md
  doc/sphinx/user/methods/basic-equations/bc.md
  doc/sphinx/user/run-aspect/visualizing-results/index.md
Labels: ready to merge, ready to test

#5777 Make sure the compiler finds worldbuilder/config.h.
  CMakeLists.txt
Labels: ready to test

#5775 add to muparser docs
  doc/sphinx/user/run-aspect/parameters-overview/muparser-format.md
Labels: ready to merge, ready to test

#5783 fix readme (c++ 14 required)
  README.md
Labels: ready to merge, ready to test

#5776 Move data file to better folder.
  data/mesh-deformation/ascii-data/spherical_shell_2d.txt
  data/test/gmg/mesh_deformation_spherical_shell_2d.txt
  tests/mesh_deformation_gmg_2d_spherical_shell.prm
  tests/mesh_deformation_gmg_2d_spherical_shell/screen-output
Labels: ready to merge

#5773 change boundary conditions to dirichlet 0 for nsinker benchmark
  benchmarks/nsinker/nsinker.prm
  tests/nsinker/screen-output
  tests/nsinker/statistics
Labels: ready to test

#5766 backport world builder simplify cmake -fPIC
  contrib/world_builder/CMakeLists.txt
Labels: ready to test

#5726 fix a bug in S40RTS and SAVANI for data reading with a max SH degree truncation
  doc/modules/changes/20240604_Liu
  doc/modules/changes/20240604_Liu2
  include/aspect/initial_temperature/S40RTS_perturbation.h
  include/aspect/initial_temperature/SAVANI_perturbation.h
  source/initial_temperature/S40RTS_perturbation.cc
  source/initial_temperature/SAVANI_perturbation.cc
  tests/initial_condition_SAVANI.prm
  tests/initial_condition_SAVANI/screen-output
  tests/initial_condition_SAVANI/solution/solution-00000.0000.gnuplot
  tests/initial_condition_SAVANI/statistics
Labels: ready to test

#5758 Add authors in a separate page.
  doc/sphinx/conf.py
  doc/sphinx/index.md
  doc/sphinx/user/authors.md
  doc/sphinx/user/index.md
Labels: documentation, ready to test

#5733 adding_documentation_to_DP_rheology
  source/material_model/rheology/drucker_prager.cc
Labels: ready to merge, ready to test

#5791 fix double<->int conversion warnings
  source/particle/property/elastic_tensor_decomposition.cc
Labels: ready to merge, ready to test

#5789 remove unused variable
  source/compat.cc
Labels: ready to merge, ready to test

#5790 fix class/struct mismatch for MaterialModelInputs
  source/material_model/interface.cc
Labels: ready to merge, ready to test

#5793 Update identity
  Jenkinsfile.osx
Labels: ready to merge

#5794 Fix typos
  source/particle/property/crystal_preferred_orientation.cc
Labels: ready to merge, ready to test

#5781 Disentangle CMakeLists.txt.
  CMakeLists.txt
  doc/CMakeLists.txt
Labels: ready to merge, ready to test

#5787 Add a signal before building patches for visualization output
  include/aspect/simulator_signals.h
  source/postprocess/visualization.cc
  tests/pre_data_out_build_patches.cc
  tests/pre_data_out_build_patches.prm
  tests/pre_data_out_build_patches/screen-output
  tests/pre_data_out_build_patches/statistics
Labels: ready to merge, ready to test

#5792 GWB: disable fortran wrappers
  CMakeLists.txt
  contrib/world_builder/CMakeLists.txt
Labels: ready to merge, ready to test

#5800 Convert all plugins to the use of the new Plugins::InterfaceBase class.
  include/aspect/adiabatic_conditions/interface.h
  include/aspect/boundary_composition/interface.h
  include/aspect/boundary_fluid_pressure/interface.h
  include/aspect/boundary_heat_flux/interface.h
  include/aspect/boundary_temperature/interface.h
  include/aspect/boundary_traction/interface.h
  include/aspect/boundary_velocity/interface.h
  include/aspect/geometry_model/initial_topography_model/interface.h
  include/aspect/geometry_model/interface.h
  include/aspect/gravity_model/interface.h
  include/aspect/initial_composition/interface.h
  include/aspect/initial_temperature/interface.h
  include/aspect/material_model/interface.h
  include/aspect/mesh_deformation/interface.h
  include/aspect/mesh_refinement/interface.h
  include/aspect/particle/generator/interface.h
  include/aspect/particle/integrator/interface.h
  include/aspect/particle/interpolator/interface.h
  include/aspect/particle/property/interface.h
  include/aspect/plugins.h
  include/aspect/postprocess/interface.h
  include/aspect/postprocess/visualization.h
  include/aspect/prescribed_stokes_solution/interface.h
  include/aspect/simulator/assemblers/interface.h
  include/aspect/termination_criteria/interface.h
  include/aspect/time_stepping/interface.h
  source/adiabatic_conditions/interface.cc
  source/boundary_composition/interface.cc
  source/boundary_fluid_pressure/interface.cc
  source/boundary_heat_flux/interface.cc
  source/boundary_temperature/interface.cc
  source/boundary_traction/interface.cc
  source/boundary_velocity/interface.cc
  source/geometry_model/initial_topography_model/interface.cc
  source/geometry_model/interface.cc
  source/gravity_model/interface.cc
  source/initial_composition/interface.cc
  source/initial_temperature/interface.cc
  source/material_model/interface.cc
  source/mesh_deformation/interface.cc
  source/mesh_refinement/interface.cc
  source/particle/generator/interface.cc
  source/particle/integrator/interface.cc
  source/particle/interpolator/interface.cc
  source/particle/property/interface.cc
  source/plugins.cc
  source/postprocess/interface.cc
  source/postprocess/visualization.cc
  source/prescribed_stokes_solution/interface.cc
  source/termination_criteria/interface.cc
  source/time_stepping/interface.cc
Labels: ready to merge, ready to test

#5801 update the indexing of vector gradients following the idea of defensive programming (compiled)
  source/particle/property/crystal_preferred_orientation.cc
Labels: ready to merge, ready to test

#5774 fix uninitialized variables
  include/aspect/material_model/rheology/diffusion_creep.h
  include/aspect/material_model/rheology/dislocation_creep.h
  include/aspect/material_model/rheology/drucker_prager.h
  include/aspect/material_model/rheology/peierls_creep.h
  source/material_model/rheology/composite_visco_plastic.cc
  source/material_model/rheology/diffusion_creep.cc
  source/material_model/rheology/dislocation_creep.cc
  source/material_model/rheology/drucker_prager.cc
  source/material_model/rheology/peierls_creep.cc
Labels: ready to merge, ready to test

#5806 update citing_aspect.bib
  doc/manual/citing_aspect.bib
Labels: ready to merge, ready to test

#5798 updated pymuparser description
  doc/sphinx/user/run-aspect/parameters-overview/muparser-format.md
Labels: ready to merge, ready to test

#5767 Add cookbook for 2d annulus pyvista visualization
  cookbooks/2d_annulus_visualization/2d_annulus_example.prm
  cookbooks/2d_annulus_visualization/doc/2d_annulus_visualization.md
  cookbooks/2d_annulus_visualization/doc/T_dev_00025.png
  cookbooks/2d_annulus_visualization/doc/vphi_00025.png
  cookbooks/2d_annulus_visualization/doc/vr_00025.png
  doc/modules/changes/20240605_KerrMadeleine
  doc/sphinx/user/cookbooks/geophysical-setups.md
  tests/2d_annulus_pyvista_cookbook.prm
  tests/2d_annulus_pyvista_cookbook/screen-output
  tests/2d_annulus_pyvista_cookbook/solution/solution-00000.0000.gnuplot
  tests/2d_annulus_pyvista_cookbook/statistics
Labels: ready to test

#5746 Create a Cookbook for the Tian Parameterization Reactive Fluid Transport Model
  cookbooks/tian_parameterization_kinematic_slab/coupled-two-phase-tian-parameterization-kinematic-slab.prm
  cookbooks/tian_parameterization_kinematic_slab/doc/coupled-porosity.png
  cookbooks/tian_parameterization_kinematic_slab/doc/schematic-diagram-model.png
  cookbooks/tian_parameterization_kinematic_slab/doc/schematic-diagram-overview.png
  cookbooks/tian_parameterization_kinematic_slab/doc/temperature-fluid-velocity.png
  cookbooks/tian_parameterization_kinematic_slab/doc/tian_parameterization_kinematic_slab.md
  cookbooks/tian_parameterization_kinematic_slab/doc/uncoupled-porosity.png
  cookbooks/tian_parameterization_kinematic_slab/uncoupled-two-phase-tian-parameterization-kinematic-slab.prm
  doc/modules/changes/20240605_douglas
  doc/sphinx/references.bib
  doc/sphinx/user/cookbooks/geophysical-setups.md
  tests/coupled_two_phase_tian_parameterization_kinematic_slab.prm
  tests/coupled_two_phase_tian_parameterization_kinematic_slab/screen-output
  tests/coupled_two_phase_tian_parameterization_kinematic_slab/solution/solution-00000.0000.gnuplot
  tests/coupled_two_phase_tian_parameterization_kinematic_slab/solution/solution-00001.0000.gnuplot
  tests/coupled_two_phase_tian_parameterization_kinematic_slab/statistics
  tests/uncoupled_two_phase_tian_parameterization_kinematic_slab.prm
  tests/uncoupled_two_phase_tian_parameterization_kinematic_slab/screen-output
  tests/uncoupled_two_phase_tian_parameterization_kinematic_slab/statistics
Labels: ready to merge, ready to test

#5810 add changelog of merged cookbook
  doc/modules/changes/20240605_thieulot
Labels: ready to merge, ready to test

#5814 Make cmake functions lowercase.
  cmake/AspectConfig.cmake.in
  cmake/fpe_check.cmake
  cmake/macro_aspect_query_git_information.cmake
  cmake/modules/FindLIBDAP.cmake
  cmake/modules/FindNETCDF.cmake
  cmake/write_config.cmake
  tests/run_test.cmake
  tests/run_testsuite.cmake
  tests/submit_results.cmake
Labels: ready to merge, ready to test

#5813 adding doi's to references_bib
  doc/sphinx/references.bib
Labels: ready to merge

#3317 Add surface topography benchmark
  benchmarks/rayleigh_taylor_instability_free_surface/Kaus_2010.csv
  benchmarks/rayleigh_taylor_instability_free_surface/doc/drip_depth.png
  benchmarks/rayleigh_taylor_instability_free_surface/doc/rayleigh_taylor_instability_free_surface.md
  benchmarks/rayleigh_taylor_instability_free_surface/doc/topography.png
  benchmarks/rayleigh_taylor_instability_free_surface/kaus_rayleigh_taylor_instability.prm
  benchmarks/rayleigh_taylor_instability_free_surface/plot_drip_depth.gnuplot
  benchmarks/rayleigh_taylor_instability_free_surface/plot_topography.gnuplot
  benchmarks/rayleigh_taylor_instability_free_surface/rose_rayleigh_taylor_instability.prm
  doc/modules/changes/20240606_glerum
  doc/sphinx/user/benchmarks/index.md
  tests/kaus_rayleigh_taylor_instability.prm
  tests/kaus_rayleigh_taylor_instability/screen-output
  tests/kaus_rayleigh_taylor_instability/solution/solution-00000.0000.gnuplot
  tests/kaus_rayleigh_taylor_instability/solution/solution-00001.0000.gnuplot
  tests/kaus_rayleigh_taylor_instability/statistics
  tests/kaus_rayleigh_taylor_instability/topography.00000
  tests/kaus_rayleigh_taylor_instability/topography.00001
Labels: ready to merge, ready to test

#5752 Added coordinate systems to Gravity model function plug-in
  doc/modules/changes/20240602_KerrMadeleine
  include/aspect/gravity_model/function.h
  source/gravity_model/function.cc
  tests/gravity_model_cartesian.prm
  tests/gravity_model_cartesian/screen-output
  tests/gravity_model_cartesian/solution/solution-00000.0000.gnuplot
  tests/gravity_model_cartesian/statistics
  tests/gravity_model_depth.prm
  tests/gravity_model_depth/screen-output
  tests/gravity_model_depth/solution/solution-00000.0000.gnuplot
  tests/gravity_model_depth/statistics
  tests/gravity_model_spherical.prm
  tests/gravity_model_spherical/screen-output
  tests/gravity_model_spherical/solution/solution-00000.0000.gnuplot
  tests/gravity_model_spherical/statistics
Labels: ready to merge, ready to test

#5812 Avoid the word 'master' where possible.
  include/aspect/postprocess/particles.h
  include/aspect/postprocess/visualization.h
  source/postprocess/particles.cc
  source/postprocess/visualization.cc
Labels: ready to merge, ready to test

#5817 changelog for removing make test
  doc/modules/changes/20240605_tjhei
Labels: ready to merge, ready to test

#5799 Add base model additional outputs to supporting material models
  include/aspect/material_model/averaging.h
  include/aspect/material_model/replace_lithosphere_viscosity.h
  source/material_model/averaging.cc
  source/material_model/reactive_fluid_transport.cc
  source/material_model/replace_lithosphere_viscosity.cc
  tests/viscoplastic_melt_fraction.prm
  tests/viscoplastic_melt_fraction/solution/solution-00000.0000.gnuplot
  tests/viscoplastic_melt_fraction/solution/solution-00001.0000.gnuplot
Labels: ready to test

#5821 Remove a member variable that is not used.
  include/aspect/boundary_traction/interface.h
Labels: ready to merge, ready to test

#5816 simplify compaction length refinement
  source/mesh_refinement/compaction_length.cc
Labels: ready to merge, ready to test

#5807 More moving around stuff in CMakeLists.txt.
  CMakeLists.txt
Labels: ready to test

#5759 Move melt transport code from Melt Simple model to Katz 2003 Mantle Melting Model
  include/aspect/material_model/melt_simple.h
  include/aspect/material_model/reaction_model/katz2003_mantle_melting.h
  source/material_model/melt_simple.cc
  source/material_model/reaction_model/katz2003_mantle_melting.cc
  tests/shear_heating_with_melt/screen-output
  tests/shear_heating_with_melt/statistics
Labels: ready to test

#5828 Add a simple test for grain size growth with particles
  tests/grain_size_growth_one_cell_particles.prm
  tests/grain_size_growth_one_cell_particles/screen-output
  tests/grain_size_growth_one_cell_particles/statistics
Labels: ready to merge

#5832 simplify code
  source/simulator/entropy_viscosity.cc
Labels: ready to merge, ready to test

#5808 Add cutoff for dry/wet creep in water fugacity calculation
  include/aspect/material_model/rheology/compositional_viscosity_prefactors.h
  source/material_model/rheology/compositional_viscosity_prefactors.cc
  tests/hk04_olivine_composite_hydration_prefactor_cutoff.prm
  tests/hk04_olivine_composite_hydration_prefactor_cutoff/screen-output
  tests/hk04_olivine_composite_hydration_prefactor_cutoff/solution/solution-00000.0000.gnuplot
  tests/hk04_olivine_composite_hydration_prefactor_cutoff/statistics
Labels: ready to test

#5764 Implementation of temperature activated strain softening
  doc/modules/changes/20240606_thieulot
  include/aspect/material_model/rheology/strain_dependent.h
  source/material_model/rheology/strain_dependent.cc
  source/material_model/rheology/visco_plastic.cc
  tests/visco_plastic_yield_temperature_activated_viscous_strain_weakening.prm
  tests/visco_plastic_yield_temperature_activated_viscous_strain_weakening/screen-output
  tests/visco_plastic_yield_temperature_activated_viscous_strain_weakening/solution/solution-00000.0000.gnuplot
  tests/visco_plastic_yield_temperature_activated_viscous_strain_weakening/statistics
Labels: ready to merge, ready to test

#5840 Add changelog entry for CPO elastic symmetry decomposition.
  doc/modules/changes/20240606_mfraters
Labels: ready to merge, ready to test

#5839 Better indent a command line.
  .github/workflows/linux.yml
Labels: ready to merge, ready to test

#5842 Remove option to advect logarithm of grain size
  doc/modules/changes/20240607_dannberg
  include/aspect/material_model/grain_size.h
  source/material_model/grain_size.cc
  tests/grain_size_growth_log.prm
  tests/grain_size_growth_log/screen-output
  tests/grain_size_growth_log/statistics
  tests/grain_size_latent_heat.cc
Labels: ready to merge, ready to test

#5769 add a cookbook for multicomponents steinberger model
  cookbooks/multicomponent_steinberger/doc/comp.field.prm
  cookbooks/multicomponent_steinberger/doc/comp.setup.prm
  cookbooks/multicomponent_steinberger/doc/compfield.multicomp.steinberger.png
  cookbooks/multicomponent_steinberger/doc/conductivity.setup.prm
  cookbooks/multicomponent_steinberger/doc/lookup.part.prm
  cookbooks/multicomponent_steinberger/doc/multicomponent_steinberger.md
  cookbooks/multicomponent_steinberger/doc/temperature.multicomp.steinberger.png
  cookbooks/multicomponent_steinberger/doc/temperature.setup.prm
  cookbooks/multicomponent_steinberger/doc/viscosity.multicomp.steinberger.png
  cookbooks/multicomponent_steinberger/steinberger_thermochemical_plume.prm
  cookbooks/steinberger/doc/steinberger.md
  doc/sphinx/references.bib
  doc/sphinx/user/cookbooks/geophysical-setups.md
Labels: ready to test

#5843 Completely gratuitous change of line breakage.
  source/postprocess/visualization.cc
Labels: ready to merge, ready to test

#5796 cookbook for mantle convection in annulus after van der Wiel
  cookbooks/mantle_convection_with_continents_in_annulus/doc/continents.png
  cookbooks/mantle_convection_with_continents_in_annulus/doc/evolution.png
  cookbooks/mantle_convection_with_continents_in_annulus/doc/mantle_convection_in_annulus.md
  cookbooks/mantle_convection_with_continents_in_annulus/doc/temperature.png
  cookbooks/mantle_convection_with_continents_in_annulus/doc/viscosity.png
  cookbooks/mantle_convection_with_continents_in_annulus/doc/viscosity_profiles.png
  cookbooks/mantle_convection_with_continents_in_annulus/modelR.prm
  cookbooks/mantle_convection_with_continents_in_annulus/world.wb
  doc/modules/changes/20240606_thieulot
  doc/modules/changes/20240607_thieulot
  doc/sphinx/references.bib
  doc/sphinx/user/cookbooks/geophysical-setups.md
  tests/cookbook_mantle_convection_annulus.prm
  tests/cookbook_mantle_convection_annulus/screen-output
  tests/cookbook_mantle_convection_annulus/statistics
Labels: ready to merge, ready to test

#5845 Consistently put a space between 'template' and '<int dim'.
  benchmarks/advection_in_annulus/advection_in_annulus.cc
  benchmarks/annulus/plugin/annulus.cc
  benchmarks/hollow_sphere/hollow_sphere.cc
  benchmarks/inclusion/compositional_fields/inclusion_compositional_fields.h
  benchmarks/nsinker/nsinker.cc
  benchmarks/nsinker_spherical_shell/nsinker.cc
  benchmarks/operator_splitting/advection_reaction/advection_reaction.cc
  benchmarks/operator_splitting/exponential_decay/exponential_decay.cc
  benchmarks/rigid_shear/plugin/rigid_shear.cc
  benchmarks/solcx/compositional_fields/solcx_compositional_fields.h
  benchmarks/solcx/solcx.h
  benchmarks/solkz/compositional_fields/solkz_compositional_fields.h
  benchmarks/solkz/solkz.h
  include/aspect/compat.h
  include/aspect/mesh_deformation/diffusion.h
  include/aspect/mesh_deformation/fastscape.h
  include/aspect/mesh_deformation/free_surface.h
  include/aspect/mesh_deformation/function.h
  include/aspect/mesh_deformation/interface.h
  include/aspect/particle/world.h
  include/aspect/postprocess/particles.h
  include/aspect/postprocess/visualization/ISA_rotation_timescale.h
  include/aspect/postprocess/visualization/grain_lag_angle.h
  include/aspect/stokes_matrix_free.h
  include/aspect/structured_data.h
  include/aspect/volume_of_fluid/field.h
  include/aspect/volume_of_fluid/utilities.h
  source/main.cc
  source/material_model/interface.cc
  source/particle/interpolator/quadratic_least_squares.cc
  source/particle/property/cpo_bingham_average.cc
  source/particle/property/crystal_preferred_orientation.cc
  source/postprocess/particles.cc
  source/postprocess/visualization/ISA_rotation_timescale.cc
  source/postprocess/visualization/grain_lag_angle.cc
  source/simulator/assemblers/interface.cc
  source/volume_of_fluid/handler.cc
  source/volume_of_fluid/utilities.cc
  tests/box_initial_mesh_deformation.cc
  tests/drucker_prager_derivatives_2d.cc
  tests/drucker_prager_derivatives_3d.cc
  tests/rheology_scaled_profile.cc
  tests/simple_nonlinear.cc
Labels: ready to test

#5846 Remove old stuff for compatibility with deal.II pre-9.5.
  include/aspect/compat.h
  source/postprocess/visualization.cc
  source/simulator/stokes_matrix_free.cc
Labels: ready to merge, ready to test

#5848 Remove code that supports in-source builds.
  CMakeLists.txt
Labels: ready to merge, ready to test

#5850 Simplify code.
  source/volume_of_fluid/handler.cc
Labels: ready to merge, ready to test

#5847 Move a signal to after we're actually done solving things.
  source/simulator/solver.cc
Labels: ready to test

#5835 string_to_unsigned_int
  include/aspect/utilities.h
  source/utilities.cc
  unit_tests/utilities.cc
Labels: ready to test

#5852 No need to fully qualify class SimulatorAccess.
  include/aspect/boundary_composition/interface.h
  include/aspect/boundary_temperature/interface.h
  include/aspect/boundary_traction/interface.h
  include/aspect/boundary_velocity/interface.h
  include/aspect/heating_model/interface.h
  include/aspect/initial_composition/interface.h
  include/aspect/initial_temperature/interface.h
  include/aspect/mesh_refinement/interface.h
  include/aspect/postprocess/interface.h
  include/aspect/termination_criteria/interface.h
Labels: ready to test

#5795 Added reaction and melt output calculations to reactive fluid flow model
  doc/modules/changes/20240606_block
  include/aspect/material_model/reactive_fluid_transport.h
  source/material_model/reactive_fluid_transport.cc
  tests/viscoplastic_melt_blob_freezing.prm
  tests/viscoplastic_melt_blob_freezing/screen-output
  tests/viscoplastic_melt_blob_freezing/solution/solution-00000.0000.gnuplot
  tests/viscoplastic_melt_blob_freezing/solution/solution-00001.0000.gnuplot
  tests/viscoplastic_melt_blob_freezing/solution/solution-00002.0000.gnuplot
  tests/viscoplastic_melt_blob_freezing/statistics
  tests/viscoplastic_melt_fraction.prm
  tests/viscoplastic_melt_fraction/screen-output
  tests/viscoplastic_melt_fraction/solution/solution-00000.0000.gnuplot
  tests/viscoplastic_melt_fraction/solution/solution-00001.0000.gnuplot
  tests/viscoplastic_melt_fraction/statistics
Labels: ready to test

#5826 Add world builder integration to CPO initial grains.
  doc/modules/changes/20240609_mfraters
  include/aspect/particle/property/crystal_preferred_orientation.h
  source/particle/property/crystal_preferred_orientation.cc
  tests/world_builder_select_grains.prm
  tests/world_builder_select_grains.wb
  tests/world_builder_select_grains/particles/particles-00000.0000.gnuplot
  tests/world_builder_select_grains/particles_cpo/CPO-00000.0000.dat
  tests/world_builder_select_grains/particles_cpo/particles-00000.0000.dat
  tests/world_builder_select_grains/particles_cpo/weighted_CPO-00000.0000.dat
Labels: ready to merge, ready to test

#5804 Update the calculation of G tensor so that its form is more consisten…
  source/particle/property/crystal_preferred_orientation.cc
Labels: ready to test

#5859 update clang-tidy rules
  .clang-tidy
Labels: ready to merge, ready to test

#5860 use c++14 type trait
  include/aspect/plugins.h
Labels: ready to merge

#5861 fix bug in unit_tests/utilities.cc
  unit_tests/utilities.cc
Labels: ready to merge

#5862 fix comment typos
  include/aspect/particle/property/crystal_preferred_orientation.h
Labels: ready to merge

#5863 CPO: use enum instead of double in set/get_deformation_type
  include/aspect/particle/property/crystal_preferred_orientation.h
  source/particle/property/cpo_elastic_tensor.cc
  source/particle/property/crystal_preferred_orientation.cc
  unit_tests/crystal_preferred_orientation.cc
Labels: ready to merge, ready to test

#5864 correct emplace_back() usage
  unit_tests/termination_criteria.cc
Labels: ready to merge, ready to test

#5818 script to convert ASCII data to netcdf files
  contrib/python/scripts/ascii2netcdf.py
  doc/modules/changes/20240606_alarshi
Labels: ready to test

#5869 Add documentation on grain size model
  source/material_model/grain_size.cc
  tests/grain_size_friction_heating.prm
Labels: ready to merge

#5838 add separate nightly deal.II master Docker script with clang
  .github/workflows/build_dealii_master_clang.yml
  contrib/docker/tester-clang/Dockerfile
  contrib/docker/tester-clang/build.sh
  contrib/docker/tester-clang/local.cfg
Labels: ready to merge, ready to test

#5879 Do not capitalize subsection
  cookbooks/kinematically_driven_subduction_2d/doc/Case2a_temperatures.prm
Labels: ready to merge

#5878 Escape backslashes in documentation
  cookbooks/inner_core_convection/inner_core_convection.cc
  source/heating_model/constant_heating.cc
Labels: ready to merge

#5823 Add eigenvalues to the outputs of the bingham average particle property
  include/aspect/particle/property/cpo_bingham_average.h
  source/particle/property/cpo_bingham_average.cc
  tests/cpo_simple_shearbox/particles/particles-00000.0000.gnuplot
  tests/cpo_simple_shearbox/particles/particles-00001.0000.gnuplot
  tests/cpo_simple_shearbox/particles/particles-00002.0000.gnuplot
  tests/world_builder_select_grains/particles/particles-00000.0000.gnuplot
  tests/world_builder_select_grains/particles_cpo/CPO-00000.0000.dat
  tests/world_builder_select_grains/particles_cpo/weighted_CPO-00000.0000.dat
Labels: ready to merge, ready to test

#5886 check.mk: do not run .part.prm files
  benchmarks/check.mk
  cookbooks/check.mk
Labels: ready to merge

#5885 benchmarks/particle_integration_scheme/ rename to .part.prm
  benchmarks/particle_integration_scheme/create.sh
  benchmarks/particle_integration_scheme/euler.part.prm
  benchmarks/particle_integration_scheme/rk2.part.prm
  benchmarks/particle_integration_scheme/rk4.part.prm
Labels: ready to merge

#5884 fix cookbooks/tian_parametrization...
  cookbooks/tian_parameterization_kinematic_slab/coupled-two-phase-tian-parameterization-kinematic-slab.prm
Labels: ready to merge

#5881 cookbooks/subduction_initiation/ rename base file
  cookbooks/subduction_initiation/subduction_initiation.prm.base
  cookbooks/subduction_initiation/subduction_initiation_compositional_fields.prm
  cookbooks/subduction_initiation/subduction_initiation_particle_in_cell.prm
  tests/subduction_initiation_compositional_fields.prm
Labels: ready to merge

#5872 Provide a base class for plugin manager classes.
  include/aspect/heating_model/interface.h
  include/aspect/plugins.h
  include/aspect/postprocess/interface.h
  source/heating_model/interface.cc
  source/postprocess/interface.cc
  tests/find_postprocess_fail_1/screen-output
Labels: ready to test

#5894 GWB: Only set -fcolor-diagnostics for cpp compilers
  contrib/world_builder/CMakeLists.txt
Labels: ready to merge

#5899 more clang-tidy fixes
  benchmarks/compressibility_formulations/plugins/compressibility_formulations.cc
  benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/simple_nonlinear.cc
  benchmarks/newton_solver_benchmark_set/spiegelman_et_al_2016/drucker_prager_compositions.cc
  benchmarks/operator_splitting/advection_reaction/advection_reaction.cc
  benchmarks/operator_splitting/exponential_decay/exponential_decay.cc
  benchmarks/shear_bands/shear_bands.cc
  benchmarks/solcx/solcx.h
  benchmarks/solitary_wave/solitary_wave.cc
  benchmarks/solkz/solkz.h
  benchmarks/tosi_et_al_2015_gcubed/tosi.cc
  source/boundary_velocity/interface.cc
  source/material_model/entropy_model.cc
  tests/melt_visco_plastic.cc
  tests/multiple_named_additional_outputs.cc
  tests/prescribed_field.cc
  tests/prescribed_field_temperature.cc
  tests/prescribed_field_with_diffusion.cc
  tests/prescribed_temperature.cc
  tests/prescribed_temperature_with_diffusion.cc
  unit_tests/additional_outputs.cc
Labels: ready to merge

#5897 Add to full A documentation
  source/simulator/parameters.cc
Labels: ready to test

#5904 improve a test
  tests/latent_heat_melt_operator_split.prm
  tests/latent_heat_melt_operator_split/screen-output
  tests/latent_heat_melt_operator_split/statistics
Labels: ready to merge, ready to test

#5906 Add tester coverage for particle interplator.
  tests/interpolor_particles_harmonic_average.prm
  tests/interpolor_particles_harmonic_average/screen-output
  tests/interpolor_particles_nearest_neighbor.prm
  tests/interpolor_particles_nearest_neighbor/screen-output
  tests/interpolor_particles_quadratic_least_squares.prm
  tests/interpolor_particles_quadratic_least_squares/screen-output
Labels: ready to test

#5901 Introspection: store discontinuous per composition
  include/aspect/introspection.h
  include/aspect/parameters.h
  source/simulator/assembly.cc
  source/simulator/checkpoint_restart.cc
  source/simulator/core.cc
  source/simulator/helper_functions.cc
  source/simulator/introspection.cc
  source/simulator/melt.cc
  source/simulator/parameters.cc
  source/simulator/solver.cc
Labels: ready to merge, ready to test

#5907 remove useless std::move
  source/postprocess/particles.cc
Labels: ready to merge, ready to test

#5913 Add missing changelog for #5331
  doc/modules/changes/20240614_dannberg
Labels: ready to merge

#5912 Fix particle update script
  contrib/utilities/update_scripts/prm_files/move_particles.py
Labels: ready to merge

#5911 Consistently format 'deal.II' in the manual.
  doc/sphinx/user/extending/index.md
  doc/sphinx/user/install/docker-container/developing-in-container.md
  doc/sphinx/user/install/local-installation/using-candi.md
  doc/sphinx/user/run-aspect/debug-mode.md
Labels: ready to merge, ready to test

#5917 Code cleanup
  include/aspect/simulator_access.h
  source/material_model/rheology/strain_dependent.cc
  source/mesh_refinement/particle_density.cc
  source/particle/interpolator/bilinear_least_squares.cc
  source/particle/interpolator/quadratic_least_squares.cc
  source/postprocess/load_balance_statistics.cc
  source/postprocess/particle_count_statistics.cc
  source/postprocess/visualization/particle_count.cc
  source/simulator/initial_conditions.cc
  source/simulator/simulator_access.cc
Labels: ready to merge

#5916 Add changelog entry for moving the particle plugin declarations.
  doc/modules/changes/20240615_mfraters
Labels: ready to merge, ready to test

#5925 Convert a number of other manager classes to the manager base class.
  include/aspect/boundary_composition/interface.h
  include/aspect/boundary_temperature/interface.h
  include/aspect/initial_composition/interface.h
  include/aspect/initial_temperature/interface.h
  include/aspect/mesh_refinement/interface.h
  include/aspect/particle/property/interface.h
  include/aspect/termination_criteria/interface.h
  include/aspect/time_stepping/interface.h
  source/boundary_composition/interface.cc
  source/boundary_temperature/interface.cc
  source/initial_composition/interface.cc
  source/initial_temperature/interface.cc
  source/mesh_refinement/interface.cc
  source/particle/property/interface.cc
  source/termination_criteria/interface.cc
  source/time_stepping/interface.cc
  tests/find_boundary_composition_model_fail_1/screen-output
  tests/find_mesh_refinement_fail_1/screen-output
Labels: ready to merge, ready to test

#5920 Add further multiple particle world instrastructure.
  include/aspect/simulator.h
  include/aspect/simulator_access.h
  source/material_model/rheology/strain_dependent.cc
  source/mesh_refinement/particle_density.cc
  source/particle/integrator/rk_2.cc
  source/particle/integrator/rk_4.cc
  source/particle/interpolator/bilinear_least_squares.cc
  source/particle/interpolator/quadratic_least_squares.cc
  source/particle/property/cpo_bingham_average.cc
  source/particle/property/cpo_elastic_tensor.cc
  source/particle/property/elastic_tensor_decomposition.cc
  source/postprocess/crystal_preferred_orientation.cc
  source/postprocess/load_balance_statistics.cc
  source/postprocess/particle_count_statistics.cc
  source/postprocess/particles.cc
  source/postprocess/visualization/particle_count.cc
  source/simulator/core.cc
  source/simulator/initial_conditions.cc
  source/simulator/simulator_access.cc
  source/simulator/solver_schemes.cc
  tests/mesh_deformation_particles.cc
  tests/particle_handler_copy.cc
  tests/particle_property_post_initialize_function.cc
Labels: ready to merge

#5836 Build aspect.debug and/or aspect.release, then link to it.
  CMakeLists.txt
  cmake/AspectConfig.cmake.in
  cmake/write_config.cmake
Labels: ready to test

#5928 Fix bug in bingham_average and the cpo test
  source/particle/property/cpo_bingham_average.cc
  tests/cpo_simple_shearbox/particles/particles-00000.0000.gnuplot
  tests/cpo_simple_shearbox/particles/particles-00001.0000.gnuplot
  tests/cpo_simple_shearbox/particles/particles-00002.0000.gnuplot
Labels: ready to merge, ready to test

#5933 Remove now superfluous Manager functions.
  include/aspect/boundary_composition/interface.h
  include/aspect/boundary_temperature/interface.h
  include/aspect/initial_composition/interface.h
  include/aspect/initial_temperature/interface.h
  include/aspect/mesh_refinement/interface.h
  include/aspect/particle/property/interface.h
  source/boundary_composition/interface.cc
  source/boundary_temperature/interface.cc
  source/initial_composition/interface.cc
  source/initial_temperature/interface.cc
  source/mesh_refinement/interface.cc
  source/particle/property/interface.cc
Labels: ready to test

#5932 Harden Plugins::ManagerBase::update() against exceptions.
  include/aspect/plugins.h
  tests/find_boundary_composition_model_fail_1/screen-output
  tests/find_mesh_refinement_fail_1/screen-output
  tests/find_postprocess_fail_1/screen-output
Labels: ready to merge, ready to test

#5856 Add Darcy field convection timestep
  doc/modules/changes/20240609_danieldouglas92
  source/time_stepping/convection_time_step.cc
  tests/darcy_convection_step.prm
  tests/darcy_convection_step/screen-output
  tests/darcy_convection_step/statistics
  tests/darcy_velocity/screen-output
  tests/darcy_velocity/statistics
Labels: ready to test

#5935 clang tidy rule fix and a fix
  .clang-tidy
  source/postprocess/visualization.cc
Labels: ready to merge, ready to test

#5924 Made FK reference temperature and pressure user inputs
  doc/modules/changes/20240624_block
  include/aspect/material_model/rheology/frank_kamenetskii.h
  source/material_model/rheology/frank_kamenetskii.cc
  tests/visco_plastic_frank_kamenetskii_pressure_user_refs.prm
  tests/visco_plastic_frank_kamenetskii_pressure_user_refs/screen-output
  tests/visco_plastic_frank_kamenetskii_pressure_user_refs/solution/solution-00000.0000.gnuplot
Labels: ready to test

#5937 make SchurComplementOperator destructor virtual
  source/simulator/solver.cc
Labels: ready to merge, ready to test

#5934 Deprecate now redundant functions in all of the Manager classes.
  include/aspect/boundary_composition/interface.h
  include/aspect/boundary_temperature/interface.h
  include/aspect/heating_model/interface.h
  include/aspect/initial_composition/interface.h
  include/aspect/initial_temperature/interface.h
  include/aspect/mesh_refinement/interface.h
  include/aspect/particle/property/interface.h
  include/aspect/postprocess/interface.h
  source/boundary_temperature/dynamic_core.cc
  source/heating_model/interface.cc
  source/particle/property/cpo_bingham_average.cc
  source/particle/property/cpo_elastic_tensor.cc
  source/postprocess/core_statistics.cc
  source/postprocess/crystal_preferred_orientation.cc
  source/postprocess/dynamic_topography.cc
  source/postprocess/geoid.cc
  source/postprocess/sea_level.cc
  source/postprocess/visualization/boundary_strain_rate_residual.cc
  source/postprocess/visualization/boundary_velocity_residual.cc
  source/postprocess/visualization/dynamic_topography.cc
  source/postprocess/visualization/geoid.cc
  source/postprocess/visualization/shear_stress.cc
  source/postprocess/visualization/strain_rate.cc
  source/postprocess/visualization/strain_rate_tensor.cc
  source/postprocess/visualization/stress.cc
  source/postprocess/visualization/stress_second_invariant.cc
  source/postprocess/visualization/surface_dynamic_topography.cc
  source/postprocess/visualization/surface_strain_rate_tensor.cc
  source/postprocess/visualization/surface_stress.cc
  source/postprocess/visualization/volumetric_strain_rate.cc
  source/simulator/core.cc
  source/simulator/helper_functions.cc
  source/volume_of_fluid/handler.cc
Labels: ready to test

#5942 Rename (has|get)_matching_plugin_object to just (has|get)_matching_plugin.
  include/aspect/boundary_composition/interface.h
  include/aspect/boundary_temperature/interface.h
  include/aspect/heating_model/interface.h
  include/aspect/initial_composition/interface.h
  include/aspect/initial_temperature/interface.h
  include/aspect/mesh_refinement/interface.h
  include/aspect/particle/property/interface.h
  include/aspect/plugins.h
  include/aspect/postprocess/interface.h
  source/boundary_temperature/dynamic_core.cc
  source/heating_model/interface.cc
  source/particle/property/cpo_bingham_average.cc
  source/particle/property/cpo_elastic_tensor.cc
  source/postprocess/core_statistics.cc
  source/postprocess/crystal_preferred_orientation.cc
  source/postprocess/dynamic_topography.cc
  source/postprocess/geoid.cc
  source/postprocess/sea_level.cc
  source/postprocess/visualization/boundary_strain_rate_residual.cc
  source/postprocess/visualization/boundary_velocity_residual.cc
  source/postprocess/visualization/dynamic_topography.cc
  source/postprocess/visualization/geoid.cc
  source/postprocess/visualization/shear_stress.cc
  source/postprocess/visualization/strain_rate.cc
  source/postprocess/visualization/strain_rate_tensor.cc
  source/postprocess/visualization/stress.cc
  source/postprocess/visualization/stress_second_invariant.cc
  source/postprocess/visualization/surface_dynamic_topography.cc
  source/postprocess/visualization/surface_strain_rate_tensor.cc
  source/postprocess/visualization/surface_stress.cc
  source/postprocess/visualization/volumetric_strain_rate.cc
  source/simulator/core.cc
  source/simulator/helper_functions.cc
  source/volume_of_fluid/handler.cc
  tests/find_boundary_composition_model_fail_1/screen-output
  tests/find_mesh_refinement_fail_1/screen-output
  tests/find_postprocess_fail_1/screen-output
Labels: ready to merge, ready to test

#5944 Avoid generator expression in custom target COMMENT text.
  CMakeLists.txt
Labels: ready to test

#5943 Name executables aspect-debug, aspect-release.
  CMakeLists.txt
Labels: ready to merge, ready to test

#5950 Push the variable that stores the active plugin names down to the base class.
  include/aspect/boundary_composition/interface.h
  include/aspect/boundary_temperature/interface.h
  include/aspect/heating_model/interface.h
  include/aspect/initial_composition/interface.h
  include/aspect/initial_temperature/interface.h
  include/aspect/particle/property/interface.h
  include/aspect/plugins.h
  include/aspect/termination_criteria/interface.h
  source/boundary_composition/interface.cc
  source/boundary_temperature/interface.cc
  source/heating_model/interface.cc
  source/initial_composition/interface.cc
  source/initial_temperature/interface.cc
  source/particle/property/interface.cc
  source/termination_criteria/interface.cc
Labels: ready to test
