Repository geodynamics/aspect, pull requests merged in 2024-12, with the labels that each got.

#6169 Rename phase transition index
  doc/modules/changes/20241201_lhy11009
  include/aspect/material_model/utilities.h
  source/material_model/grain_size.cc
  source/material_model/utilities.cc
  source/material_model/visco_plastic.cc
  tests/composite_viscous_outputs_phases.cc
Labels: ready to test

#6175 Allow recursive includes in parameter files
  benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/input_t.prm
  benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/input_t_gmg.prm
  benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/input_v_gmg.prm
  doc/modules/changes/20241204_gassmoeller
  doc/sphinx/user/run-aspect/parameters-overview/structure.md
  source/main.cc
  tests/include_prm_file.prm
  tests/include_prm_file/original.prm
  tests/include_prm_file/screen-output
  tests/include_prm_file/statistics
  tests/include_prm_file_recursive.prm
  tests/include_prm_file_recursive/original.prm
  tests/include_prm_file_recursive/screen-output
  tests/include_prm_file_recursive/statistics
  tests/original_prm.prm
  tests/original_prm/original.prm
Labels: ready to merge

#6181 sphinx doc: add plugin for svg conversion
  doc/sphinx/conf.py
  doc/sphinx/environment.yml
Labels: documentation, ready to test

#6184 docs: fix links
  CONTRIBUTING.md
  cookbooks/geomio/doc/geomio.md
  cookbooks/multicomponent_steinberger/doc/multicomponent_steinberger.md
  cookbooks/steinberger/doc/steinberger.md
  doc/sphinx/conf.py
  doc/sphinx/references.bib
  doc/sphinx/user/answers.md
  doc/sphinx/user/extending/index.md
  doc/sphinx/user/run-aspect/visualizing-results/index.md
Labels: documentation, ready to test

#6185 www: add 3.0 release
  cite.html
  header.include
  index.html
Labels: www

#6177 Update code style in dynamic core plugin
  include/aspect/boundary_temperature/dynamic_core.h
  source/boundary_temperature/dynamic_core.cc
Labels: ready to merge

#6192 www: update database.js and add 3.0 release stuff
  citing.html
  database.js
Labels: www

#6191 update references to zenodo and manual
  doc/make_cite_html.py
  doc/sphinx/references.bib
Labels: ready to merge

#6194 update release-tasklist
  contrib/release/release-tasklist.md
Labels: ready to merge, ready to test

#6196 Adding final? publications of 2024
  doc/manual/citing_aspect.bib
Labels: ready to merge, ready to test
