Repository geodynamics/aspect, pull requests merged in 2024-10, with the labels that each got.

#6060 Revise the discussion about how plugins work in the documentation.
  doc/sphinx/user/extending/idea-of-plugins.md
Labels: ready to merge

#6061 Update the documentation of plugins (part 1).
  doc/sphinx/user/extending/plugin-types/geometry-models.md
  doc/sphinx/user/extending/plugin-types/gravity-models.md
  doc/sphinx/user/extending/plugin-types/heating-models.md
  doc/sphinx/user/extending/plugin-types/initial-conditions.md
Labels: ready to merge

#5735 Remove detection and driver for parameter GUI.
  CMakeLists.txt
  cmake/write_config.cmake
  doc/aspect-gui
  doc/modules/changes/20240602_tjhei
  doc/sphinx/user/run-aspect/gui/images/aspect-gui.png
  doc/sphinx/user/run-aspect/gui/index.md
  doc/sphinx/user/run-aspect/gui/installing.md
  doc/sphinx/user/run-aspect/gui/using.md
  doc/sphinx/user/run-aspect/index.md
Labels: ready to merge, ready to test

#6065 Update the documentation of plugins (part 2).
  doc/sphinx/user/extending/plugin-types/material-models.md
  doc/sphinx/user/extending/plugin-types/mesh-refinement.md
  doc/sphinx/user/extending/plugin-types/postprocessors.md
  doc/sphinx/user/extending/plugin-types/temp-bc.md
  doc/sphinx/user/extending/plugin-types/terminate-criteria.md
  doc/sphinx/user/extending/plugin-types/velocity-bc.md
  doc/sphinx/user/extending/plugin-types/vis-postprocessors.md
Labels: ready to merge

#6066 Add test for checkpoint/restart multiple particle worlds
  tests/checkpoint_08_particles_multiple_worlds.cc
  tests/checkpoint_08_particles_multiple_worlds.prm
  tests/checkpoint_08_particles_multiple_worlds/log.txt1
  tests/checkpoint_08_particles_multiple_worlds/log.txt2
  tests/checkpoint_08_particles_multiple_worlds/particles-00009.0000.gnuplot1
  tests/checkpoint_08_particles_multiple_worlds/particles-00009.0000.gnuplot2
  tests/checkpoint_08_particles_multiple_worlds/particles-2-00009.0000.gnuplot1
  tests/checkpoint_08_particles_multiple_worlds/particles-2-00009.0000.gnuplot2
  tests/checkpoint_08_particles_multiple_worlds/screen-output
  tests/checkpoint_08_particles_multiple_worlds/statistics1
  tests/checkpoint_08_particles_multiple_worlds/statistics2
Labels: ready to merge

#6069 Qualify round() as std::round().
  source/mesh_deformation/fastscape.cc
  source/particle/generator/uniform_box.cc
  source/particle/generator/uniform_radial.cc
  source/simulator/core.cc
  source/simulator/helper_functions.cc
Labels: ready to test

#6057 fix test for weighted BFBT preconditioner
  tests/nsinker_bfbt.prm
  tests/nsinker_bfbt/screen-output
  tests/nsinker_bfbt/statistics
Labels: ready to merge, ready to test

#6079 update gitignore
  .gitignore
Labels: ready to test

#6077 use correct type for particle counts
  source/postprocess/load_balance_statistics.cc
  source/postprocess/particles.cc
Labels: ready to test

#6076 nsinker benchmark: explicitly specify AMG
  benchmarks/nsinker/nsinker.prm
  benchmarks/nsinker/nsinker_bfbt.prm
  benchmarks/nsinker/nsinker_gmg.prm
  tests/nsinker_amg.cc
  tests/nsinker_amg.prm
  tests/nsinker_amg/screen-output
  tests/nsinker_amg/statistics
Labels: ready to test

#6078 Change Weighted BFBT preconditioner pressure scaling factor
  source/simulator/assemblers/stokes.cc
Labels: ready to test

#6088 Indent doxygen comments
  cookbooks/kinematically_driven_subduction_2d/composition_trms_statistics.h
  cookbooks/kinematically_driven_subduction_2d/isotherm_depth.h
  cookbooks/kinematically_driven_subduction_2d/trench_location.h
  cookbooks/tomography_based_plate_motions/plugins/tomography_based_plate_motions.h
  include/aspect/boundary_composition/spherical_constant.h
  include/aspect/boundary_temperature/spherical_constant.h
  include/aspect/boundary_traction/interface.h
  include/aspect/initial_composition/slab_model.h
  include/aspect/introspection.h
  include/aspect/material_model/reaction_model/grain_size_evolution.h
  include/aspect/material_model/reaction_model/katz2003_mantle_melting.h
  include/aspect/material_model/rheology/peierls_creep.h
  include/aspect/material_model/rheology/strain_dependent.h
  include/aspect/material_model/utilities.h
  include/aspect/melt.h
  include/aspect/mesh_deformation/fastscape.h
  include/aspect/particle/integrator/euler.h
  include/aspect/particle/integrator/interface.h
  include/aspect/particle/interpolator/distance_weighted_average.h
  include/aspect/particle/property/interface.h
  include/aspect/postprocess/ODE_statistics.h
  include/aspect/postprocess/crystal_preferred_orientation.h
  include/aspect/simulator.h
  include/aspect/simulator/assemblers/interface.h
  include/aspect/simulator_access.h
  include/aspect/simulator_signals.h
  include/aspect/time_stepping/repeat_on_nonlinear_fail.h
  include/aspect/utilities.h
Labels: ready to merge, ready to test

#6089 add test for mixed compositions and particles
  tests/continental_extension_mixed_compositions_particles.prm
  tests/continental_extension_mixed_compositions_particles/screen-output
Labels: ready to test

#6102 Fix type mismatch.
  source/particle/manager.cc
Labels: ready to test

#6103 Microscropic clean-ups.
  include/aspect/utilities.h
  source/postprocess/gravity_point_values.cc
  source/postprocess/visualization.cc
  source/utilities.cc
Labels: ready to test

#6095 Convert year to second in the adiabatic profile function
  doc/modules/changes/20241021_ranpengli
  source/adiabatic_conditions/compute_profile.cc
  tests/update_script.prm
  tests/update_script_2.prm
  tests/update_script_2/updated2.prm
Labels: ready to test

#6112 change usage of MPI::broadcast
  source/simulator/parameters.cc
Labels: ready to test

#6113 update README for spherical nsinker benchmark
  benchmarks/nsinker/README.md
  benchmarks/nsinker_spherical_shell/README.md
Labels: ready to test
