Repository geodynamics/aspect, pull requests merged in 2024-02, with the labels that each got.

#5556 Fix the name of a variable.
  source/geometry_model/chunk.cc
Labels: ready to test

#5558 Spell 'Cartesian' with an upper-case C in the documentation.
  source/boundary_traction/initial_lithostatic_pressure.cc
  source/geometry_model/initial_topography_model/function.cc
  source/gravity_model/vertical.cc
  source/initial_composition/slab_model.cc
Labels: ready to test

#5557 Update documentation of a function slightly.
  include/aspect/utilities.h
Labels: ready to test

#5559 Better document and check initial topography models.
  include/aspect/geometry_model/initial_topography_model/interface.h
  source/geometry_model/initial_topography_model/ascii_data.cc
  source/geometry_model/initial_topography_model/function.cc
  source/geometry_model/initial_topography_model/prm_polygon.cc
Labels: ready to test

#5560 Implement calling initial topography models from the spherical shell model.
  source/geometry_model/spherical_shell.cc
Labels: ready to test

#5561 Better document conventions around spherical coordinates.
  include/aspect/utilities.h
  source/geometry_model/chunk.cc
Labels: ready to test

#5564 require CMake 3.3.0
  CMakeLists.txt
  benchmarks/CMakeLists.txt
  benchmarks/advection_in_annulus/CMakeLists.txt
  benchmarks/annulus/plugin/CMakeLists.txt
  benchmarks/blankenbach/plugin/CMakeLists.txt
  benchmarks/burstedde/CMakeLists.txt
  benchmarks/compressibility_formulations/plugins/CMakeLists.txt
  benchmarks/crameri_et_al/case_1/CMakeLists.txt
  benchmarks/davies_et_al/case-2.3-plugin/CMakeLists.txt
  benchmarks/diffusion_of_hill/CMakeLists.txt
  benchmarks/doneahuerta/CMakeLists.txt
  benchmarks/entropy_adiabat/plugins/CMakeLists.txt
  benchmarks/finite_strain/CMakeLists.txt
  benchmarks/hollow_sphere/CMakeLists.txt
  benchmarks/inclusion/CMakeLists.txt
  benchmarks/inclusion/compositional_fields/CMakeLists.txt
  benchmarks/infill_density/CMakeLists.txt
  benchmarks/king2dcompressible/plugin/CMakeLists.txt
  benchmarks/layeredflow/CMakeLists.txt
  benchmarks/newton_solver_benchmark_set/nonlinear_channel_flow/CMakeLists.txt
  benchmarks/newton_solver_benchmark_set/spiegelman_et_al_2016/CMakeLists.txt
  benchmarks/nsinker/CMakeLists.txt
  benchmarks/nsinker_spherical_shell/CMakeLists.txt
  benchmarks/operator_splitting/advection_reaction/CMakeLists.txt
  benchmarks/operator_splitting/exponential_decay/CMakeLists.txt
  benchmarks/rayleigh_taylor_instability/CMakeLists.txt
  benchmarks/rigid_shear/plugin/CMakeLists.txt
  benchmarks/shear_bands/CMakeLists.txt
  benchmarks/sinking_block/CMakeLists.txt
  benchmarks/solcx/CMakeLists.txt
  benchmarks/solcx/compositional_fields/CMakeLists.txt
  benchmarks/solitary_wave/CMakeLists.txt
  benchmarks/solkz/CMakeLists.txt
  benchmarks/solkz/compositional_fields/CMakeLists.txt
  benchmarks/solubility/plugin/CMakeLists.txt
  benchmarks/tangurnis/code/CMakeLists.txt
  benchmarks/time_dependent_annulus/plugin/CMakeLists.txt
  benchmarks/tosi_et_al_2015_gcubed/CMakeLists.txt
  benchmarks/viscosity_grooves/CMakeLists.txt
  benchmarks/yamauchi_takei_2016_anelasticity/CMakeLists.txt
  cookbooks/CMakeLists.txt
  cookbooks/anisotropic_viscosity/CMakeLists.txt
  cookbooks/finite_strain/CMakeLists.txt
  cookbooks/free_surface_with_crust/plugin/CMakeLists.txt
  cookbooks/inner_core_convection/CMakeLists.txt
  cookbooks/magnetic_stripes/CMakeLists.txt
  cookbooks/morency_doin_2004/CMakeLists.txt
  cookbooks/prescribed_velocity/CMakeLists.txt
  cookbooks/prescribed_velocity_ascii_data/CMakeLists.txt
  cookbooks/tomography_based_plate_motions/plugins/CMakeLists.txt
  cookbooks/vankeken_subduction/plugin/CMakeLists.txt
  doc/CMakeLists.txt
  doc/plugin-CMakeLists.txt
  tests/CMakeLists.txt
  tests/run_testsuite.cmake
  unit_tests/CMakeLists.txt
Labels: ready to merge, ready to test

#5563 Implement a 'surface elevation' visualization postprocessor.
  doc/modules/changes/20240204_bangerth
  include/aspect/postprocess/visualization/surface_elevation.h
  source/postprocess/topography.cc
  source/postprocess/visualization/depth.cc
  source/postprocess/visualization/surface_elevation.cc
  tests/surface_elevation_box_ascii_data.prm
  tests/surface_elevation_box_ascii_data/screen-output
  tests/surface_elevation_box_ascii_data/solution/solution_surface-00000.0000.gnuplot
  tests/surface_elevation_box_ascii_data_moved_origin.prm
  tests/surface_elevation_box_ascii_data_moved_origin/screen-output
  tests/surface_elevation_box_ascii_data_moved_origin/solution/solution_surface-00000.0000.gnuplot
  tests/surface_elevation_box_function.prm
  tests/surface_elevation_box_function/screen-output
  tests/surface_elevation_box_function/solution/solution_surface-00000.0000.gnuplot
  tests/surface_elevation_box_prm_polygon.prm
  tests/surface_elevation_box_prm_polygon/screen-output
  tests/surface_elevation_box_prm_polygon/solution/solution_surface-00000.0000.gnuplot
  tests/surface_elevation_chunk_ascii_data.prm
  tests/surface_elevation_chunk_ascii_data/screen-output
  tests/surface_elevation_chunk_ascii_data/solution/solution_surface-00000.0000.gnuplot
  tests/surface_elevation_chunk_ascii_data_3d.prm
  tests/surface_elevation_chunk_ascii_data_3d/screen-output
  tests/surface_elevation_chunk_ascii_data_3d/solution/solution_surface-00000.0000.gnuplot
  tests/surface_elevation_chunk_ascii_data_3d_colatitude.prm
  tests/surface_elevation_chunk_ascii_data_3d_colatitude/screen-output
  tests/surface_elevation_chunk_ascii_data_3d_colatitude/solution/solution_surface-00000.0000.gnuplot
Labels: ready to test

#5367 require SUNDIALS and deal.II 9.5
  .github/workflows/linux.yml
  CMakeLists.txt
  README.md
  cmake/AspectConfig.cmake.in
  contrib/ci/Dockerfile
  contrib/docker/docker/Dockerfile
Labels: ready to merge, ready to test

#5571 Document spherical coordinates better.
  include/aspect/utilities.h
  source/geometry_model/initial_topography_model/ascii_data.cc
  source/utilities.cc
Labels: ready to test

#5572 Import global topography with longitudes 0...2*pi.
  data/geometry-model/initial-topography-model/ascii-data/global_1deg.txt.gz
  data/geometry-model/initial-topography-model/ascii-data/test/shell_3d_outer.0.txt
  data/geometry-model/initial-topography-model/ascii-data/test/shell_3d_outer_2.0.txt
  source/geometry_model/chunk.cc
  tests/chunk_initial_topography_ascii_data_3d/screen-output
  tests/chunk_initial_topography_ascii_data_3d/statistics
  tests/chunk_initial_topography_ascii_data_3d_colatitude/statistics
  tests/surface_elevation_chunk_ascii_data_3d/solution/solution_surface-00000.0000.gnuplot
  tests/surface_elevation_chunk_ascii_data_3d_colatitude/solution/solution_surface-00000.0000.gnuplot
  tests/surface_elevation_chunk_ascii_data_global_3d/solution/solution_surface-00000.0000.gnuplot
Labels: ready to test

#5578 Report World Builder version on model start
  CMakeLists.txt
  source/global.cc
Labels: ready to merge

#5579 Add a changelog.
  doc/modules/changes/20240216_bangerth
Labels: ready to test

#5577 Add the finishing touches on importing global topography.
  source/geometry_model/spherical_shell.cc
  tests/spherical_shell_initial_topography_ascii_data_3d.prm
  tests/spherical_shell_initial_topography_ascii_data_3d/screen-output
  tests/spherical_shell_initial_topography_function_3d.prm
  tests/spherical_shell_initial_topography_function_3d/screen-output
  tests/spherical_shell_initial_topography_function_3d/solution/solution_surface-00000.0000.gnuplot
  tests/surface_elevation_spherical_shell_ascii_data_global_3d.prm
  tests/surface_elevation_spherical_shell_ascii_data_global_3d/screen-output
  tests/surface_elevation_spherical_shell_ascii_data_global_3d/solution/solution_surface-00000.0000.gnuplot
Labels: ready to test
