Repository geodynamics/aspect, pull requests merged in 2024-03, with the labels that each got.

#5598 Add required cmake attribute.
  CMakeLists.txt
Labels: ready to test

#5597 Call non-virtual function.
  source/compat.cc
  tests/spherical_shell_initial_topography_function_3d/solution/solution_surface-00000.0000.gnuplot
  tests/surface_elevation_spherical_shell_ascii_data_global_3d/solution/solution_surface-00000.0000.gnuplot
Labels: ready to test

#5599 fix-declarations
  source/material_model/entropy_model.cc
Labels: ready to test

#5600 Add typos spell checker.
  .github/workflows/typos.yml
  .typos.toml
  CONTRIBUTING.md
  benchmarks/buiter_et_al_2016_jsg/exp_1.prm
  benchmarks/shear_bands/plot_hist_and_porosity.py
  cookbooks/grain_size_ridge/doc/grain_size_ridge.md
  cookbooks/inner_core_convection/doc/inner_core_traction.part.1.prm
  cookbooks/inner_core_convection/inner_core_traction.prm
  cookbooks/steinberger/steinberger.prm
  cookbooks/tomography_based_plate_motions/plugins/tomography_based_plate_motions.cc
  cookbooks/tomography_based_plate_motions/plugins/tomography_based_plate_motions.h
  data/material-model/steinberger/visc.m
  doc/modules/changes/20230718_lhy11009
  doc/modules/to-2.5.0.h
  include/aspect/material_model/utilities.h
  include/aspect/mesh_deformation/fastscape.h
  include/aspect/postprocess/crystal_preferred_orientation.h
  include/aspect/simulator.h
  source/mesh_deformation/fastscape.cc
  source/postprocess/crystal_preferred_orientation.cc
  tests/box_simple_log_viscosity_depth_average.prm
  tests/drucker_prager_derivatives_2d.cc
  tests/drucker_prager_derivatives_3d.cc
  tests/entropy_initial_lookup_wb.wb
  tests/particle_periodic_quarter_shell.prm
  tests/particle_periodic_quarter_shell_2.prm
  tests/traction_multiple_model.prm
  tests/vep_chemical_compositions.prm
  tests/visco_plastic_peierls_mei_viscosity_approx.prm
Labels: ready to test

#5612 Adding new publications for 2024
  doc/manual/citing_aspect.bib
Labels: ready to merge

#5609 Update 'Peierls strain rate residual tolerance'
  doc/sphinx/parameters/Material_20model.md
  source/material_model/diffusion_dislocation.cc
  source/material_model/rheology/peierls_creep.cc
  tests/visco_plastic_peierls_idrissi_exact.prm
  tests/visco_plastic_peierls_mei_exact.prm
  tests/visco_plastic_phases_peierls_mei_exact.prm
Labels: ready to merge, ready to test

#5615 make entropy_reader a vector
  include/aspect/material_model/entropy_model.h
  source/material_model/entropy_model.cc
Labels: ready to merge, ready to test

#5616 Add explicit initialization for initialize_current_linearization_point
  source/simulator/helper_functions.cc
Labels: ready to merge, ready to test

#5596 Update documentation around the issue of topography in some places.
  include/aspect/geometry_model/interface.h
  source/geometry_model/chunk.cc
  source/geometry_model/spherical_shell.cc
Labels: documentation, ready to test

#5617 periodic GMG
  source/simulator/core.cc
  source/simulator/stokes_matrix_free.cc
  tests/periodic_box_gmg.prm
  tests/periodic_box_gmg/screen-output
  tests/periodic_box_gmg/statistics
Labels: ready to test

#5618 VSCode: build configurations
  .vscode/cmake_configurations.json
Labels: ready to test
