Repository geodynamics/aspect, pull requests merged in 2025-06, with the labels that each got.

#6241 Fix Fastscape topography for periodic boundary by setting the values of ghost nodes earlier
  source/mesh_deformation/fastscape.cc
Labels: ready to test

#6313 fix shell-check warnings on indent script
  contrib/utilities/indent
Labels: ready to merge, ready to test

#6242 Fix Typos in postprocess.md
  source/postprocess/crystal_preferred_orientation.cc
Labels: ready to merge, ready to test

#6322 indent comment
  source/mesh_refinement/density.cc
Labels: ready to merge, ready to test

#6329 Python support: add CMake logic
  CMakeLists.txt
Labels: ready to merge, ready to test

#6193 bib: fix fieldstone
  benchmarks/viscosity_grooves/doc/viscosity_grooves.md
  doc/sphinx/references.bib
Labels: ready to merge, ready to test

#6331 avoid unnecessary copy of a Vector
  source/mesh_deformation/diffusion.cc
Labels: ready to merge, ready to test

#6328 Fix formatting of list in "Nullspace removal" documentation.
  source/simulator/parameters.cc
Labels: ready to merge, ready to test

#6333 Particles random number generator fix
  doc/modules/changes/20250610_bakerdunn
  include/aspect/particle/manager.h
  source/particle/manager.cc
  tests/particle_load_balancing_removal/particles/particles-00001.0000.gnuplot
  tests/particle_load_balancing_removal_addition/particles/particles-00001.0000.gnuplot
  tests/particle_load_balancing_removal_addition_properties/particles/particles-00001.0000.gnuplot
  tests/particles_with_AMR_on/screen-output
  tests/particles_with_AMR_on/statistics
  tests/visco_plastic_vep_stress_build-up_yield_particles/screen-output
  tests/visco_plastic_vep_stress_build-up_yield_particles/statistics
  tests/viscoelastic_bending_beam_particles/screen-output
  tests/viscoelastic_bending_beam_particles/statistics
  tests/viscoelastic_numerical_elastic_time_step_particles/screen-output
  tests/viscoelastic_numerical_elastic_time_step_particles/statistics
Labels: ready to merge, ready to test

#6339 fix a typo in seismic anomaly postprocessor
  source/postprocess/visualization/seismic_anomalies.cc
Labels: ready to merge, ready to test

#6307 Add support for spherical coordinate system in initial topography function
  doc/modules/changes/20250609_tiannh
  source/geometry_model/initial_topography_model/function.cc
  tests/spherical_shell_initial_topography_function_3d_spherical.prm
  tests/spherical_shell_initial_topography_function_3d_spherical/screen-output
  tests/spherical_shell_initial_topography_function_3d_spherical/statistics
Labels: ready to merge, ready to test

#6320 removed deprecated input options
  source/postprocess/visualization.cc
Labels: ready to merge, ready to test

#6348 Remove the unused function, get_radius()
  include/aspect/geometry_model/chunk.h
  include/aspect/geometry_model/ellipsoidal_chunk.h
  source/geometry_model/chunk.cc
  source/geometry_model/ellipsoidal_chunk.cc
Labels: ready to merge, ready to test

#6343 Multicomponent compressible Equation of state cleanup
  source/material_model/equation_of_state/multicomponent_compressible.cc
Labels: ready to merge, ready to test

#6345 Update some commentary in chunk.cc.
  source/geometry_model/chunk.cc
Labels: ready to test

#6357 Mark input variables of a function as 'const'.
  include/aspect/mesh_deformation/fastscape.h
  source/mesh_deformation/fastscape.cc
Labels: ready to merge, ready to test

#6358 Clean up copying a table somewhat.
  source/mesh_deformation/fastscape.cc
Labels: ready to merge, ready to test

#6359 Optimize returning a potentially large table.
  source/mesh_deformation/fastscape.cc
Labels: ready to merge, ready to test

#6361 Minor clean-up of the FastScape configuration bits.
  CMakeLists.txt
Labels: ready to merge, ready to test

#6369 Mark some functions in the test suite with 'override'.
  tests/additional_outputs_02.cc
  tests/additional_outputs_03.cc
  tests/heat_advection_by_melt.cc
Labels: ready to merge, ready to test

#6354 Add a test for 2d shell with initial topography.
  source/geometry_model/spherical_shell.cc
  tests/spherical_shell_initial_topography_function_2d_spherical.prm
  tests/spherical_shell_initial_topography_function_2d_spherical/screen-output
  tests/spherical_shell_initial_topography_function_2d_spherical/solution/solution_surface-00000.0000.gnuplot
  tests/spherical_shell_initial_topography_function_2d_spherical/statistics
Labels: ready to merge, ready to test

#6364 implement range-based for loop with index
  source/postprocess/visualization/heating.cc
Labels: ready to merge, ready to test

#6360 Replicate a data structure across processes using shared memory rather than MPI_Broadcast.
  source/mesh_deformation/fastscape.cc
Labels: ready to merge, ready to test

#6370 Fix list in Temperature field documentation.
  source/simulator/parameters.cc
Labels: ready to merge, ready to test

#6371 Fix Instantiation of OperatorCellData
  source/simulator/solver/matrix_free_operators.cc
Labels: bug, ready to merge, ready to test

#6382 Remove a comment that's now no longer correct.
  include/aspect/material_model/interface.h
Labels: ready to merge, ready to test

#6393 include FASTSCAPE info in detailed.log
  cmake/write_config.cmake
Labels: ready to test

#6353 Update temperature field after entropy is solved
  source/simulator/solver_schemes.cc
  tests/entropy_adiabat/screen-output
  tests/entropy_adiabat/statistics
  tests/entropy_conduction/screen-output
  tests/entropy_conduction/statistics
  tests/entropy_half_space/screen-output
  tests/entropy_half_space/statistics
  tests/entropy_initial_lookup/screen-output
  tests/entropy_initial_lookup_wb/screen-output
  tests/entropy_initial_lookup_wb/statistics
  tests/entropy_plasticity/screen-output
  tests/entropy_plasticity/statistics
Labels: ready to merge, ready to test

#6390 Use the more modern version of MPI::broadcast().
  source/simulator/parameters.cc
Labels: ready to merge, ready to test

#6391 range-based for loop, bilinear_least_squares:81, 208
  source/particle/interpolator/bilinear_least_squares.cc
Labels: ready to merge, ready to test

#6397 Fix list in documentation for compositional fields.
  source/simulator/parameters.cc
Labels: ready to merge, ready to test

#6398 Convert a couple more loops to range-based format.
  source/postprocess/interface.cc
  source/postprocess/visualization.cc
Labels: ready to merge, ready to test

#6401 Some more cleanup of CMakeLists.txt.
  CMakeLists.txt
Labels: ready to merge, ready to test

#6399 Better error message for fastscape detection.
  CMakeLists.txt
Labels: ready to merge, ready to test

#6408 Add fastscape test
  tests/fastscape_1.prm
  tests/fastscape_1/screen-output
  tests/fastscape_1/topography.00000
  tests/fastscape_1/topography.00001
  tests/fastscape_1/topography.00002
Labels: ready to merge, ready to test

#6405 Convert friction coeff into angles of internal friction
  contrib/python/scripts/convert_friction_coeff_into_angles_of_internal_friction.py
Labels: ready to merge, ready to test

#6374 Modify depths in presence of topography in chunk.
  include/aspect/geometry_model/chunk.h
  source/geometry_model/chunk.cc
  tests/chunk_initial_topography_ascii_data/screen-output
  tests/chunk_initial_topography_ascii_data/statistics
  tests/chunk_initial_topography_ascii_data_3d/screen-output
  tests/chunk_initial_topography_ascii_data_3d/statistics
  tests/chunk_initial_topography_ascii_data_3d_colatitude/screen-output
  tests/chunk_initial_topography_ascii_data_3d_colatitude/statistics
  tests/chunk_lithostatic_pressure_2d_initial_topography/screen-output
  tests/chunk_lithostatic_pressure_2d_initial_topography/solution/solution-00000.0000.gnuplot
  tests/chunk_lithostatic_pressure_2d_initial_topography/statistics
Labels: ready to merge, ready to test

#6372 Add Particle histogram postprocessor
  doc/modules/changes/20250613_bakerdunn
  include/aspect/postprocess/particle_distribution_score.h
  source/postprocess/particle_distribution_score.cc
  tests/particle_distribution_score.prm
  tests/particle_distribution_score/screen-output
  tests/particle_distribution_score/statistics
  tests/particle_distribution_score_3d.prm
  tests/particle_distribution_score_3d/screen-output
  tests/particle_distribution_score_3d/statistics
Labels: ready to merge, ready to test

#6412 Add density anomaly postprocessor
  doc/modules/changes/20250613_rhino1999
  include/aspect/lateral_averaging.h
  include/aspect/postprocess/visualization/density_anomaly.h
  source/postprocess/visualization/density_anomaly.cc
  source/simulator/lateral_averaging.cc
  tests/visualization_density_anomaly_1.prm
  tests/visualization_density_anomaly_1/screen-output
  tests/visualization_density_anomaly_1/solution/solution-00000.0000.gnuplot
  tests/visualization_density_anomaly_2.prm
  tests/visualization_density_anomaly_2/screen-output
  tests/visualization_density_anomaly_2/solution/solution-00000.0000.gnuplot
Labels: ready to merge, ready to test

#6400 Depth with deformation postprocessor
  doc/modules/changes/20250613_neuharth
  include/aspect/postprocess/current_surface.h
  include/aspect/postprocess/visualization/depth_including_mesh_deformation.h
  source/postprocess/current_surface.cc
  source/postprocess/visualization/depth_including_mesh_deformation.cc
  tests/depth_with_mesh_deformation.prm
  tests/depth_with_mesh_deformation/screen-output
  tests/depth_with_mesh_deformation/solution/solution-00000.0000.gnuplot
  tests/depth_with_mesh_deformation/solution/solution-00001.0000.gnuplot
Labels: ready to test

#6426 Declare the existence of explicit specializations.
  include/aspect/volume_of_fluid/handler.h
Labels: ready to test

#6416 No longer exclude volume_of_fluid/handler.cc from the unity builds.
  CMakeLists.txt
Labels: ready to test

#6429 Fix some typos
  doc/modules/to-2.0.0.h
  source/postprocess/composition_velocity_statistics.cc
Labels: ready to merge, ready to test

#6428 Fix list formatting for "refinement criteria merge operation"
  source/mesh_refinement/interface.cc
Labels: ready to merge, ready to test

#6431 Some more consistency for function plugins
  include/aspect/boundary_composition/function.h
  include/aspect/boundary_heat_flux/function.h
  include/aspect/boundary_temperature/function.h
  include/aspect/boundary_traction/function.h
  include/aspect/boundary_velocity/function.h
  include/aspect/gravity_model/function.h
  include/aspect/initial_composition/function.h
  include/aspect/initial_temperature/function.h
  source/boundary_composition/function.cc
  source/boundary_heat_flux/function.cc
  source/boundary_temperature/function.cc
  source/boundary_traction/function.cc
  source/boundary_velocity/function.cc
  source/geometry_model/initial_topography_model/function.cc
  source/gravity_model/function.cc
  source/initial_composition/function.cc
  source/initial_temperature/function.cc
Labels: ready to merge, ready to test

#6423 Following PR #6402: Add two seismic anomalies test
  tests/visualization_seismic_anomalies_1.prm
  tests/visualization_seismic_anomalies_1/screen-output
  tests/visualization_seismic_anomalies_1/solution/solution-00000.0000.gnuplot
  tests/visualization_seismic_anomalies_2.prm
  tests/visualization_seismic_anomalies_2/screen-output
  tests/visualization_seismic_anomalies_2/solution/solution-00000.0000.gnuplot
Labels: ready to merge, ready to test

#6430 Only link against gfortran when necessary.
  CMakeLists.txt
Labels: ready to merge, ready to test

#6436 Minor updates to tests/CMakeLists.txt.
  tests/CMakeLists.txt
Labels: ready to test

#6075 Account for the Darcy Velocity and/or the Fluid Velocity when Determining Outflow Boundaries
  doc/modules/changes/20241024_danieldouglas92
  include/aspect/simulator.h
  source/simulator/core.cc
  source/simulator/helper_functions.cc
  tests/darcy_convection_step.prm
  tests/darcy_outflow.prm
  tests/darcy_outflow/screen-output
  tests/darcy_outflow/statistics
  tests/fluid_outflow.prm
  tests/fluid_outflow/screen-output
  tests/fluid_outflow/statistics
  tests/no_dirichlet_on_outflow_melt/screen-output
  tests/no_dirichlet_on_outflow_melt/statistics
  tests/prescribed_velocity_boundary/screen-output
Labels: ready to test

#6433 Add astyle example usage to CONTRIBUTING.md docs
  CONTRIBUTING.md
Labels: ready to merge, ready to test

#6441 Disentangle the bottom of CMakeLists.txt.
  CMakeLists.txt
Labels: ready to test

#6448 ignore all .DS_Store files in all directories
  .gitignore
Labels: ready to merge, ready to test

#6413 Save rotation matrix again after projection and correction
  source/particle/property/crystal_preferred_orientation.cc
  tests/cpo_karato_simple_shearbox/particles/particles-00000.0000.gnuplot
  tests/cpo_karato_simple_shearbox/particles/particles-00001.0000.gnuplot
  tests/cpo_simple_shearbox/particles/particles-00001.0000.gnuplot
  tests/cpo_simple_shearbox/particles/particles-00002.0000.gnuplot
  tests/cpo_simple_shearbox/particles_cpo/CPO-00001.0000.dat
  tests/cpo_simple_shearbox/particles_cpo/CPO-00002.0000.dat
  tests/cpo_simple_shearbox/particles_cpo/particles-00001.0000.dat
  tests/cpo_simple_shearbox/particles_cpo/particles-00002.0000.dat
  tests/cpo_simple_shearbox/particles_cpo/weighted_CPO-00001.0000.dat
  tests/cpo_simple_shearbox/particles_cpo/weighted_CPO-00002.0000.dat
Labels: ready to test

#6447 Fix incorrect test name
  tests/chunk_lithostatic_pressure_2d_initial_topography.prm
  tests/chunk_lithostatic_pressure_3d.prm
  tests/chunk_lithostatic_pressure_3d/screen-output
  tests/chunk_lithostatic_pressure_3d/solution/solution-00000.0000.gnuplot
  tests/chunk_lithostatic_pressure_3d/statistics
Labels: ready to merge, ready to test

#6427 Use target_include_directories() instead of include_directories().
  CMakeLists.txt
  cmake/AspectConfig.cmake.in
Labels: ready to test

#6451 Tell plugins where to find WorldBuilder headers.
  cmake/AspectConfig.cmake.in
Labels: ready to merge, ready to test

#6453 Adding lines to tidal heating test .prm file
  tests/constant_tidal_heating.prm
Labels: ready to merge, ready to test

#6456 cpo: slip_cross_product --> slip_outer_product
  source/particle/property/crystal_preferred_orientation.cc
Labels: ready to merge, ready to test

#6381 Add Fluid Velocity Statistics Postprocessor
  doc/modules/changes/20250612_danieldouglas92
  include/aspect/postprocess/fluid_velocity_statistics.h
  source/postprocess/fluid_velocity_statistics.cc
  tests/darcy_convection_step.prm
  tests/darcy_convection_step/screen-output
  tests/darcy_convection_step/statistics
  tests/melt_velocity_postprocessor.prm
  tests/melt_velocity_postprocessor/screen-output
  tests/melt_velocity_postprocessor/statistics
Labels: ready to merge, ready to test

#6449 Avoid direct MPI calls in the sea level postprocessor.
  source/postprocess/sea_level.cc
Labels: ready to merge, ready to test

#6460 Update some commentary in CMakeLists.txt.
  CMakeLists.txt
Labels: ready to merge, ready to test

#6458 Found 3 new publications for 2020
  doc/manual/citing_aspect.bib
Labels: ready to merge, ready to test

#6463 Shuffle around the remaining cmake bits not already in their right place.
  CMakeLists.txt
Labels: ready to merge, ready to test

#6373 Implementation of plastic dilation
  doc/modules/changes/20250616_yiminjin
  include/aspect/material_model/interface.h
  include/aspect/material_model/rheology/drucker_prager.h
  include/aspect/material_model/rheology/visco_plastic.h
  include/aspect/newton.h
  include/aspect/simulator/assemblers/stokes.h
  include/aspect/simulator/solver/matrix_free_operators.h
  source/material_model/interface.cc
  source/material_model/rheology/drucker_prager.cc
  source/material_model/rheology/visco_plastic.cc
  source/material_model/visco_plastic.cc
  source/simulator/assemblers/newton_stokes.cc
  source/simulator/assemblers/stokes.cc
  source/simulator/assembly.cc
  source/simulator/core.cc
  source/simulator/newton.cc
  source/simulator/solver/matrix_free_operators.cc
  source/simulator/solver/stokes_matrix_free_local_smoothing.cc
  tests/kaus_2010_with_plastic_dilation.prm
  tests/kaus_2010_with_plastic_dilation/screen-output
  tests/kaus_2010_with_plastic_dilation/statistics
  tests/matrix_nonzeros_4/statistics
  tests/matrix_nonzeros_5/statistics
  tests/matrix_nonzeros_6/statistics
  tests/matrix_nonzeros_7/statistics
  tests/prescribed_dilation.cc
  tests/prescribed_dilation/screen-output
  tests/prescribed_dilation_gmg/screen-output
  tests/prescribed_dilation_newton/screen-output
  tests/prescribed_dilation_newton/statistics
  tests/prescribed_dilation_newton_singleadvection/screen-output
  tests/prescribed_dilation_newton_singleadvection/statistics
  tests/spherical_nsinker/statistics
  tests/visco_plastic_newton_nonlinear_channelflow/screen-output
Labels: ready to test

#6467 Substantially simplify some MPI code.
  source/main.cc
Labels: ready to merge, ready to test

#6459 Discuss some more aspects of 2d models.
  doc/sphinx/user/methods/basic-equations/2d-models.md
Labels: ready to merge, ready to test

#6477 Convert percent to fraction in Geodynamic WorldBuilder
  contrib/world_builder/source/world_builder/features/oceanic_plate_models/composition/tian2019_water_content.cc
  contrib/world_builder/source/world_builder/features/subducting_plate_models/composition/tian2019_water_content.cc
Labels: ready to test

#6478 Add 4 publications from scix for 2022
  doc/manual/citing_aspect.bib
Labels: ready to merge, ready to test

#6446 Add CPO serialization.
  doc/modules/changes/20250616_mfraters
  include/aspect/postprocess/crystal_preferred_orientation.h
  source/postprocess/crystal_preferred_orientation.cc
Labels: ready to merge, ready to test

#6376 Add sea level curve function
  doc/modules/changes/20250616_xlia62
  include/aspect/mesh_deformation/fastscape.h
  source/mesh_deformation/fastscape.cc
  tests/fastscape_sea_level_function.prm
  tests/fastscape_sea_level_function/fastscape/SeaLevel0000000.vtk
  tests/fastscape_sea_level_function/fastscape/SeaLevel0000025.vtk
  tests/fastscape_sea_level_function/log.txt
  tests/fastscape_sea_level_function/statistics
Labels: ready to merge, ready to test

#6469 Add a reaction model and particle property that allows for the generation of crust and lithosphere
  doc/modules/changes/20250616_jdannberg
  include/aspect/material_model/reaction_model/crust_and_lithosphere_formation.h
  include/aspect/particle/property/crust_and_lithosphere_formation.h
  source/material_model/reaction_model/crust_and_lithosphere_formation.cc
  source/particle/property/crust_and_lithosphere_formation.cc
  tests/crustal_formation_particles.prm
  tests/crustal_formation_particles/screen-output
  tests/crustal_formation_particles/statistics
Labels: ready to merge

#6487 check that plugins implement the advection_field_for_boundary_initialization function
  source/particle/property/interface.cc
Labels: ready to merge, ready to test

#6484 Avoid yet more direct MPI calls.
  source/utilities.cc
Labels: ready to merge, ready to test

#6480 improve the documentation of the strain_rate postprocessor
  source/postprocess/visualization/strain_rate.cc
Labels: ready to test

#6489 Allow sea level function defined in seconds
  source/mesh_deformation/fastscape.cc
Labels: ready to merge, ready to test

#6490 for_loop_range-based_rk_2.cc:83
  source/particle/integrator/rk_2.cc
Labels: ready to merge, ready to test

#6491 for_loop_range-based_manager:436
  source/particle/manager.cc
Labels: ready to merge, ready to test

#6499 Update citation format for documentation.
  source/simulator/parameters.cc
Labels: ready to merge, ready to test

#6496 Simplify a call to MPI_Scan using deal.II facilities.
  source/particle/manager.cc
Labels: ready to test

#6472 Add fastscape-fortran checkpointing
  include/aspect/mesh_deformation/fastscape.h
  include/aspect/mesh_deformation/interface.h
  source/mesh_deformation/fastscape.cc
  source/mesh_deformation/interface.cc
  source/simulator/checkpoint_restart.cc
Labels: ready to merge, ready to test

#6501 Remove usage of deprecated name
  benchmarks/compressibility_formulations/plugins/compressibility_formulations.cc
  source/material_model/equation_of_state/multicomponent_compressible.cc
  source/material_model/multicomponent_compressible.cc
  tests/check_compositional_field_functions.cc
  tests/check_compositional_field_names.cc
Labels: ready to merge, ready to test

#6503 Use lower-case spelling in CMakeLists.txt.
  doc/plugin-CMakeLists.txt
Labels: ready to merge, ready to test

#6432 Add initial kinetic driving force cookbook
  cookbooks/phase_transition_kinetics/CMakeLists.txt
  cookbooks/phase_transition_kinetics/doc/phase-transition-kinetics.md
  cookbooks/phase_transition_kinetics/doc/simple-subduction-Q10-evolution.png
  cookbooks/phase_transition_kinetics/doc/simple-subduction-Q9-evolution.png
  cookbooks/phase_transition_kinetics/doc/thermodynamic-driving-force-olivine-wadsleyite.png
  cookbooks/phase_transition_kinetics/phase-transition-kinetics.cc
  cookbooks/phase_transition_kinetics/phase-transition-kinetics.h
  cookbooks/phase_transition_kinetics/simple-subduction.prm
  cookbooks/phase_transition_kinetics/thermodynamic-driving-force-profile-olivine-wadsleyite.txt
  doc/modules/changes/20250614_buchanankerswell
  doc/sphinx/references.bib
  doc/sphinx/user/cookbooks/geophysical-setups.md
  tests/phase_transition_kinetics.cc
  tests/phase_transition_kinetics.prm
  tests/phase_transition_kinetics/screen-output
  tests/phase_transition_kinetics/statistics
Labels: ready to merge, ready to test

#6482 Adding latitudinal variation to Tidal heating model
  doc/modules/changes/20250613_hyunseong96
  include/aspect/heating_model/tidal_heating.h
  source/heating_model/tidal_heating.cc
  tests/tidal_heating_latitude.prm
  tests/tidal_heating_latitude/screen-output
  tests/tidal_heating_latitude/statistics
Labels: ready to merge, ready to test

#6511 for_loop_range-based_rk_4.cc:93
  source/particle/integrator/rk_4.cc
Labels: ready to merge, ready to test

#6457 add function of bedrock_river_incision_rate (Kf) and bedrock_transport_coefficient (Kd)
  doc/modules/changes/20250617_xlia62
  include/aspect/mesh_deformation/fastscape.h
  source/mesh_deformation/fastscape.cc
  tests/fastscape_kf_function.prm
  tests/fastscape_kf_function/fastscape/Topography0000000.vtk
  tests/fastscape_kf_function/fastscape/Topography0000025.vtk
  tests/fastscape_kf_function/log.txt
  tests/fastscape_kf_function/statistics
Labels: ready to merge, ready to test

#6479 Add Drucker-Prager plasticity to Steinberger model
  data/material-model/steinberger/test-steinberger-compressible/test-radial-visc-higher.txt
  doc/modules/changes/20250617_rhino1999
  include/aspect/material_model/steinberger.h
  source/material_model/steinberger.cc
  tests/steinberger_plasticity_1.prm
  tests/steinberger_plasticity_1/screen-output
  tests/steinberger_plasticity_1/solution/solution-00000.0000.gnuplot
  tests/steinberger_plasticity_1/statistics
  tests/steinberger_plasticity_2.prm
  tests/steinberger_plasticity_2/screen-output
  tests/steinberger_plasticity_2/solution/solution-00000.0000.gnuplot
  tests/steinberger_plasticity_2/statistics
Labels: ready to test

#6513 Modify the depths in merged chunks to account for initial topo.
  source/geometry_model/initial_topography_model/ascii_data.cc
  source/geometry_model/two_merged_chunks.cc
Labels: ready to merge, ready to test

#6510 for_loop_range-based_quadratic_least.cc:482
  source/particle/interpolator/quadratic_least_squares.cc
Labels: ready to merge, ready to test

#6507 Add an assert for clarity and ascii data topography.
  include/aspect/geometry_model/ellipsoidal_chunk.h
  source/geometry_model/ellipsoidal_chunk.cc
  source/geometry_model/initial_topography_model/prm_polygon.cc
  tests/ellipsoidal_chunk_topography/solution/solution-00000.0000.gnuplot
Labels: ready to merge, ready to test

#6335 Enable phase transitions in multicomponent compressible
  doc/modules/changes/20250613_naliboff
  include/aspect/material_model/equation_of_state/multicomponent_compressible.h
  include/aspect/material_model/multicomponent_compressible.h
  source/material_model/equation_of_state/multicomponent_compressible.cc
  source/material_model/multicomponent_compressible.cc
  tests/multicomponent_compressible_averaging_phases_no-change.prm
  tests/multicomponent_compressible_averaging_phases_no-change/screen-output
  tests/multicomponent_compressible_averaging_phases_no-change/solution/solution-00000.0000.gnuplot
  tests/multicomponent_compressible_averaging_phases_no-change/statistics
  tests/multicomponent_compressible_phases_compositions_box.prm
  tests/multicomponent_compressible_phases_compositions_box/screen-output
  tests/multicomponent_compressible_phases_compositions_box/solution/solution-00000.0000.gnuplot
  tests/multicomponent_compressible_phases_compositions_box/statistics
Labels: ready to test

#6518 Split manual sections into individual pages.
  doc/sphinx/user/methods/basic-equations/2d-models.md
  doc/sphinx/user/methods/basic-equations/comments.md
  doc/sphinx/user/methods/basic-equations/index.md
Labels: ready to merge, ready to test

#6502 Scale reactions by reaction-fluid time scale
  source/material_model/reactive_fluid_transport.cc
  tests/coupled_two_phase_tian_parameterization_kinematic_slab/screen-output
  tests/coupled_two_phase_tian_parameterization_kinematic_slab/solution/solution-00001.0000.gnuplot
  tests/coupled_two_phase_tian_parameterization_kinematic_slab/statistics
  tests/tian_MORB/screen-output
  tests/tian_MORB/statistics
  tests/tian_gabbro/screen-output
  tests/tian_gabbro/statistics
  tests/tian_peridotite/screen-output
  tests/tian_peridotite/statistics
  tests/tian_sediment/screen-output
  tests/tian_sediment/statistics
  tests/tian_water_mass_conservation.prm
  tests/tian_water_mass_conservation/screen-output
  tests/uncoupled_two_phase_tian_parameterization_kinematic_slab/screen-output
  tests/uncoupled_two_phase_tian_parameterization_kinematic_slab/statistics
Labels: ready to test

#6523 for_loop_range-based_interface.cc:64
  source/mesh_refinement/interface.cc
Labels: ready to merge, ready to test

#6522 Convert one more loop.
  source/geometry_model/two_merged_chunks.cc
Labels: ready to merge, ready to test

#6508 Add lithosphere computation as a function.
  cookbooks/tomography_based_plate_motions/plugins/tomography_based_plate_motions.cc
  cookbooks/tomography_based_plate_motions/plugins/tomography_based_plate_motions.h
Labels: ready to merge, ready to test

#6520 Units and equations format fixed for postprocessor in the manual.
  source/postprocess/dynamic_topography.cc
  source/postprocess/visualization/ISA_rotation_timescale.cc
  source/postprocess/visualization/adiabat.cc
  source/postprocess/visualization/artificial_viscosity.cc
  source/postprocess/visualization/artificial_viscosity_composition.cc
  source/postprocess/visualization/depth.cc
  source/postprocess/visualization/dynamic_topography.cc
  source/postprocess/visualization/geoid.cc
  source/postprocess/visualization/grain_lag_angle.cc
  source/postprocess/visualization/gravity.cc
  source/postprocess/visualization/heat_flux_map.cc
  source/postprocess/visualization/heating.cc
  source/postprocess/visualization/maximum_horizontal_compressive_stress.cc
  source/postprocess/visualization/melt_fraction.cc
  source/postprocess/visualization/nonadiabatic_pressure.cc
  source/postprocess/visualization/nonadiabatic_temperature.cc
  source/postprocess/visualization/principal_stress.cc
  source/postprocess/visualization/shear_stress.cc
  source/postprocess/visualization/strain_rate.cc
  source/postprocess/visualization/stress.cc
  source/postprocess/visualization/stress_second_invariant.cc
  source/postprocess/visualization/surface_dynamic_topography.cc
  source/postprocess/visualization/surface_elevation.cc
  source/postprocess/visualization/surface_strain_rate_tensor.cc
  source/postprocess/visualization/surface_stress.cc
  source/postprocess/visualization/temperature_anomaly.cc
  source/postprocess/visualization/vertical_heat_flux.cc
  source/postprocess/visualization/volumetric_strain_rate.cc
Labels: ready to merge, ready to test

#6526 Merge duplicate update functions in fastscape-fortran
  include/aspect/mesh_deformation/fastscape.h
  source/mesh_deformation/fastscape.cc
Labels: ready to merge, ready to test

#6515 Add some compatibility classes.
  include/aspect/compat.h
Labels: ready to test

#6443 Kernel density postprocessor & test case
  doc/modules/changes/20250619_bakerdunn
  include/aspect/postprocess/particle_distribution_statistics.h
  include/aspect/postprocess/particle_pdf.h
  source/postprocess/particle_distribution_statistics.cc
  source/postprocess/particle_pdf.cc
  tests/particle_distribution_statistics.prm
  tests/particle_distribution_statistics/screen-output
  tests/particle_distribution_statistics/statistics
  tests/particle_distribution_statistics_per_particle.prm
  tests/particle_distribution_statistics_per_particle/screen-output
  tests/particle_distribution_statistics_per_particle/statistics
  tests/particle_distribution_statistics_singlecell.prm
  tests/particle_distribution_statistics_singlecell/screen-output
  tests/particle_distribution_statistics_singlecell/statistics
Labels: ready to merge, ready to test

#6517 Add documentation on installing and linking fastscape-fortran to ASPECT
  doc/sphinx/user/install/local-installation/fastscape.md
  doc/sphinx/user/install/local-installation/index.md
  doc/sphinx/user/install/local-installation/obtaining.md
Labels: ready to merge, ready to test

#6529 Adds 7 more publications in 2024 from scix
  doc/manual/citing_aspect.bib
Labels: ready to merge, ready to test

#6530 Change arguments of viscosity function
  include/aspect/material_model/steinberger.h
  source/material_model/steinberger.cc
Labels: ready to merge, ready to test

#6532 Remove an invalid escape sequence.
  source/mesh_deformation/fastscape.cc
Labels: ready to merge, ready to test

#6533 Convert an enum to an enum class.
  include/aspect/mesh_deformation/fastscape.h
  source/mesh_deformation/fastscape.cc
Labels: ready to merge, ready to test

#6536 Simplify some macros
  source/material_model/reaction_model/grain_size_evolution.cc
  source/material_model/reaction_model/katz2003_mantle_melting.cc
  source/material_model/reaction_model/tian2019_solubility.cc
  source/material_model/rheology/ascii_depth_profile.cc
  source/material_model/rheology/composite_visco_plastic.cc
  source/material_model/rheology/compositional_viscosity_prefactors.cc
  source/material_model/rheology/constant_viscosity_prefactors.cc
  source/material_model/rheology/diffusion_creep.cc
  source/material_model/rheology/diffusion_dislocation.cc
  source/material_model/rheology/dislocation_creep.cc
  source/material_model/rheology/drucker_prager.cc
  source/material_model/rheology/drucker_prager_power.cc
  source/material_model/rheology/frank_kamenetskii.cc
  source/material_model/rheology/friction_models.cc
  source/material_model/rheology/peierls_creep.cc
  source/material_model/rheology/strain_dependent.cc
Labels: ready to merge, ready to test

#6395 adding a cookbook based on Burchardt et all 2012 on sinking anhydrite…
  cookbooks/sinking_of_anhydrite_block_in_salt_diapir/doc/diapir.png
  cookbooks/sinking_of_anhydrite_block_in_salt_diapir/doc/results.png
  cookbooks/sinking_of_anhydrite_block_in_salt_diapir/doc/setup.png
  cookbooks/sinking_of_anhydrite_block_in_salt_diapir/doc/setups.png
  cookbooks/sinking_of_anhydrite_block_in_salt_diapir/doc/sinking_of_anhydrite_block_in_salt_diapir.md
  cookbooks/sinking_of_anhydrite_block_in_salt_diapir/sinking_of_anhydrite_block_in_salt_diapir.prm.base
  cookbooks/sinking_of_anhydrite_block_in_salt_diapir/sinking_of_anhydrite_block_in_salt_diapir_particle_in_cell.prm
  doc/modules/changes/20250615_thieulot
  doc/sphinx/references.bib
  doc/sphinx/user/cookbooks/geophysical-setups.md
  tests/cookbook_sinking_anhydrite_block.prm
  tests/cookbook_sinking_anhydrite_block/screen-output
  tests/cookbook_sinking_anhydrite_block/statistics
Labels: ready to merge, ready to test

#6538 Do not store duplicate information. Also, don't mis-use it.
  include/aspect/postprocess/crystal_preferred_orientation.h
  source/postprocess/crystal_preferred_orientation.cc
Labels: ready to merge, ready to test

#6537 Derive VectorFunctionFromVelocityFunctionObject from VectorFunctionFromTensorFunctionObject.
  include/aspect/utilities.h
  source/utilities.cc
Labels: ready to merge, ready to test

#6439 Tomography based mantle convection model cookbook
  cookbooks/tomography_based_plate_motions/2D_slice_with_faults_slabs_and_topo.prm
  cookbooks/tomography_based_plate_motions/doc/Fig_flow_around_slabs.png
  cookbooks/tomography_based_plate_motions/doc/Fig_high_res_surface_deformation.png
  cookbooks/tomography_based_plate_motions/doc/Fig_topography_test.png
  cookbooks/tomography_based_plate_motions/doc/tomography_based_plate_motions-2.part.prm
  cookbooks/tomography_based_plate_motions/doc/tomography_based_plate_motions.md
  cookbooks/tomography_based_plate_motions/input_data/input_topography_smooth_gauss.txt
  cookbooks/tomography_based_plate_motions/input_data/slab2_depth_thickness_2D.txt.gz
  cookbooks/tomography_based_plate_motions/plugins/tomography_based_plate_motions.cc
  cookbooks/tomography_based_plate_motions/plugins/tomography_based_plate_motions.h
  doc/modules/changes/20250619_alarshi
  doc/sphinx/references.bib
  tests/tomography_based_plate_motions_cookbook-2.cc
  tests/tomography_based_plate_motions_cookbook-2.prm
  tests/tomography_based_plate_motions_cookbook-2/screen-output
  tests/tomography_based_plate_motions_cookbook-2/solution/solution-00000.0000.gnuplot
  tests/tomography_based_plate_motions_cookbook-2/solution/solution_surface-00000.0000.gnuplot
  tests/tomography_based_plate_motions_cookbook-2/statistics
  tests/tomography_based_plate_motions_cookbook.prm
  tests/tomography_based_plate_motions_cookbook/solution/solution-00000.0000.gnuplot
Labels: ready to merge, ready to test

#6512 Update fastscape-fortran ghost nodes to fix boundary issues
  source/mesh_deformation/fastscape.cc
  tests/fastscape_test_fixed_ghost_nodes.prm
  tests/fastscape_test_fixed_ghost_nodes/screen-output
  tests/fastscape_test_fixed_ghost_nodes/topography.00000
  tests/fastscape_test_fixed_ghost_nodes/topography.00005
  tests/fastscape_test_open_ghost_nodes.prm
  tests/fastscape_test_open_ghost_nodes/screen-output
  tests/fastscape_test_open_ghost_nodes/topography.00000
  tests/fastscape_test_open_ghost_nodes/topography.00005
Labels: ready to merge, ready to test

#6486 Add Tests for Melt Fractions and Mass Conservation -> Reactive Fluid Transport
  source/material_model/reaction_model/tian2019_solubility.cc
  tests/reactive_fluid_transport_melt_fraction_no_reaction.prm
  tests/reactive_fluid_transport_melt_fraction_no_reaction/screen-output
  tests/reactive_fluid_transport_melt_fraction_no_reaction/statistics
  tests/reactive_fluid_transport_melt_fraction_tian_approximation.prm
  tests/reactive_fluid_transport_melt_fraction_tian_approximation/screen-output
  tests/reactive_fluid_transport_melt_fraction_tian_approximation/statistics
  tests/reactive_fluid_transport_melt_fraction_zero_solubility.prm
  tests/reactive_fluid_transport_melt_fraction_zero_solubility/screen-output
  tests/reactive_fluid_transport_melt_fraction_zero_solubility/statistics
  tests/reactive_fluid_transport_no_reaction/screen-output
  tests/reactive_fluid_transport_no_reaction/statistics
  tests/reactive_fluid_transport_zero_solubility.prm
  tests/reactive_fluid_transport_zero_solubility/screen-output
  tests/reactive_fluid_transport_zero_solubility/statistics
Labels: ready to merge, ready to test

#6528 add entropy statistics
  doc/modules/changes/20250619_ranpengli
  include/aspect/material_model/entropy_model.h
  include/aspect/postprocess/entropy_statistics.h
  source/material_model/entropy_model.cc
  source/postprocess/entropy_statistics.cc
  tests/entropy_multicomponent_1_equilibration.prm
  tests/entropy_multicomponent_1_equilibration/statistics
Labels: ready to test

#6543 fix a typo
  source/material_model/grain_size.cc
Labels: ready to merge, ready to test

#6497 No longer special-case core.cc for unity builds.
  CMakeLists.txt
  source/simulator/core.cc
Labels: ready to test

#6550 Remove another vestige of separate unity builds.
  CMakeLists.txt
Labels: ready to test

#6549 Add initial topography implementation for merged box geometry model
  doc/modules/changes/20250624_alarshi
  include/aspect/geometry_model/two_merged_boxes.h
  source/geometry_model/two_merged_boxes.cc
  tests/two_merged_boxes_initial_topography.prm
  tests/two_merged_boxes_initial_topography/screen-output
  tests/two_merged_boxes_initial_topography/solution/solution-00000.0000.gnuplot
  tests/two_merged_boxes_initial_topography/solution/solution_surface-00000.0000.gnuplot
  tests/two_merged_boxes_initial_topography/statistics
Labels: ready to merge, ready to test

#6562 Open namespace aspect only once.
  include/aspect/utilities.h
Labels: ready to test

#6565 Include <mpi.h> where necessary.
  include/aspect/material_model/utilities.h
  include/aspect/plugins.h
  include/aspect/utilities.h
  source/global.cc
Labels: ready to test

#6567 Forward-declare WorldBuilder::World.
  include/aspect/simulator.h
  source/simulator/simulator_access.cc
Labels: ready to test

#6568 Move compatibility material into namespace aspect.
  include/aspect/compat.h
  source/compat.cc
Labels: ready to test

#6569 Have different cmake variables for header and source files.
  CMakeLists.txt
Labels: ready to test

#6572 Move material into namespace aspect.
  include/aspect/citation_info.h
  source/citation_info.cc
Labels: ready to test

#6559 Move function into namespace aspect. Also add necessary headers.
  source/postprocess/matrix_statistics.cc
Labels: ready to test

#6573 Move print_aspect_header() into namespace aspect.
  include/aspect/global.h
  source/global.cc
  source/main.cc
Labels: ready to test

#6579 Do not guard inclusion of <mpi.h> with DEAL_II_WITH_MPI.
  include/aspect/material_model/utilities.h
  include/aspect/plugins.h
  include/aspect/utilities.h
  source/global.cc
  source/postprocess/matrix_statistics.cc
Labels: ready to test

#6575 Guard only those parts with #ifdef that need to be guarded.
  source/initial_temperature/world_builder.cc
Labels: ready to test

#6583 Move the global functions in main.cc into an anonymous namespace.
  source/main.cc
Labels: ready to test

#6593 Fix non-matching braces.
  include/aspect/compat.h
Labels: ready to test
