Repository geodynamics/aspect, pull requests merged in 2025-04, with the labels that each got.

#6268 Be more explicit when we omit certain operations.
  source/postprocess/composition_velocity_statistics.cc
Labels: ready to test

#6270 Make the rotation terms neater
  source/material_model/rheology/elasticity.cc
Labels: ready to merge, ready to test

#6274 Only ask for required outputs in more places
  cookbooks/tomography_based_plate_motions/plugins/tomography_based_plate_motions.cc
  source/material_model/grain_size.cc
  source/material_model/reaction_model/grain_size_evolution.cc
  source/postprocess/visualization/material_properties.cc
  source/postprocess/visualization/named_additional_outputs.cc
  source/simulator/assembly.cc
  tests/melt_visco_plastic.cc
Labels: ready to merge

#6269 Fix phases for background material and plasticity in the grain size material model.
  include/aspect/material_model/grain_size.h
  source/material_model/grain_size.cc
  tests/grain_size_yield_phases.prm
  tests/grain_size_yield_phases/screen-output
  tests/grain_size_yield_phases/statistics
Labels: ready to merge

#6281 Get better errors when failing to read an input file.
  source/main.cc
Labels: ready to test
