Repository geodynamics/aspect, pull requests merged in 2025-08, with the labels that each got.

#6631 Micro-edit.
  source/mesh_deformation/interface.cc
Labels: ready to test

#6634 disable floating point exception during finalization
  source/main.cc
Labels: bug, ready to merge, ready to test

#6640 Github-Actions: use deal.II 9.6 for nounity and indent+doc tester
  .github/workflows/linux.yml
Labels: ready to test

#6649 Fix capitalization of ParticleDistributionScore postprocessor
  source/postprocess/particle_distribution_score.cc
  tests/particle_distribution_score.prm
  tests/particle_distribution_score_3d.prm
Labels: ready to merge, ready to test

#6647 Re-use rather than re-created std::regex objects.
  source/main.cc
  source/simulator/parameters.cc
Labels: ready to test

#6652 small typo fixes
  include/aspect/simulator/solver/block_stokes_preconditioner.h
Labels: ready to test

#6618 Update phase transition kinetics cookbook
  cookbooks/phase_transition_kinetics/doc/phase-transition-kinetics.md
  cookbooks/phase_transition_kinetics/doc/simple-subduction-Q10-evolution.png
  cookbooks/phase_transition_kinetics/doc/simple-subduction-Q9-evolution.png
  cookbooks/phase_transition_kinetics/phase-transition-kinetics.cc
  cookbooks/phase_transition_kinetics/phase-transition-kinetics.h
  cookbooks/phase_transition_kinetics/simple-subduction.prm
  cookbooks/phase_transition_kinetics/thermodynamic-driving-force-profile-olivine-wadsleyite.txt
  tests/phase_transition_kinetics/screen-output
  tests/phase_transition_kinetics/statistics
Labels: ready to merge, ready to test
