Repository geodynamics/aspect, pull requests merged in 2025-09, with the labels that each got.

#6657 Sort more solver schemes. Deprecate first timestep only.
  include/aspect/parameters.h
  include/aspect/simulator.h
  source/material_model/entropy_model.cc
  source/simulator/core.cc
  source/simulator/parameters.cc
  source/simulator/solver_schemes.cc
  tests/boukare_melting_diagram.prm
  tests/melt_boukare_EOS.prm
  tests/melt_boukare_averaging.prm
  tests/melting_rate_test.prm
Labels: ready to merge

#6665 do not use deprecated "Use years in output instead of seconds"
  benchmarks/solubility/plugin/solubility.cc
  contrib/opendap/prm_files/aspect_test.prm
  contrib/opendap/prm_files/aspect_url_test.prm
  cookbooks/magnetic_stripes/magnetic_stripes.cc
  source/boundary_composition/function.cc
  source/boundary_convective_heating/function.cc
  source/boundary_heat_flux/function.cc
  source/boundary_temperature/function.cc
  source/boundary_velocity/function.cc
  source/heating_model/function.cc
  source/material_model/melt_boukare.cc
  source/material_model/melt_global.cc
  source/material_model/reaction_model/katz2003_mantle_melting.cc
  source/material_model/reactive_fluid_transport.cc
  source/particle/property/composition_reaction.cc
  source/simulator/parameters.cc
Labels: ready to test

#6674 add missing mpi.templates.h include
  source/postprocess/current_surface.cc
Labels: ready to test

#6672 Add time scaling factor in TS
  doc/modules/changes/20250920_tiannh
  source/time_stepping/function.cc
  tests/time_stepping_function_years.prm
  tests/time_stepping_function_years/screen-output
  tests/time_stepping_function_years/statistics
Labels: ready to merge, ready to test

#6688 Add assertions.
  source/boundary_convective_heating/interface.cc
Labels: ready to test
